### ISSUE TITLE
IPv6 on nitter.net

### ISSUE THREAD

**Issue by unixfox** [zedeus/nitter#100]
Is it possible to add IPv6 on nitter.net?
It seems that nitter.net is hosted on Vultr and Vultr does support IPv6: https://www.vultr.com/docs/configuring-ipv6-on-your-vps
You may even already have an IPv6 assigned to the VPS and ready to be added as an AAAA record on your DNS server.

**Comment by setenforce0** [comment]
Done, can someone with ipv6 test to make sure the site is reachable? Thanks

**Comment by unixfox** [comment]
It does work on IPv6 as you can see here: https://nat64check.go6lab.si/v6score/measurement-193181/

**Comment by UnderEu** [comment]
Is isn't working

`$ dig AAAA nitter.net

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> AAAA nitter.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41773
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;nitter.net.			IN	AAAA

;; AUTHORITY SECTION:
nitter.net.		10800	IN	SOA	1-you.njalla.no. you.can-get-no.info. 2307310552 21600 7200 1814400 86400

;; Query time: 150 msec
;; SERVER: 2606:4700:4700::1001#53(2606:4700:4700::1001) (UDP)
;; WHEN: Sat Sep 09 14:31:29 -03 2023
;; MSG SIZE  rcvd: 109`

**Comment by zedeus** [comment]
The current hosting provider doesn't support IPv6 and there are no plans to move to a different one.

**Comment by marek22k** [comment]
I came across online at https://flokinet.social/@flokinet/111042066150421067.

**Comment by marek22k** [comment]
I would classify the lack of IPv6 support in 2023 not as a feature request, but as a bug.
