### ISSUE TITLE
"No items found" Error When Running Docker-Compose with Nitter

### ISSUE THREAD

**Issue by juste97** [zedeus/nitter#1004]
Hello,

I've just configured a test instance using the Docker setup method, and followed the README to set up my nitter.conf file. Despite this, when I run docker-compose up, I consistently receive a "No items found" message for any query I make on my local instance. Is this a known issue with the current Docker image? Or is there something specific that I might have missed during the setup process? Any guidance would be greatly appreciated.

Thank you.

**Comment by FahriBilici** [comment]
I have the same problem. Any solution for this?

**Comment by zedeus** [comment]
https://github.com/zedeus/nitter/wiki/Guest-Account-Branch-Deployment
