### ISSUE TITLE
403?

### ISSUE THREAD

**Issue by ArchivingToolsForWBM** [zedeus/nitter#1006]
I noticed when saving nitter pages to the wayback machine, especially this instance on the search: https://nitter.privacydev.net/search?f=tweets&q=testing123&since=&until=&near= returns 403. Is nitter directly against saving its pages?

**Comment by zedeus** [comment]
Nitter heavily restricts non-human usage at the moment due to massive amounts of traffic and the small amount of working public instances.

**Comment by ArchivingToolsForWBM** [comment]
so the instances are... well this then: https://www.youtube.com/watch?v=Ydz-xKyqtkk&t=81s (an analogy of an overloaded instance to a toy being heavily overvoltaged that it popped).

Hope this is only temporary. I save nitter pages as a backup in case saving twitter pages fails.

**Comment by HashLiver** [comment]
> Nitter heavily restricts non-human usage at the moment due to massive amounts of traffic and the small amount of working public instances.

![403](https://github.com/zedeus/nitter/assets/42889797/10eff86a-e4cf-430d-a420-25d4fb32c263)

I'm human, but I'm still banned for now....

**Comment by zedeus** [comment]
@HashLiver Please email me your IP address, I'll take a look.

**Comment by fitzsim** [comment]
In Emacs, `M-x eww RET nitter.net RET` (executed by me, a human) produces the `403 Forbidden` result.

**Comment by Antigravityd** [comment]
> In Emacs, `M-x eww RET nitter.net RET` (executed by me, a human) produces the `403 Forbidden` result. (Not complaining, just reporting a use case; great job on Nitter!) (update: nevermind, received a simple Emacs-side workaround on #emacs).

Mind sharing the details of the workaround? #emacs doesn't log, unfortunately.

**Comment by fitzsim** [comment]
Duncan Wilkie ***@***.***> writes:

>  In Emacs, M-x eww RET nitter.net RET (executed by me, a human) produces
>  the 403 Forbidden result. (Not complaining, just reporting a use
>  case; great job on Nitter!) (update: nevermind, received a simple
>  Emacs-side workaround on #emacs).
>
> Mind sharing the details of the workaround? #emacs doesn't log,
> unfortunately.

This works on Emacs 29.1:

(defun my-eww-retrieve-with-accept-language (oldfun url callback cbargs)
  (let ((url-request-extra-headers (cons '("Accept-Language" . "en-US")
                                         url-request-extra-headers)))
    (funcall oldfun url callback cbargs)))

(advice-add 'eww-retrieve :around #'my-eww-retrieve-with-accept-language)

**Comment by untitaker** [comment]
I do not recommend publicly sharing bypasses of intentional anti-bot measures.

**Comment by 0xpr03** [comment]
this is why we can't have nice things.. scraper will adopt that pertty quick and we're back to a) dead instances and b) captchas people hate so much here..

**Comment by 0xpr03** [comment]
There are also enough other instances to pick from: https://status.d420.de
