### ISSUE TITLE
Theme in URI string should be attached to Nitter links

### ISSUE THREAD

**Issue by terr72** [zedeus/nitter#1011]
https://nitter.net/debian?theme=Twitter
doesn't result in corresponding links on the page.

Links like
https://nitter.net/debian/status/1691842007910727957#m
should instead be
https://nitter.net/debian/status/1691842007910727957?theme=Twitter#m

As alternative a cookie could be set to store the alternative theme.
Otherwise every link resets Nitter back to the default black background theme.

**Comment by zedeus** [comment]
>As alternative a cookie could be set to store the alternative theme.
That's what the settings page is for, not sure I'm getting the point here.

**Comment by terr72** [comment]
Ah, OK.
I'm clearing cookies upon exit. I fixed this by excluding the Nitter instance.
