### ISSUE TITLE
UNable to fetch the data

### ISSUE THREAD

**Issue by Anant-2005** [zedeus/nitter#1012]
I followed the instructions and set up nitter using nim. My problem is that I have access to the nitter frontend using localhost. but it cann't fetch any datalike tweets or users. I think there is some backend config I need to create. Please help me out!
![image](https://github.com/zedeus/nitter/assets/108405792/e800f71c-f503-4389-8636-d53a3e8d1a2b)

**Comment by zedeus** [comment]
#983

**Comment by Anant-2005** [comment]
It's hosted on my localserver and I can't search anything on it. The issue you asked me to see was related to online server. I am not able to see anything after hosting it locally. What should I do?

**Comment by zedeus** [comment]
No, it's related to Nitter in general.
