### ISSUE TITLE
In an RSS feed, a tweet containing only a GIF and a quote-retweet will not have a title and will thus will have no link to that tweet

### ISSUE THREAD

**Issue by pin-grid-array** [zedeus/nitter#1013]
The title is confusing but basically the problem is this:

User A writes a tweet. Let's call this tweet R.

User B quote-retweets tweet R and inputs only a GIF in their tweet (with no additional text). Let's call this tweet S.

In the RSS feed of User B, the entry for tweet S does not have a title, which means that entry does not have a link to the nitter website version of tweet S. (When looking at the body of the entry of tweet S, the URL of tweet R is displayed. This is expected and is not a problem.)

Looking at my feed reader's source code, I can see the URL of tweet S is in fact there, just without anything between the `<a>` and `</a>` tags. So actually, the link to tweet S is effectively invisible and unclickable.

**Comment by pin-grid-array** [comment]
I finally found a live example of this occurring and was able to look at the RSS feed code before the relevant tweet containing the GIF dropped off the feed.

[Here is the RSS feed](https://nitter.poast.org/yugiohtas/with_replies/rss). Take a look at what is currently the 3rd most recent entry, which has a `pubdate` of Thu, 21 Sep 2023 15:22:24 GMT. Notice how there is no text between the `<title></title>` tags.

My feed reader uses what is between those tags as the title of the entry. Normally, the reader puts that title text between `<a>` and `</a>` tags to link to the nitter website version of that tweet. But in this case, there is no text between the entry's `<a>` and `</a>`, so in the reader there is no title for this entry.

The `<a href="">` does correctly contain a link to the nitter website version of that tweet, taken from the URL between the feed's `<link>` and `</link>` tags. But because there is no text between `<a>` and `</a>`, there is nothing for the user to click on to get to that website.

**Comment by zedeus** [comment]
This is essentially #988 and by extension #132. Thank you for the example though, didn't know #988 was still an issue.
