### ISSUE TITLE
error 404 and empty response

### ISSUE THREAD

**Issue by moha-ep** [zedeus/nitter#1016]
I have installed a Nitter instance locally due to the high volume of requests that the public instances are getting. 

My installation steps are as follows:
- Clone the project with the following command `git clone --depth 1 https://github.com/zedeus/nitter.git`
- Copy the example configuration file `cp nitter.example.conf nitter.conf` and modify the redisHost line from "localhost" to "nitter-redis".
- Start the build and containers
- Start the browser to see if the instance is running
- Or it seems that the instance works 
![image](https://github.com/zedeus/nitter/assets/106144010/26a5f0bc-4ae4-4dfe-a4ef-2b2184b0e524)

- It's time to test the requests 
![image](https://github.com/zedeus/nitter/assets/106144010/48992ec9-a8fd-408d-8d6a-6034b7f7a3a4)

- Ooops something seems to be wrong.... I look at the docker log to see if there is something wrong and I find that the request made to the x/twitter api responds with a `404 not found`. 
![image](https://github.com/zedeus/nitter/assets/106144010/aa8c1047-ad78-417f-978b-e4f4e3d8604e)

Has anyone had the same thing happen to him/her and has he/she been able to solve it?

Thnx

**Comment by zedeus** [comment]
#983
