### ISSUE TITLE
Server: 502 Bad Gateway

### ISSUE THREAD

**Issue by sammypanda** [zedeus/nitter#1029]
![502 bad gateway nginx 1.22.1 on chromium](https://github.com/zedeus/nitter/assets/38725335/b4ed1caf-a1a7-4826-b5b7-57a592c7091f)

*tested on firefox & ungoogled chromium + two different internet connections*

**Comment by notherenorthere** [comment]
> ![502 bad gateway nginx 1.22.1 on chromium](https://user-images.githubusercontent.com/38725335/269498599-b4ed1caf-a1a7-4826-b5b7-57a592c7091f.png)
> 
> _tested on firefox & ungoogled chromium + two different internet connections_

it's happening to everyone https://github.com/zedeus/nitter/issues/983#issuecomment-1728716178

**Comment by DarrenSem** [comment]
Without nitter (or other frontends like it? Ideas? `ANYONE?`), to many of us without accounts "Twitter" is dead. Dead like a parrot. It is an eX-Twitter.

**Comment by EHP4321** [comment]
https://twstalker.com/ is still up
Its not as good but might be enough for your immediate needs

> Without nitter (or other frontends like it? Ideas? `ANYONE?` ● ), to many of us without accounts "Twitter" is dead. Dead like a parrot. It is an eX-Twitter.
> 
> ● https://greycoder.com/alternative-interfaces-to-twitter-that-are-currently-working-and-reasonably-fast/ didn't help.

**Comment by moha-ep** [comment]
Use https://nitter.poast.org/

**Comment by zedeus** [comment]
I broke the server, but there's no need to talk about Nitter being gone, it's just the main instance that's broken. Check https://status.d420.de

**Comment by yassernasc** [comment]
phew..
btw, I would recommend creating another instance to serve as a 'playground', if I understood correctly.

**Comment by OmegaDreamLord** [comment]
https://nitter.poast.org/

This instance works out of the list of them you can find, at least for me it worked.

**Comment by sammypanda** [comment]
I'm okay with waiting, just this issue is useful to redirect people to and keep tabs/updates going on the 502

**Comment by DarrenSem** [comment]
> Without nitter (or other frontends like it? Ideas? `ANYONE?` ● ), to many of us without accounts "Twitter" is dead. Dead like a parrot. It is an eX-Twitter.
> 
> ● https://greycoder.com/alternative-interfaces-to-twitter-that-are-currently-working-and-reasonably-fast/ didn't help.

Sorry folks. I panicked.

**Comment by zedeus** [comment]
It's back.
