### ISSUE TITLE
RSS is not available?

### ISSUE THREAD

**Issue by highroller** [zedeus/nitter#1034]
There used to be a RSS icon at the upper right corner, now there is none.  I tried to add /rss at the end of the url manually, but it's not working.  Is Rss available now?  If not, is there a plan to add it back?  Great to see Nitter.net is back online at least.

**Comment by highroller** [comment]
I just found that nitter.net rss is disabled, but some other instances has rss enabled.

**Comment by zedeus** [comment]
I've answered this several times. It's disabled on purpose for traffic reasons. I'll turn it back on some time in the near future, I don't know when. Check status.d420.de to pick an instance that has RSS enabled.
