### ISSUE TITLE
Videos on user page being entirely preloaded

### ISSUE THREAD

**Issue by evilantishad0w** [zedeus/nitter#1036]
e.g. https://nitter.cz/elonmusk

This uses up user bandwidth on metered connections, and also places a heavier load on twitter servers, which incentivizes the company to disallow nitter access.

Edit: Quick test re-enabling proxy shows this happens whether proxy is enabled or not.

**Comment by pin-grid-array** [comment]
I agree that that is a big problem but I don't see any videos getting preloaded except for GIFs (actually MP4s). I do not have `Enable HLS video streaming (requires JavaScript)` enabled, but even when I do, there is no preloading of videos.

When I look at the code, in the `<video>` tag I see `data-autoload="false"`. I guess that means preloading is disabled for me.

**Comment by zedeus** [comment]
I don't know what you're talking about, this isn't how videos work on nitter. With HLS disabled and proxying enabled, you can't even play the videos. With HLS enabled, nothing from the video is preloaded before you click the play button.

**Comment by zedeus** [comment]
No response, closing.
