### ISSUE TITLE
Twitter deprecated /1.1/guest/activate

### ISSUE THREAD

**Issue by ThallesP** [zedeus/nitter#1038]
https://twittercommunity.com/t/deprecation-of-the-1-1-guest-activate-endpoint-in-the-twitter-api/200591

Is there any other ways to keep nitter alive?

**Comment by zedeus** [comment]
Old news, didn't affect nitter, but guest tokens because unusable for other reasons. See #983

**Comment by ThallesP** [comment]
> Old news, didn't affect nitter, but guest tokens became unusable for other reasons. See #983

Sorry, couldn't find where you said that you moved away from guest tokens, and i found references of that endpoint in the code.
The endpoint seems to be working, but twitter is planning on removing it, wouldn't that be a problem in the future?

**Comment by zedeus** [comment]
It's still used in master, but master is completely broken. See #985
