### ISSUE TITLE
Nitter can't find any account

### ISSUE THREAD

**Issue by stemy2** [zedeus/nitter#1039]
No matter wich instance i use, i can't find any of the actually existing accounts i'm searching. And it happens since a long long time. Did twitter/X made this kind of problem unsolvable ?

**Comment by zedeus** [comment]
https://nitter.net/search?f=users&q=Elon+musk
Works just fine. Example please?

**Comment by stemy2** [comment]
Now, its working also for me too. But i swear it didn't worked on the said instance when i opened the ticket.
