### ISSUE TITLE
nitter.net blocked by quad9

### ISSUE THREAD

**Issue by leonghui** [zedeus/nitter#104]
nitter.net is the default endpoint used in the FF addon [Invidition](https://gitlab.com/Booteille/invidition) but recently it stopped working. Traced the issue to the DoH provider.

> Threat Intelligence Providers who have listed this domain:
>
>     DOMAINTOOLS Hotlist
> 

See https://www.quad9.net/result/?url=nitter.net

**Comment by Perflyst** [comment]
It got removed: https://www.quad9.net/result/?url=nitter.net
