### ISSUE TITLE
The newest Docker image is broken & not up to date.

### ISSUE THREAD

**Issue by moonleay** [zedeus/nitter#1043]
I installed nitter using the [docker image](https://hub.docker.com/layers/zedeus/nitter/latest/images/sha256-c0275459df4de2331a1ceac61c42be30a8731e168f582851134b5ec25af75171?context=explore) and it is not the newest version.
[My instance](https://nitter.moonleay.net/about)
vs
[Nitter's official instance](https://nitter.net/about).

Did the docker image move to another repository?

**Comment by zedeus** [comment]
It is up to date, nitter.net is just running the #985 PR. See #983 for more details.
