### ISSUE TITLE
Remove link preview link, title description and add views

### ISSUE THREAD

**Issue by libreom** [zedeus/nitter#1044]
𝕏 stopped showing link, headlines(title) and description to make posts look cleaner,improve aesthetics and readability [[1]](https://www.theverge.com/2023/10/4/23903859/x-elon-musk-headlines-links-image-twitter)
for feature parity, cleaner posts, improved readability (IMO) nitter should make same change
Here's how it currently is in [twitter](https://twitter.com/406mama/status/1714261027741995030)
![image](https://github.com/zedeus/nitter/assets/111110599/9ca0cf29-0238-45c0-8da6-acacdada4605)
and in [nitter ](https://nitter.net/406mama/status/1714261027741995030)with current differences highlighted
![image](https://github.com/zedeus/nitter/assets/111110599/44c6e8be-9159-4852-8798-f11d291558de)
Current differences are about part of link, title and description, duration difference and absence of views
So please provide this enhancement and maintain feature parity

**Comment by zedeus** [comment]
I, like many others, very strongly disagree with this design change. It doesn't improve anything, it just hides very important link information, and doesn't count when it comes to feature parity. Nitter aims to support the things Twitter does, not to look the same.
