### ISSUE TITLE
Nitter is down

### ISSUE THREAD

**Issue by davidmreid** [zedeus/nitter#1050]
404. That’s an error. The requested URL was not found on this server. That’s all we know.

**Comment by zedeus** [comment]
What instance? Please include at least a little bit of information.

**Comment by davidmreid** [comment]
404 error codes are generated when a user attempts to access a webpage that does not exist, has been moved, or has a dead or broken link. The 404 error code is one of the most frequent errors a web user encounters.
*************************************************
downforeveryoneorjustme.com: Is Nitter.net down? It's not just you! nitter.net is down.
saashub.com: We cannot reach Nitter right now. It is possible that they are experiencing global issues.
websitedown.info: Website Availability Check For Nitter.Net: Down
*******************************
notopening.com: nitter.net is up and reachable. If you're not able to reach it, it might just be your connection.
isitdownorjust.me: Nitter.net seems to be working.
*******************************
None of these options worked:
1) Try clearing your Internet cookies and browser cache. 
--Proceed to refresh your browser by hitting the CTRL + F5 keys simultaneously.
2) Try clearing your computers DNS cache so your computer grabs the most recent cache from your ISP.
3) Try resetting your modem and restart your computer.
4) Finally try accessing the website using an online proxy service till your ISP resolves the problem.

**Comment by iitzRichie** [comment]
I've been having loading issues with Nitter recently. Also, I feel like iOS 17.1 has broke the Nitter web app. It just doesn't seem to be as responsive as it was pre iOS 17.1, but maybe that's just due to the loading issues, I'm not sure.

**Comment by zedeus** [comment]
All those downtime checking websites won't work for nitter.net due to anti-bot measures that blocked their IPs. The rest of your message comes off as AI generated. I still don't know what your issue actually is.

**Comment by davidmreid** [comment]
This is the answer from Nitter.Net today:

 It's been several months (from March to October 2023) that we've been dealing with numerous changes on Twitter's side to block Nitter, which are making maintenance of the service increasingly complex and time-consuming.

We have therefore decided to close our Nitter service, due to a lack of time and energy to devote to its upkeep. This choice will enable us to invest our energy in other projects.

We advice you to use other Nitter instances, among those that are still maintained. Find the instances list here.

https://nitter.lacontrevoie.fr/


-David

---------------------------
David Reid
209-294-5349
***@***.***






On Friday, October 27, 2023 at 06:51:30 AM PDT, Zed ***@***.***> wrote: 







All those downtime checking websites won't work for nitter.net due to anti-bot measures that blocked their IPs. The rest of your message comes off as AI generated. I still don't know what your issue actually is.

**Comment by zedeus** [comment]
No, that's not nitter.net, and this is clearly not a real person.
