### ISSUE TITLE
Cert expired for nitter.net

### ISSUE THREAD

**Issue by Apachez-** [zedeus/nitter#1051]
The Lets Encrypt cert used by nitter.net just expired:

Valid until: Sunday, October 29, 2023 at 5:52:28 AM

Results in following error in browsers:

```
Your connection is not private
Attackers might be trying to steal your information from nitter.net (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_DATE_INVALID
```

**Comment by kugiyasan** [comment]
Seems like something similar happened last year, there were propositions to disable HSTS but it never happened https://github.com/zedeus/nitter/issues/676

I'll take this opportunity to thank zedeus and the contributors on this project, you guys are making it possible to view Twitter posts without sacrificing my privacy, and I really appreciate it!

**Comment by pixiekat** [comment]
Seconding the thanks to the project and zedeus. I don't have Twitter anymore but there are still people I like who haven't made the switch to other platforms so it's nice to follow them :)

**Comment by 0xpr03** [comment]
Yes nitter.net is currently down. No you can still use nitter: Pick a working instance from the [instance status page](https://status.d420.de) for now. (For all new people visiting this issue.)

**Comment by sclerometer** [comment]
type `thisisunsafe` on error page

**Comment by Apachez-** [comment]
It works now, case closed :-)

Issued on: Sunday, October 29, 2023 at 4:08:31 PM

Expires on: Saturday, January 27, 2024 at 4:08:30 PM

So see y'all in 3 months ;-)

**Comment by neves-0** [comment]
Well... 3 months later :)

**Comment by Apachez-** [comment]
Still not updated :-( (as of 2024-02-03 about 17:10 CET):

Common Name (CN)	nitter.net
Organization (O)	<Not Part Of Certificate>
Organizational Unit (OU)	<Not Part Of Certificate>
Common Name (CN)	R3
Organization (O)	Let's Encrypt
Organizational Unit (OU)	<Not Part Of Certificate>

Issued On	Sunday, October 29, 2023 at 4:08:31 PM
Expires On	Saturday, January 27, 2024 at 4:08:30 PM

**Comment by NetworkWebMasters** [comment]
nitter.net still working perfectly with nitter-harvest, ignore expired certificate.

**Comment by Apachez-** [comment]
> nitter.net still working perfectly with nitter-harvest, ignore expired certificate.

Unfortunately later versions of Google Chrome (and its forks like Chromium etc) no longer allows to bypass an expired certificate. Also because nitter.net have HSTS configured.

So this is still an issue since the cert is still expired and because of that https://nitter.net doesnt work...
