### ISSUE TITLE
RSS feed contains wrong content

### ISSUE THREAD

**Issue by vanitasvitae** [zedeus/nitter#106]
Hi!
I hope this is the right issue tracker.

I'm using the rss feature of nitter.net to follow the tweets of a twitter user.
Sometimes (around once a month or so) the RSS feed contains ~20 unrelated tweets that I highly doubt the user composed, liked or retweeted in any way. Often these tweets are in a foreign language and are not related to the users interests and/or political views.

Just to make sure I checked the users twitter but couldn't find a trace of the rogue tweets, so I'm pretty sure this is a bug in nitter (or nitter.net).

**Comment by ryazo** [comment]
Similar bug for me, sometimes instead of receiving the requested resource, I receive an unrelated twitter picture (to anything I've been recently been viewing), and more recently, an RSS file. I usually browser "Tweets & Replies". I don't have anything specific.

 I think when the server is under load, there are some bizarre race conditions going on.

**Comment by zedeus** [comment]
I'm aware of this issue already but it has been low priority because it's non-deterministic (hard to troubleshoot) and no particularly private data is being served yet. I believe it's a problem with httpbeast, the Nim web server used, hopefully I can do some troubleshooting to get it fixed soon.

**Comment by zedeus** [comment]
I did some testing by doing things like blasting a local server with hundreds of requests per second, but I failed to trigger it reliably. This is harder than I expected.

**Comment by zedeus** [comment]
Changed the web server instead, it should now be fixed. Please reopen if you experience leaks again

**Comment by jk-na** [comment]
> Changed the web server instead, it should now be fixed. Please reopen if you experience leaks again

This has happened to my Nitter feeds three times already today (hadn't happened for a long while but recently started again).
