### ISSUE TITLE
[Request] OpenSearch

### ISSUE THREAD

**Issue by smnthermes** [zedeus/nitter#107]
Please, add support to OpenSearch, to make it possible to add Nitter to the search box of browsers.

**Comment by Perflyst** [comment]
"Firefox could not download the search plugin from: http://localhost:8080/opensearch"

That is not working @setenforce0

**Comment by setenforce0** [comment]
Left the path to the xml file hardcoded accidentally, will amend

**Comment by setenforce0** [comment]
@Perflyst Can you confirm that the fix works please? :)

**Comment by setenforce0** [comment]
Tested working, please reopen if there are any more issues.

**Comment by Perflyst** [comment]
Yes it works, thanks
