### ISSUE TITLE
Support for Internationalized domain name

### ISSUE THREAD

**Issue by treble2019** [zedeus/nitter#108]
If you go to this tweet it does not show the *localghost*

https://nitter.net/rfreebern/status/1214560971185778693#m

Thanks for your efforts!

preview here:
![1](https://user-images.githubusercontent.com/52563208/72064408-17b2a900-32dc-11ea-82c3-52d43d5c1fa9.jpg)

Or may be it is only my PC. sorry!

**Comment by Perflyst** [comment]
What exactly do you miss on the tweet displayed by nitter?
From what is the screenshot? Twitter or Nitter? Please post also a screenshot from either Twitter or Nitter, so we can see both.

**Comment by zedeus** [comment]
![image](https://user-images.githubusercontent.com/9434921/72069914-8564d200-32e8-11ea-85b1-e48f6076d49f.png)
Looks fine to me, nitter vs twitter on Firefox. It does however depend on system fonts. Proper emoji support will be added, see #48, but it's currently low priority as there's a lot of solutions, some requiring JavaScript, others having very large images to contain all emojis.

**Comment by treble2019** [comment]
I am sorry. I had to install the package `fonts-noto-color-emoji ` on xubuntu.
