### ISSUE TITLE
"Replace YouTube links with Invidious" is applied to everything and not just URLs

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zedeus/nitter#109]
Nitter is buggy regarding the "Replace YouTube links with Invidious" setting:

It sometime replace the word "youtube" in a tweet with the Invidious url, example:

On Nitter:

![nitter](https://user-images.githubusercontent.com/47571719/72230148-8aa57380-35ab-11ea-9679-c11b40497e2e.png)

On Twitter:

![twitter](https://user-images.githubusercontent.com/47571719/72230153-9729cc00-35ab-11ea-9ccd-f1e2ac6c13d9.png)

(from this tweet: https://nitter.net/KSI_MakesMyDay/status/1128284789264588801)

But it's also inconsistent and do things correctly in some other tweet:

https://nitter.net/MalekBA91/status/1215913705625587713

**Comment by zedeus** [comment]
Damn, guess I generalized the regex a bit too much. Will fix tomorrow

**Comment by TheFrenchGhosty** [comment]
I think I understand why it happens, it looks like it replaced "[youtube com]ment", I guess it's applied even when it's not an URL and that's why it's causing this problem.

**Comment by Booteille** [comment]
If that's the case, that's probably bound to a missing backslash before a point. `\.` instead of `.`.
But I didn't look at the code where's the regex in question to check it.

**Comment by zedeus** [comment]
`ytRegex = re"([A-z.]+\.)?youtu(be.com|.be)"` - yep, my mistkae
