### ISSUE TITLE
Proxy images

### ISSUE THREAD

**Issue by Perflyst** [zedeus/nitter#11]
Currently images like banner / profile image or media is not proxied and if you wanna view it, it redirects to Twitter.

**Comment by zedeus** [comment]
This is already done. The folder in /tmp is a media cache.

**Comment by Perflyst** [comment]
If I click on a profile image I for example get a link like https://nitter.net/pic/C5B7E60C4BD0F/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F648888480974508032%2F66_cUYfj_200x200.jpg which redirects me to https://pbs.twimg.com/profile_images/648888480974508032/66_cUYfj_200x200.jpg
