### ISSUE TITLE
[REQUEST] Guest Account Pool Service

### ISSUE THREAD

**Issue by singlash26** [zedeus/nitter#1104]
Hi @zedeus , as per your [comment](https://github.com/zedeus/nitter/pull/985#issuecomment-1690348144), did you get a chance to create a guest account pool service? Or, could you please let me know how are you utilizing 37k guest accounts (as mentioned in this [comment](https://github.com/zedeus/nitter/issues/983#issuecomment-1684921201))?

**Comment by zedeus** [comment]
Not yet, but a community member made this one for public instances: https://twitterminator.x86-64-unknown-linux-gnu.zip/

**Comment by singlash26** [comment]
Thanks @zedeus , this is really a nice one. Any clue on setting something like this for Private instances as well ?

**Comment by zedeus** [comment]
It may happen in the future, but for now there's no plans no.
