### ISSUE TITLE
Tweet contents are not escaped

### ISSUE THREAD

**Issue by jarrodldavis** [zedeus/nitter#1106]
It appears that tweet contents are not properly escaped, so any HTML content will be [rendered verbatim](https://github.com/zedeus/nitter/blob/b62d73dbd373f08af07c7a79efcd790d3bc1a49c/src/views/tweet.nim#L319), causing the rest of the page to be broken. For example, [here's a tweet that contains `<select>`](https://nitter.net/adamwathan/status/1721581482680975496#m) as part of its text. Since `<select>` is rendered as part of the HTML document and not as escaped text, the rest of the page looks like its being removed entirely since it's being parsed as children of the `<select>` and thus being discarded.

<img width="1282" alt="Screenshot 2023-11-07 at 5 36 27 PM" src="https://github.com/zedeus/nitter/assets/235875/a7394997-1b61-48e8-8879-94b6b93cac8d">

**Comment by zedeus** [comment]
Damn, that's technically a security vulnerability. I'll look into it asap.

**Comment by zedeus** [comment]
This only affects long/note tweets. Twitter doesn't escape these longer tweets for some reason, but they do escape normal tweets. Fixing this is therefore low priority, and it's quite non-trivial.

**Comment by wolfmanfp** [comment]
I found another tweet which is affected. This one lists HTML opening tags, which are cut off when opened in Nitter:
https://nitter.net/WebDesignMuseum/status/1718660434457239868

**Comment by ButteredCats** [comment]
Just started running https://github.com/zedeus/nitter/pull/831 on my instance and that fixes it. Both [the first](https://nitter.catsarch.com/adamwathan/status/1721581482680975496#m) and [the second](https://nitter.catsarch.com/WebDesignMuseum/status/1718660434457239868) example look (mostly) fine with it. In the second example `<dir>` starts to become a link to search it in Nitter for some reason, but I consider that better than the entire tweet going missing.

**Comment by zedeus** [comment]
That PR implements a simple, but evidently broken fix. I thought of it myself, but it breaks Twitter's tweet entities and how they're applied. It gave me an idea though, I'll look into it.
