### ISSUE TITLE
New setup returns no results

### ISSUE THREAD

**Issue by job2310** [zedeus/nitter#1108]
Have set up a nitter instance for myself and a friend to use but I'm getting no results post install when I search for a X username. From reading the issues I can see this seems to be a known problem but some instances are working.  Would be interested to know how they're doing it.

Thanks,
Josh

**Comment by 253153** [comment]
How did you fix it?

**Comment by zedeus** [comment]
https://github.com/zedeus/nitter/wiki/Guest-Account-Branch-Deployment
