### ISSUE TITLE
Remove the image `width` in the RSS feed

### ISSUE THREAD

**Issue by Massedil** [zedeus/nitter#111]
I don't know if there is a reason, but the `width="250"` attribute inside the `img` tag makes that images are displayed smaller than they really are in my FreshRSS viewer.

Expected : 
No `width="250"` inside the `img` tag.
The RSS reader knows how to display the image.

https://github.com/zedeus/nitter/blob/master/src/views/rss.nimf#L31
https://github.com/zedeus/nitter/blob/master/src/views/rss.nimf#L34
https://github.com/zedeus/nitter/blob/master/src/views/rss.nimf#L38

**Comment by zedeus** [comment]
I'm reluctant to do this as the RSS viewers I've tried display them in full size, which often is not a good idea. I copied the way invidious does it, which also has the width attribute. I don't use the feature myself so I can't say for sure what's best, maybe a `max-width` or `max-height` attribute? Maybe a config option to set RSS image width? 
/cc @Perflyst @TheFrenchGhosty @Mikaela @vanitasvitae

Here's an example:
![image](https://user-images.githubusercontent.com/9434921/72677312-3b73ad00-3a9b-11ea-8f0d-82bb717a5376.png)

**Comment by Massedil** [comment]
Here, there is a `max-width:558px;` but no HTML attribute and the display is as expected in FreshRSS :
https://github.com/RSS-Bridge/rss-bridge/blob/master/bridges/TwitterBridge.php#L345

I think FreshRSS remove the initial CSS information and use its proper CSS (`max-width:100%`) but it keeps the HTML attribute `width="250"` that take precedence over the CSS.

So I think removing the `width="250"` attribute and setting a CSS `max-width:100%` or `max-width:NNNpx;` would solve the issue.

I think it is not a good idea to set a `max-height` attribute because if you follow a "comic strip" with a long height it will be too small to read.

What do you think about it?

**Comment by TheFrenchGhosty** [comment]
I'm personally okay with a fixed width, but 250 is maybe a bit small. I'm not confortable enough with CSS to know a better way to do it.

**Comment by Owyn** [comment]
250 is literally unreadable, I follow image artists and with 250 I can't even see what is drawn there

Tho I wouldn't like to actually scroll images up\right in my rss feed - I'd rather open full version in browser, but for that I'd need to see what the image is about, so my suggestion would be:

`max-width:100%`
`max-height:100%`

so it'd at least fit into feed reader

just look how ridiculous it looks currently with max width 250:
![image](https://user-images.githubusercontent.com/1309656/140646395-81082f8b-852c-4c74-afaa-1e2cab1d7ba7.png)
