### ISSUE TITLE
No items found - Network issues?

### ISSUE THREAD

**Issue by keynet** [zedeus/nitter#1114]
Built nitter from latest GitHub source, no errors or warnings, installed redis etc. Executable is 3.4M
However when it runs, I get "No items found", a bit like issue #839, though in all other respects appears OK.

So I installed docker, ran latest nitter image, same result. Also previous docker image - same.
I'm thinking it's something to do with networking or config, so removed reverse proxy and firewall temporarily, and exposed nitter to port 80. Same result. 
Tried variations of hostname etc in config, still nothing.

I see debug like this, so I conclude it's talking to something (this is with an Apache reverse proxy on 7997).
```
Connected to Redis at localhost:6379
INFO Jester is making jokes at http://0.0.0.0:7997
[tokens] added new token to pool
[tokens] added new token to pool
[tokens] added new token to pool
[tokens] added new token to pool
[tokens] added new token to pool
[tokens] added new token to pool
[tokens] added new token to pool
[tokens] added new token to pool
[tokens] added new token to pool
[tokens] added new token to pool
```
Wireshark shows a packet to twitter.com when searching, and a response of about 750 bytes, then nothing 

I can use a 3rd party hosted instance no problem, but want to run my own instance.
I must have missed something.  What more debug can I do ?

Appreciate any help

**Comment by zedeus** [comment]
The new era implemented by #985 hasn't been merged into master yet. See #983 for more details.
Here's a guide to set it up: https://github.com/zedeus/nitter/wiki/Guest-Account-Branch-Deployment

**Comment by keynet** [comment]
Great, thanks, got it to work with guest account branch. 
Is it possible to generate actual Twitter links, not redirected (I don't seem to be able to make it do it by clearing the redirect options). Use case is a private nitter instance creating RSS for a public website via FreshRSS, where people won't have access to my nitter instance, and would probably expect Twitter links anyway.
Thanks again

**Comment by zedeus** [comment]
@keynet this isn't officially supported, but you can set replaceTwitter to twitter.com in nitter.conf and it should work just fine. Remember to set `https = true` as well, otherwise the links will be http only.

**Comment by keynet** [comment]
Thanks, yes I had tried that setting, but no setting seems to change the link URL's. I can perhaps look at the code if you point me in the right direction. I think the use case for creating an RSS from Twitter is valuable.
