### ISSUE TITLE
Error 502 on some i/lists (Expected { but got " instead)

### ISSUE THREAD

**Issue by wiz0u** [zedeus/nitter#1119]
Ex: https://nitter.net/i/lists/1118641912884412417
On this list and some other lists, we get this error:
```
An error has occured in one of your routes.
Detail: jsony.nim(51) parseHook
asyncfutures.nim(385) read
asyncfutures.nim(385) read
asyncfutures.nim(385) read
Expected { but got " instead. At offset: 353
```

**Comment by wiz0u** [comment]
This error started appearing around Nov 16, 17:45 UTC
It worked correctly before that

**Comment by wiz0u** [comment]
Now the error appears to have moved on page 3 (Load more tweets), so it's probably a specific tweet that is messing things up.

You might want to look at this bug now, before it disappear by itself because the tweet is no longer listed.

**Comment by jcmag** [comment]
same error with: https://nitter.net/i/lists/1726957725526163791

**Comment by jcmag** [comment]
not specific to the lists by the way : https://nitter.net/xai

```
An error has occured in one of your routes.

Detail: jsony.nim(51) parseHook
asyncfutures.nim(385) read
asyncfutures.nim(385) read
asyncfutures.nim(385) read
asyncfutures.nim(385) read
asyncfutures.nim(385) read
Expected { but got " instead. At offset: 359
```

**Comment by zedeus** [comment]
Fixed
