### ISSUE TITLE
User has many tweets but only a few can be loaded

### ISSUE THREAD

**Issue by MoonlessForest** [zedeus/nitter#1124]
Sometimes a user has more than a thousand (or even several thousand) tweets, but only a few can be loaded, and attempting to load the rest either results in an error or a "No more items" message being displayed. Switching to another instance or trying later doesn't resolve the issue. Older tweets can still be accessed through direct links.
I've only experienced this issue with Korean accounts/tweets for some reason, however (Japanese, English and Chinese ones seem to always load properly), although it might just be a coincidence.

**Comment by zedeus** [comment]
Same thing happens when accessing the account via Twitter directly, please test before opening an issue.

**Comment by zedeus** [comment]
No problem, that's what Nitter is for after all :)
