### ISSUE TITLE
disable infinite scroll?

### ISSUE THREAD

**Issue by dontpnc** [zedeus/nitter#1134]
i'm using lists example (nitter.net/i/lists/000000) and i have 200 members but timeline is to big with tweets, how to see only 5-10 max latest tweets on my timeline instead of +200?

**Comment by zedeus** [comment]
Infinite scroll is disabled by default unless the instance operator changes the config, in which case you can open the settings page and turn it off yourself. Lists serving a lot of tweets is unfortunately a problem caused by Twitter/X, the "limit" parameter for the endpoint doesn't work. I could limit it to only return the latest x amount of tweets, but then pagination would involve making the same massive request over and over, which isn't an acceptable solution.

**Comment by dontpnc** [comment]
> **Lists serving a lot of tweets is unfortunately a problem caused by Twitter/X, the "limit" parameter for the endpoint doesn't work. I could limit it to only return the latest x amount of tweets, but then pagination would involve making the same massive request over and over, which isn't an acceptable solution.**


I noticed that the example list (1003294326628192257) with the following parameter:

https://nitter.net/search?f=tweets&q=list%3A1003294326628192257&since=&until=&near=

shows only 20 tweets in the timeline, displaying the newest tweets without exceeding the limit unless I manually 'load more'.

However, when using the direct list URL:

https://nitter.net/i/lists/1003294326628192257

it displays more than 50 tweets in the timeline. Is there a way to configure or specify a parameter to limit the timeline to only display the 10 latest tweets without having to load more?

**Comment by zedeus** [comment]
No, there is no parameter to do that. The first link performs a search using the SearchTimelime endpoint. The second link uses the endpoint for retrieving list tweets, which for whatever reason no longer supports the "limit" parameter. If you want to retrieve only 20 tweets you can use search, there is no other way.

**Comment by dontpnc** [comment]
Thank you for clarifying.

I'm leaning towards using the first link with the search endpoint to limit the timeline to 20 tweets. Could you please provide information on whether there is any distinction in the rate limiting when using the search endpoint compared to the endpoint for retrieving list tweets? Specifically, I'm concerned about the 500 request rate limit and how it might be affected by choosing one link over the other.

**Comment by zedeus** [comment]
The search endpoint is limited fairly heavily, allowing a max of 50 requests every 15 minutes. Note however there is another rate limit that can get triggered easily without requesting very often. Not much is known about it, can't help you sorry. You can see the base limit per endpoint here: https://github.com/zedeus/nitter/blob/583c858cdf3486451ed6a0627640844f27009dbe/src/auth.nim#L10-L24
