### ISSUE TITLE
Issue with Retweet Count Collection

### ISSUE THREAD

**Issue by NetworkWebMasters** [zedeus/nitter#1135]
I can't collect retweets count after 8-9 days

sinceDate = 2023-12-01
untilDate = 2023-12-17

I can only collects retweets count from 2023-12-08 to 2023-12-16 or 2023-12-09 to 2023-12-16

I can't collect retweets count from 2023-12-01 to 2023-12-08 or 2023-12-01 to 2023-12-09

**Comment by zedeus** [comment]
I don't know what you mean, please provide links to what works and what doesn't. Also, if you're scraping public instances, please don't.

**Comment by NetworkWebMasters** [comment]
I'm using ntscraper on VMware Ubuntu localhost nitter instance.

nitter is working properly on http://localhost, but when i try to scrap old tweet count it shows 0.

**Comment by zedeus** [comment]
Good to know, but I still need some queries to reproduce this. Please provide a nitter.net link.

**Comment by NetworkWebMasters** [comment]
Link: https://nitter.net/SalaarTheSaga

Example: 

If we try to scrap retweet counts from 2023-12-14 to 2023-12-21
Daily Retweet counts total shows properly like below

Date	Tweets	Retweets
Dec 20, 2023	10	4
Dec 19, 2023	11	10
Dec 18, 2023	14	18
Dec 17, 2023	7	4
Dec 16, 2023	5	4
Dec 15, 2023	8	2
Dec 14, 2023	3	1

If we trying to scrap retweet counts of this account from 2023-12-01 to 2023-12-13
Daily Retweet counts total shows 0.

Date	Tweets	Retweets
Dec 13, 2023	8	0
Dec 12, 2023	2	0
Dec 11, 2023	1	0
Dec 8, 2023 	1	0
Dec 7, 2023 	1	0
Dec 6, 2023 	2	0
Dec 5, 2023 	7	0
Dec 4, 2023 	2	0
Dec 3, 2023 	3	0
Dec 2, 2023 	7	0
Dec 1, 2023 	13	0

**Comment by NetworkWebMasters** [comment]
Unfortunately this is a problem with Nitter. As you can see when you specify the dates on the website and go to https://nitter.net/SalaarTheSaga/search?f=tweets&q=&since=2023-12-01&until=2023-12-13&near=, it only shows the tweets and no retweets. If you add the filter to only show the retweets, as in https://nitter.net/SalaarTheSaga/search?f=tweets&q=&f-nativeretweets=on&since=2023-12-01&until=2023-12-13&near=, it still shows no retweets.

**Comment by zedeus** [comment]
If you click the bird icon you'll see what Nitter is doing, and you can verify that it actually isn't a Nitter problem at all. The search Nitter performs through Twitter's API returns nothing, because that's what Twitter decided.

![Screenshot_2023-12-25-16-54-26-87_0b2fce7a16bf2b728d6ffa28c8d60efb](https://github.com/zedeus/nitter/assets/9434921/d2f1a0e8-866e-4d16-b5bf-c396c25cf67f)
