### ISSUE TITLE
Question about RSS Feed/Request and tokenCount = 10

### ISSUE THREAD

**Issue by dontpnc** [zedeus/nitter#1139]
I'm running an private instance but i want to understand how nitter works before running an public one and i have a question about rss.

RSS feed appears to be fetched or updated every 10 minutes. I'm contemplating setting this update frequency to 1 minute by adjusting the rssMinutes parameter.

Could kindly provide more details on how the RSS feed updates are handled? I'm interested in understanding whether this involves sending requests using my tokens at the specified interval (1 minute). Any insights into the mechanics behind the RSS feed updates and token usage would be greatly appreciated.

If i make a request to localhost:1111/i/lists/1111/rss does this count as Api.listTweets: request?
 

Nitter.conf file tokenCount = 10 but i have 20 tokens, does this mean nitter will ignore the other 10 tokens or should i update to tokenCount = 20?

**Comment by zedeus** [comment]
RSS gets cached for the duration of the minutes config you mentioned, defaulting to 15. When a user requests /rss nitter checks if that query has been cached, and then serves it if so. If not, the data gets fetched using the API and stored in the cache again. The data automatically gets removed after the rssMinutes have passed. Ignore tokenCount, it's a leftover from the old authentication strategy. All guest accounts will be used, assuming they're valid.

>If i make a request to localhost:1111/i/lists/1111/rss does this count as Api.listTweets: request?

Yes, same goes for every other page with RSS support.

**Comment by dontpnc** [comment]
Does Nitter automatically make requests to Twitter even when user don't specifically request RSS feed, especially when `rssMinutes` is set to 0?"

**Comment by zedeus** [comment]
No, it never makes any requests by itself
