### ISSUE TITLE
RSS feed: exlude Re:-tweets via search string?

### ISSUE THREAD

**Issue by gloschtla** [zedeus/nitter#114]
Can nitter's searching query RSS feed respect excluding strings? for example: excluding retweets and replies in the results of searched hashtag string

stackoverflow.com/questions/27941940/how-to-exclude-retweets-and-replies-in-a-search-api

**Comment by gloschtla** [comment]
Sorry, I found the answer. The feature is already implemented. 

After searching for your hashtag, just use the filter function by pressing on the drop down arrow on the right end of the search bar, in order to exclude Retweets and Replies.

**Comment by nogira** [comment]
For future reference to anyone that encounters this, here is an example:
`https://nitter.eu/search/rss?q=-filter:replies+from:elonmusk+min_faves:200+-dogecoin`

You have the start, `https://nitter.eu/search/rss?q=`, then the search query (same as if you type it in the twitter search bar) containing `-filter:replies` + `from:elonmusk` + `min_faves:200` + `-dogecoin`

More parameters can be found here: https://zapier.com/blog/twitter-advanced-search-guide/
