### ISSUE TITLE
Where do I put the guest_accounts.jsonl file? Putting it in the nitter folder in nitter's home does not do anything.

### ISSUE THREAD

**Issue by rikafuruda** [zedeus/nitter#1143]
This was originally an issue about an error 400 bad request, but after finding out the culprit (stated below)and creating a guest account, I still can't seem to get it to work.
Im very new to this stuff so I don't know where i'd put it outside of that folder.

**Comment by zedeus** [comment]
You need to follow these instructions: https://github.com/zedeus/nitter/wiki/Guest-Account-Branch-Deployment

**Comment by rikafuruda** [comment]
> You need to follow these instructions: https://github.com/zedeus/nitter/wiki/Guest-Account-Branch-Deployment

Hi, thank you for replying 😁
I managed to fix up the issues I was having before (https ones, it was an issue with Redis), but even after following the guest accounts guide, when i restart nitter I still can't view users or tweets.

**Comment by rikafuruda** [comment]
i fixed it i simply forgot to switch to the guest_accounts branch
