### ISSUE TITLE
Cannot load any content

### ISSUE THREAD

**Issue by naujokas2021** [zedeus/nitter#1153]
Hello,

I followed all steps how to launch nitter on the server. Looks like everything works, but no information is returned on any requests.

![image](https://github.com/zedeus/nitter/assets/88821797/917cb304-89bb-41f5-90e8-fe02d210838e)

Docker logs:

![image](https://github.com/zedeus/nitter/assets/88821797/2c348f71-a737-4b4a-9aed-bda6b2366da2)

Is there anything else what should be added but is not written on README?

**Comment by zedeus** [comment]
Follow this: https://github.com/zedeus/nitter/wiki/Guest-Account-Branch-Deployment
