### ISSUE TITLE
Alternative site for RSS feeds

### ISSUE THREAD

**Issue by TenebrisD90** [zedeus/nitter#1158]
If Nitter is dead, what do we do now to get feeds from Twitter?

**Comment by Just-Prog** [comment]
https://docs.rsshub.app/routes/social-media#twitter

need some configurations

**Comment by TenebrisD90** [comment]
> https://docs.rsshub.app/routes/social-media#twitter
> 
> need some configurations

Some user feeds don't work for some reason
![Capture](https://github.com/zedeus/nitter/assets/103512893/05987884-e99c-45f5-83a7-9566ae988122)

**Comment by Just-Prog** [comment]
> > https://docs.rsshub.app/routes/social-media#twitter
> > need some configurations
> 
> Some user feeds don't work for some reason ![Capture](https://private-user-images.githubusercontent.com/103512893/300865816-05987884-e99c-45f5-83a7-9566ae988122.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NTc2NjQsIm5iZiI6MTcwNjY1NzM2NCwicGF0aCI6Ii8xMDM1MTI4OTMvMzAwODY1ODE2LTA1OTg3ODg0LWU5OWMtNDVmNS04M2E3LTk1NjZhZTk4ODEyMi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQyMzI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWZkZDJlODZlNTcwZjlkYjVkNmY3ZjNlMzczYWNkNGZlYmRiMTI0Yjk5NzA3OGQxNDc2MTNiNWYyNDc2OGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kpn8m5kvbLa0I4GC8zXNSSEGioRxTBWM3dDb8Cg57zQ)

try to use self-hosted RSSHub instead of using official public instance (rsshub.app), it was banned from many websites with supported by RSSHub

**Comment by tweitzel** [comment]
RSShub uses the same auth mechanisms as nitter; it appears that entire API has now been rate limited to 0. An entirely new mechanism is required.

**Comment by Just-Prog** [comment]
> RSShub uses the same auth mechanisms as nitter; it appears that entire API has now been rate limited to 0. An entirely new mechanism is required.

sad :(
