### ISSUE TITLE
I'm new and I want to run a private instance to scrape tweets

### ISSUE THREAD

**Issue by CubeAuCarre** [zedeus/nitter#1163]
Hi !

For a webscraping project I tried to run a local instance of Nitter.

Tried downloading Nitter and running it on a local Redis server but I'm not sure if it's ran correctly.

I'm getting 

user@DESKTOP-ND6TROH:~/nitter_server/nitter$ ./nitter
Starting Nitter at http://shinywil
Connected to Redis at 127.0.0.1:6379

can i directly start to make requests to get tweets to : 127.0.0.1:6379 ? Is Nitter already connected and ready to print out tweets ?

Thank you in advance for your responses !!

**Comment by AlyoshaVasilieva** [comment]
Nitter no longer works.

**Comment by Nimble-Bubble** [comment]
If you use a version that supports regular accounts, you can use those for a local instance. We used to use guest accounts, but those can't be created anymore.

**Comment by ILudw1g** [comment]
There are some nitter instances that still work for me?

**Comment by AritzUMA** [comment]
There is a repository to do a local nitter with regular accounts to scrape tweets?
