### ISSUE TITLE
can I use nitter with my own account? how?

### ISSUE THREAD

**Issue by estebanlm** [zedeus/nitter#1168]
Hi, 
I understand the regular use of nitter is -at least for the moment-, dead since guest accounts no longer works. 
Now, I would like to use it as a frontend (and scrapper) for personal use it.
lurking here, it seems this can be done but I have no idea how to do it... any hints on what can I do?
thanks!

**Comment by estebanlm** [comment]
also, by curiosity... how the instances that are still working are doing it?

**Comment by zedeus** [comment]
Guest accounts still work, they just expire after 30 days and we no longer have a way to create them. Authentication using a real account is possible but has issues, you can find stuff about how to do it in recent replies to #983.
