### ISSUE TITLE
Make the frontpage be like Twitter's

### ISSUE THREAD

**Issue by Zero3K** [zedeus/nitter#117]
*subject*

In other words, allow a user to register an account on Nitter (or use a cookie that has a list of the inputted username's followed users) and then display the followed user's tweets, etc. on the frontpage (instead of just having the username search).

**Comment by IamRifki** [comment]
I'm pretty sure an accounts feature will be implemented soon.

**Comment by Zero3K** [comment]
Will it allow the addition of my feature request?

**Comment by IamRifki** [comment]
Yes, have you even read the README?

**Comment by Zero3K** [comment]
Oh, I didn't read it fully. That's good to know.
