### ISSUE TITLE
list of Nitter instances are gone?

### ISSUE THREAD

**Issue by expertmanofficial** [zedeus/nitter#1170]
seriously, please make it to stay. I want to know what Nitter instances are currently working.

**Comment by 2gn** [comment]
They apparently removed it, as [the page](https://github.com/zedeus/nitter/wiki/Instances) is currently gone and displays markdown editor when accessed.
Also, the official instance of nitter is down right now. I wonder what happened to zedeus.

**Comment by ButteredCats** [comment]
You can use https://status.d420.de/ to view currently working Nitter instances. Although soon enough they'll all be nonfunctional.
