### ISSUE TITLE
What public instances are working as of today?

### ISSUE THREAD

**Issue by TheArgentinian** [zedeus/nitter#1176]
It says they will eventually all stop working. So, which can still be used? Save me time from trying them all.

**Comment by DKB-91** [comment]
https://status.d420.de/

To be captain obvious, if there is no bar, that instance has bitten the dust.

**Comment by TheArgentinian** [comment]
> https://status.d420.de/
> 
> To be captain obvious, if there is no bar, that instance has bitten the dust.

ty, I was using the Wiki here but the checkboxes never get updated

**Comment by beansofhell** [comment]
https://github.com/sekai-soft/freebird

use free bird

dont forget 
proxiesVideos = false

TO ENABLE VIDEO PLAYBACK !!!!!!!!!!
![image](https://github.com/zedeus/nitter/assets/126506518/745806b5-0755-44ab-8096-b6bf6773a129)
![image](https://github.com/zedeus/nitter/assets/126506518/d25323ea-a8af-49e0-bb3a-da89902ab3fc)


ENJOY 
![image](https://github.com/zedeus/nitter/assets/126506518/04d6504e-6e27-4600-9632-c22b4447dd8f)


HOST YOUR OWN 

AND USE YOUR OWN INSTACE,, YOU MUST PUT A BURNER TWITTER ACCOUNT THO 


BUT ITS PRETTY EASY USING DOCKER-CONPOSE

**Comment by ILudw1g** [comment]
will this still work after nitter is down now after recent events? @beansofhell

**Comment by beansofhell** [comment]
> will this still work after nitter is down now after recent events? @beansofhell

Yes … use FreeBird 
You must use docker

but you can use tailspace…  no need to be too tech savvy just follow the README 

It worked for me

**Comment by beansofhell** [comment]
> will this still work after nitter is down now after recent events? @beansofhell

https://github.com/sekai-soft/freebird/tree/master

Follow the readme … don’t forget to a burner account there
