### ISSUE TITLE
building failed

### ISSUE THREAD

**Issue by grandpa1946** [zedeus/nitter#1177]
nitter/src/nitter.nim(9, 8) Error: cannot open file: types
       Tip: 42 messages have been suppressed, use --verbose to show them.
nimble.nim(229)          buildFromDir

    Error:  Build failed for the package: nitter

**Comment by zedeus** [comment]
The project is dead, and you didn't include enough information to provide assistance.

**Comment by grandpa1946** [comment]
> The project is dead, and you didn't include enough information to provide assistance.

 nimble build --verbose -d:release
     Info:  Nimble data file "/home/debian/.nimble/nimbledata2.json" has been loaded.
  Verifying dependencies for nitter@0.1.0
    Reading official package list
   Checking for jester@#baca3f
     Info:  Dependency on jester@#baca3f already satisfied
  Verifying dependencies for jester@0.5.0
    Reading official package list
   Checking for httpbeast@>= 0.3.0
     Info:  Dependency on httpbeast@>= 0.3.0 already satisfied
  Verifying dependencies for httpbeast@0.4.1
    Reading official package list
   Checking for asynctools@#0e6bdc3ed5bae8c7cc9
     Info:  Dependency on asynctools@#0e6bdc3ed5bae8c7cc9 already satisfied
  Verifying dependencies for asynctools@0.1.1
    Reading official package list
   Checking for https://github.com/timotheecour/asynctools@#pr_fix_compilation
     Info:  Dependency on https://github.com/timotheecour/asynctools@#pr_fix_compilation already satisfied
  Verifying dependencies for asynctools@0.1.1
    Reading official package list
   Checking for karax@#5cf360c
     Info:  Dependency on karax@#5cf360c already satisfied
  Verifying dependencies for karax@1.3.0
    Reading official package list
   Checking for ws@any version
     Info:  Dependency on ws@any version already satisfied
  Verifying dependencies for ws@0.5.0
    Reading official package list
   Checking for dotenv@>= 2.0.0
     Info:  Dependency on dotenv@>= 2.0.0 already satisfied
  Verifying dependencies for dotenv@2.0.1
    Reading official package list
   Checking for sass@#7dfdd03
     Info:  Dependency on sass@#7dfdd03 already satisfied
  Verifying dependencies for sass@0.3.0
    Reading official package list
   Checking for nimcrypto@#a079df9
     Info:  Dependency on nimcrypto@#a079df9 already satisfied
  Verifying dependencies for nimcrypto@0.6.0
    Reading official package list
   Checking for markdown@#158efe3
     Info:  Dependency on markdown@#158efe3 already satisfied
  Verifying dependencies for markdown@0.8.6
    Reading official package list
   Checking for packedjson@#9e6fbb6
     Info:  Dependency on packedjson@#9e6fbb6 already satisfied
  Verifying dependencies for packedjson@0.2.2
    Reading official package list
   Checking for supersnappy@#6c94198
     Info:  Dependency on supersnappy@#6c94198 already satisfied
  Verifying dependencies for supersnappy@2.1.3
    Reading official package list
   Checking for redpool@#8b7c1db
     Info:  Dependency on redpool@#8b7c1db already satisfied
  Verifying dependencies for redpool@0.1.0
    Reading official package list
   Checking for https://github.com/zedeus/redis@#d0a0e6f
     Info:  Dependency on https://github.com/zedeus/redis@#d0a0e6f already satisfied
  Verifying dependencies for redis@0.3.0
    Reading official package list
   Checking for https://github.com/zedeus/redis@#d0a0e6f
     Info:  Dependency on https://github.com/zedeus/redis@#d0a0e6f already satisfied
  Verifying dependencies for redis@0.3.0
    Reading official package list
   Checking for zippy@#ca5989a
     Info:  Dependency on zippy@#ca5989a already satisfied
  Verifying dependencies for zippy@0.10.7
    Reading official package list
   Checking for flatty@#e668085
     Info:  Dependency on flatty@#e668085 already satisfied
  Verifying dependencies for flatty@0.3.4
    Reading official package list
   Checking for jsony@#1de1f08
     Info:  Dependency on jsony@#1de1f08 already satisfied
  Verifying dependencies for jsony@1.1.5
    Reading official package list
   Checking for oauth@#b8c163b
     Info:  Dependency on oauth@#b8c163b already satisfied
  Verifying dependencies for oauth@0.10
    Reading official package list
   Checking for sha1@any version
     Info:  Dependency on sha1@any version already satisfied
  Verifying dependencies for sha1@1.1
   Building nitter/nitter using c backend
  Executing /home/debian/.nimble/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.1.0 --path:/home/debian/.nimble/pkgs2/karax-1.3.0-481742b3d0c0e3c92174b1bdd08a4a94853250af --path:/home/debian/.nimble/pkgs2/packedjson-0.2.2-8aec1ecc233e2ac4d04f0a3dd02d03c73d7b4665 --path:/home/debian/.nimble/pkgs2/redis-0.3.0-9b1a45983890db1f1775ecddc51925000d183c57 --path:/home/debian/.nimble/pkgs2/supersnappy-2.1.3-a197de45773703f7134301043e416fb5025c614d --path:/home/debian/.nimble/pkgs2/asynctools-0.1.1-54314dceabb06b20908ecb0f2c007e9ff3aaa054 --path:/home/debian/.nimble/pkgs2/ws-0.5.0-ae4daf4ae302d0431f3c2d385ae9d2fe767a3246 --path:/home/debian/.nimble/pkgs2/zippy-0.10.7-8ec66d2af90ca93f96c0388ae933f03a60ff67d1 --path:/home/debian/.nimble/pkgs2/flatty-0.3.4-48109ac5d2f65f9d1a61f5077ba0eb61d104a90a --path:/home/debian/.nimble/pkgs2/jsony-1.1.5-143f6938d399f92f5bf6c7dcf4e589f2b28634db --path:/home/debian/.nimble/pkgs2/httpbeast-0.4.1-b23e57a401057dcb9b7fae1fb8279a6a2ce1d0b8 --path:/home/debian/.nimble/pkgs2/markdown-0.8.6-53b43fa57e6aa106e634ae97b793f1c6e7da7ce6 --path:/home/debian/.nimble/pkgs2/jester-0.5.0-afb591b0a6cd39f4d5f2195bffb7095640e3da97 --path:/home/debian/.nimble/pkgs2/redpool-0.1.0-3d2665fc592c25cbe5d253957bc16e9666227c3d --path:/home/debian/.nimble/pkgs2/asynctools-0.1.1-5e7df4178ee5c148532ff8c44a22015d576624d8 --path:/home/debian/.nimble/pkgs2/sass-0.3.0-21e4dcb1ab3d32d343df1d8293affa9ea9c92f70 --path:/home/debian/.nimble/pkgs2/sha1-1.1-2610d27cf248adf98fd9b86e906eb87781ba9d8c --path:/home/debian/.nimble/pkgs2/nimcrypto-0.6.0-be9a4654dd5839b97f39d5060d98f18ba868623c --path:/home/debian/.nimble/pkgs2/oauth-0.10-55b2ff9c5051f3bc8712f39b942556c493b0a9a5 --path:/home/debian/.nimble/pkgs2/dotenv-2.0.1-9a9e39544f129e6666935796610da79fbe724510 -o:/home/debian/nitter/nitter /home/debian/nitter/src/nitter.nim
Hint: used config file '/home/debian/.choosenim/toolchains/nim-2.0.2/config/nim.cfg' [Conf]
Hint: used config file '/home/debian/.choosenim/toolchains/nim-2.0.2/config/config.nims' [Conf]
Hint: used config file '/home/debian/nitter/config.nims' [Conf]
...................................................................................................................................................................
/home/debian/nitter/src/nitter.nim(9, 8) Error: cannot open file: types
nimble.nim(229)          buildFromDir

    Error:  Build failed for the package: nitter
     Info:  Nimble data file "/home/debian/.nimble/nimbledata2.json" has been saved.
