### ISSUE TITLE
Are there working "twitter account to rss feed" alternatives now?

### ISSUE THREAD

**Issue by gety9** [zedeus/nitter#1179]
I don't need feed / tweets hosting. I just need feed generation part.

Example: i provide names of accounts: jamesbond9, wildtreeman1

and it generates "jamesbond9.xml" and "wildtreeman1.xml" with tweets and url to tweet. (i am fine reading tweets on twitter, i just don't want to constantly check manually if there is something new)

**Comment by iitzRichie** [comment]
Looking for the same myself. I think we're just gonna have to go back to that shithole and turn notifications on, which don't even work most times 😑.

**Comment by zedeus** [comment]
Not really.
