### ISSUE TITLE
TLS certificate issue with Nitter.net

### ISSUE THREAD

**Issue by abshda** [zedeus/nitter#118]
![Screenshot_20200202-023046__01](https://user-images.githubusercontent.com/17269831/73598938-0c157380-4564-11ea-80a9-591de3c5d587.jpg)

**Comment by Perflyst** [comment]
Until this issue is resolved, there are other public instances available: https://github.com/zedeus/nitter/wiki/Instances

**Comment by zedeus** [comment]
Hi, sorry about the downtime. I was at FOSDEM when it happened and unable to fix it till now.
