### ISSUE TITLE
[Question] https://nitter.esmailelbob.xyz/ this instance is working till now and if i selfhost nitter i think it will work too?

### ISSUE THREAD

**Issue by HakaishinShwet** [zedeus/nitter#1181]
selfhosting with docker and just browsing and seeing tweets this much selfhosted nitter can do?

**Comment by HakaishinShwet** [comment]
btw thanks for your hardwork @zedeus

**Comment by pin-grid-array** [comment]
Yes, of course selfhosting will work, and it'll be the only way to use Nitter going forward. All public instances that use guest tokens will be dead soon.

**Comment by EsmailELBoBDev2** [comment]
PS: my instance is dead

**Comment by vehosah** [comment]
And it's alive again

**Comment by EsmailELBoBDev2** [comment]
You know its rate limited right?
