### ISSUE TITLE
Everything running fine in local but unable to fetch any post or tweet in selfhosted frontend, nitter.esmailelbob.xyz this instance is still working so whats the issue in my case?

### ISSUE THREAD

**Issue by HakaishinShwet** [zedeus/nitter#1183]
Attaching all files ss you can see everything working well locally with reverse proxing with nginxproxymanager with docker compose method but unable to fetch twitter post or users.
From my recent issue i created someone was saying that selfhosting way is still working plus this nitter.esmailelbob.xyz/ public instance is still working fine so whats the issue in my case can anyone guide me please :-))

![20240225_09h26m32s_grim](https://github.com/zedeus/nitter/assets/55040435/bbcbeb90-58fc-4538-a9f5-f9a2a1a7806c)
![20240225_09h26m08s_grim](https://github.com/zedeus/nitter/assets/55040435/1065197e-b790-4c95-a1bc-65e4c128e8cf)
![20240225_09h25m13s_grim](https://github.com/zedeus/nitter/assets/55040435/e7b67201-602a-4087-8c6f-785feaf9e073)
![20240225_09h23m32s_grim](https://github.com/zedeus/nitter/assets/55040435/433daf28-70e6-4324-b2ff-276cb98e8229)
![20240225_09h23m26s_grim](https://github.com/zedeus/nitter/assets/55040435/9971347c-ab4e-40df-9abe-2ba1ad5477fe)
![20240225_09h23m18s_grim](https://github.com/zedeus/nitter/assets/55040435/f23bc076-bbab-4a86-9f66-3c59ed9c238e)
![20240225_09h21m03s_grim](https://github.com/zedeus/nitter/assets/55040435/b5167f11-114c-4342-a43c-55967d1f644b)
![20240225_09h20m28s_grim](https://github.com/zedeus/nitter/assets/55040435/d84a034f-d919-43a6-8193-f4d56659e2f3)

**Comment by HakaishinShwet** [comment]
@zedeus any idea?

**Comment by zedeus** [comment]
Self-hosting doesn't work out of the box anymore, Nitter is broken. See #1156
