### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by cmj** [zedeus/nitter#1187]
After switching over to throwaway accounts the other day, we are seeing randomness in items injected into feeds which disrupts the hash for changes. My only observation is [who to follow](https://i.imgur.com/Nj3jTQ4.png) injected at random 1-3 times in timelines.

These are happening when using _legit_ accounts. Never seen on guest accounts obviously as guests can't follow users.
I know nitter is dead but for the rest of us, I'm curious if there's something to look at to filter the raw feed.

- https://i.imgur.com/Nj3jTQ4.png this will be injected 1-2 times at random
- https://i.imgur.com/OZWFFmL.png the change it interrupts

I looked at this briefly and this is beyond rss.nimf.

**Comment by TechFanTheo** [comment]
Can you clarify or explain further ?

**Comment by cmj** [comment]
@TechFanTheo Yes. I was just coming back to this today. Turns out after a few days the feeds righted themselves.

The feeds would be incomplete or interrupted by who-to-follow elements.

The parser even shows ```startsWith("tweet"):``` so these other elements should not have shown up.  So I'm not sure how the feeds where wrongly interpreted.

I cannot put my finger on what happened but it was definitely an issue.
Only takeaway is, it takes new accounts a few days to not be manipulated.

Simple RSS feed tool to check:
https://gist.github.com/cmj/d3fe8e4f6beb72a1cafec8cc352b7430

Here is a GGI script that works:
https://gist.github.com/cmj/72ff073bd8e6c0a2ac7b26d88fb28c54

**Comment by cmj** [comment]
Closing this as it doesn't seem to be an issue anymore.
