### ISSUE TITLE
Nitter is dead completely now

### ISSUE THREAD

**Issue by vehosah** [zedeus/nitter#1189]
Now what guys, any idea 😔

**Comment by dieperdev** [comment]
@vehosah https://nitter.poast.org is the *only* working public instance right now and doesn’t require verification (as listed [here](https://github.com/zedeus/nitter/wiki/Instances#public)), but please don’t use it for web scrapers 🙂.

**Comment by TheArgentinian** [comment]
> @vehosah https://nitter.poast.org is the _only_ working public instance right now and doesn’t require verification (as listed [here](https://github.com/zedeus/nitter/wiki/Instances#public)), but please don’t use it for web scrapers 🙂.

![image](https://github.com/zedeus/nitter/assets/59894621/82ca682e-36bb-4901-b0b3-bc8f2357aa42)

**Comment by dieperdev** [comment]
> > @vehosah https://nitter.poast.org is the _only_ working public instance right now and doesn’t require verification (as listed [here](https://github.com/zedeus/nitter/wiki/Instances#public)), but please don’t use it for web scrapers 🙂.
> 
> ![image](https://private-user-images.githubusercontent.com/59894621/311443374-82ca682e-36bb-4901-b0b3-bc8f2357aa42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTQyNzMsIm5iZiI6MTcwOTk5Mzk3MywicGF0aCI6Ii81OTg5NDYyMS8zMTE0NDMzNzQtODJjYTY4MmUtMzZiYi00OTAxLWIwYjMtYmM4ZjIzNTdhYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE0MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzRjN2UzNTY1NWRiYzg3ZWJmZDAyMGQxMDBiMTJmZTJmMmQ2YzQ3ZWE1NjIxYjcxMTIwODY3NTM1NDk1ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WEwT4GWgk4syLQ3LdlUrERu0RbvuxFq0hwu0DsYAKc8)

Not sure why that happens, it’s working perfectly fine for me.

**Comment by TheArgentinian** [comment]
> > > @vehosah https://nitter.poast.org is the _only_ working public instance right now and doesn’t require verification (as listed [here](https://github.com/zedeus/nitter/wiki/Instances#public)), but please don’t use it for web scrapers 🙂.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/59894621/311443374-82ca682e-36bb-4901-b0b3-bc8f2357aa42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5OTQyNzMsIm5iZiI6MTcwOTk5Mzk3MywicGF0aCI6Ii81OTg5NDYyMS8zMTE0NDMzNzQtODJjYTY4MmUtMzZiYi00OTAxLWIwYjMtYmM4ZjIzNTdhYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE0MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzRjN2UzNTY1NWRiYzg3ZWJmZDAyMGQxMDBiMTJmZTJmMmQ2YzQ3ZWE1NjIxYjcxMTIwODY3NTM1NDk1ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WEwT4GWgk4syLQ3LdlUrERu0RbvuxFq0hwu0DsYAKc8)
> 
> Not sure why that happens, it’s working perfectly fine for me.

I hit the "Return to Nitter" on your link and it works :D
