### ISSUE TITLE
Feature Request: uptime monitor for nitter instances

### ISSUE THREAD

**Issue by gloschtla** [zedeus/nitter#119]
is it possible to create an uptime monitor for all open nitter instances, so nitter.net can automatically forward traffic to them, whenever nitter.net is down? Maybe you can cooperate with the infrastructure of uptime.invidio.us

**Comment by zedeus** [comment]
I'd like to make a nice featureful one similar to searx.space with versioning and latency, but for now I can refer you to https://xnaas.github.io/nitter-instances/ by @xnaas

**Comment by xnaas** [comment]
Additionally, @gloschtla, you can review the wiki (https://github.com/zedeus/nitter/wiki/Instances#third-party-nitter-services) for other helpful tools. [Farside](https://github.com/benbusby/farside) is another tool that exists, though I've never personally tried it out.
