### ISSUE TITLE
compilation problem with libsass

### ISSUE THREAD

**Issue by OleaSTeROleaSTeR** [zedeus/nitter#1192]
hello all

I'm trying to run nitter on an ubuntu machine with a rootless user, but with GCC.
I compiled/installed nimble libpcre redis, without problem, but I have a problem with libsass.

```
nimble scss
   Compiling tools/gencss (from package nitter) using c backend
could not load: libsass.so
```

I cannot install this library with a package manager because I am not root (apt aptitude).

I found a nimble package which adds the libsass library to nimble
`https://github.com/dom96/sass`

I added it to nim with the command

`nimble install sass`

but "nimble scss" still gives me the same error.

is "nimble scss" supposed to work with dom96/sass???

**Comment by zedeus** [comment]
>I cannot install this library with a package manager because I am not root (apt aptitude).

Then you can't build Nitter the standard way, but you can use the Docker image instead. Maybe you can download the .so file needed from your distro's repository and manually include that instead, but this is advanced and not something I can help with.

**Comment by OleaSTeROleaSTeR** [comment]
I have the "libsass.so" libraries. I compiled them. 

`autonia@wayne:~/opt/nitter$ ls /home/autonia/opt/sass/lib
 libsass.a  libsass.la  libsass.so  libsass.so.1  libsass.so.1.0.0  pkgconfig`

but I can't add the custon path to these libraries so that NIM can find them
Under Linux you can add alternative LIBRARY path with the `LD_LIBRARY_PATH` command, but unfortunately for me, it doesn't work on UBUNTU.

for the moment I am looking for the solution on UBUNTU forums. If it's possible !!!

**Comment by OleaSTeROleaSTeR** [comment]
finally I found the solution...
I copied the libsass.so library into the /lib directory of nimble (/nim/lib).
nimble finds it and the compilation finishes without errors

` Compiling tools/gencss (from package nitter) using c backend
Compiled to public/css/style.css
   Success: Execution finished`

I can reach Niiter via a web browser. everything looks ok...

except that I come across a 404 error with all my requests
` "404 Not Found:  --- url: https://api.twitter.com/gr........"`

**Comment by zedeus** [comment]
As expected. Refer to the other issues.
