### ISSUE TITLE
Cannot automatically access Nitter.poast.org

### ISSUE THREAD

**Issue by arusyo** [zedeus/nitter#1196]
I use Google Apps Script to automatically retrieve the rss feed every 15 minutes, but recently (especially in the last few days) when I try to retrieve the rss feed on nitter.poast.org, it says 'Address unavailable' and I cannot retrieve it continuously. I can access it manually... Has nitter.poast.org blocked such access?

**Comment by pin-grid-array** [comment]
> Has nitter.poast.org blocked such access?

Probably.

But I think you will receive a better answer if you contact the owner of that instance. This is what the owner wrote in a different thread:

<img width="590" alt="fffffffffffffff" src="https://github.com/zedeus/nitter/assets/62707303/eea4ae2c-bc01-4373-8964-d6e65c894679">

**Comment by arusyo** [comment]
oh I see...
I didn't know that statement...
 Thank you for telling about it.
 I'll email him!
