### ISSUE TITLE
Required input 'Signup' not provided."

### ISSUE THREAD

**Issue by aman29271** [zedeus/nitter#1197]
Hi ! I am new to this community. I was doing this local setup of nitter on my desktop. The last request provided for the retrieval of Oauth code for guest account is not working for me. I am getting this error.

Request :
`curl -s -XPOST 'https://api.twitter.com/1.1/onboarding/task.json' \
          -H 'Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAFXzAwAAAAAAMHCxpeSDG1gLNLghVe8d74hl6k4%3DRUMF4xAQLsbeBhTSRrCiQpJtxoGWeyHrDb5te2jpGskWDFW82F' \
          -H 'Content-Type: application/json' \
          -H "User-Agent: TwitterAndroid/10.10.0" \
          -H "X-Guest-Token: ${guest_token}" \
          -d "{\"flow_token\":\"${flow_token}\",\"subtask_inputs\":[{\"open_link\":{\"link\":\"next_link\"},\"subtask_id\":\"NextTaskOpenLink\"}]}" | jq -c -r '.subtasks[0]|if(.open_account) then {oauth_token: .open_account.oauth_token, oauth_token_secret: .open_account.oauth_token_secret} else empty end'`

Response : 

`{
	"errors": [
		{
			"code": 366,
			"message": "Required input 'Signup' not provided."
		}
	]
}`

I am sucessfully able to get the flow token but the Oauth Token is somehow now working out.

Thanks for help

**Comment by zedeus** [comment]
Hate to break it to ya, but guest accounts don't work anymore. The only way to use Nitter now is by creating burner accounts, which I don't officially support yet. See this post for a collection of other posts talking about it: https://github.com/zedeus/nitter/issues/983#issuecomment-1944095658
