### ISSUE TITLE
Nitter.com outdated certificate

### ISSUE THREAD

**Issue by CodeSoftGit** [zedeus/nitter#1198]
Nitter.net has an outdated certificate, which causes issues with HSTS.

![image](https://github.com/zedeus/nitter/assets/137560679/33c5c4cb-ce86-48aa-9b77-db50e344d38e)

**Comment by pin-grid-array** [comment]
[It's been like that for a while](https://github.com/zedeus/nitter/issues/1174)  and won't be fixed. Also, Nitter is dead, outside of hosting an instance yourself using the credentials of an actual Twitter account.
