### ISSUE TITLE
Not all attachments are shown

### ISSUE THREAD

**Issue by ButteredCats** [zedeus/nitter#1199]
It looks like not all attachments are showing up sometimes. It may only apply to videos or there's something specific that's broken, because I know just photos work fine.

Take a look at https://*nitter_instance*/MattBinder/status/1785778592967766297 versus https://twitter.com/MattBinder/status/1785778592967766297

It happens both on poast and my private instance. Can't really test it anywhere else.

On Nitter you're only able to see the picture and the other attached video doesn't appear.

**Comment by zedeus** [comment]
That's #697, it was never implemented

**Comment by ButteredCats** [comment]
Oh my bad, this is the first time I've ever run into this (or at least noticed it) and hadn't seen that issue.

I'll close this.
