### ISSUE TITLE
Warn users in wiki about controversial instance from poast.org hosting nazi/hate-speech content

### ISSUE THREAD

**Issue by notune** [zedeus/nitter#1201]
I already tried removing the poast.org instance for hosting nazi content from the instances wiki. Unfortunately @zedeus reverted this. I am unsure why. I think this kind of instance should not be promoted for obvious reasons. 
Again, here is the proof that the nitter.poast.org instance is ran by literal nazis:
https://archive.is/6sUHJ: poast.org -> linking to owner @graf (https://poa.st/@graf), @graf is retweeting nazi account @NorseRealist (retweet cant be archived but here is owners reply): https://archive.is/xdlr6, and just in case if you are still wondering if @NorseRealist really is a nazi account: https://poa.st/@NorseRealist/posts/AircNshd4rYmUULOTY, also the fact that they have a nazi swastika emote named ":windmilloffriendship:" should already say everything

There are enough other instances that work without any problems, and aren't posting hatespeech/nazi content:
[nitter.privacydev.net](https://nitter.privacydev.net/) 	🇫🇷 
[xcancel.com](https://xcancel.com/) 	🇺🇸 	✅ 	
[nitter.tiekoetter.com](https://nitter.tiekoetter.com/) 	🇩🇪 	✅ 	
[bird.habedieeh.re](https://bird.habedieeh.re/) 	🇨🇦 	✅ 	
[nitter.kavin.rocks](https://nitter.kavin.rocks/) 	🇮🇳 	✅ 	
[t.com.sb](https://t.com.sb/) 	🇪🇪 	✅ 	
[nitter.qwik.space](https://nitter.qwik.space/) 	🇸🇪 	✅ 	
[nitter.lunar.icu](https://nitter.lunar.icu/) 	🇩🇪 	✅

**Comment by notune** [comment]
@bkiac @skyler14 why the thumbs down? Do you think my statement is false, or do you think it doesn't matter what they are hosting and we should promote them regardless of what they do?

**Comment by erikk333** [comment]
People do have extremely disturbing thoughts. But if this isn't being enforced in the nitter instance itself I see no reason to remove it

**Comment by notune** [comment]
> People do have extremely disturbing thoughts. But if this isn't being enforced in the nitter instance itself I see no reason to remove it

the problem I see here, is that the owner of poast.org, is highly likely also the owner of nitter.poast.org. I think its absolutely inappropriate to list an instance where the owner of the nitter server is retweeting and promoting nazi content. Moreover, if I am in the EU, I can get into legal troubles by accessing a domain with illegal content. If a user simply wants to use nitter, and looks in the wiki, and doesnt know what kind of content is hosted on poast.org, nitter being the subdomain, then he could get into trouble for accessing such content regularly. I think we should at least put a disclaimer that the underlying server is potentially hosting illegal content: https://en.wikipedia.org/wiki/Bans_on_Nazi_symbols

**Comment by notune** [comment]
I added a disclaimer to the wiki. I think this is the evry least we can do. At least to inform people what kind of site they would be using.

**Comment by BitesizedLion** [comment]
> I think its absolutely inappropriate to list an instance where the owner of the nitter server is retweeting and promoting nazi content

Why? I don't agree with his view but what does his views have to do with the Nitter instance?

They're not promoting anything on the instance and it's not monetized as far as I can see.

> Moreover, if I am in the EU, I can get into legal troubles by accessing a domain with illegal content. If a user simply wants to use nitter, and looks in the wiki, and doesnt know what kind of content is hosted on poast.org, nitter being the subdomain, then he could get into trouble for accessing such content regularly.

You should back this up with some sources, also you're not "accessing such content" when you visit nitter.poast.org because nitter.poast.org and poast.org aren't the same.

> I added a disclaimer to the wiki.

I just reverted that, it should be discussed first.

**Comment by notune** [comment]
OK to be honest I am not 100% sure if it is illegal here in the EU. I am not a lawyer. But what I can tell you is that the server [is owned by kiwifarms](https://news.ycombinator.com/item?id=39162384) , which is such an extreme group that even the very liberal cloudflare blocked them. https://en.m.wikipedia.org/wiki/Kiwi_Farms
I am not saying we need to remove them from the wiki, but at the very least put some form of disclaimer there what kind of people are hosting this. I am pretty sure most people wouldn't want to support such people, but censoring this information on the wiki is unnecessary at best.

**Comment by BitesizedLion** [comment]
> OK to be honest I am not 100% sure if it is illegal here in the EU. I am not a lawyer.

Then don't say that?

> But what I can tell you is that the server [is owned by kiwifarms](https://news.ycombinator.com/item?id=39162384)

I don't see anything actually proving that, Poast and KiwiFarms aren't owned by the same person I can say that at least.

Poast is owned by this "graf" guy, KiwiFarms is owned by "null"/joshua moon

The server that hosts nitter.poast.org is hosted by WholeSale Internet, KiwiFarms is hosted at AS399647 "Rumble USA Inc." 

```
❯ ipinfo nitter.poast.org
Core
- IP           173.208.145.50
- Anycast      false
- Hostname     nitter.poast.org
- City         Kansas City
- Region       Missouri
- Country      United States (US)
- Flag         🇺🇸
- Currency     USD ($)
- Location     39.0997,-94.5786
- Organization AS32097 WholeSale Internet, Inc.
- Postal       64170
- Timezone     America/Chicago
```

**Comment by notune** [comment]
Just because they are on different servers doesn't mean they aren't hosted by the same person. Also just because I wanted to remove the instance doesn't mean that we need to remove information about it.

**Comment by BitesizedLion** [comment]
> Just because they are on different servers doesn't mean they aren't hosted by the same person.

I'm just saying I don't see any evidence to support that claim.

**Comment by notune** [comment]
Also I am not the only one wanting to remove them from the wiki: https://github.com/zedeus/nitter/wiki/Instances/_compare/1c842904d42bfcd84e3820fb9518412bce2746a1

**Comment by BitesizedLion** [comment]
> Also I am not the only one wanting to remove them from the wiki: [Wiki: Instances/_compare/1c842904d42bfcd84e3820fb9518412bce2746a1 ()](https://github.com/zedeus/nitter/wiki/Instances/_compare/1c842904d42bfcd84e3820fb9518412bce2746a1)

Nobody said you were the only one.

**Comment by BitesizedLion** [comment]
I would support removal if the instance itself displayed any disgusting content like that, but it just doesn't seem to be the case.

**Comment by notune** [comment]
The question is: What speaks against adding a disclaimer, saying that the poast.org instance (which is linked to on https://nitter.poast.org/about) is blocked by most mastodon instances for hate speech.

**Comment by notune** [comment]
I have to apologize. I just asked some lawyers and it is legal to access this site, because it is hosted in the US. It would be illegal to host it in Germany, but since it's not the case, it is legal. So I have to apologize for removing the instance without first starting this discussion.

**Comment by notune** [comment]
I would however greatly appreciate it if we could add some kind of disclaimer maybe like this: "Disclaimer: nitter.poast.org is a controversial instance, because the underlying mastodon server on poast.org is blocked by most Mastodon servers for hate-speech"

**Comment by erikk333** [comment]
Disclaimer sounds as a good idea. The instance is still listed because it's functional and the user is informed

**Comment by notune** [comment]
Ok great. @BitesizedLion is it OK for you too?

**Comment by notune** [comment]
I wasn't complaining I was simply not understanding why I was getting downvotes. This is why I asked. There is no other reason. Also the admin does not only tolerate them he is retweeting accounts that have nazi swastika emotes in his profile, and are posting antisemitic things. I would favor a deletion of that instance in the wiki, but I am glad if we can simply agree on a short disclaimer, that tells nitter users that the underlying mastodon server on poast.org is blocked by most Mastodon servers for hate-speech.

**Comment by BitesizedLion** [comment]
> Ok great. @BitesizedLion is it OK for you too?

I still don't really understand why it's necessary, as I really don't see how the poast.org Mastodon instance being "blocked by most mastodon instances for hate speech" is relevant to the Nitter instance.

**Comment by iiTzRichie** [comment]
Apologies if this sounds like I don't know what I'm talking about, because honestly I just don't care enough to follow all the religion/ideology bs in the world, but wouldn't you need to be searching for it to see that type of content? You're linking to the account of the instance owner as evidence of the owner being that type of person, but who's even looking at their account to begin with?

**Comment by notune** [comment]
> Apologies if this sounds like I don't know what I'm talking about, because honestly I just don't care enough to follow all the religion/ideology bs in the world, but wouldn't you need to be searching for it to see that type of content? You're linking to the Twitter account of the instance owner as evidence of the owner being that type of person, but who's even looking at their account to begin with?

It's not their Twitter account. I was simply interested in seeing who hosted the nitter.poast.org instance so I went to poast.org. And when clicking on the owner @ graf, the first thing I am seeing is that he is retweeting nazi content. (on the server poast.org which is a Mastodon instance hosted on their server) I am not using this instance anymore, and I just wanted to warn others about the instance too. I think it's reasonable to add this information to the wiki.

**Comment by BitesizedLion** [comment]
> > Apologies if this sounds like I don't know what I'm talking about, because honestly I just don't care enough to follow all the religion/ideology bs in the world, but wouldn't you need to be searching for it to see that type of content? You're linking to the Twitter account of the instance owner as evidence of the owner being that type of person, but who's even looking at their account to begin with?
> 
> It's not their Twitter account. I was simply interested in seeing who hosted the nitter.poast.org instance so I went to poast.org. And when clicking on the owner @ graf, the first thing I am seeing is that he is retweeting nazi content. (on the server poast.org which is a Mastodon instance hosted on their server) I am not using this instance anymore, and I just wanted to warn others about the instance too. I think it's reasonable to add this information to the wiki.

Actually that post wasn't "nazi content", it was a clip of a cat playing with a fridge magnet. The guy who posted it might be a nazi but that post was not "nazi content".

**Comment by zedeus** [comment]
Your arguments against having the instance on the instance list are frankly invalid. You claim a user might get in trouble for accessing a domain that hosts illegal content, well guess what, Twitter hosts plenty of it, so it doesn't matter which instance you pick. The host's political beliefs couldn't matter less. They put a lot of effort into running a public instance with hundreds of real accounts as a high effort public utility with zero return. Using the instance isn't exactly going to fund Nazi extremism or something, it only costs them time and money.  What you're doing is only wasting people's time and robbing people of a very useful utility. Removing the instance is unacceptable, and adding a disclaimer is completely unnecessary. Closing.

**Comment by notune** [comment]
The problem I see here is that, as the instance nitter.poast.org gets more popular, poast.org might also get more popular, the nitter server being an ad for poast.org. It's like those companies giving away freebies, so at the end you like the company and might purchase something from them. Similarly if nitter.poast.org gives away their services for free, I see that as an ad for the hate-speech poast.org server. I agree that I am not founding nazi extremism simply by visiting the site, but I would like to inform the users on the wiki what kind of server this is. I have to apologize for maybe having overreacted a bit by immediatly having removed the instance from the wiki, this was not a smart move by me, and maybe if I would've started the discussion first, more people might have been on my side. Also I backpedaled on the illegal content part, I first thought that this was the case, but after being clarified by lawyers I agree that it isnt illegal. I just think it would be nice to add a disclaimer, whatever that might look like. Just to inform the people, so that they can make their own decision if they want to use the instance or not.

**Comment by zedeus** [comment]
If someone decides to go to the server it's pretty quickly obvious what sort of content is on there, so it's not necessary to put a warning ahead of time. It's not like it's full of gore or porn, it's just politics. If you want to shield your eyes from politics you disagree with, you're gonna have a hard time. This isn't the place or time for that.

**Comment by notune** [comment]
I don't see literal hate-speech and antisemitic content such as a comment from an anime figure "Only 2?!?!" on a grafiti "death 2 jews" as being politics. Its hatespeech. How is that politics?

**Comment by zedeus** [comment]
You can find exactly the same, and worse, from all political orientations, on Twitter. You can find racism against all races, hatred against all religions, and worse things like CP. Does that mean Twitter is an illegal-content-hosting hatespeech site that should be avoided? Maybe, but it's not relevant to the mission of Nitter.

**Comment by notune** [comment]
Good point, and the way I see it, nitters mission is to enable people to access Twitter without supporting it. Maybe people are even avoiding it because of the issues you mentioned. But then they unknowingly switch to a nitter instance that has the same problems, and at the end they have maybe not achieved what they wanted. But if we would add a disclaimer to the wiki then they could make an informed decision if they want to use this server or not. I don't think that we can necessarily expect from the people to exactly find out who is hosting a given instance. Maybe a short disclaimer like this:
nitter.poast.org¹

¹poast.org is blocked on multiple mastodon servers for hate-speech

or something like that.

**Comment by zedeus** [comment]
All nitter instances have the exact same problems, it doesn't matter that it's hosted under a poast.org sub-domain. A disclaimer, and this issue in general, is more like to draw attention to the Mastodon instance than not talking about it at all.

**Comment by erikk333** [comment]
nitter.poast.org is a working instance. The posts load. I think in other issue it was explained that it had 200 Twitter accounts

**Comment by animegrafmays** [comment]
https://uwu.social/users/nazi_accusations/statuses/112650718129530026

**Comment by animegrafmays** [comment]
> @animegrafmays From what I can tell looking at the wiki commit history, he was actually talking about this antisemitic tweet: https://poa.st/@NorseRealist/posts/AircNshd4rYmUULOTY The above just confirmed that the owner is retweeting accounts with Nazi swastika symbols. Not good.

good thing it's 1. not a tweet 2. not accessable by the nitter and 3. not representative of nitter or the project, it's contributors or users as a whole and

**Comment by animegrafmays** [comment]
> @animegrafmays What do u have to say to this then? https://accollective.noblogs.org/post/2021/06/18/admin-of-poa-st-anime-graf-mays-revealed-daniel-stevens-of-ontario-canada/ also this: https://hexbear.net/post/2363789 and this: https://eu.usatoday.com/story/news/nation/2023/06/02/hack-of-poast-ties-to-truth-social/70279266007/
> 
> > You may have never heard of Poast before. The two-year-old site is not widely known outside of extremist circles and the researchers who study racist, homophobic and antisemitic communities online. But the site, which has about 30,000 users, has become a refuge for some of the most hateful communities on the internet, [according to reports](https://www.dailydot.com/debug/leak-poast-kiwi-farms/) in the Daily Dot.

>What do u have to say to this then?
this is github, not kiwifarms or another dox laundering website. grow up.

**Comment by CoeJoder** [comment]
Why does the poast.org nitter instance still work?  I can't seem to find answers why it works yet all other instances do not...
