### ISSUE TITLE
ActivityPub support

### ISSUE THREAD

**Issue by BalooUriza** [zedeus/nitter#121]
Since birdsite.monster is gone, and twitter.activitypub.actor is unreliable, perhaps having activitypub support would be handy.

**Comment by Perflyst** [comment]
You can use the RSS feed from nitter to create a activity pub bot

**Comment by zedeus** [comment]
This is definitely outside the scope of Nitter. An external project using Nitter's upcoming API can be built instead, or like @Perflyst said RSS bots can be used to publish tweets.

**Comment by zedeus** [comment]
https://github.com/robertoszek/pleroma-bot
