### ISSUE TITLE
Non .onion links in .onion RSS

### ISSUE THREAD

**Issue by emanruse** [zedeus/nitter#136]
Hi,

I gave RSS a try through http://3nzoldnxplag42gqjs23xvghtzf6t6yzssrtytnntc6ppc7xxuoneoad.onion/ however I notice that all URLs inside the RSS articles are https://nitter.snopyta.org. One would expect them to be onion links too.

Is that something to be fixed?

**Comment by emanruse** [comment]
It seems the same with the other onion instance too.

**Comment by zedeus** [comment]
This depends on nitter's config file, maybe ask @Perflyst

**Comment by emanruse** [comment]
> This depends on nitter's config file, maybe ask @Perflyst 

Should we wait for him to check in here or are you suggesting that I should contact him in some other way?

**Comment by Perflyst** [comment]
just wait for me, i am round ;)
since i just add a tor "proxy" in front of the clearnet nitter the domain does of course not match the onion url.
to support onion in RSS you would need to host a "tor only" instance, and i dont want to run 2 nitter instances

**Comment by emanruse** [comment]
> just wait for me, i am round ;)

Great :)

> to support onion in RSS you would need to host a "tor only" instance, and i dont want to run 2 nitter instances

I see. Which of the 2 onion instances is the one you run? Perhaps we can also talk to the maintainer of the other one?

**Comment by Perflyst** [comment]
I dont think anyone runs a onion only nitter instance at the moment. This would be required here to "fix" your issue.

**Comment by FireMasterK** [comment]
Checkout my Instance of Nitter, this does not occur in my instance.
http://32beeap3r6whfe2me4wqmblvru73o27si3v2uiilkxjhfvxbgzfcjwad.onion/

**Comment by zedeus** [comment]
Closing as a non-issue, this is up to the service provider and cannot be fixed by Nitter.
