### ISSUE TITLE
Redirection extensions in the wiki are redundant with HTTPS Everywhere

### ISSUE THREAD

**Issue by 07416** [zedeus/nitter#137]
https://github.com/zedeus/nitter/wiki/Extensions

Use custom rules with [the addon](https://www.eff.org/https-everywhere), see this writeup for further information: https://old.reddit.com/r/firefox/comments/fgu0fw/https_everywhere_has_full_redirection/

**Comment by zedeus** [comment]
Feel free to add it to the wiki
