### ISSUE TITLE
"Tweets & Replies" section is sometimes incomplete

### ISSUE THREAD

**Issue by sojusnik** [zedeus/nitter#138]
When comparing the "[Tweets](https://nitter.net/AngelaBerger_)" and "[Tweets & Replies](https://nitter.net/AngelaBerger_/with_replies)" sections of [this](https://nitter.net/AngelaBerger_) account as an example, then you'll notice that the latter has far fewer entries.

Any ideas why and how to resolve that?

**Comment by zedeus** [comment]
This is how it's fetched from twitter:
https://twitter.com/search?q=from%3AAngelaBerger_%20include%3Anativeretweets&src=typd&f=live

As you can see, the result is the same. Tweets & Replies is fetched this way because the tab requires you to login (with the legacy layout). There's not much I can do

**Comment by sojusnik** [comment]
I have another observation with [this](https://nitter.net/Roadmap2050_AT) account. This time concerning retweets:

In the "[Tweets & Replies](https://nitter.net/Roadmap2050_AT/with_replies)" section some retweets are missing, in comparison to the "[Tweets](https://nitter.net/Roadmap2050_AT)" section. For instance [this](https://nitter.net/ClemensFoerst/status/1242784906587115521#m) or [this](https://nitter.net/WienEnergie/status/1242773544322375680#m) retweet and so on.

> Tweets & Replies is fetched this way because the tab requires you to login (with the legacy layout).

Are you sure, that you have to log in for replies? I can read replies on Twitter without logging in, see f.i. [here](https://twitter.com/nature/with_replies).

**Comment by zedeus** [comment]
You can see them now because Twitter has a new javascript-based layout that doesn't require login to see that tab. The old layout which nitter uses does require you to login

**Comment by sojusnik** [comment]
> You can see them now because Twitter has a new javascript-based layout that doesn't require login to see that tab. The old layout which nitter uses does require you to login

Do you plan to use the new Twitter layout for Nitter too?

What about the missing retweets?

**Comment by zedeus** [comment]
Maybe, but not anytime soon as it requires rewriting most of nitter's code as it would be mostly based on an actual JSON API with guest tokens rather than web scraping. The retweets are not missing because of nitter, like I said if you do the equivalent search on twitter, they don't show up
