### ISSUE TITLE
Videos sometimes don't appear

### ISSUE THREAD

**Issue by sojusnik** [zedeus/nitter#140]
Take f.i. the following tweet: you'll see a video on [Twitter](https://twitter.com/robbyhunke/status/1241019457973215234), but not on [Nitter](https://nitter.net/robbyhunke/status/1241019457973215234). As a temporary workaround, there could be a hint in Nitter if a tweet contains a video or not, because if you don't double check on Twitter, then you won't notice if there is a video or not.

**Comment by zedeus** [comment]
This hasn't happened for a while, I think it was a temporary IP ban. Reopen if it comes back.
