### ISSUE TITLE
Add a "Link to Twitter" button 

### ISSUE THREAD

**Issue by Eldog02** [zedeus/nitter#145]
The way I use Nitter is via a Tampermonkey script that just auto-redirects me from a twitter post to its Nitter equivalent. I do this because, well, most people don't use Nitter. They use twitter, and are only comfortable with using the official twitter frontend.

It would be invaluable to me to have an automatic "Link to twitter" button so I can quickly reference the tweet in question for people who _don't_ use Nitter, without copying the url and manually editing it to say twitter.com instead of nitter.net.

I made a little 5 minute mockup, to show exactly what I mean.
![image](https://user-images.githubusercontent.com/34759177/79030138-97634480-7b65-11ea-955f-2a6d7a616e1b.png)

**Comment by zedeus** [comment]
The twitter icon in the top right does this

**Comment by Eldog02** [comment]
Oops, thanks for the response
