### ISSUE TITLE
Tweet preview for quote retweets isn't always shown

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#148]
I've noticed it happens when there are medias

See the difference:
+ [quote retweet without media, has preview](https://nitter.net/WayneG1939/status/1255633566542835712#m)
+ [tweet with media, has no preview](https://nitter.net/DIMENSION_YT/status/1255566517112111109#m)

And nitter vs twitter screenshot:
<img src="https://i.ibb.co/pdtM7Fr/Screenshot-20200430-010011-Browser-1.png" width="250"> <img src="https://i.ibb.co/B35dtms/Screenshot-20200430-005916-Browser-1.png" width="250">

**Comment by zedeus** [comment]
Showing it would require an extra request since the old interface (which nitter scrapes) doesn't preview it.
![image](https://user-images.githubusercontent.com/9434921/80666179-05c36480-8a8b-11ea-9763-be147e85aa05.png)

**Comment by zedeus** [comment]
This is no longer a problem, it required the new API
