### ISSUE TITLE
Add new "in tweet" search filter

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#149]
Typicall situation: you want to search for a word, to see tweets about it, but you end up with getting irrelevant results because of people having this word in their username.

For instance, [search nitter](https://nitter.net/search?f=tweets&q=nitter)

Having such filter would really help getting relevant results.

**Comment by jtagcat** [comment]
I (mentioned) requested author (and others) filter in #152 

What about leaving the search box for actual tweet content, and either add additional search boxes (for author, participant (being replied to)) or use github style author:@jtagcat participant:@jtagcat). If not using the other search boxes / gh style filters, assume it's for the tweet's content.

**Comment by zedeus** [comment]
Unfortunately Twitter's search doesn't work like that.

**Comment by zedeus** [comment]
I haven't found a way to do this without manually filtering tweets out, see here https://github.com/zedeus/nitter/issues/219#issuecomment-657054165 why this isn't something I'm going to do.
