### ISSUE TITLE
RSS Feeds with replies stopped working recently

### ISSUE THREAD

**Issue by sojusnik** [zedeus/nitter#154]
From the 7th May RSS Feeds [with replies](https://nitter.net/dollarsanddata/with_replies/rss) stopped working, while [without replies](https://nitter.net/dollarsanddata/rss) continue to work.

**Comment by zedeus** [comment]
nitter.net runs an experimental version with a cache based on Redis instead of SQLite. I made a type for the profile caching which resulted in this. Fixed now, sorry about that.
