### ISSUE TITLE
Setting to display media tweets only in lists?

### ISSUE THREAD

**Issue by cnte-dev** [zedeus/nitter#156]
I mostly use Twitter to follow artists. Could you add a setting to display only media tweets and hide all text-only tweets? You can do this when you're viewing a profile, of course, but not when you're viewing (say) a list.

I use Stylus and a bit of custom CSS to do this in regular Twitter -- or, rather, 'old' Twitter. But now that the old Twitter UI is being removed, Nitter seems like a much better alternative! And the privacy options are a big bonus. The only downside is that I can't see an easy way to hide non-media tweets using a userscript or CSS (which is probably because the HTML is so clean by comparison). So it would be nice to have a native option for this!

**Comment by zedeus** [comment]
Lists don't support search/media tabs yet, but with the search view you can filter it to media only. 
Example: https://nitter.net/search?q=list%3ANASA%2Fastronauts&f-media=on

**Comment by cnte-dev** [comment]
That does work, but it seems to be non-chronological?

**Comment by zedeus** [comment]
It's chronological, but retweets show the original date they were posted

**Comment by cnte-dev** [comment]
Ah, sorry, missed a retweet icon on a post and got confused. That works, thank you!
