### ISSUE TITLE
Twitter is removing the Old UI, will this affect Nitter?

### ISSUE THREAD

**Issue by IamRifki** [zedeus/nitter#157]
Here's the notice that they gave.

![](https://user-images.githubusercontent.com/39834015/81482763-97895980-9263-11ea-97d7-0330cc358279.png)

**Comment by zedeus** [comment]
That is bad news indeed. I have played around with the new public API that uses guest tokens just like the old video API, but I don't know how feasible it's going to be. Will definitely require a large rewrite of the nitter backend.

**Comment by IamRifki** [comment]
I remembered that [twitter-scraper](https://github.com/bisguzar/twitter-scraper) supports the new UI, if I remember correctly.

**Comment by IamRifki** [comment]
I'm going to guess this will massively setback all the other features until further notice, Why did you chose to scrape the old UI in the first place anyway?

**Comment by zedeus** [comment]
I wasn't even aware the new UI existed when I started working on nitter.

**Comment by IamRifki** [comment]
Actually nvm, they use the old UI.

**Comment by zedeus** [comment]
For those who are wondering, I have been working on rewriting part of the backend to use the new JSON-based API, without requiring a developer account. It's _fast_, loading a full timeline page with profile and photo gallery in just ~400 ms vs Twitter loading the same thing in 1.3-1.5 seconds.

It's not done yet, but I'm making a lot of progress and it should be ready for deployment before June 1st. Here's my current todo list:
- [ ] Lists (easy)
- [ ] Preview media in quotes
- [ ] Promo video cards
- [ ] Parse profile bio mentions/hashtags
- [ ] Handle request error codes, show suspended
- [ ] Write proper Redis library and use it for caching
- [ ] Store tokens in Redis
- [ ] Improve general error handling code to prevent crashes
- [ ] Videos are apparently always available as mp4, new playback preferences?
- [ ] Bold search queries
- [ ] Consider using hover card API endpoint for profiles, it uses the "old" API with separate limits but same tokens, equally as fast if not faster, allows fetching multiple profiles at a time
- [ ] Move search bar below tabs

**Comment by zedeus** [comment]
After a few hotfixes, https://nitter.net is now running Nitter v2, and it's going very well so far. Despite an incredible amount of traffic (10-30 tweets per _second_), it's as fast as a local instance, serving tweets in 2-300 ms and timelines in 3-600 ms. I did some fairly heavy stress tests on some endpoints a couple weeks ago so it should hold up, but I am a little worried.

**Comment by roytam1** [comment]
> After a few hotfixes, https://nitter.net is now running Nitter v2, and it's going very well so far.

and now getting "Instance Down" message.

**Comment by Perflyst** [comment]
Just use another instance for the moment https://github.com/zedeus/nitter/wiki/Instances#list-of-public-nitter-instances

**Comment by zedeus** [comment]
https://nitter.net temporarily broke either due to a full disk causing requests to fail thus repeatedly trying to fetch tokens, or simply because the token strategy is too aggressive for the massive amount of traffic leading to a rate limit. thankfully it didn't last for long, so it's back now.

**Comment by zedeus** [comment]
Old Twitter is gone and nitter lives on, closing.

**Comment by Symbian9** [comment]
@zedeus, It seems like with latest changes on Twitter, Nitter now can't' show pinned tweets anymore:

- profile page: https://nitter.net/app4soft
- pinned tweet: https://nitter.net/app4soft/status/1484644315909525505

Something is broken again?

**Comment by zedeus** [comment]
They started returning "429 too many requests" when using the official web client's bearer token with the timeline endpoint, so I switched it over to using the search endpoint instead. Unfortunately this doesn't include pinned tweets, nor does the alternative bearer token I've been experimenting with. Not sure what to do about this.

**Comment by zedeus** [comment]
@Symbian9 Nitter now supports pinned tweets again, ended up going with the alternative token and just fetching the pinned tweet separately, works nicely and is still very fast.

**Comment by Symbian9** [comment]
> Nitter now supports pinned tweets again

Thanks for the hotfix!

**Comment by Symbian9** [comment]
@zedeus As an addition, I see that some ***quoted tweets inside pinned tweet not shown on profile page***, BUT shown in single tweet page — is it related or separate issue should be created?

- profile page (with pinned tweet): https://nitter.net/solvespace
  - 
![Screenshot_2022-01-23_11-02-26](https://user-images.githubusercontent.com/13188580/150671736-11044af2-645f-4e9f-815b-31683a25153a.png)
- single tweet page: https://nitter.net/SolveSpace/status/1484163030887841794
  - 
![Screenshot_2022-01-23_11-06-39](https://user-images.githubusercontent.com/13188580/150671761-ec9bed7e-3466-4690-a1a4-4d01ed8ec53a.png)

**Comment by zedeus** [comment]
That's a new issue, I'll look into it. Thank you for the example!

**Comment by zedeus** [comment]
Done, let me know if you find any other issues

**Comment by Symbian9** [comment]
> That's a new issue, I'll look into it. Thank you for the example!
> Done, let me know if you find any other issues

Thanks! Yes, I will let you know ;)

I'm just curious does some tweets are "shadow hidden" by Twitter, because I already sew that some separate tweets (not pinned & without any quoted tweets) also not shown in Nitter, but shown on Twitter in a manner that almost nobody else see it.

May it be some sort/new form of "shadow ban"?

- https://entreresource.com/twitter-shadowban/
- https://nitter.net/app4soft/status/1470927148722663425
- https://nitter.net/app4soft/status/1470107369036296204

**Comment by zedeus** [comment]
I don't know, it's impossible to check and Nitter can't do anything about it. The tweets you posted work just fine in Nitter. You can't scroll far enough down the timeline to find them since you have so many tweets, but that applies to Twitter as well (this is where it stops loading, same as Nitter):
![image](https://user-images.githubusercontent.com/9434921/150673650-4af60ab2-9744-48ef-a6d5-c7e053c9e82c.png)

Searching for them works fine:
![image](https://user-images.githubusercontent.com/9434921/150673681-80febff2-40d4-4532-9d97-bae293c77287.png)

**Comment by Symbian9** [comment]
FTR, Has you seen next tweet when scrolled my Twitter page?

- https://nitter.net/app4soft/status/1484835492399132676

Because on Nitter it is not shown on my page (i.e. `https://nitter.net/app4soft`, I checked yesterday just after tweeted) and only one of my followers on Twitter tells me that he sew it on Twitter (as notification from followed acount):

- https://nitter.net/app4soft/status/1484900838858539008

**Comment by Symbian9** [comment]
@zedeus, here are another examples of "Tweet not found" on Nitter, BUT visible on Twitter:

- https://twitter.com/NotWoofers/status/1495814589510041601
  - https://nitter.net/NotWoofers/status/1495814589510041601#m
- https://twitter.com/NotWoofers/status/1495814787514748930
  - https://nitter.net/NotWoofers/status/1495814787514748930#m

**Comment by zedeus** [comment]
That's because nitter.net is hosted in Germany, where that account is censored.

**Comment by Symbian9** [comment]
> That's because nitter.net is hosted in Germany

Ok, got it. Its working from another instance ;)

- https://nitter.fdn.fr/NotWoofers/status/1495814589510041601#m

@zedeus, BTW, could be there some notification like:

```
This might be censored by instance hoster.

Try with another one instance instead.
```

**Comment by zedeus** [comment]
Unfortunately not, their API returns the same as if the tweet actually didn't exist

**Comment by jeffalo** [comment]
Hey, I don't know if this is useful but thought I should share:

Twitter still serves the old site to Googlebot and archive.org's user agents. Perhaps that could be used in places where the new website/api is insufficient?
