### ISSUE TITLE
confused on how to use nitter

### ISSUE THREAD

**Issue by dln949** [zedeus/nitter#158]
Hi, VERY new to nitter - just ran across it today.  I've been reading, and tried it out at nitter.net, but there is something I do not understand:  

How do I log in to my Twitter account via nitter?  

Did I just miss that somewhere on the main page where that was explained?  

If I got to nitter.net, all it asks for is the Twitter user name.  

I'm guessing I'm probably just completely misunderstanding how nitter is intended to be used.

**Comment by zedeus** [comment]
Nitter is a read-only interface to access Twitter content without JavaScript and without ever communicating directly with Twitter's servers. The intention is not for you to login with your Twitter account, but this is a feature I'd like to do in the far future as a lot of people seem to like Nitter's interface.

**Comment by dln949** [comment]
Ok, I understand now, thanks for the clarification.
