### ISSUE TITLE
Add explanation about HMAC

### ISSUE THREAD

**Issue by thansk** [zedeus/nitter#161]
I have been searching for an hour and still have no idea what to put for it.

**Comment by zedeus** [comment]
It's a private key for cryptographic signing of video URLs to avoid attackers from overloading your server. It should be a random string

**Comment by thansk** [comment]
Where do I get that?

**Comment by zedeus** [comment]
Where do you get a random string? Just generate one or write some random characters

**Comment by thansk** [comment]
Seems like I am having the same problem as #162 and I just assumed it has something to do with HMAC.

**Comment by zedeus** [comment]
Rasonable assumption but HMAC is only used for videos
