### ISSUE TITLE
Images don't work on Self-Hosted Copy?

### ISSUE THREAD

**Issue by ChaseHall** [zedeus/nitter#162]
Hello, 
I am running a self hosted copy of nitter, however images aren't loading. I added a /tmp  volume in Docker, as I saw that images are written to /tmp, but that did not help, they still look [like this](https://i.imgur.com/m9j1Wxb.png)

    https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F875656342718918656%2FR4WpwH70_bigger.jpg:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Thanks in advance.

**Comment by AeliusSaionji** [comment]
I had this problem while running nitter behind lighttpd- it went away when I switched to nginx. I'm sure it's a reverse proxy configuration issue, but I don't know how to fix it.

**Comment by ChaseHall** [comment]
Weird, I'm using Apache2 for my reverse proxy, and I've never had any issues with any other services.. @AeliusSaionji

**Comment by zedeus** [comment]
Did you check the Apache wiki page?
https://github.com/zedeus/nitter/wiki/Apache

**Comment by somini** [comment]
Is there any chance of replacing the URL a base64 version of it, so that it works outside the box on Apache (particularly on cheap shared hosts)? This can be a compile time option even.

For those shared hosts, you don't have a possibility of changing the Apache configuration.

**Comment by ChaseHall** [comment]
Looks like I forgot to Encode Slashes, closing since it's fixed now.

**Comment by somini** [comment]
> @somini a base64 encoded url would be longer and not transparent to the user, while also requiring more effort for browser extension developers that want to proxy media

Did not think about that particular use case, that's correct.

> If this is something you really want (for the shared hosts use case you mentioned), I can add this as a compile-time option

The cleanest way would be to have a different route `/pic/enc/$ENCODED_URL` (or similar), and adding a configuration variable to default to those links for the whole application. That way both ways would "work" without forking the code into untested compile time options.

I can open a new issue for this if you require.

**Comment by zedeus** [comment]
An instance-wide compile-time or config option that changes `/pic/`'s behaviour would be easiest, otherwise an argument would have to be passed from routing to all the html generation code. With a config/compile-time option the `getPicUrl` function that encodes the url can just do something different

**Comment by somini** [comment]
I never worked with Nim, but from what I can tell:

- https://github.com/zedeus/nitter/blob/master/src/routes/media.nim#L68

This is where the `pic` routes are defined. We would add `/pic/enc/@encURL` to decode the URL first and pass it to the existing function. This would be unconditional.

- https://github.com/zedeus/nitter/blob/1b9fa40237a83401b327a23dbec89af028610aa5/src/utils.nim#L33

This is where the URL links are created. We would add a new boolean config option to generate the `/pic/enc/@encURL` instead.

I can probably create a WIP merge request for this. Should it be based on the `master` or `nitter-v2`?

**Comment by awsms** [comment]
Why isn't %2F properly decoded for images URL?
All the images redirect to https://nitter.net/pic/orig/media%2F* links
So https://nitter.net/pic/orig/media%2FF6T0sjoXcAAL_EH.jpg instead of https://nitter.net/pic/orig/media/F6T0sjoXcAAL_EH.jpg
That's the case on the official nitter instance, which is using https://github.com/zedeus/nitter/commit/537af7f

**Comment by zedeus** [comment]
It's an encoded url that proxies the image through Nitter. For the most common case the beginning of it is elided and only media/... is kept. Not encoding it would cause a lot of problems.
