### ISSUE TITLE
Search with browser language by default

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#163]
Adding `lang:<two letter language code>` to the search query will give results for this language. You can retrieve browser's language and search with it.

If you are searching for something not in English, it will really improve search results.

**Comment by zedeus** [comment]
I think doing so by default is a bad idea since it will filter out tweets in other languages

**Comment by B0pol** [comment]
That's the goal, but I was thinking about the search pages, i.e. https://nitter.net/search and home page https://nitter.net only: when the user see the search bar.

I've seen nitter [in this thread](https://github.com/zedeus/nitter/issues/83#issuecomment-546925965) use searches to show tweets from an user or multiple users with user1,user2,user3 lists, and I think that what you are talking about. I agree in this case it would be a bad idea, but if you limit to the nitter search pages it's not a problem anymore.

**Comment by zedeus** [comment]
Automatically filtering out tweets in other languages from the search is not a good idea as it's not obvious to the user. I agree with #164

**Comment by B0pol** [comment]
Most search engines do that, hidden or not (google, duckduckgo, qwant, searx, youtube, **twitter**, bing and the list is very long).
Twitter does it under the hood. Change your browser language to something not English, search something regularly discussed (i.e. covid) you're gonna see almost no results in English. 

For "it's not obvious" I totally agree… _but in reverse_. As a non-English speaker, I personally I though Nitter was terrible for searches… until I found this parameter just today. Then it was not obvious for me Nitter is searching in English, and I'm sure I'm not the only one thinking that.

There are several ways to show the user if you really want. Some screenshots:

Qwant: dropdown menu with the currently used language shown, here Français (French) ![image](https://user-images.githubusercontent.com/58657617/82700779-2daf7d80-9c6f-11ea-84dd-d07d73dd0509.png)
searx: dropdown menu with the currently used language shown, here English (United States) : 
![image](https://user-images.githubusercontent.com/58657617/82700833-4750c500-9c6f-11ea-81e8-f7b6085aeb52.png)
bing: dropdown menu `Langue`, meaning Language in English: 
![image](https://user-images.githubusercontent.com/58657617/82700877-5e8fb280-9c6f-11ea-89e2-7e3e2780b599.png)

**Comment by zedeus** [comment]
Search engines don't hide results in other languages, they prioritize results, unlike the `lang` filter. From what I've seen it's not easily possible to do with Twitter's search but I haven't tried explicitly changing my browser language to see how it behaves, it may just be a simple header value

**Comment by zedeus** [comment]
Closing in favor of #164
