### ISSUE TITLE
Fix jank effect

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#167]
It happens when a page has a lot of pictures such as a twitter profile, or the media tab in a twitter profile, and even more when you have a low connection.
Relevant video: https://youtube.com/watch?v=4-d_SoCHeWE

**Comment by B0pol** [comment]
It is really noticeable here (and even more if you have low connection)

https://nitter.net/MelTamaoe/status/1262838615387840513#m

**Comment by Poopooracoocoo** [comment]
What are your thoughts on lazy loading?

**Comment by zedeus** [comment]
It hasn't been 100% fixed, but the banner and profile picture now always have the proper size, so the majority of the jank is gone. I may look into improving it further for images/videos in tweets at a later point, but I consider it good enough for now.
