### ISSUE TITLE
Reduce the wasted space on the screen

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zedeus/nitter#17]
![nitter](https://user-images.githubusercontent.com/47571719/62803064-f9504380-bad8-11e9-9574-61fd40de650d.png)

In my opinion the wasted space on the side of the content is too big, it's great for phones use but on a PC it's really too much, in my opinion you should align the left column to the left of the page and increase the size of the content, in theory it should still act the same on phones.

**Comment by zedeus** [comment]
I disagree with this, a wide tweet column would result in very long lines of text. You're free to host your own instance and modify the css.
