### ISSUE TITLE
Replies are missing some notice

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#171]
https://nitter.net/JosephDumont16/status/1267217952136400902#m

scroll down until "LOL, it really hurts seeing these theories"…
you'll see that this comment is a reply to a tweet noticed "This account owner limits who can view their tweets."
![image](https://user-images.githubusercontent.com/58657617/83409097-0184c100-a414-11ea-873e-1a17d8163b72.png)

Now click on the comment, or go to the link: https://nitter.net/BritishMola/status/1267224210138632193#m
Nitter don't show he's replying to a hidden tweet
![image](https://user-images.githubusercontent.com/58657617/83408969-cedac880-a413-11ea-921b-72a521f66291.png)

whereas twitter display the notice 
![image](https://user-images.githubusercontent.com/58657617/83408919-b7034480-a413-11ea-84f1-f79ff9a003e0.png)

(I've tried both nitter.net and  nitter v2 — #169 — hosted locally).

**Comment by B0pol** [comment]
OK, according to the about page, nitter.net is using nitter v2, commit https://github.com/zedeus/nitter/commit/08bae11 , this is why I don't see a difference.

Here is what nitter.42l.fr shows , commit https://github.com/zedeus/nitter/commit/52983e5

<img src="https://user-images.githubusercontent.com/58657617/83417065-dd2fe100-a421-11ea-97bd-863c60f4b333.png" width="200">

**Comment by zedeus** [comment]
Dead links, a new example would be nice if this is still an issue

**Comment by zedeus** [comment]
I think this works fine, a bit hard to tell
![image](https://user-images.githubusercontent.com/9434921/147896213-99c04520-0d86-45b3-a050-353dc361cf0a.png)
