### ISSUE TITLE
wrong relative upload date

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#172]
It's a regression with v2, #169
My timezone is GMT+2. Screenshot from nitter.42l.fr, commit https://github.com/zedeus/nitter/commit/52983e5

![image](https://user-images.githubusercontent.com/58657617/83428855-6e5b8380-a433-11ea-8b89-3cdec641a521.png)

Screenshot from nitter.net, commit https://github.com/zedeus/nitter/commit/08bae11

![image](https://user-images.githubusercontent.com/58657617/83428955-964ae700-a433-11ea-8e96-1375e0cdcad8.png).

I've tried with commit https://github.com/zedeus/nitter/commit/00dfb2fee43e2999b00d06f7aaf5871659d08cd0 (latest on master, before #169), this bug doesn't happen, then it's a regression with #169.

**Comment by zedeus** [comment]
All timestamps are correctly shown in UTC time, instead of relative to the server location. With that said I think I know what went wrong. When calculating the relative timestamps, I use the local timestamp.. I'll push a fix right away

**Comment by B0pol** [comment]
I've edited the title because it seems not right, look at these screenshot

![Screenshot_20200602-190328_Firefox_Preview](https://user-images.githubusercontent.com/58657617/83548270-c9f54200-a503-11ea-82e1-fa356dcfd91c.png)

![Screenshot_20200602-190322_Firefox_Preview](https://user-images.githubusercontent.com/58657617/83548414-0759cf80-a504-11ea-8d2f-4144cb33564d.png)

i'm one hour in the future with nixnet.services (yesterday i've tried to change [this](https://github.com/zedeus/nitter/blob/e453d9dd595fd5ebd1f98332ee9cd0370a91c117/src/formatters.nim#L102), from now - then to then - now to see what happens if it would be tweeted in the future, and it shows "now", not something like -X hours).

As it is changing with instances, "All timestamps are correctly shown in UTC time, instead of _relative to the server location_., I doubt

**Comment by zedeus** [comment]
Yeah, there was a little error in my timestamp parsing logic, thank you for reporting

**Comment by zedeus** [comment]
Should be fixed now

**Comment by B0pol** [comment]
Yes, https://github.com/zedeus/nitter/commit/293029383314bb2cc4f1c089d1f0039e49160512 fixes this bug. I hope all instances that updated to v2 will update again and soon for this fix. thank you
