### ISSUE TITLE
Cannot store preferences anymore

### ISSUE THREAD

**Issue by cy8aer** [zedeus/nitter#174]
I am not able to store my settings anymore.

Git version 00dfb2fee43e2999b00d06f7aaf5871659d08cd0
- select preferences
- change parameters (e. g: nitter.com -> own.serv.er, invidious.com -> own.vidserv.er, change theme to twitter)
- click save preferences

Expected: Page should minimum show the twitter theme
Actual behaviour:
- nitter page has still nitter theme
- when selecting preferences all old parameters (e.g. nitter.com...) are set, no new settings anymore

This was tested with firefox (76.0.1 with my normal profile and - of course a new clean one), 
chromium (clean). Sometimes I can see the twitter theme for one, two pages. More interesting: RSS feeds (old ones too) now link e.g. to nitter.com and not to my own server.

**Comment by zedeus** [comment]
Is this with a local server? If so, did you set `https` to false in the config?

**Comment by cy8aer** [comment]
`config.nims` is default:

--define:ssl
--define:useStdLib

# workaround httpbeast file upload bug
--assertions:off
```
and server is behind an apache proxy.

**Comment by zedeus** [comment]
I meant `nitter.conf`

**Comment by zedeus** [comment]
Also, the current master is no longer working since they're quickly phasing out the legacy UI. #169 reimplements the API backend.

**Comment by cy8aer** [comment]
hmm, yes, it is true. Changing it to false...
... and it works. Ok I see this should depend on 312ff786 where the settings are moved to cookies.

The bug was sitting in front of the keyboard ;-)

Closing issue
