### ISSUE TITLE
Red on black isn't the best thing to read

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zedeus/nitter#18]
In my opinion having Red text on a black (or any) background isn't really the best thing to read, you should have every text in white (or gray)  while keeping red as the second color of the UI (like the line under "Tweet" for example)

![nitter](https://user-images.githubusercontent.com/47571719/62805314-20aa0f00-badf-11e9-8d80-f7683c476e98.png)

**Comment by zedeus** [comment]
The red text is very readable to me, and it's a deliberate design choice to distinguish important elements. Like I said in the other issue you're free to modify the css. Themes will be supported in the future so this is a non-issue really.
