### ISSUE TITLE
Forward-Back-Navigation with infinite scrolling

### ISSUE THREAD

**Issue by treble2019** [zedeus/nitter#180]
Not sure this can be fixed (i.e) it is a feature not a bug.

After scrolling 'lets say more than 1 page' with infinite scroll. I click on a select tweet (neet?) or image. Now it opens (in the same Tab). But now press back and you are now located at a different scroll position. Tested with Bromite.

Not sure how other sites keep it.

**Comment by B0pol** [comment]
Yeah. It used to rewrite browser history by changing URL, but then you had to press back several times to go to the previous post.

If we can cache the position without rewriting browser history that would be really cool
