### ISSUE TITLE
RSS feeds do not match the filters?

### ISSUE THREAD

**Issue by Amanoki** [zedeus/nitter#181]
For example, I want to filter tweets that contain medias from user @ cnni, the rss link is 
https://nitter.net/cnni/search/rss?f=tweets&f-media=on

Then I want to filter tweets which contain the keyword "Australia" from the same user, the rss link is
https://nitter.net/cnni/search/rss?f=tweets&q=Australia

But it seems like the two different links are actually the same feed and not match the actual filters. Sometimes both two rss links link to the feed that matches the media filter, sometimes both two links link to the feed that matches the "Australia" filter. 
And if I make a third filter and generate a new rss link, these three links will all link to the feed that matches the third filter.

Is it the right way it works?
Is it possible to generate different feeds for each filter?

---------
And another question, I want to filter tweets that contain the keyword "wordA" OR "wordB" OR "wordC" at the same time. Is there a way to do this? Thanks!!

**Comment by zedeus** [comment]
This is a regression, fixed now. For your second question, your example should just work
