### ISSUE TITLE
videos don't start playing, invinite buffering

### ISSUE THREAD

**Issue by humarf** [zedeus/nitter#188]
I run nitter from the prebuild docker container. When I try to play videos in tweets it hangs when loading the videos waiting for the data to come. I guess it's a configuration issue since on nitter.net same videos work. I activated hls streaming and mp4 playback. I tried with and without proxying videos. Docker container raises no errors. I don't know what else could be wrong. Do you have an idea what else I could try?

Thx for your help.

**Comment by zedeus** [comment]
Is it running behind nginx or another reverse proxy? Any console output in the browser? I'm guessing it's due to a CSP misconfiguration

**Comment by humarf** [comment]
It's runnung behind an apache reverse proxy. I took confuguration from the wiki here. But it also happens when I address the nitter instance in my local network directly. Will check browser console.

**Comment by humarf** [comment]
Checked browser log. I guess you are right. It says:

`(redirected from 'https://video.twimg.com/ext_tw_video/1270356349755539460/pu/pl/1280x720/qauMAycPk-iiGoVk.m3u8') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I guess I have to add something in the proxy configuration -but what?

**Comment by zedeus** [comment]
What do you get with proxying enabled?

**Comment by humarf** [comment]
That helped. I forgot to add `ProxyPreserveHost On`. Now video works when proxying is on. Thank you!

Should it also work without proxying?

**Comment by zedeus** [comment]
The use case for that is very limited, ie. when the server has awful bandwidth restrictions or the client's connection to twitter is much faster which is unlikely. So it should, but it doesn't matter if it does

**Comment by humarf** [comment]
Ok, I go with proxying enabled then. Thanks a lot for your quick help!
