### ISSUE TITLE
Support Unix Domain Sockets

### ISSUE THREAD

**Issue by somini** [zedeus/nitter#189]
Suporting listening on a UNIX domain socket(`/run/nitter.sock`, for example) instead of an address:port combo.

This is different from #182.

**Comment by zedeus** [comment]
I don't think the web server supports this

**Comment by somini** [comment]
I wanted to automate the installation process as much as possible, and that involves choosing a localhost port that does not collide with an existing process.
An UNIX socket solves that, but if it's not possible that's fine. You can close this.

---

I added nitter to the AUR, BTW.
https://aur.archlinux.org/packages/nitter-git/

**Comment by Mennaruuk** [comment]
Hi! I just installed the AUR package. When attempting to run Nitter, I face this error. Does anyone have a good solution for this? Thanks a lot!
```
[Menna@linux ~]$ nitter
io.nim(734)              open
Error: unhandled exception: cannot open: ./nitter.conf [IOError]
```

**Comment by somini** [comment]
@Mennaruuk These questions should really be put on the AUR comments.

In you case, I would double check the `/etc/nitter.conf` contents, and use only systemd to start the serve: `sudo systemctl start nitter`.

**Comment by Mennaruuk** [comment]
> @Mennaruuk These questions should really be put on the AUR comments.
> 
> In you case, I would double check the `/etc/nitter.conf` contents, and use only systemd to start the serve: `sudo systemctl start nitter`.

Okay, thank you!

**Comment by greendev223** [comment]
where is /etc/nitter.conf
