### ISSUE TITLE
iOS Shortcut for Twitter Redirecting

### ISSUE THREAD

**Issue by nitrohorse** [zedeus/nitter#19]
I couldn't find a contact email for you @zedeus, so I'm just putting this here as an FYI in case it helps anyone. Please feel free to close this issue.

On iOS there's a capability called "Shortcuts":
> A shortcut is a quick way to get one or more tasks done with your apps. The Shortcuts app lets you create your own shortcuts with multiple steps. - https://support.apple.com/guide/shortcuts/welcome/ios

So here's a shortcut for redirecting Twitter URLs to Nitter URLs :smile: (inspired by [this Invidious shortcut](https://www.reddit.com/r/shortcuts/comments/a02y5p/request_is_there_a_shortcut_that_allows_invidious/eaebuau/)):
- https://www.icloud.com/shortcuts/3e90ac68c77b45eb82cb18dab519ff76

This shortcut opens the Nitter URL in Firefox but can be configured for any browser that has its own URL Scheme, for example:
- `ddgQuickLink://{url}` ([DuckDuckGo Browser](https://apps.apple.com/us/app/duckduckgo-privacy-browser/id663592361))
- `brave://open-url?url={url}` ([Brave Browser](https://apps.apple.com/us/app/brave-fast-privacy-browser/id1052879175))

Really loving Nitter! Awesome work!

**Comment by nitrohorse** [comment]
Here’s also an open-source, very simple Twitter redirect extension for Firefox: https://addons.mozilla.org/en-US/firefox/addon/twitter-to-nitter-redirect/ 😄

**Comment by Perflyst** [comment]
I have added a wiki article: https://github.com/zedeus/nitter/wiki/Extensions

**Comment by Mennaruuk** [comment]
Link is down :(
