### ISSUE TITLE
Add how many are left

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#190]
When not using infinite scrolling.
E.g. "Load more (27 left)", "Load more (27 comments left)"

**Comment by zedeus** [comment]
Twitter doesn't give us this information, so that's not possible

**Comment by B0pol** [comment]
Twitter give the replies number, isn't it possible to count from it?

**Comment by zedeus** [comment]
Sure, but then we have to keep track of how many replies you've loaded since the cursor value tells us nothing, requiring server-side state. Nitter is _stateless_, so that is not going to happen.

**Comment by B0pol** [comment]
ok, thanks for the answer
