### ISSUE TITLE
Direct Messages

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#195]
I can list many reasons, why Nitter probably wouldn't be great for logging in and so on, but I need to use DMs often enough that email notifications aren't enough. I end up keeping twitter open as a pin. It also drains loads of performance and privacy.

**Comment by FireMasterK** [comment]
I think this a duplicate duplicate of #155 because it covers this

**Comment by zedeus** [comment]
Yeah, you can add it in a comment there
