### ISSUE TITLE
Option/Flag To Hide Replies in RSS

### ISSUE THREAD

**Issue by cyntalan** [zedeus/nitter#197]
I noticed that nitter appears to have the means to hide replies, but it doesn't seem to reflect that in the RSS feed variant. Am I missing something, or is this possible? It's the one thing keeping me from switching from TwitRSS.me.

**Comment by zedeus** [comment]
The preference to hide replies only applies to the replies when viewing a tweet. To hide replies from timelines, you can use the search feature then exclude replies, this works as expected with RSS

**Comment by cyntalan** [comment]
I feel I'm feeling a bit foolish at the moment. Is there a particular means to use the search function to only pull that user? I'm finding that any concept I use to search out just the user's posts without other user's replies gives a lot of junk or otherwise unrelated outside of things like mentions.

I don't actually USE twitter all that much, so it may be as simple as me not knowing syntax that mirrors what you'd use in twitter normally. I literally only use it as a means to RSS track a few people's posts. With TwitRSS.me, it only ever grabbed the user's posts from the onset, so I might just be unaware of the search syntax.

**Comment by zedeus** [comment]
Go to the user's timeline and click the search bar?

**Comment by cyntalan** [comment]
...yep, that's about what I was missing. Told you I was being foolish.
