### ISSUE TITLE
Exception message: no such column: location

### ISSUE THREAD

**Issue by Perflyst** [zedeus/nitter#20]
Opening a profile with latest commit on selfhosted instance results in an exception. Full output is here: https://privatebin.net/?1c96c07ad13afaaf#DpXCg3rbkbW2yw6ysd55ys7RgchWm2sjhhtFfDNkGgAK

I am running inside a LXC. 

```
$ nimble  -v
nimble v0.10.2 compiled at 2019-08-08 15:25:55
git hash: couldn't determine git hash
```

commit hash b718bbe15c1708ae83e7b2ade6492c3cfb382f73, build with `nimble build`

**Comment by zedeus** [comment]
For now just delete the `cache.db` file. I'll look into adding some error handling.

**Comment by Perflyst** [comment]
It seems like it just need a column called "location" in the database. What about some sql migration scripts like Invidious has?
