### ISSUE TITLE
"Token Parse Fail" after 9 days of regular usage (fixed)

### ISSUE THREAD

**Issue by somini** [zedeus/nitter#200]
This is that same thing as #196.

It seems my IP is rate-limited by Twitter, I'm running it on a cloud VM. I use only RSS, and follow about 10 usernames.

Is there a way to cool off the requests on nitter itself and just return stale data when Twitter rate-limits us? At the very list can we rate-limit the requests to `twitter.com`?

If I might ask, what's your approach on `nitter.com`, which must be getting massive amounts of requests?

**Comment by somini** [comment]
At the very least, I just want the nitter daemon to keep alive even when rate-limited, and handle it more gracefully.

Here are some logs of the crash:
```
Jun 23 22:01:33 $HOSTNAME nitter[40784]: fetching token failed
Jun 23 22:01:34 $HOSTNAME nitter[40784]: asyncfutures.nim(383)    read
Jun 23 22:01:34 $HOSTNAME nitter[40784]: asyncfutures.nim(431)    asyncCheckCallback
Jun 23 22:01:34 $HOSTNAME nitter[40784]: Error: unhandled exception: Too many open files [OSError]
Jun 23 22:01:34 $HOSTNAME systemd[1]: nitter.service: Main process exited, code=exited, status=1/FAILURE
Jun 23 22:01:34 $HOSTNAME systemd[1]: nitter.service: Failed with result 'exit-code'.
```

**Comment by robhuen** [comment]
It seems, I have the same problem:

`
Jun 24 08:14:03 $HOSTNAME nitter[1563]: fetching token failed
`

Also, `curl https://twitter.com | grep gt=`
tested from three different machines in three different IP ranges is empty. 

Maybe twitter changed something again?

Btw: Is nitter.com using a commit not available on github? ([bde3c36](https://github.com/zedeus/nitter/commit/bde3c36))

**Comment by splacat** [comment]
Same here `token parse fail`all the time. `

**Comment by humarf** [comment]
Don't know weather it is for the same reason but I receive this message from my nitter docker container for a couple of hours :
`nitter    | fetching token failed`
It seems related to the problems above. I'd be happy for any hints what I could do.

**Comment by splacat** [comment]
Maybe @zedeus can help us. Do you have an special token for nitter.net? Thank you!

**Comment by gurify** [comment]
I'm receiving the same "fetching token failed" error both on Digital Ocean instance and my home one.

**Comment by zedeus** [comment]
Twitter changed the way tokens are given to clients, so it required a change to how nitter gets them. Luckily it didn't affect any rate limits, which btw is 500 tokens per 30 minutes, where if you exceed that you have to wait till the next 30 minute window. Update to latest commit to fix it.

**Comment by zedeus** [comment]
Yes I was running bde3c36 before pushing it, it's just a minor cleanup.

**Comment by humarf** [comment]
For me that fixed it. Thanks!

**Comment by splacat** [comment]
great! works fine now. Thanks @zedeus!

**Comment by robhuen** [comment]
Now (30 minutes later ...) it also works for me :-). Thank you!

**Comment by Felix83000** [comment]
When will a build with this fixed problem be generated on Docker Hub? Thanks

**Comment by somini** [comment]
Can confirm this is fixed on the latest commit, thanks for the fast turnaround.
