### ISSUE TITLE
Feeds and searches are showing "No items found"

### ISSUE THREAD

**Issue by DarkDotFail** [zedeus/nitter#201]
I operate the Nitter instance at https://nitter.dark.fail

All feeds are showing "No items found". Search results return the same. Could this be a result of Twitter blocking my server's IP address? I am unsure how to check to see if this is the case.

![nitter-no-items-found](https://user-images.githubusercontent.com/56766556/85583609-efbac600-b62d-11ea-9ea7-17ee418d0aad.PNG)

**Comment by Amolith** [comment]
It's very likely related to #200. Try upgrading to the latest commit and restarting Nitter

**Comment by Amolith** [comment]
Is it still broken for you? I'm seeing this:

![image](https://user-images.githubusercontent.com/29460675/85594326-5c868e00-b637-11ea-99da-a78f788335e8.png)

**Comment by zedeus** [comment]
Are you running the latest commit?

**Comment by DarkDotFail** [comment]
It is running 613e460

It is working again, never determined the problem.

**Comment by harryadel** [comment]
I'm running into the same issue using the docker installation.

```
docker build -t nitter:latest .
docker run -v $(pwd)/nitter.conf:/src/nitter.conf -d -p 8080:8080 nitter:latest
```
The latest commit is `e17775972290d8acb8899e3c32aaca9df5d37240`
On Amazon EC2 Ubuntu
```
uname -a
Linux ip-172-31-2-152 5.3.0-1032-aws #34~18.04.2-Ubuntu SMP Fri Jul 24 10:06:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
