### ISSUE TITLE
Not possible to view timeline of users with empty username

### ISSUE THREAD

**Issue by llacb47** [zedeus/nitter#203]
Hi,

currently in both twitter and nitter it is not possible to view the timeline of users that have no username. 

The timelines of the authors of these tweets cannot be viewed in nitter:

```
https://nitter.net/i/status/1264998641368027144
https://nitter.net/i/status/1906902928
```

Since the authors of these tweets have no username, it is currently not possible to view their timelines except on the twitter app or on these pages spoofing user-agent to googlebot.

```
https://twitter.com/intent/user?user_id=71996998
https://twitter.com/intent/user?user_id=34313404
```

I think nitter could solve this by implementing this API endpoint `/i/user/{user id}`. On twitter, `https://twitter.com/i/user/{user id}` can be used to view a timeline given a user id. For example, `https://twitter.com/i/user/12` redirects to `https://twitter.com/jack`. Obviously for this to work with these "no-username" users the implementation should be a bit different (not redirecting to usernames) but you get the idea.

I know this is a very niche issue so if not worth the effort or if this is something that should be fixed on twitter's side feel free to close. I just thought that since the twitter mobile app can show these timelines, why shouldn't nitter?

**Comment by zedeus** [comment]
Superseded by #295
