### ISSUE TITLE
Accounts: Comment On Tweets

### ISSUE THREAD

**Issue by trymeouteh** [zedeus/nitter#205]
Please allow for accounts to make comment or "nitter tweets" on twitter tweets.

I would like this to use activitypub and be decentralised/federated just like how Mastodon works were you can make a post and it can be read on other instances. This way if I make a comment on a tweet on nitter.net, it can be read on other nitter instances and someone can reply to my comment on another nitter instance.

Also it will be cool to allow us to import/export our comments incase a user decides to switch to another nitter instance and can easily migrate over by importing/exporting a file.

It will also be important to have a privacy setting to decide if by going to our nitter profile page, to allow anyone to see all the comments you made or to have all of your comments hidden to everyone.

**Comment by zedeus** [comment]
I'm not against this idea, but it sounds like a lot of work for little benefit. The goal of Nitter is not to replace Twitter or Mastodon, it's being a bridge between them. 
Being able to comment on tweets sounds cool, but also brings with it a bunch of issues, and it would take a lot of effort.
The alternative I consider much more doable is creating an ActivityPub bridge with Nitter's API (when it exists), which then lets you interact with tweets from ActivityPub services. If it's all done from a single Mastodon/Pleroma instance, there could be a separate comments tab under tweet that shows them.

**Comment by trymeouteh** [comment]
I suggested this so people can comment on tweets without censorship. Twitter is known for censorship and if Nitter is front-end to Twitter, Nitter can be a second layer to allow free speech on tweets.

**Comment by zedeus** [comment]
I agree, but I also think utilizing existing ActivityPub instances is a better idea via some integration perhaps, I'm not sure.
