### ISSUE TITLE
Replies order is sometimes broken

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#208]
When you watch replies to a tweet, I mean direct replies, it's sometimes actually not a direct reply.
Screenshot:
![nitter_replies_1](https://user-images.githubusercontent.com/58657617/86536845-5d8ea980-beda-11ea-8197-e17a21274be9.png)
Here as you can see, I just clicked on "Load more", but it is supposed to be a direct reply.
But when you click on it:
![nitter_replies_2_1](https://user-images.githubusercontent.com/58657617/86536981-616efb80-bedb-11ea-9734-386946e68d41.png)
![nitter_replies_2_2](https://user-images.githubusercontent.com/58657617/86536984-63d15580-bedb-11ea-956b-710e1d2a3abb.png)
you see that it's not a top reply.

**Comment by zedeus** [comment]
I saw this too but if you go to the Twitter page it still happens, nothing I can do
