### ISSUE TITLE
faq draft

### ISSUE THREAD

**Issue by ghost** [zedeus/nitter#209]
FAQ:
1.
Should I ever be concerned about irrelevant things?
No.
2.
Does name "nitter" come from the fact that "tw(o)" is "ni" or is it because "**nit**ka" means "thread" in polish?

**Comment by zedeus** [comment]
Nitter is a portmanteau of Nim and Twitter, and I've seen a few interpretations that say Not + Twitter = Nitter, both are fine with me.
