### ISSUE TITLE
Use HTTP response code 410 for suspended account

### ISSUE THREAD

**Issue by osamak** [zedeus/nitter#210]
To make the "unofficial API" goal even more superb, let suspended accounts return the [HTTP response code 410 (Gone)](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#410).

**Comment by zedeus** [comment]
Closing as this is unnecessary, "unofficial API" refers to the APIs used by Nitter, not Nitter itself. This response code may be used for the planned REST API however
