### ISSUE TITLE
HTTP HEAD requests not supported

### ISSUE THREAD

**Issue by sparked435** [zedeus/nitter#211]
Trying to use HTTP HEAD to see if a Tweet exists returns 404, instead of a 200 OK. Using GET works okay.

For example (choosing a completely random tweet I had a link for):

Jul06:1519 @ack:~ $ curl -I https://nitter.net/Neuronmisfire/status/628011819878236162
HTTP/1.1 404 Not Found
Server: nginx/1.14.1
Date: Mon, 06 Jul 2020 19:19:23 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 3122
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

Jul06:1520 @ack:~ $ curl -o /dev/null -s -D - https://nitter.net/Neuronmisfire/status/628011819878236162 
HTTP/1.1 200 OK
Server: nginx/1.14.1
Date: Mon, 06 Jul 2020 19:21:30 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 4911
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline'; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'; media-src 'self' blob:; worker-src 'self' blob:; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; connect-src 'self' https://*.twimg.com; manifest-src 'self'
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Referrer-Policy: no-referrer

If I remember correctly, this behavior is forbidden in the HTTP RFC's.

**Comment by zedeus** [comment]
That's interesting, would you expect it to work for all routes?

**Comment by puckipedia** [comment]
According to the RFC, https://tools.ietf.org/html/rfc7231#section-4.3.2, yes, you `SHOULD` have this work for every route. Most services (afaik?) implement it by just doing a GET and discarding the body. Returning a 404 on an unknown method is wrong either way, you should return a 405.

**Comment by zedeus** [comment]
Since tweets aren't cached it seems rather silly to only do a HEAD request, you can just discard the body. Closing since implementing this would take a lot of effort with afaik 0 benefits.

**Comment by Dominick-Peluso-Bose** [comment]
> Since tweets aren't cached it seems rather silly to only do a HEAD request, you can just discard the body. Closing since implementing this would take a lot of effort with afaik 0 benefits.

I use benphelps/homepage which has a "ping" feature that uses HEAD requests to monitor services. These HEAD requests seem to be causing my reverse proxy (Caddy) to spit out a lot of errors in its log:

```
INF ts=1672154164.0996127 msg=Unsolicited response received on idle HTTP channel starting with "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>...
```
Unfortunately I don't think there is a way to force benphelps/homepage to use GET requests instead of HEAD. But there would be some benefit if HEAD requests were supported, albeit a small benefit...

**Comment by zedeus** [comment]
You can probably tell Caddy to return 200 on any HEAD request
