### ISSUE TITLE
RSS: Filters

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#213]
https://docs.rsshub.app/en/social-media.html#twitter

So there's a few types of posts:
 - Tweets
 - Replies
 - (Reply to own tweet, thread replies)
 - Public replies (they start with a dot)
 - Retweets
 - Quote tweets
 - Polls

It would be nice to filter what you want and don't. Some feed clients can filter messages (Thunderbird), that have a 'header': `RT by @un`. Would begin with first marking all types of tweets and then allowing filters by modifying the feed URL.

**Comment by zedeus** [comment]
Retweets and replies are already marked with RT and R, you can filter tweets using the search tab (it supports RSS).

**Comment by jtagcat** [comment]
Indeed, but (this issue now contains 2 FRs):
 - It would be nice to see other types marked as well in your feed (with RT, R), as the capacity to do so it almost there.
 - The advanced search lacks 'author' field. searched tweets also match tweets (for example) replying to the author.
   - Participants (being repland to) and mentions filters would also be nice.

**Comment by zedeus** [comment]
What other types? By search I mean the search tab on a profile page. If you want to filter out replies you can just expand the search menu and exclude replies

**Comment by jtagcat** [comment]
> What other types?

Let's say you subscribe to replies, retweets, polls, and quotes.
Right now:
```
R by @foo: something
RT by @foo: something
@foo: something
@foo: something
```
By marking other types, you would get:
```
R by @foo: something
RT by @foo: something
P by @foo: something
Q by @foo: something
```

> By search I mean the search tab on a profile page. If you want to filter out replies you can just expand the search menu and exclude replies

Didn't know that, thanks for noting (maybe make it more apparent (that it's compatible with RSS, and exists, when the user is going after the rss feed).

Maybe when pressing the RSS button, instead of giving the feed, give a page with a (search) filter field, and at the bottom 'get feed'. Something like 'build your own feed'.

**Comment by nogira** [comment]
For future reference to anyone that encounters this, here is an example:
`https://nitter.eu/search/rss?q=-filter:replies+from:elonmusk+min_faves:200+-dogecoin`

You have the start, `https://nitter.eu/search/rss?q=`, then the search query (same as if you type it in the twitter search bar) containing `-filter:replies` + `from:elonmusk` + `min_faves:200` + `-dogecoin`

More parameters can be found here: https://zapier.com/blog/twitter-advanced-search-guide/
