### ISSUE TITLE
Document currently implemented filters.

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#215]
I wanted to make a FR to filter for author, participant (being replied to) and more. Seems that `author:@jtagcat` seems to work fine already.

**Comment by zedeus** [comment]
https://help.twitter.com/en/using-twitter/twitter-advanced-search

**Comment by jtagcat** [comment]
As general project discussion, would you plan using GH wiki or any other platform for documentation?

**Comment by zedeus** [comment]
Both, not sure which platform, I might just host it myself.
