### ISSUE TITLE
Simplify advanced filters.

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#217]
The current advanced search checkboxes take up space, provide unnecessarily too much information for the user to go through the first time, and every consecutive time searching, parse through:
![screenshot of the advanced filters](https://user-images.githubusercontent.com/38327267/87087845-57befe00-c223-11ea-9156-b87276215b84.png)

Remove the exclude section, check all the boxes by default, and add a 'select/unselect all' button(s).

**Comment by zedeus** [comment]
Filter doesn't mean include, it means "only show this". I know it's a lot of boxes, and it could be a lot more (Twitter has many other content types), but it's the best layout I could come up with (especially without using JavaScript).

**Comment by jtagcat** [comment]
I can't see the problem there. So if you start with Filter (whitelist) all checked:
 - to get only replies: click deselect all, click replies
 - to get everything but videos: uncheck videos

**Comment by zedeus** [comment]
It's a problem because it doesn't work like that. If you filter images, pro videos and quotes, you get no results because a tweet that satisfies all three filters doesn't exist. It's an exclusive AND query, if you click the Twitter icon top right after doing a search you're taken to the equivalent search page with the actual query.

**Comment by jtagcat** [comment]
> It's a problem because it doesn't work like that. If you filter images, pro videos and quotes, you get no results because a tweet that satisfies all three filters doesn't exist. It's an exclusive AND query, if you click the Twitter icon top right after doing a search you're taken to the equivalent search page with the actual query.

A checkbox for 'the checkboxes work in and/or mode' could solve it, but I see your point. Feel free to close.

**Comment by zedeus** [comment]
I agree, but where would you fit in that checkbox, without screwing up the layout on all screen sizes?

**Comment by jtagcat** [comment]
I would make an additional incomplete row above the checkboxes.

Though a better question to ask if if it works without JS.

**Comment by zedeus** [comment]
Closing in favor of #116
