### ISSUE TITLE
Search: Threads

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#218]
Advanced search: allow searching for thread/multi-tweet posts (user replies to own tweet).

Optional: 'Thread' _and_ 'Thread in replies', marking if the first (top level, root) tweet is by the user or not.

**Comment by zedeus** [comment]
Twitter has a very obscure "in_thread" filter, but you can't compose a search that only shows threads including the first tweet, excluding all non-thread tweets.

**Comment by jtagcat** [comment]
```
Root tweet (1)
|
Tweet 2
|
Tweet 3
```
So do only tweets 2 and 3 get the `in_thread` filter? Can you do any searches about threads?

**Comment by zedeus** [comment]
Yes, if you also want the root tweet you get every tweet that isn't inside a thread.

**Comment by jtagcat** [comment]
Not getting the root tweet seems fine to me. In theory, it's also possible to get the parent of a returned search result, until root is found (would provide really fancy compacted threads, but not needed imo).

**Comment by zedeus** [comment]
It's possible in theory, but has the same issue as I mentioned in https://github.com/zedeus/nitter/issues/219#issuecomment-656494871. You can do this yourself already by searching `from:<user> filter:self_threads` which will show you only self-thread replies. I don't see this as useful enough to try squeezing it into the search menu right now, but I'll keep it in mind when I write the documentation for search.
