### ISSUE TITLE
Search: Starts with

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#219]
Allow searching for starts with, this enables searching for top level tweets mentioning or dot mentioning others.

**Comment by zedeus** [comment]
Twitter doesn't support this, and doing extra filtering will provide misleading results.

**Comment by jtagcat** [comment]
Why will it provide misleading results?
user @ nitter: starts with `.@jtagcat`
page = 1
while results < 10; do
nitter to twitter: search .@jtagcat, page n
twitter: here's page 1
nitter: do any of these _start_ with .@jtagcat, if yes keep the result(s) and results++ for each
page++
done

**Comment by zedeus** [comment]
Then you're doing multiple API requests per search which will take longer (2-400 ms per request), and it would take a lot of changes to implement custom filters. It's possible but currently out of scope.

**Comment by zedeus** [comment]
I think for now this kind of feature (advanced custom search) is too out of scope and should be left to developers using the Nitter API (when it exists). Doing a "starts with" query is complicated, consider the search "starts with test". This could require tens of search requests before a single tweet shows up starting with "test", and we don't necessarily want to run ten search requests (taking 3-4 seconds) just to a show a single tweet. This is fine if you're a developer making a research tool, but it's far too unintuitive as part of the web client. "why is it slow?", "why did it only show one tweet?", etc.
