### ISSUE TITLE
Handle nitter instance in url: search filter

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#220]
With searches, you can either use `url:<id>` or `url:<the actual url>`.

It doesn't work well with `<the actual url>`, because it's not handled, twitter doesn't know nitter.

Nitter should look for `url:`, replace the current nitter instance (and I also think nitter.net anyway) by twitter.com, remove trailing `#r` or `#m`, then send the request.

**Comment by zedeus** [comment]
I don't see the issue. If it doesn't work well with the full Nitter url, why not just use the ID? Part of the current search design is the input field is completely untouched, letting the user perform an exact search.

**Comment by B0pol** [comment]
Because #134 is still not implemented, it would save some time. I currently do that several times per day, I guess you don't see the issue because you don't use it a lot.

**Comment by zedeus** [comment]
If trimming the url to just use the id is too much work, you could right-click copy the url from the Twitter icon top right.
