### ISSUE TITLE
Increase top bar tap target size

### ISSUE THREAD

**Issue by mathijshenquet** [zedeus/nitter#226]
These buttons are imho too small to function as tap targets on mobile:

![Screenshot_20200722-143743_Trebuchet~3](https://user-images.githubusercontent.com/242143/88178006-00a92800-cc2a-11ea-8574-1e863fd8feca.png)

I would suggest giving them some left-right padding and possible slightly increasing the icon sizes

I would be interested in contributing on this.

**Comment by sale2000** [comment]
I would suggest a hamburger menu (in the right side with text drop down) instead of icons. See github.com/zedeus/nitter in a mobile browser.
