### ISSUE TITLE
Bad # detection

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#227]
If there is a character right before a #, it won't be considered as a #, i.e. ...#Hashtag won't be changed into a link ...[#Hashtag](https://nitter.net/search?q=%23Hashtag)

I encountered ...# and ?# but it should probably happen with other

<img src="https://i.ibb.co/XYbk0XB/Screenshot-20200725-120245-Fennec-F-Droid.png" width="300"> <img src="https://i.ibb.co/yBCL3yP/Screenshot-20200725-120322-Fennec-F-Droid.png" width="300">
Link: https://nitter.net/Guillaume_Bigot/status/1286908201259225088#m

**Comment by B0pol** [comment]
if you remove https://github.com/zedeus/nitter/blob/master/src/parserutils.nim#L9 ? here it works. But why did you exclude `\w-_./?`?

**Comment by zedeus** [comment]
If you remove that it also matches hashtags in links
