### ISSUE TITLE
Add support for embeds

### ISSUE THREAD

**Issue by Perflyst** [zedeus/nitter#23]
Nitter currently not support Twitter embeds. Would be nice if it does.

**Comment by Booteille** [comment]
IMO it's one of the most important feature Nitter needs actually.

**Comment by zedeus** [comment]
I'm not really sure what you mean by this, can you show me an example?

**Comment by Perflyst** [comment]
Take a look here: https://help.twitter.com/en/using-twitter/how-to-embed-a-tweet
There are examples of different embedds.

**Comment by theel0ja** [comment]
Related: https://github.com/heiseonline/embetty-server

**Comment by Zero3K** [comment]
How much longer until this is added?

**Comment by zedeus** [comment]
@Zero3K  Within the next month or so, been busy recently

**Comment by Zero3K** [comment]
Thanks for adding support for them when you do.

**Comment by skyler14** [comment]
I'm curious if this feature got implemented, actively would like to use in a project.

**Comment by zedeus** [comment]
It's on the top of my todo list, but I don't have the funds to continue development yet.

**Comment by jtagcat** [comment]
Though not a large sum, hope it helps.

![jtagcat is now sponsoring zedeus](https://user-images.githubusercontent.com/38327267/90053894-9e908f80-dcca-11ea-9e49-38c636d0b77b.png)

**Comment by bertvandepoel** [comment]
The organisation I'm a member of is looking for a privacy-friendly (and preferably FOSS) way to include social media links on a website. We might be able to sponsor/donate to make this happen (it would need to go to a vote though). Is there a specific number you're looking at do make this happen? As a non-profit, it would be much more convenient for us to do a one time payment than a monthly sponsorship. But we could consider both. If you prefer not to discuss money in public, you can always email me.

**Comment by zedeus** [comment]
@bertvandepoel that sounds great, thank you for reaching out! I'll send you an email later today to discuss.

**Comment by bertvandepoel** [comment]
@zedeus is it possible you've forgotten to email me? Or did something go wrong someplace?

**Comment by zedeus** [comment]
@bertvandepoel sorry, the past month has been very busy so I totally forgot. I'll send you an email right away!

**Comment by Elaborendum** [comment]
Was there any progress on this or is it still on the to do list?

**Comment by zedeus** [comment]
Closed by #515
