### ISSUE TITLE
docker Error building image

### ISSUE THREAD

**Issue by ghost** [zedeus/nitter#232]
I have this error when i build nitter with `docker build -t nitter:latest .`

`     Error: Specified directory (/src/nitter) does not contain a .nimble file.
The command '/bin/sh -c apk update     && apk add libsass-dev libffi-dev openssl-dev redis     && nimble build -y -d:release --passC:"-flto" --passL:"-flto"     && strip -s nitter     && nimble scss' returned a non-zero code: 1
`
Anyone has the same issue ? if yes how to resolve that ?

**Comment by mehkera** [comment]
Soory but this docker works for me : [docker-nitter](https://github.com/goodtiding5/docker-nitter)
