### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by jamieadamsuk** [zedeus/nitter#239]
Hi,

I'm trying to run Nitter on my raspberry pi (arm 32bit). I can't use the docker image, so am trying to build from source.

I've installed Nim v.1.2.6.

The build is failing with:

`     Error: Could not read package info file in /home/adamsj/repositories/nitter/nitter.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     scss        Generate css
        ... printPkgInfo() failed.`

I have installed libsass-dev:

`Package: libsass-dev
Source: libsass
Version: 3.5.5-4
Architecture: armhf
Maintainer: Debian Sass team <pkg-sass-devel@lists.alioth.debian.org>
Installed-Size: 6370`

Any tips to get this working?

**Comment by jginspace** [comment]
This will be a problem with your install of nim. I got exactly the same feedback on Ubuntu 18.04 when I had nim from the repos, as well as the binaries (v1.2.6) from nim-lang.org

First note that nitter requires nim >= 1.2.0, so remove anything older than that. Then I noticed the install script for the binaries hadn't copied the nimble binary, so I copied that over (I chose /usr/local/bin). Then it worked.
