### ISSUE TITLE
When filtering for links, then pictures and videos are also shown

### ISSUE THREAD

**Issue by sojusnik** [zedeus/nitter#242]
When enabling Filter > Links in the [search](https://nitter.net/search), then the results not only contain Tweets with links, but pictures and videos too. However, I'm expecting to see only Tweets with clickable URLs (even without `www.` or `http(s)://`) within the text of a Tweet.

**Comment by zedeus** [comment]
As I've [previously](https://github.com/zedeus/nitter/issues/219#issuecomment-656494871) explained, Twitter specific things like search filters are untouched by Nitter, and it will stay that way. Tweets with pictures and videos include a twimg or similar link in the tweet, so they get picked up by that filter.
