### ISSUE TITLE
Remove navigation bar at start, when gifs are on autoplay

### ISSUE THREAD

**Issue by sojusnik** [zedeus/nitter#243]
When autoplay of gifs is enabled, then the navigation bar is shown, when gifs start to play. Only after moving the mouse over the gif, the navigation bar disappears. Would be nice, if the navigation bar could be hidden from the start.

Happens on Ubuntu 20.04 with Firefox 79.0.

**Comment by zedeus** [comment]
As far as I know this is a Firefox quirk, not much I can do
