### ISSUE TITLE
RSS: keep newline characters for readability

### ISSUE THREAD

**Issue by notofoe** [zedeus/nitter#245]
Blank lines are [currently removed](https://github.com/zedeus/nitter/blob/75fea828cb20ea92c53a0740dc96bf553ec67621/src/views/rss.nimf#L57) when generating RSS feeds, which breaks the layout of some tweets (e.g. [poems](https://nitter.net/yitianshijieipn/status/1291206928454959104#m) or [bulleted lists](https://nitter.net/yitianshijieipn/status/1294112418830774273#m)). Leaving blank lines will make those tweets easier to read.

**Comment by zedeus** [comment]
They are not removed, they are stripped from the beginning and end.
