### ISSUE TITLE
Can't subscribe to nitter rss feeds with ttrss

### ISSUE THREAD

**Issue by stemy2** [zedeus/nitter#246]
Hello,

I can subscribe to nitter's rss feeds with any feed reader, except TTRSS. Either i have the following error messages:

`Error while reading the response. This may be due to an expiration of the request to the server and/or network problems. The server's response has been traced in the browser console.`

either i have an HTTP 500 error. And i'm sure the TTRSS server works fine.

However, when the usernames doesn't contain an underscore, it works fine.

**Comment by zedeus** [comment]
Does this still happen?
