### ISSUE TITLE
Wasted space in desktop (responsive view)

### ISSUE THREAD

**Issue by sale2000** [zedeus/nitter#255]
These days people post large images that show up very tiny because of zoom-out (whatever making image small) - hence unreadable. See attachment.
![1](https://user-images.githubusercontent.com/35148108/92991649-b59ee900-f4e5-11ea-8b0c-a9b876b0a0fa.png)

Ideally like a webpage can nitter be always resized at least to 1280x800 laptop. I mean most laptops/monitors are 1280 width.

There is so much wasted space in left and right of page. (May be as a temporary test you can make it appear in a 'drop-down' menu in Theme -> Responsive/Wide view.

Some how related to https://github.com/zedeus/nitter/issues/30

**Comment by zedeus** [comment]
I get your point, but browsing twitter/nitter without margins would be a horrible experience in my opinion.

Also related: https://github.com/zedeus/nitter/issues/17
