### ISSUE TITLE
List query returns "No items found"

### ISSUE THREAD

**Issue by sharkusmanch** [zedeus/nitter#256]
I have a previously working nitter link that queried a list and did some filtering. Was returning tweets as expected up until a few days ago. Have tried different lists and accounts, no luck.

Same query, but using nasa/astronauts:
https://nitter.net/search?f=tweets&q=list%3Anasa%2Fastronauts&e-nativeretweets=on&e-replies=on&since=&until=&near=

Returns:
```
No items found
```

**Comment by zedeus** [comment]
When performing the same search via Twitter, it says "This is an invalid search query. Please try a different one."
Seems like they removed this filter, but it's still listed in their docs, not sure what's going on.

**Comment by sharkusmanch** [comment]
Looks like it is now working
