### ISSUE TITLE
An error has occured in one of your routes. (2)

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#259]
Related: #131 

The docker host VM suffered from running suddenly with no disk.

```
An error has occured in one of your routes.

Detail: strutils.nim(1087) parseInt
asyncfutures.nim(383) read
asyncfutures.nim(383) read
asyncfutures.nim(383) read
asyncfutures.nim(383) read
invalid integer: Show
```
Removed anything to do with the docker container, yet still I get this error on some items.
Some items I could get to display after a refresh, others I couldn't at all.

**Comment by jtagcat** [comment]
`-_-`
Looks like browser cache was the issue. No idea why.

**Comment by jtagcat** [comment]
Huh, magic. It seems to appear on random, and I was just making connections :/

**Comment by zedeus** [comment]
This has been happening more frequently on nitter.net as well, it's even happening constantly right now. I looked into it and found the issue, will push a fix in a bit.
