### ISSUE TITLE
Move nitter specific things to subdirectory

### ISSUE THREAD

**Issue by Perflyst** [zedeus/nitter#26]
Nitter settings and info currently could also be an user. What if I wanna visit a user called "settings"?
I wouldnt move the users because Twitter uses twitter.com/username, what about

`nitter.net/.nitter/settings` or similar?

**Comment by zedeus** [comment]
twitter.com/settings goes to the settings page and twitter.com/about goes to their about page, so I don't think this is an issue

**Comment by Perflyst** [comment]
Oops, sorry didnt checked this.
