### ISSUE TITLE
Jester route exception

### ISSUE THREAD

**Issue by splacat** [zedeus/nitter#261]
When following an external link that points to any post of my Nitter instance the browser shows:

Jester route exception
An error has occured in one of your routes.

Detail: strutils.nim(1087) parseInt
asyncfutures.nim(383) read
asyncfutures.nim(383) read
asyncfutures.nim(383) read
asyncfutures.nim(383) read
invalid integer: Show

Logs are not showing any error.

**Comment by zedeus** [comment]
Update to latest commit

**Comment by splacat** [comment]
Just updated it and is working fine now. Thanks @zedeus. Closing this.
