### ISSUE TITLE
504 gateway timeout on pictures/videos

### ISSUE THREAD

**Issue by sheddup** [zedeus/nitter#266]
\* On nitter.net
example https://nitter.net/pic/media%2FElDf2PjXEAEsTXp.jpg%3Fname%3Dsmall

**Comment by zedeus** [comment]
Nitter has been DDoS'd by a massive scraping attack. Attempts to block IPs didn't help enough, so the instance is down for now.

**Comment by zedeus** [comment]
Accidentally blocked Twitter IPs, they're unblocked now and nitter.net is running again.
