### ISSUE TITLE
hashtag hyperlink bug 

### ISSUE THREAD

**Issue by dundundunnn** [zedeus/nitter#267]
sometimes hyperlinks of hashtags doesnt appear

**Comment by zedeus** [comment]
example?

**Comment by dundundunnn** [comment]
https://nitter.net/tyabo6/status/1282511303353839616
https://twitter.com/tyabo6/status/1282511303353839616

**Comment by Mennaruuk** [comment]
I can now see the hyperlinks for the hashtags in the OP’s links. Should this issue be closed?
