### ISSUE TITLE
RSS feed fails to parse when account has invalid characters

### ISSUE THREAD

**Issue by hanbaobun** [zedeus/nitter#268]
RSS Feed fails to parse when account has invalid characters such as  or .
Attemping to view RSS feed results in "XML Parsing Error: not well-formed"

**Comment by zedeus** [comment]
Example? This doesn't tell me enough to figure out a fix

**Comment by hanbaobun** [comment]
Here's an [example of an account](https://nitter.net/puffyvolvo/rss) with broken rss

**Comment by zedeus** [comment]
Works fine for me using Feedbro, what client are you using?

**Comment by cjfloss** [comment]
Opening on Firefox with [RSSPreview](https://addons.mozilla.org/en-US/firefox/addon/rsspreview/) extension gives me this error

![Screenshot from 2020-11-07 17 18 32](https://user-images.githubusercontent.com/5838486/98451573-47f5ee80-211d-11eb-8da7-15de9c23ac4a.png)
