### ISSUE TITLE
Add means to filter/exclude specified hashtags

### ISSUE THREAD

**Issue by sharkusmanch** [zedeus/nitter#269]
Would it be possible to add a means to filter specified hashtags from a search? Looks like the Twitter search API might not support this, but would it be complex to add on top?

### Example

Querying a list https://nitter.net/search?f=tweets&q=list%3Anasa%2Fastronauts

Would like to exclude tweets with the hashtag `#ad`

**Comment by zedeus** [comment]
Adding `-#ad` is enough

**Comment by sharkusmanch** [comment]
Thanks. Didn't know that was an option.

Here's the example query for anyone that finds this later:
```
-#ad list:nasa/astronauts
```

```
https://nitter.net/search?f=tweets&q=-%23ad+list%3Anasa%2Fastronauts&e-nativeretweets=on&e-replies=on&since=&until=&near=
```
