### ISSUE TITLE
Make .tweet-content.media-body clickable

### ISSUE THREAD

**Issue by vinliao** [zedeus/nitter#270]
**Problem**
It's kind of a minor thing, but it seems odd to not be able to click the tweet on the tweet content.

**Desired behavior**
Make the content of tweet (`<div class="tweet-content media-body">blahblahblah</div>`) clickable.

**Comment by zedeus** [comment]
tweets are clickable but https://github.com/zedeus/nitter/issues/76 made it so click events can't pass through the text field (tweet-content), meaning you have to click around it. it sucks and it's been on my mind for a long time, the only option I can think of is making bidirectional support a preference which also sucks.

**Comment by vinliao** [comment]
Have you ever considered making the div into an `<a>` tag instead?
