### ISSUE TITLE
Intermitent 404 on rss feeds

### ISSUE THREAD

**Issue by danieljakots** [zedeus/nitter#280]
Hi,
I'm running cad7584 with docker. I subscribed to some rss feeds. From time to time, instead of having a 200, I get a 404. I was advised to remove "-d:release" from nimble build to get logs. But they're not super helpful.

Here's the log both when it worked and when it didn't.

```
DEBUG GET /reuters/rss
DEBUG   200 OK {"content-type": @["application/rss+xml; charset=utf-8"], "min-id": @["HBaCwKeF+P7q6CQAAA=="]}
DEBUG GET /reuters/rss
DEBUG   404 Not Found {"content-type": @["text/html;charset=utf-8"]}
```

**Comment by diabolic-preacher** [comment]
I see this randomly happening from yesterday on some of the nitter rss feeds that i subscribe, but i noticed that not only the rss resource but also the profile page on that specific nitter instance also gives a 404 regardless of which device I use. @danieljakots if you face this issue, could you also please check the profile page on that nitter instance..for example, you gave an example of reuters account.

**Comment by danieljakots** [comment]
Since there's little interest in this, there's no point in keeping it open so I close it.

**Comment by kevincox** [comment]
I am seeing this. For example on the official instance https://nitter.net/endangeredcomic/rss frequently returns 404. Is the problem that a backend failure is being turned into a 404 instead of a 502 or 500?

**Comment by mostfunkyduck** [comment]
I use a self hosted instance with about a dozen feeds and this happens to all of them on a daily basis.

**Comment by zedeus** [comment]
@mostfunkyduck what commit are you running?

**Comment by mostfunkyduck** [comment]
47f47bb

**Comment by zedeus** [comment]
Weird, any interesting logs? Does it only affect RSS feeds?

**Comment by mostfunkyduck** [comment]
Logs are empty, though if there's a way to crank up the verbosity, happy to do so.  I see this rendering tweets/profiles as well, though I usually am using the RSS feeds to read stuff (with ample refreshing of the feeds), so I'm not sure how prevalent the issue is.

**Comment by zedeus** [comment]
Is it the usual "Page not found" error page? How often does it happen? Nitter itself can't be told to make more logs unfortunately

**Comment by mostfunkyduck** [comment]
The RSS feed reader I use (miniflux) gets a HTTP 404 error.  I reproduced in the browser just now with `@quinnypig` and it rendered the profile and banner, but no tweets.  I checked in dev tools when this was happening and everything was returning 200s and the console was empty. 
![image](https://user-images.githubusercontent.com/2138274/148064012-bfc86c4c-b8a4-43ba-9558-ebe5d8aa3602.png)

For what it's worth, it seems to happen regularly if I refresh the page enough times.  Each refresh is hit or miss - it doesn't start consistently breaking, subsequent refreshes may work.

I can try building from source and attempting to reproduce with debug logs on at some point this week, depending on how much time I have for it.

**Comment by zedeus** [comment]
This sounds exactly like what would happen before my recent fixes to the token pool, I can't imagine it why it would still happen now

**Comment by mostfunkyduck** [comment]
Interesting, how was it breaking? That might help me debug. I could also try configuring the token pool differently if that could somehow impact behavior.

**Comment by mostfunkyduck** [comment]
gotta step away for a bit, but I tried doubling the token count in the config from 10 to 20 and redeployed and I haven't been able to reproduce yet.  My HUNCH is that this has to do with token expiry times more than the increased count, but we'll see.  I'm going to let it sit for a while and see what happens to the feeds.

**Comment by zedeus** [comment]
@mostfunkyduck I've reworked the token pool's logic completely to hopefully fix every remaining issue that can cause intermittent 404s/"rate limits", let me know if it's still an issue with the latest commit

**Comment by mostfunkyduck** [comment]
@zedeus awesome! I've deployed the latest. I'll give it about 12 hours before declaring victory.  I didn't watch it closely enough to pinpoint when it starts failing, but 12 hours seems ample.  I also noticed the new `enableDebug` config setting and I have that on.

**Comment by mostfunkyduck** [comment]
@zedeus Sorry for the delayed response.  The fix we discussed here didn't actually work, BUT 3d91ae0256d899da5346449c26380fa269011b6e seems to have done the trick. I applied it as soon as it hit master and haven't had a 404 since, compared to them setting in almost immediately before.

**Comment by VIEWVIEWVIEW** [comment]
> @zedeus Sorry for the delayed response. The fix we discussed here didn't actually work, BUT [3d91ae0](https://github.com/zedeus/nitter/commit/3d91ae0256d899da5346449c26380fa269011b6e) seems to have done the trick. I applied it as soon as it hit master and haven't had a 404 since, compared to them setting in almost immediately before.

@zedeus is this deployed on nitter.net? Today had the same issue as @mostfunkyduck had: I use an rss feed reader, and got a 404 on https://nitter.net/HindenburgRes/rss.

**Comment by zedeus** [comment]
@VIEWVIEWVIEW you can see which commit is being used on the about page, nitter.net/about
It was probably just an intermittent server issue.
