### ISSUE TITLE
video returning 404

### ISSUE THREAD

**Issue by kotonbu** [zedeus/nitter#281]
I am trying to run my own instance of nitter but when trying to play video they return 404. tried with both proxy videos on and off with same results.

**Comment by zedeus** [comment]
I need more info to know whats going on here, like apache/nginx, vps host, etc

**Comment by kotonbu** [comment]
> I need more info to know whats going on here, like apache/nginx, vps host, etc

running behind a nginx reverse proxy on a dedicated server from scaleway.

**Comment by zedeus** [comment]
did you use the recommended nginx config?
https://github.com/zedeus/nitter/wiki/Nginx

**Comment by kotonbu** [comment]
I didn't originally but edited the config afterwords to have the settings in the recommended config and reloaded nginx. That was still giving 404 but now I tried deleting the original config, pasting in the recommended one, changing only the required items and that has fixed the problem.

**Comment by zedeus** [comment]
Cool, this stuff is brittle as hell
