### ISSUE TITLE
Sometimes "more replies" leads to no more replies

### ISSUE THREAD

**Issue by somini** [zedeus/nitter#282]
The "more replies" link appears on tweets that don't appear to have more replies.

On Twitter itself, the replies appear after the fold, with a "show more replies link".

Here's an example, this the reply itself. The "more replies" link appears on the parent tweet.

https://nitter.net/linguistica67/status/1327639551741976576

**Comment by zedeus** [comment]
This seems to work now, guessing it was an issue on Twitter's side
