### ISSUE TITLE
Unrelated tweets in RSS streams

### ISSUE THREAD

**Issue by stemy2** [zedeus/nitter#283]
Hello,

When consulting the RSS stream of an user i'm following, i had the surprise to find some tweet from another person totally unrelated to him. It wasn't even retweets, it was tweets from another person.

In the example here below, some trump's tweets are without explicit reason on the rss stream of another person.
![Screenshot_20201117_095536](https://user-images.githubusercontent.com/22192600/99368355-f2ef7080-28b2-11eb-8ecb-3ede94611b17.png)

**Comment by zedeus** [comment]
Well, that's strange to say the least. Do you know if those tweets were both in the same rss response, or is this a feed that mixed multiple responses?

**Comment by stemy2** [comment]
No, how can i have a such information ?

Another precision: these unrelated tweets are not in the actual nitter thread.

**Comment by zedeus** [comment]
Has it happened more than once?

**Comment by stemy2** [comment]
No, only this time.

**Comment by ysh16** [comment]
I can confirm this behavior, it has happened twice to me, both times today.
Please let me know if and how I can provide more information.
![2021-01-13-133151_1918x1056_scrot](https://user-images.githubusercontent.com/77393013/104454720-92289f80-55a6-11eb-8989-35b8a9ed0fb7.png)
![2021-01-13-133959_1918x1056_scrot](https://user-images.githubusercontent.com/77393013/104454727-9359cc80-55a6-11eb-8dc1-7f9d0aed89c2.png)

**Comment by stemy2** [comment]
It happened again, this is on the main instance.
![Screenshot_20210126_003007](https://user-images.githubusercontent.com/22192600/105779013-6d003d80-5f65-11eb-96dd-3e57b8fce46e.png)

**Comment by zedeus** [comment]
I think this _might_ be related to the issue described [here](https://github.com/zedeus/nitter/issues/305#issuecomment-767212981), if it isn't I have absolutely no idea. With an error that isn't only spontaneous, but seemingly very rare, I have basically no chance of reproducing and debugging it.

**Comment by zedeus** [comment]
Actually, from 23:46 to 23:57 a ton of Redis errors were printed (multiple per second), which coincides with @stemy2's feed (latest tweet is from 23:51). It's some error with the Redis clients, which might mean their usage overlaps a bit, resulting in different RSS feeds getting mashed together. It's an error that has happened a few times in the past, but like mentioned above it's quite difficult to find out why, I'll have to investigate further.

**Comment by stemy2** [comment]
It just happened again. 

I hopt the xml file from the stream will help you a bit.
[rss-1.txt](https://github.com/zedeus/nitter/files/5899491/rss-1.txt)

**Comment by stemy2** [comment]
It seems that you are right when you suppose that it's a redis problem.

I just tried to go to the URL of an account that has unrelated tweets in its RSS streams, and i got this:

```
An error has occured in one of your routes.

Detail: redis.nim(122) raiseReplyError
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
redpool.nim(61) getProfileIdIter
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
Expected '$' at the beginning of a status reply got '�'
```

The page has no other content and the page title is "Jester route exception".

At the time i'm writing is, the problem is still there and affects all my subscriptions.

**Comment by rzumer** [comment]
This happens to me almost every day, sometimes 2-3 times a day, it's very annoying because I have a setup where feed updates (polled every 5 minutes) are sent to a chatroom and I get spammed with 10-20 messages whenever it happens.

**Comment by zedeus** [comment]
I think this has been solved now, please reopen if not.

**Comment by stemy2** [comment]
Hello, it happened again.

**Comment by zedeus** [comment]
What instance?

**Comment by stemy2** [comment]
The main instance, nitter.net.
