### ISSUE TITLE
Search comes up with same tweets

### ISSUE THREAD

**Issue by privsecti** [zedeus/nitter#286]
When you search something on nitter and click 'Load more', it shows same tweets over and over again.

It would be nice to have some kind of 'sort by date' option in the search to prevent duplicate results.

**Comment by zedeus** [comment]
Do you have an example where this happens?

**Comment by privsecti** [comment]
Try: [https://nitter.net/search?f=tweets&q=클립스튜디오](https://nitter.net/search?f=tweets&q=%ED%81%B4%EB%A6%BD%EC%8A%A4%ED%8A%9C%EB%94%94%EC%98%A4)

Here's screenshot with repeating results. (Marked duplicates with red boxes.)

[![nitter-net-search.png](https://i.postimg.cc/HxZQCqjr/nitter-net-search.png)](https://postimg.cc/HcMJwPwm)

**Comment by zedeus** [comment]
They are not actually duplicates, they're retweets by different people. To avoid this, Nitter would have to keep track of which retweets have been shown on previous pages, which is infeasible. You can enable "infinite scroll" in preferences which lets you view more search results while filtering out duplicate retweets.

**Comment by privsecti** [comment]
Thank you. Didn't realize those are just retweets flooding the search. I enabled infinite scroll + filtered retweets and now it works as I expected.
