### ISSUE TITLE
Certificate Expired

### ISSUE THREAD

**Issue by georgelemental** [zedeus/nitter#287]
nitter.net's SSL certificate expired today.

**Comment by Mennaruuk** [comment]
Until the SSL certificate is renewed, you can check out the other Nitter instances [here](https://github.com/zedeus/nitter/wiki/Instances).

**Comment by fuckyourdumbshit** [comment]
> 
> 
> Until the SSL certificate is renewed, you can check out the other Nitter instances [here](https://github.com/zedeus/nitter/wiki/Instances).

Good idea, I didn't even think to do that. Interestingly it seems that the RSS feeds generated on nitter.net still work on my computer but firefox has no workaround to ignoring the security blurb and going to the site anyway.

**Comment by Mennaruuk** [comment]
> 
> 
> > Until the SSL certificate is renewed, you can check out the other Nitter instances [here](https://github.com/zedeus/nitter/wiki/Instances).
> 
> Good idea, I didn't even think to do that. Interestingly it seems that the RSS feeds generated on nitter.net still work on my computer but firefox has no workaround to ignoring the security blurb and going to the site anyway.

Interesting. I think whatever RSS reader you're using isn't compliant with HSTS, hence your still seeing the feed. I added a random feed to RSSOwl and it worked right away. I also tried accessing the link directly in an old version of SeaMonkey. While it prompted me that the certificate has expired, there is an option to add the site as an exception. Once I did that, I was able to see the RSS feed.

**Comment by Rult** [comment]
@Mennaruuk Do you happen to know which Android RSS readers have HSTS?
