### ISSUE TITLE
Feature Request: Cache images/videos

### ISSUE THREAD

**Issue by benpro** [zedeus/nitter#288]
Ability to cache to local disk images and videos.
Or is it already the case? My cache directory is empty though.

**Comment by zedeus** [comment]
It used to be the case, but it was replaced with efficient streaming. The empty cache directory is a leftover from that. I'd like to avoid the complexity of implementing a proper cache, and instead recommend using a cache like http://squid-cache.org, or nginx's built-in `proxy_cache`.

**Comment by benpro** [comment]
Hmm. Ok.
I'd still prefer a save to disk then serve files. So next time someone load the same tweet it will be served from the disk cache and not streamed again from twitter.
