### ISSUE TITLE
X more replies not clickable on a tweet

### ISSUE THREAD

**Issue by Perflyst** [zedeus/nitter#29]
If you have a tweet with different replies which also have replies there is a button with `x more replies`. If you click it, it should show the current hidden replies.

Example: https://nitter.net/pewdiepie/status/1160983286031798272

**Comment by zedeus** [comment]
This will be supported but it's somewhat a long-term goal, as it requires JavaScript and some infrastructure to support this kind of thing. It will be added along with infinite scrolling and similar features

**Comment by zedeus** [comment]
This is now somewhat supported, it just links to the tweet above so it doesn't really do anything new. Using JS to dynamically fetch the comments and display them similar to how Twitter does it will be added in the future.
