### ISSUE TITLE
Deleting tweets causes duplicate entries in feed.

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#293]
I think the feed is capped to 20 tweets. Deleting any tweet in there causes the next older tweet(s) to appear.

If the older tweet has already been in the feed, a duplicate entry is created. Yet Thunderbird, doesn't identify the tweets as identical.

I'd like to confirm whether the re-appearing tweets are identical in the feed or not, and is this an issue of Nitter or Thunderbird.

**Comment by zedeus** [comment]
All RSS entries have the full tweet url as the guid, meaning they're unique. I don't think this is a Nitter issue.
