### ISSUE TITLE
Feature request: Expand t.co URLs

### ISSUE THREAD

**Issue by gloschtla** [zedeus/nitter#294]
Unfortunately nitter.net provides URLs incomplete as they appear in tweets, after they were automatically shortened via t.co

Incomplete URLs sometimes lead to wrong pages or to Error 404.

**Comment by zedeus** [comment]
Nitter extracts the full "expanded_url", I don't see how they can be incomplete. The displayed URL is shortened for obvious reasons. I don't understand what's wrong here, can you provide an example?

**Comment by zedeus** [comment]
No example provided, closing.
