### ISSUE TITLE
Support /i/user/[userid] urls

### ISSUE THREAD

**Issue by 0x7D2B** [zedeus/nitter#295]
Twitter has a URL scheme which allows linking to users using their id, rather than username: ` /i/user/[userid]`

For example, https://twitter.com/i/user/20603690 will redirect to https://twitter.com/korindo. It would be quite nice to have Nitter support this as well.

Looking at Twitter itself, the web app will GET https://api.twitter.com/1.1/users/show.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&user_id=20603690. The response will include `screen_name`, which will be the username of the user. Nitter actually already uses `show.json` in `getProfile`, but with the username (screen_name) as the argument.

**Comment by zedeus** [comment]
Solved by #450
