### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by romanrm** [zedeus/nitter#299]
The About page says: "Unofficial API (no rate limits or developer account required)"
Great! But how to use it? There's no link from that line in About to the API documentation. And no mention of it on the github page. Or is it so unofficial, that the only way to figure it out is from digging in the source code? I'll rather parse the HTML then. Thanks

**Comment by zedeus** [comment]
Nitter does not yet have an API itself, it uses Twitter's unofficial API.

**Comment by romanrm** [comment]
The About page really reads like it already has an API (listed as a bullet point along with RSS Feeds and Themes). I'd suggest clarifying that. Thanks!
