### ISSUE TITLE
"User not found" but tweets still load

### ISSUE THREAD

**Issue by prot475** [zedeus/nitter#301]
I've noticed this with several accounts.  I can access their individual tweets but not their man user page.

WON'T LOAD: https://nitter.net/ali/

LOADS FINE: https://nitter.net/ali/status/1341100031886172168

WON'T LOAD: https://nitter.net/realDonaldTrump

LOADS FINE: https://nitter.net/realDonaldTrump/status/1341169419259531265

**Comment by zedeus** [comment]
Rate limit
