### ISSUE TITLE
Provide releases/versions

### ISSUE THREAD

**Issue by hashworks** [zedeus/nitter#309]
It would be great if you could provide releases / fixed versions of nitter so one can provide OS packages.

**Comment by zedeus** [comment]
Nitter's versioning now is the current commit's date and tag, like so: 2022.01.30-ff96ba3
Releases will likely never happen, sorry.

**Comment by sschnabe** [comment]
I'm fine with timestamped tags. Can we include time?

**Comment by ehmry** [comment]
Why will releases never happen? Would you prefer that Nitter not be packaged by distros?

**Comment by CyberTailor** [comment]
Please make lives of people maintaining Nitter easier and provide actual versions.
https://repology.org/project/nitter/versions
