### ISSUE TITLE
About page is trying to redirect to About user

### ISSUE THREAD

**Issue by Booteille** [zedeus/nitter#31]
When clicking on the About button on the top right, Nitter tries to redirect me to a Twitter user called About.

You should probably move the About webpage under another path.

![Screenshot_2019-09-02 Error](https://user-images.githubusercontent.com/2203721/64131290-ef63ec80-cdc7-11e9-9590-8815170a8ce0.png)

**Comment by Perflyst** [comment]
There just is no about page yet... :)
If it gets added this wont happen anymore. Remember the WIP from the readme
