### ISSUE TITLE
[Feature Suggestion] prefers-color-scheme

### ISSUE THREAD

**Issue by Mennaruuk** [zedeus/nitter#312]
Hello! I was wondering if `prefers-color-scheme` could be implemented in Nitter, even if as an opt in. If enabled, Nitter would check for system theme and switch to either light or dark mode. GitHub has something similar to this, and DuckDuckGo uses `prefers-color-scheme`. I really like Nitter's default theme; it's distinctive and pretty. But I only use it at night since it's dark.

**Comment by zedeus** [comment]
I think I know what to do, but with so many other high priority things, this probably won't be done for a while. If anyone else wants to tackle this, I'd be happy to offer some guidance, it's a fairly small amount of work.

**Comment by Mennaruuk** [comment]
No problem, thank you for your hard work!!!!!
