### ISSUE TITLE
nitter follow list rss/atom

### ISSUE THREAD

**Issue by J0hsHH** [zedeus/nitter#313]
like you have on Invidious you can get a rss feed from all of the channels you follow inn 1 rss feed not individual rss feed like you can do on nitter.

**Comment by zedeus** [comment]
You can get an rss feeds with up to around 25 accounts like this: https://nitter.net/NASA,SpaceX,ElonMusk/rss
Alternatively you can create a list on Twitter and access it via Nitter: https://nitter.net/esa/lists/astronauts

**Comment by J0hsHH** [comment]
ok thanks  i did not know you culde do that. me bad

**Comment by impredicative** [comment]
> You can get an rss feeds with up to around 25 accounts like this: https://nitter.net/NASA,SpaceX,ElonMusk/rss
> Alternatively you can create a list on Twitter and access it via Nitter: https://nitter.net/esa/lists/astronauts

Doesn't work. It says "the instance has been rate limited".
