### ISSUE TITLE
DockerHub builds out of date

### ISSUE THREAD

**Issue by FireMasterK** [zedeus/nitter#314]
This is due to travis failing.

Reported at https://github.com/zedeus/nitter/issues/305#issuecomment-762875316

**Comment by zedeus** [comment]
Our builds on Travis keep failing due to some request error leading to a dockerhub rate limit. I have no idea what to do about this.

**Comment by Perflyst** [comment]
Dockerhub can build on push to master automatically. Try to setup those image builds on hub.docker.com, I don't think dockerhub rate limits itself.

**Comment by FireMasterK** [comment]
Or we could use GitHub actions for multi architecture builds.

**Comment by FireMasterK** [comment]
#317 should close this.

**Comment by setenforce0** [comment]
Thank you @FireMasterK!
