### ISSUE TITLE
[Feature request] Hide responses by default

### ISSUE THREAD

**Issue by stemy2** [zedeus/nitter#322]
Hello,

It's not a secret, Twitter can be very toxic. For this reason, i'd like to see some tweets via their own URL, but i'm systematically afraid to see some aggresive response (i'm higly sensitive to negative reactions). Is it possible to hide it by default ?

**Comment by zedeus** [comment]
You can hide tweet replies in the settings, and enable it by default in the instance config. This will not be set as the default config.
