### ISSUE TITLE
Adding New Instances

### ISSUE THREAD

**Issue by Mennaruuk** [zedeus/nitter#325]
I have a few questions about adding new instances.

1. What SSL grade should be expected for instances? I've seen some with A+, others with A, even others with B.
2. How can I check that the source code is same as Nitter.net's? I'm trying to cross-check instance source codes with Nitter.net's. [Nitter's license](https://github.com/zedeus/nitter/blob/master/LICENSE) is [AGPLv3.](https://choosealicense.com/licenses/agpl-3.0)

**Comment by zedeus** [comment]
SSL grade is not something I have an opinion on, it should just be as high as possible.
As for source code verification, you can check what git commit it was compiled with on the /about page, but this can be spoofed and doesn't account for uncommitted changes. Verifying server-side application code is virtually impossible, that's the biggest downside of not self-hosting. I could add some automatic code hash, but it would be trivial to spoof. There may be some fancy method that can achieve this to some extent, but I'm not aware of it at least.

**Comment by xnaas** [comment]
Somewhat relevant...there's something super wrong with the SSL/TLS on the official nitter.net – you can't even curl the site because of it. See: https://github.com/upptime/upptime/issues/171#issuecomment-789151093
