### ISSUE TITLE
Firefox Enhanced Tracking Protection blocking HLS playback unless it's proxied

### ISSUE THREAD

**Issue by Mennaruuk** [zedeus/nitter#326]
On Firefox, if Firefox Enhanced Tracking Protection is turned on, the browser will block HLS playback, even if it's enabled in Nitter's settings. There are two methods to work around this problem:

1. Turn on proxy streaming
![image](https://user-images.githubusercontent.com/52135169/105651606-5387c480-5e85-11eb-8028-493f7f99bfb8.png)

2. Disable ETP
![image](https://user-images.githubusercontent.com/52135169/105651679-8467f980-5e85-11eb-89b6-09224dc5ac03.png)

I wanted to point this out since it's been bugging me for a while, and I didn't know what's up. This probably applies to tracking protection and ad blockers on smartphones. Interestingly, uBlock Origin isn't interfering with HLS playback, so there was no need to disable it for Nitter.

**Comment by zedeus** [comment]
Proxying is not a workaround, it's the default and intended behavior to preserve privacy. Firefox complaining about streaming Twitter files through Nitter is not something I can do anything about.
