### ISSUE TITLE
Accounts redirecting to archived tweets of the previous proprietary

### ISSUE THREAD

**Issue by stemy2** [zedeus/nitter#327]
Hello,

This problem happens in specific cases. Some political personalities are giving their account to their successors, and it's updated on twitter but not on nitter. For example: the account @PressSec belong to the actual POTUS's press secretary, but on nitter, it redirects to @PressSec45, wich are the archived tweets of the previous press secretary. I don't know if i'ts happening with all instances, but i'm facing it very often.

**Comment by zedeus** [comment]
Duplicate of #321
