### ISSUE TITLE
invidio.us is deprecated and as been replaced by a new domain

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zedeus/nitter#328]
Please see: https://github.com/iv-org/invidious/issues/1694

Nitter still uses [replaceYouTube = "invidio.us"](https://github.com/zedeus/nitter/blob/master/nitter.conf#L34) in the config, this should be updated to use https://redirect.invidious.io/

**Comment by Perflyst** [comment]
Already done in https://github.com/zedeus/nitter/pull/324

**Comment by TheFrenchGhosty** [comment]
@Perflyst Oops, my bad I forgot to check the PRs.
