### ISSUE TITLE
use http when redirect to invidious

### ISSUE THREAD

**Issue by rachmadaniHaryono** [zedeus/nitter#331]
when using redirect option for youtube it will always use https. i run invidious and nitter on local docker and the invidous run on `http://127.0.0.1:3000`.

temporary solution for this is to use extension such as https://addons.mozilla.org/en-US/firefox/addon/redirector/ for firefox and redirect https to http for invidious instance

e: i just check my nitter instance and i found out that it also use http instead https so i have to create two redirect rule on that extension

**Comment by radhta** [comment]
you can use nginx to get this working for you as well (providing https, and redirecting to http; or proxying or even change link provided by nitter)..

this is such an edge case.. the browser might also be attempting to switch to https; as persons may configure it http, when https is available, in internet-facing instances, https would be preferred anyway (better safe than sorry)

**Comment by rachmadaniHaryono** [comment]
> you can use nginx

i have zero experience with nginx but i will try this

> this is such an edge case

i am aware of this so i'm ok if the dev will not fix will close the issue

**Comment by zedeus** [comment]
This would require redoing how substitutions are done which I would like to avoid. One solution is to disable it, and rely on a browser extension to redirect you (like Privacy Redirect).
