### ISSUE TITLE
#m (hashtag m)

### ISSUE THREAD

**Issue by Mennaruuk** [zedeus/nitter#333]
I couldn't find an existing issue for this, but is there a way to get rid of the #m (hashtag m) at the end of URLs?

Example: https://nitter.net/FunnyVines/status/1328430219665973248#m

**Comment by zedeus** [comment]
This is done to auto-focus the main post in threads, since you'll otherwise just see the first post which is disorienting and inconvenient. I could not and still have not been able to find a better solution to this that doesn't require JavaScript.

**Comment by Mennaruuk** [comment]
No problem, I was just curious about it. It's difficult to search in the code for something like this. Thank you for your clarification!
