### ISSUE TITLE
RSS feed displaying tweets not made by account

### ISSUE THREAD

**Issue by Ogwalla** [zedeus/nitter#334]
The RSS feed for various accounts are being filled with spam tweets that weren't made by the author.

**Comment by jdsys271** [comment]
Experiencing the same thing.. I also experienced this a while ago too.
For example, Elon Musk:
![2021-02-01](https://user-images.githubusercontent.com/63431535/106447840-a3204e80-648a-11eb-83e5-391cd65a2dba.png)

**Comment by jdsys271** [comment]
Possibly related to: https://github.com/zedeus/nitter/issues/106

**Comment by zedeus** [comment]
Duplicate of #106
