### ISSUE TITLE
Rate Limited

### ISSUE THREAD

**Issue by jamin724** [zedeus/nitter#336]
Hi,
Sorry I do not know really anything when it comes to these types of issues but I was using nitter for an RSS feed for twitter and now it says there is an error because it is rate limited. Is that something that can be fixed or am I doomed to never have an RSS feed of a twitter profile as it seems all other options are drying up.

**Comment by Mennaruuk** [comment]
#305

**Comment by jamin724** [comment]
That seemed to work thank you for helping me.
