### ISSUE TITLE
Support unified cards

### ISSUE THREAD

**Issue by xnaas** [zedeus/nitter#345]
Here is the unsupported card type...it appears to just be a YouTube link?

* [Tweet on Twitter](https://twitter.com/Tesla/status/1363595197926539268)
* [Tweet on nitter.net](https://nitter.net/Tesla/status/1363595197926539268)
* [Tweet on nitter.42l.fr](https://nitter.42l.fr/Tesla/status/1363595197926539268)
* [Tweet on nitter.nixnet.services](https://nitter.nixnet.services/Tesla/status/1363595197926539268)
* [Tweet on nitter.actionsack.com](https://nitter.actionsack.com/Tesla/status/1363595197926539268)

**Comment by zedeus** [comment]
This is part of their gradual move to "unified cards". The card payload contains a JSON serialized card that requires an entirely new parser, and it can have multiple cards. It appears simple at first but it's quite complex.

**Comment by xnaas** [comment]
Looks great. That particular card is...unfortunate as clicking it leads to a 404 on YouTube, but at least Nitter is rendering it. :)

**Comment by zedeus** [comment]
Works on my end with replaceYouTube set to piped, and with it disabled. What link are you getting?

**Comment by xnaas** [comment]
When it's set to only go to YouTube, no redirects, the link is https://youtube.com/f_GHVSL35-k // that's the original link when viewed on Twitter as well, which *also* leads to a 404.

**Comment by xnaas** [comment]
Hmm, definitely strange. I'll have to look into it more then; sounds like not a nitter issue per se.
