### ISSUE TITLE
Wiki edit-locked?

### ISSUE THREAD

**Issue by Jonta** [zedeus/nitter#346]
If so, I suggest putting up a notice about it to avoid confusion

And I request edit-permission

**Comment by TheFrenchGhosty** [comment]
@Jonta I recommended him in the Matrix to move the wiki to its own repository, like we did for [Invidious](https://github.com/iv-org/invidious): https://github.com/iv-org/documentation since there was an abuse, people spamming edits and people often changing stuff for no reason.

I'm guessing this is related.

**Comment by zedeus** [comment]
It's locked to contributors for the time being, you should be able to edi tit

**Comment by zedeus** [comment]
Oh, it's "collaborators", my bad. I'll revert it, but please keep the edits to a minimum, use the preview feature, and stop moving things around, it causes lots of spam in our IRC, @willemijns

**Comment by willemijns** [comment]
of course ! but i did not see the edit function :-(

![image](https://user-images.githubusercontent.com/4061615/109271667-2590f980-7810-11eb-898c-7eadce0658a1.png)

**Comment by zedeus** [comment]
It's at the top @willemijns 
![image](https://user-images.githubusercontent.com/9434921/109375355-73633b80-78bc-11eb-935f-bd9627906999.png)

**Comment by willemijns** [comment]
ok now !

**Comment by willemijns** [comment]
> @Jonta I recommended him in the Matrix to move the wiki to its own repository, like we did for [Invidious](https://github.com/iv-org/invidious): https://github.com/iv-org/documentation since there was an abuse, people spamming edits and people often changing stuff for no reason.

Le's stay absolutly clear. i'm directly targeted so i answer to that.

I did not see the preview button.

PERIOD. 

I think we can close the subject.

Sébastien WILLEMIJNS.

**Comment by Jonta** [comment]
I thought @willemijns was a bot, with that same edit-message every time, but I'm guessing that's the default message if one doesn't leave one's own edit-message

Does make it tedious to browse through the changes in the GitHub-web-UI though

What's a better interface?

The wiki doesn't seem to be included when cloning this repo
