### ISSUE TITLE
Wiki: Criteria for "slow", "defunct", etc?

### ISSUE THREAD

**Issue by Jonta** [zedeus/nitter#348]
It's a bit too vague right now

https://github.com/zedeus/nitter/wiki/Instances

**Comment by willemijns** [comment]
move only after one month of down state ?

**Comment by Jonta** [comment]
> move only after one month of down state ?

A whole month seems pretty long to me. Would put the criterium between 90% and 95% uptime per year: https://en.m.wikipedia.org/wiki/High_availability#Percentage_calculation

**Comment by zedeus** [comment]
It's vague but there's no good way to manage this page with the sheer amount of instances and the work it takes to manually check stuff. It will be replaced with an automated page eventually.
