### ISSUE TITLE
How to redirect video.twimg.com videos to Nitter?

### ISSUE THREAD

**Issue by Mennaruuk** [zedeus/nitter#350]
If there is a video URL like:
https://video.twimg.com/ext_tw_video/1362790502899347463/pu/vid/360x640/LhGfp5APT3xRb12m.mp4
How can I redirect it to Nitter?

**Comment by zedeus** [comment]
Like so:
https://nitter.cc/pic/video.twimg.com%2Fext_tw_video%2F1362790502899347463%2Fpu%2Fvid%2F360x640%2FLhGfp5APT3xRb12m.mp4

You can include the https://, doesn't matter

**Comment by Mennaruuk** [comment]
Thanks @zedeus !

**Comment by sergeevabc** [comment]
@zedeus, it means I have to encode URL first, so browser extensions like [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/) which process browser requests via regex alone will not help in this case, right?
