### ISSUE TITLE
Scrapping or is it through API ?

### ISSUE THREAD

**Issue by Feldunost** [zedeus/nitter#351]
Hello,

It's very confusing about the functionality, is it :
- a scrapper on twitter through php or something similar,
- a pool of free API available that are shared

If i create a private nitter instance, does it means it's visible to others existing nitter instances ?

Thanks for clearing thoses points.

**Comment by zedeus** [comment]
Nitter uses a combination of public and private Twitter APIs, using the credentials they use for their own web client, and guest tokens. Nitter instances do not talk to each other, and no html scraping is done. I hope that answers your questions.

**Comment by Feldunost** [comment]
So basically, i can request my own public and private API, whitout being limited if i host it in private ?
Because i am no response since a few days, which is probably due to being rate limited.

**Comment by zedeus** [comment]
The "rate limited" error messages you may see on some Nitter instances is due to a bug, they are not actually rate limited. The only rate limit that can affect a Nitter instance is IP-based, but it requires a _lot_ of requests.

**Comment by Feldunost** [comment]
I think i spotted the problem, requests for rss refresh were made every 10 minute.
Which is probably why i got blocked on nitter, changed for 2 hours refresh for approx 10 twitter requests.
