### ISSUE TITLE
Nitter instance resolver?

### ISSUE THREAD

**Issue by snakyjake1** [zedeus/nitter#354]
Is there something that can solve the problem of finding a dynamic functional nitter instance instead of using a static (temporarily defunct) instance?

I have a lot of Nitter RSS feeds, and don't like changing the Nitter instance when an instance is defuncted.

**Comment by sojusnik** [comment]
BTW, the official nitter.net instance is "rate limited" for weeks, if not months. Any plans to resolve this soon?

**Comment by willemijns** [comment]
> I have a lot of Nitter RSS feeds, and don't like changing the Nitter instance when an instance is defuncted.

I think a script can extract all OK servers from the wiki and randomly redirect to a server.

1 ) download https://github.com/zedeus/nitter/wiki/Instances

2) for every lines of this page 
   a) extract the next lines of every "<td align="left">✅</td>"
   b) extract URL from this line like"<td align="left"><a href="https://nitter.himiko.cloud" rel="nofollow">nitter.himiko.cloud</a></td>"
done

3) place all of them on a tiny DB and ramdomly send an URL via 302 HTTP redirection.

**Comment by chr15m** [comment]
@willemijns @snakyjake1 I built twiiit.com for this purpose. Source code here: https://github.com/chr15m/twiiit.com

**Comment by willemijns** [comment]
Good job !

**Comment by zedeus** [comment]
Closing since various projects exist now that do this
