### ISSUE TITLE
provide onion address in rss, not original address.

### ISSUE THREAD

**Issue by kamou** [zedeus/nitter#357]
when getting rss for users over some of the "official" onion adresses, it is possible to get the original address.

http://3nzoldnxplag42gqjs23xvghtzf6t6yzssrtytnntc6ppc7xxuoneoad.onion/ gives https://nitter.snopyta.org

http://npf37k3mtzwxreiw52ccs5ay4e6qt2fkcs2ndieurdyn2cuzzsfyfvid.onion gives http://nitter.net

this is not only annoying, but could also be considered a leak.

this is not happening with i23nv6w3juvzlw32xzoxcqzktegd4i4fu3nmnc2ewv4ggiu4ledwklad.onion tho.

**Comment by Perflyst** [comment]
That's more or less expected because the clearnet instances are just additionally exposed as onion addresses. The last one is probably an onion only nitter instance which has its onion address configured in nitter itself.

**Comment by kamou** [comment]
ok ! I understand. May I suggest to mark these instances as broken then ? I mean, when I use an onion, I expect to stay inside tor and never get out.

**Comment by kamou** [comment]
also shouldn't it be possible from the nitter to detect which address have been used thanks to the X-Forwarded-Host header ?
