### ISSUE TITLE
Large nitter feed

### ISSUE THREAD

**Issue by outofstep314** [zedeus/nitter#360]
I really enjoy the work that the contributors of nitter have provided people. I was wondering if it were possible to create a RSS feed for about 100 twitter accounts that displays no retweets and no replies? Thank you in advance for your help!

**Comment by somini** [comment]
What's wrong with subscribing to those 100 feeds on your reader?

**Comment by fuzxi** [comment]
I suspect that's the issue - subscribing to (and managing) 100 different feeds instead of one combined feed.
OP, if that is the issue, you might try something like https://github.com/cristoper/feedmixer

**Comment by OSTurtle** [comment]
I would like that too. My rss-reader wouldn't need to call the endpoints one-by-one which will take longer and rate-limiting applies to the device. Ending up with some feeds which are updated and some others aren't.

I know, it's possible to create a Twitter list with all account that I want to follow. However I don't have a Twitter account and don't want one.

**Comment by somini** [comment]
> rate-limiting applies to the device

Does it really? The nitter server caches everything, that's the whole point. Is this an actual issue, or just a theoretical concern?

**Comment by OSTurtle** [comment]
I mixed that up with invidious which I had rate-limit problems. Seems that this doesn't apply to bitter sry

**Comment by zedeus** [comment]
Duplicate of #228
