### ISSUE TITLE
Move thread to the top on account frontpage if new sub tweet is added

### ISSUE THREAD

**Issue by Symbian9** [zedeus/nitter#361]
### Expected behavior

When new sub tweet added to thread whole thread should be moved to the top (as Twitter did)

<details>
     <summary>Account frontpage (Twitter screenshot)</summary>

![pic1](https://i.imgur.com/2by1Qo8.jpg)

</details>

### Actual behavior

If new tweet added to thread only last tweet shown at the top

<details>
     <summary>Account frontpage (Nitter screenshot)</summary>

![pic2](https://i.imgur.com/dn8YcKi.jpg)

</details>

### Additional info

- Server: `nitter.fdn.fr`
- Tweet thread: https://nitter.fdn.fr/app4soft/status/1371774774079291394

**Comment by zedeus** [comment]
This requires additional requests to fetch the thread, since it isn't on the same page. Closing as wontfitx.
