### ISSUE TITLE
Using remote Redis server

### ISSUE THREAD

**Issue by Varulv1997** [zedeus/nitter#365]
Hello there !
I'm writing a tutorial about how to host Nitter on Heroku, I made a custom buildpack and I'm willing to host many instances for the public use, but I would like to know how can I use remote Redis instances especially that they have passwords. If you can help me please with this (Nitter won't start without Redis starting, I tried to disable Redis to avoid issues but no luck).
Here's my nitter.config:

```
[Server]
address = "0.0.0.0"
port = 9191
https = false  # disable to enable cookies when not using https
staticDir = "./public"
title = "A newborn Nitter"
hostname = "localhost"

[Cache]
listMinutes = 240  # how long to cache list info (not the tweets, so keep it high)
rssMinutes = 10  # how long to cache rss queries
redisHost = "REDIS_SERVER_ADDRESS"
redisPort = 10836
**redisAuth = ""** something like this ? I can't figure it out yet.
redisConnections = 20 # connection pool size
redisMaxConnections = 30
# max, new connections are opened when none are available, but if the pool size
# goes above this, they're closed when released. don't worry about this unless
# you receive tons of requests per second

[Config]
hmacKey = "secretkey" # random key for cryptographic signing of video urls
base64Media = false # use base64 encoding for proxied media urls
tokenCount = 10
# minimum amount of usable tokens. tokens are used to authorize API requests,
# but they expire after ~1 hour, and have a limit of 187 requests.
# the limit gets reset every 15 minutes, and the pool is filled up so there's
# always at least $tokenCount usable tokens. again, only increase this if
# you receive major bursts all the time

# Change default preferences here, see src/prefs_impl.nim for a complete list
[Preferences]
theme = "Nitter"
proxyVideos = true
hlsPlayback = true
infiniteScroll = true
```
Here's what I get when I start Nitter with the remote Redis server:
```
2021-03-30T12:51:17.390313+00:00 app[web.1]: Exception message: -NOAUTH Authentication required
2021-03-30T12:51:17.390314+00:00 app[web.1]: Exception type: [RedisError]
2021-03-30T12:51:17.539131+00:00 heroku[web.1]: Process exited with status 1
2021-03-30T12:51:17.611056+00:00 heroku[web.1]: State changed from starting to crashed
```

Thank you !

**Comment by Rjevski** [comment]
@zedeus could you please reopen this? I'm having the same issue.

Currently I work around it by using the following in the start script (before actually starting Nitter) which disables the Redis server's password beforehand, but obviously this isn't ideal:

    echo -e "AUTH $REDIS_PASSWORD\nSET requirepass \"\"\n" | netcat -N ${REDIS_HOST:-localhost} ${REDIS_PORT:-6379}

Furthermore would it be possible to support Redis URLs as opposed to passing hostname & port separately? Most PaaS such as Heroku or Dokku natively support `redis://` URLs and it would be great if those were supported out of the box instead of having to manually split them.

**Comment by nikhilCad** [comment]
@Varulv1997 can you please link the tutorial?

**Comment by Varulv1997** [comment]
> @zedeus could you please reopen this? I'm having the same issue.
> 
> Currently I work around it by using the following in the start script (before actually starting Nitter) which disables the Redis server's password beforehand, but obviously this isn't ideal:
> 
> ```
> echo -e "AUTH $REDIS_PASSWORD\nSET requirepass \"\"\n" | netcat -N ${REDIS_HOST:-localhost} ${REDIS_PORT:-6379}
> ```
> 
> Furthermore would it be possible to support Redis URLs as opposed to passing hostname & port separately? Most PaaS such as Heroku or Dokku natively support `redis://` URLs and it would be great if those were supported out of the box instead of having to manually split them.

What I basically did was to use a remote Redis server, I couldn't get to disable using Redis natively (new to nim) and Heroku's Redis won't work in any way. Try to use a remote instance it will connect.

**Comment by Varulv1997** [comment]
> @Varulv1997 can you please link the tutorial?

Deploying Nitter on Heroku seems to have many problems, I'm currently working on this but progressing slowly, (busy).

**Comment by Varulv1997** [comment]
> @Varulv1997 can you please link the tutorial?

I deployed it today successfully with some focus, one last step (see below) and I'll publish a tutorial, I intend to make a Heroku button too.

I can't seem to serve static files on Heroku as it throws a 403, so I'm looking for a way if I can use `nimassets` or any workaround.

**Comment by nikhilCad** [comment]
Bibliogram (an Instagram alternative that serves rss feeds) says that you should not host it on Heroku.

https://git.sr.ht/~cadence/bibliogram-docs/tree/master/docs/Installing%20%28basic%29.md (see the bottom of page)

I don't know how much of this applies to Heroku though, I just wanted to tell you @Varulv1997

**Comment by Varulv1997** [comment]
> Bibliogram (an Instagram alternative that serves rss feeds) says that you should not host it on Heroku.
> 
> https://git.sr.ht/~cadence/bibliogram-docs/tree/master/docs/Installing%20%28basic%29.md (see the bottom of page)
> 
> I don't know how much of this applies to Nitter though, I just wanted to tell you @Varulv1997

Thanks for the heads up, I never heard about Bibliogram, looking for it I don't see the similarity between the two.

Nim apps are almost non-existent on Heroku, after a long search I found out this one (working) exception (http://nim-heroku-example.herokuapp.com/) but (by looking at its source code) it's not serving any static content.

**Comment by Rjevski** [comment]
I've got Nitter successfully working on my instance on Dokku (which is very close to Heroku) and never had any issues with static files.

What's the problem you are seeing?

**Comment by nikhilCad** [comment]
@Rjevski nothing acrually, on Bibliogram page theyvsaid that if you host on Heroku and if your instance gets rate limited, the rate limit will stay there permanently as insta will identify that the requests are coming from cloud, which is "shady".

Instagram is super hard to get rss feeds from as compared to twitter, so I think Nitter won't have the same issue...

**Comment by Varulv1997** [comment]
> I've got Nitter successfully working on my instance on Dokku (which is very close to Heroku) and never had any issues with static files. What's the problem you are seeing?
> […](#)
> On 24 Apr 2021, at 19:23, Varulv ***@***.***> wrote: Bibliogram (an Instagram alternative that serves rss feeds) says that you should not host it on Heroku. https://git.sr.ht/~cadence/bibliogram-docs/tree/master/docs/Installing%20%28basic%29.md (see the bottom of page) I don't know how much of this applies to Nitter though, I just wanted to tell you @Varulv1997 Thanks for the heads up, I never heard about Bibliogram, looking for it I don't see the similarity between the two. Nim apps are almost non-existent on Heroku, after a long search I found out this one (working) exception (http://nim-heroku-example.herokuapp.com/) but (by looking at its source code) it's not serving any static content. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Jester can't serve static files on Heroku for some reason, I'm getting 403s.

**Comment by trumad** [comment]
@Varulv1997 Did you ever get this working? And is a deploy button available?
