### ISSUE TITLE
What's the state of Nitter?

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zedeus/nitter#370]
@zedeus 

Nitter hasn't received any commit for 2 months, and almost 3 months from you. 

You also haven't been active for a long while on IRC/Matrix.

Nitter.net has been (basically) shut down for months.

Nitter is also buggy and hard to maintain because of the crashes.

So I'm wondering... what's the state of Nitter? Did you gave up? Is the project dead?

**Comment by somini** [comment]
I run my own instance (in the cloud even), and it's working as intended. Doesn't seem dead to me, just "complete" for now.

Running a public instance is a losing game, it's extremely labour intensive (not to mention expensive), a legal grey area, cannot be legally pivoted to a "job" (unless it's for some spammer or SEO leech), and will attract abuse and angry comments.

If anything, the community should focus on making it as easy as possible to host this yourself. Submit it to all your distros, write guides on how to configure it.
Here's my humble contribution, I'm dogfooding it: https://aur.archlinux.org/packages/nitter-git/

I want to thank @zedeus for his work, it's very much appreciated.

**Comment by setenforce0** [comment]
I wont speak for @zedeus, but there's been some commits and nitter.net is back up and running :)
