### ISSUE TITLE
Tweets so-called "not found"

### ISSUE THREAD

**Issue by stemy2** [zedeus/nitter#374]
Hello,

Usually, i have this error when the said tweet has been deleted, but this time, i have the message on tweets that actually exists.

**Comment by somini** [comment]
I get this too sometimes, refreshing the page usually fixes it.

**Comment by stemy2** [comment]
> I get this too sometimes, refreshing the page usually fixes it.

Most of times, it doesn't.

**Comment by somini** [comment]
Are you sure your instance isn't being rate limited, or blocked outright? Twitter rate limits work in mysterious ways...

**Comment by zedeus** [comment]
No examples, closing.

**Comment by jarbus** [comment]
I'm getting this issue, but only with some accounts.

![image](https://user-images.githubusercontent.com/42819002/152569920-5546521a-f998-44dc-8d85-a7ea766c32d3.png)

**Comment by jarbus** [comment]
@zedeus I'm on [this commit](https://github.com/zedeus/nitter/commit/92ace2b). The instance is nitter.thegarbus.net.

**Comment by zedeus** [comment]
That commit is ancient, please upgrade.

**Comment by jarbus** [comment]
Yeah that did it, apologies for not thinking of it myself.

**Comment by David-Lor** [comment]
I'm having this problem with the latest version. I've been trying different Nitter instances (I tried different self-host instances using different Tor proxies, an instance without proxy and some public instances), and found that a certain 'so-called not-found tweet' can appear randomly. I guess it may have something do to with some dark magic going on on Twitter's side :face_exhaling: . I even encountered that a certain instance returned a tweet as not-found, then later on returned it as found (it may be that it was a self-hosted through-Tor instance whose proxy changed IP, idk).

In my concrete use-case I'm building a scraper that scrapes Nitter, and I was having problems with this issue while reviewing tweets for verifying if they still exist or not. I "fixed" the problem by just querying multiple instances for a certain tweet (if any instance returns it, it exists; if all instances say not found, I can guess it doesn't exist). This can still affect my other part of the scraping - searching tweets by date, but I can run different scans over time, so it can return undiscovered tweets later on.

**Comment by zedeus** [comment]
It's due to Twitter requiring authentication to view "sensitive" content in several countries now, e.g. Germany and Sweden.

**Comment by zedeus** [comment]
Bot attacks.

**Comment by Kratoklastes** [comment]
Same problem here using 1.1.49 (Firefox extension); 

- OS is latest Arch (**btw**). 
- Firefox is 114.0.1 
- no VPN; 
- AU location.

**Specifics:**
Have not got a single twitter -> nitter redirect to work. (Random instance or nitter.net)

For other data-harvesters:

- Wikipedia redirects are OK but the layout is borked; 
- '_that video site_' redirects just say "this site not configured for https"; 
- instagram - seems to work OK (who cares);
- reddit - times out (who cares). 

I don't really care about '_that video site_'  - I have aliases (y0-y9) to my fave 'content creators'  using ytfzf, and if I want some other video I have yt-dl. 

And reddit and instavag - like quora, they need to die in a fire.

**Comment by garoto** [comment]
"Meds"

**Comment by somini** [comment]
See #919
