### ISSUE TITLE
How can Nitter parse Twitter after the recent JavaScript requirement? 

### ISSUE THREAD

**Issue by ivan55634** [zedeus/nitter#379]
I'm getting
```
JavaScript is not available.
We’ve detected that JavaScript is disabled in this browser. Please enable JavaScript or switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center.

```
with all user agents I tried.

However Nitter seems to continue to work fine. How do you achieve this?

**Comment by iWantToKeepAnon** [comment]
I 2nd this.  Nitter can't be a screen scrape I'm guessing, the conf file doesn't have API keys either.  Is there a design doc?

**Comment by TheFrenchGhosty** [comment]
API.

**Comment by llacb47** [comment]
How do you think twitter works when you're logged out? You can view tweets and profiles.

**Comment by ivan55634** [comment]
With JavaScript on.

Nitter does http request with custom user agenents, and somehow it works.

**Comment by zedeus** [comment]
Nitter uses API keys and guest tokens to access various APIs. If you are interested in building something similar, take a look at the code.
