### ISSUE TITLE
User not found and RSS breakage

### ISSUE THREAD

**Issue by Salastil** [zedeus/nitter#383]
Currently it seems that a lot of instances are getting this error thrown. This is affecting the RSS feeds as well. Tweets are visible if you directly link to them, as is all of the related content like images and video, but going to the profile page doesn't work. Testing between public instances yields differing results on what profiles work and which do not. I've completely flattened my docker image and deleted all content, rolling back a version to see if it was unique to the latest commit. It seems if the profile is not cached already it will not be found.

![image](https://user-images.githubusercontent.com/46979341/117919062-597da600-b2ba-11eb-917c-d827487b0c88.png)

**Comment by valexandersaulys** [comment]
FWIW this "just fixed itself" quite suddenly for me. 

I launched a nitter instance maybe three hours ago and now its fine. Go figure.

**Comment by dimspith** [comment]
Can confirm, fixed on a personal instance too. Twitter is probably changing stuff.

**Comment by Salastil** [comment]
Confirming that it just fixed itself on my instance, I'll leave this bug report open because its clear that Twitter is in the process of changing things and likely will return to whatever caused this bug.

**Comment by Zerwin** [comment]
Did that occur again ? If not I would suggest closing the ticket instead and in case it occurs again a new Issue can be opened up.

**Comment by Salastil** [comment]
Yeah this appears to have resolved itself without any interventions. If it crops up again it will likely be a different change by Twitter.

**Comment by worldofgeese** [comment]
I encountered the same issue but much more recently (hasn't worked the last month) with users and pages showing as "user not found and "page not found". Finally took a few minutes this weekend to fix it: I needed to blow away my mounted redis directory in nitter-redis and recreate to get it to work.
