### ISSUE TITLE
Nitter fails to connect to redis

### ISSUE THREAD

**Issue by fluffyloopy** [zedeus/nitter#387]
```
Starting Nitter at 127.0.0.1
Failed to connect to Redis.
```

**Comment by fluffyloopy** [comment]
Nvm. i misplaced the ip and port.

**Comment by makerio90** [comment]
> Failed to connect to Redis.

wdym? im having the same issue. Redis is ruining fine but nitter cant connect for some reason.

**Comment by fluffyloopy** [comment]
> > Nvm. i misplaced the ip and port.
> 
> wdym? im having the same issue. Redis is ruining fine but nitter cant connect for some reason.

In nitter.conf. the first port is for where port used for opening nitter on browser. The one under redis shouldn't be changed. I messed that part up
