### ISSUE TITLE
Nitter fails to run with fetching token and certificate verify failed

### ISSUE THREAD

**Issue by fluffyloopy** [zedeus/nitter#388]
![image](https://user-images.githubusercontent.com/36381994/118696652-f47cff80-b827-11eb-8870-dfc6147f0ea8.png)

**Comment by Zerwin** [comment]
Did you set the hostname correct ? Looks to me like you didn't change it from the default (nitter.net)

**Comment by fluffyloopy** [comment]
> Did you set the hostname correct ? Looks to me like you didn't change it from the default (nitter.net)

Issues running on termux I think? Or some android thing. I forgot. Android issues
