### ISSUE TITLE
Expired SSL cert on nitter.net & cert mismatch on nitter.net

### ISSUE THREAD

**Issue by emanuelb** [zedeus/nitter#392]
Visiting: https://nitter.net/ in Firefox:
Return:

Websites prove their identity via certificates, which are valid for a set time period. The certificate for nitter.net expired on 5/28/2021.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Also visiting https://www.nitter.net/
Return:

Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for `www.nitter.net`. The certificate is only valid for `nitter.net`.
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by douardda** [comment]
isn't this the same as #377?

**Comment by emanuelb** [comment]
No, the other issue is also regarding problems in the SSL certificate but it explain incomplete chain situation, while this issue is about expired certificate & domain mismatch for www domain, which is another bugs.

**Comment by douardda** [comment]
Oh yes you are right.

In any case, it's a bit sad that nitter.net is unusable for days now...

**Comment by emanuelb** [comment]
Yes, that's why I opened this issue (which affect posted links to nitter.net etc...), meanwhile other nitter instances can be used, list at: 
https://github.com/zedeus/nitter/wiki/Instances#list-of-public-nitter-instances

**Comment by douardda** [comment]
I know, but the 2 or 3 instances I've tried are either down or slow or rate limited... so I've deployed my own instance :-)

**Comment by setenforce0** [comment]
Cert has been renewed, we don't use the www subdomain hence we don't have a cert for it :)
