### ISSUE TITLE
IBM always screws up whatever site hosting

### ISSUE THREAD

**Issue by Thespikedballofdoom** [zedeus/nitter#393]
twitter.com/IBM

502 gateway error

on non cloudflare domains it gave me this

An error has occured in one of your routes.

Detail: strutils.nim(1315) parseEnum
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
Invalid enum value: audiospace

**Comment by Thespikedballofdoom** [comment]
any tabs of the IBM profile like /with_replies makes it work

**Comment by Mennaruuk** [comment]
Yeah getting the same issue too #390

**Comment by Findus23** [comment]
The suggestion from https://github.com/zedeus/nitter/issues/390#issuecomment-852854965 fixed this for me.

```diff
diff --git a/src/types.nim b/src/types.nim
index 4c48020..7640dd4 100644
--- a/src/types.nim
+++ b/src/types.nim
@@ -125,6 +125,7 @@ type
     messageMe = "message_me"
     videoDirectMessage = "video_direct_message"
     imageDirectMessage = "image_direct_message"
+    audiospace = "audiospace"
 
   Card* = object
     kind*: CardKind

**Comment by Zerwin** [comment]
I just tested on my instance and I could call IBM no matter the tab. Does this still occur to you ?
