### ISSUE TITLE
Add our instance

### ISSUE THREAD

**Issue by TROMsite** [zedeus/nitter#398]
https://bird.trom.tf/ is our instance that we test daily. I didn't find a better way to add it to the list, so I am asking it here. I apologize if this wasn't the right place.

**Comment by Mennaruuk** [comment]
Just edit the wiki [here ](https://github.com/zedeus/nitter/wiki/Instances)and add the instance.

**Comment by TROMsite** [comment]
Gotcha. Doing it now. Cheers!
