### ISSUE TITLE
nitter docker arm64 tested on RPI4

### ISSUE THREAD

**Issue by takov751** [zedeus/nitter#399]
As i couldn't build docker version for arm64 as the nim-alpine docker only available for amd64 due dockerhub does not build for arm on its own. There are other solutions ,but until then i recreated the Dockerfile with the original nim building docker.
If someone willing to experiment with it. Tested on RPI4 ,build time around 1 hour.

New Dockerfile for arm64
```
FROM alpine as nim
EXPOSE 8080


RUN apk add --no-cache g++ curl tar xz nodejs

RUN  mkdir -p /nim;     curl -sL "https://nim-lang.org/download/nim-1.4.8.tar.xz"     |tar xJ --strip-components=1 -C /nim;     cd /nim; sh build.sh;     rm -r c_code tests;     ln -s `pwd`/bin/nim /bin/nim

RUN apk --no-cache add libsass-dev libffi-dev openssl-dev redis openssh-client git mercurial

RUN cd /nim; nim c koch; ./koch tools;    ln -s `pwd`/bin/nimble /bin/nimble;    ln -s `pwd`/bin/nimsuggest /bin/nimsuggest;    ln -s `pwd`/bin/testament /bin/testament
ENV PATH=~/.nimble/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

COPY . /src/nitter
WORKDIR /src/nitter

RUN nimble build -y -d:release --passC:"-flto" --passL:"-flto" \
    && strip -s nitter \
    && nimble scss

FROM redis:6.0.4-alpine
WORKDIR /src/
RUN apk --no-cache add pcre-dev sqlite-dev
COPY --from=nim /src/nitter/nitter /src/nitter/start.sh /src/nitter/nitter.conf ./
COPY --from=nim /src/nitter/public ./public
CMD ["./start.sh"]

```

**Comment by unixfox** [comment]
I have published a Docker image that is compatible with ARM64, intel x86/AMD64 and maybe with ARMv7 (not tested): https://quay.io/repository/unixfox/nitter

The image is based on https://github.com/goodtiding5/docker-nitter, so it is a bit different from the original nitter docker image.
And the image is automatically updated for every new commit from https://github.com/zedeus/nitter.

**Comment by zedeus** [comment]
Thank you @unixfox! I've added a link to the readme so people won't trip over the broken ARM64 image in the official Docker repo.

**Comment by Hilasr** [comment]
ح

**Comment by woj-tek** [comment]
Actually looking at [`workflows/build-docker.yml`](https://github.com/zedeus/nitter/blob/master/.github/workflows/build-docker.yml#L36) and especially `platforms` line and [workflow documentation](https://github.com/marketplace/actions/docker-setup-buildx#outputs) I wonder if adding it would be problematic. I guess it boils down to lack of nim's base image for arm64, which was requested a while back: https://github.com/moigagoo/nimage/issues/40.

Could we re-open _this_ issue to allow tracking in the future?

**Comment by unixfox** [comment]
> Actually looking at [`workflows/build-docker.yml`](https://github.com/zedeus/nitter/blob/master/.github/workflows/build-docker.yml?rgh-link-date=2022-08-18T08%3A35%3A17Z#L36) and especially `platforms` line and [workflow documentation](https://github.com/marketplace/actions/docker-setup-buildx#outputs) I wonder if adding it would be problematic.

How do you want to build a docker image for another platform other than `linux/amd64` if the base docker image for nim is not available for arm64...?

**Comment by woj-tek** [comment]
My comment was somewhat out of place - in the next sentence I already mentioned: "I guess it boils down to lack of nim's base image for arm64" so I'm aware of it. I wonder what's the main roadblock for nimlang to provide multi-arch images, considering that there are unofficial ones that (seems to) work, like the one that you use (ghcr.io/maxisoft/nim-docker-images/nim)

**Comment by unixfox** [comment]
Please use new the official ARM64 docker image: `zedeus/nitter:latest-arm64`. Mine is not going away, but this one is official and compiled on every new commit.
