### ISSUE TITLE
Create issues for each ToDo

### ISSUE THREAD

**Issue by Perflyst** [zedeus/nitter#4]
Tracking todos in a readme is not very nice because people who are interested in this project dont get notifications on updates.

**Comment by zedeus** [comment]
It's mostly because so far this has been a relatively small personal project with no announcements etc anywhere. I just setup the official instance yesterday and will be accelerating development over the next few weeks.

**Comment by talentlessguy** [comment]
There is a tab called "Projects" where you can put tasks and issues, check it out
