### ISSUE TITLE
An error has occured in one of your routes.

### ISSUE THREAD

**Issue by pluja** [zedeus/nitter#400]
I was trying to read the @Monero feed but it is failing with several instances:

https://nitter.eu/monero
https://nitter.snopyta.org/monero
https://nitter.42l.fr/monero

This is what I get:

```
An error has occured in one of your routes.

Detail: strutils.nim(1315) parseEnum
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
Invalid enum value: audiospace
```

**Comment by pluja** [comment]
This is weird because if I use it as a multi feed it works:
https://nitter.eu/monero,snowden

Monero is failing, but Snowden's feed is working good.

But there are some other users that are not working:
https://nitter.eu/jack,aanotnop

But if I just put **one** user that works and another that does not they work:
https://nitter.eu/jack,snowden
https://nitter.eu/aantonop,snowden

But putting them all together with a working user gives error:
https://nitter.eu/jack,aanotnop,monero,snowden

**Comment by SViN24** [comment]
I also found an account that also has the same issue
https://twitter.com/Ixy
^ this works

on various instances
https://nitter.dark.fail/Ixy
https://nitter.pussthecat.org/Ixy
https://tweet.lambda.dance/Ixy
https://nitter.fdn.fr/Ixy
https://nitter.nixnet.services/Ixy
https://nitter.pussthecat.org/Ixy
https://nitter.42l.fr/Ixy
these dont.
