### ISSUE TITLE
[Question] Limitations on requests

### ISSUE THREAD

**Issue by nikitapilgrim** [zedeus/nitter#403]
Let me ask, if an unofficial api is used, what restrictions does it have? Why is the instance blocked? 
If nitter was deployed on lambda, would frequent ip changes solve the problem?

**Comment by Zerwin** [comment]
About the api, taken from [here](https://github.com/zedeus/nitter/issues/351#issuecomment-789782936)

> Nitter uses a combination of public and private Twitter APIs, using the credentials they use for their own web client, and guest tokens. Nitter instances do not talk to each other, and no html scraping is done. I hope that answers your questions.

As for the instance block, I take it you mean you are getting the rate limit message (on your own server), to which I can suggest the solution from [here](https://github.com/zedeus/nitter/issues/305#issuecomment-859947242)

> for small personal instances, you can get away with setting tokenCount in nitter.conf to 1, should prevent most of those errors.

From what I read, getting blocked is not really related to IP but rather to how nitter handles the tokens.

**Comment by zedeus** [comment]
There aren't really any restrictions. Cloud IPs are generally banned by Twitter, e.g. AWS and GCP servers.
