### ISSUE TITLE
RSS tested, only 1 missing feature

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zedeus/nitter#41]
I did some more testing with the RSS and the only thing missing is the fact that the author field does not contain a link to the nitter author page

Invidious implemented it like that:
```
    <author>
      <name>Linus Tech Tips</name>
      <uri>https://invidio.us/channel/UCXuqSBlHAE6Xw-yeJA0Tunw</uri>
    </author>

```

While you use:
```
     <dc:creator>@elonmusk</dc:creator>
```

According to http://www.rssboard.org/rss-profile#namespace-elements-dublin-creator there is a limitation in ``<dc:creator>`` so you need to use ``<author\>``

Otherwise everything else is perfect and RSS appears to be feature complete

**Comment by zedeus** [comment]
Well I can do this, but it makes all RSS feed validators complain about this:
```
Undefined author element: name
Undefined author element: uri
Invalid email address
```

Like I said I don't use it myself, so I don't know if this is an issue in the wild with common RSS readers. I tried want-my-rss which displays the same thing for both

**Comment by TheFrenchGhosty** [comment]
I just compared and it looks likes you're using a different type of RSS:

Invidious uses:
``
<feed xmlns:yt="http://www.youtube.com/xml/schemas/2015" xmlns:media="http://search.yahoo.com/mrss/" xmlns="http://www.w3.org/2005/Atom" xml:lang="en-US">
``

While you use: 
``
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
``

It looks like you following the rules of ``atom`` (``xmlns:atom``) while Invidious uses something custom (``feed xmlns:yt``).

I will need to do some more research about it

**Comment by zedeus** [comment]
Both are atom but invidious includes the YouTube xml namespace which allows these lines:
```
<yt:videoId>8w3McEymcc8</yt:videoId>
<yt:channelId>UCERm5yFZ1SptUEU4wZ2vJvw</yt:channelId>
```

**Comment by zedeus** [comment]
Closing for now, please reopen if you find a better solution that doesn't break RSS compliance.
