### ISSUE TITLE
Unsupported Feature

### ISSUE THREAD

**Issue by Tombstone2K** [zedeus/nitter#411]
This link is unsupported in nitter. the page prompted me to open an issue.
https://mobile.twitter.com/i/events/1417605578764034049

Thanks :)

**Comment by DavidCatalanoit** [comment]
Forse che devo inserire per configurare cl'email github associata alla mia mail personale rendendo l'anonimato?
O è già stata effettuata correttamente dall'applicazione github?

**Comment by zedeus** [comment]
Duplicate of #234
