### ISSUE TITLE
Unraid Docker Container - Community Apps Support

### ISSUE THREAD

**Issue by Joshndroid** [zedeus/nitter#412]
I was wondering if you would consider support Unraid as a docker installation method for Nitter?
I utilise Unraid as my main server PC as many others do out there.
If you have not heard of Unraid before - https://unraid.net/
Unraid community apps - https://unraid.net/community/apps

I have taken the time to get this to work in order to free up my server PC with an unnecessary VM installation when I'm already running docker.

I have hastily written up a guide that is what my current template is for Unraid which has been working for days with my domain and SSL certs working as it should.

I was thinking of submitting a pull request with a modified readme.md however I am unsure how you would like to proceed with differing installation methods outside of your original methods. 

In any event this is what I have thus far as below;

--------------------------------------------------------------------------------------------------------------------------

**Nitter – Unraid Docker Installation**

This Unraid Docker Installation guide will mostly assume a few things;
1.	You have docker enabled within Unraid
2.	You have enable community apps within Unraid
3.	You have enable within settings the ability to utilize dockerhub for search results (see settings within apps tab)
4.	_OPTIONAL - You have a reverse proxy container and network to allow for SSL connections_

With that in mind, the installation of Nitter is rather simple once you have the above setup.

5.	Head over to apps and search for Nitter
6.	Click to begin the installation of Nitter within the search result. (Repo is zedeus/nitter)
7.	Set the toggle on the right in the template as ‘advanced view’
8.	Set your ‘Icon URL’ as https://github.com/zedeus/nitter/blob/master/public/logo.png?raw=true
9.	Set your ‘WebUI’ as http://[IP]:[PORT:8282]/ (this could be changed to whatever suits your local server port requirements - see below)
10.	Set ‘Extra Parameters’ as --restart=always
11.	_OPTIONAL - Set network type as your network that you utilize for your SSL certs (for me its proxnetwork). ELSE Set your network type as needed_
12.	Add in your static IP address that you will utilize for Nitter.

13.	Add in a ‘path’ as;

- Name – Appdata
- Container Path - /config
- Host Path - /mnt/user/appdata/nitter
- Default Value - /mnt/user/appdata/nitter
- Acccess Mode – Read/Write
- Description – Appdata location

14.	Add in a ‘variable’ as;

- Name – PUID
- Key - PUID
- Value – 99
- Default Value - 99
- Description – PUID

15.	Add in a further ‘variable’ as;

- Name – PGID
- Key – PGID
- Value – 100
- Default Value – 100
- Description – PGID

16.	Now add in a ‘port’ as;

- Name – Port
- Container Port – 8080
- Host Port – 8282 (this could be changed to whatever suits your local server port requirements)
- Default Value – 8282 (this could be changed to whatever suits your local server port requirements - as above)
- Connection Type – TCP
- Description – Container Port: 8080

17.	Uncheck the ‘Start Container After Install’ checkbox
18.	Click apply to download/install the container.

19.	Now to generate the require ‘nitter.conf;’

- Enter terminal from the webGUI of Unraid and navigate over to /mnt/user/appdata/nitter
- Use your terminal text editor of choice (vi or nano)
   For example – nano nitter.conf
- Paste in the following nitter.conf

```
[Unit]
Description=Nitter (An alternative Twitter front-end)
After=syslog.target
After=network.target

[Service]
Type=simple

# set user and group
User=nitter
Group=nitter

# configure location
WorkingDirectory=/home/nitter/nitter
ExecStart=/home/nitter/nitter/nitter

Restart=always
RestartSec=15

[Install]
WantedBy=multi-user.target
```

20.	Start your Nitter docker container
21. _OPTIONAL – Head over to your SSL cert provider container of choice and set-up as necessary to server certs to your Nitter instance for your domain_.

**Comment by setenforce0** [comment]
Thanks for the guide! I think this would work better as a wiki page rather than adding it to the readme, once the wiki page is set up we can link to it from the readme instead.

**Comment by Joshndroid** [comment]
Absolutely. That sounds like a good idea.

**Comment by Joshndroid** [comment]
I have since created a wiki entry. 
https://github.com/zedeus/nitter/wiki/Unraid-Docker-Container---Community-Apps-Installation-Guide
If anyone has an Unraid box they are using to verify, I am more than happy for that to occur prior to it being linked to the official readme

**Comment by SnakeGator** [comment]
I've had Nitter running on Unraid for a while now, I may be able to help.  I just set up a new instance following your wiki page and here are some things I noticed.

Many of the steps (8, 9, 10, 13, and 14) are taken care of already by your CA template.  Including them in an installation guide seems redundant and makes the process seem more complicated than it is.  

For step 12, I could be wrong but I thought the general advice when using a custom proxy network was to not assign IP addresses and allow the containers to communicate through dns on the custom network.

The location /config doesn't exist in the Nitter container from what I can tell.  And placing a nitter.conf in the appdata location that /config points to doesn't seem to apply to the install.  I tried adding the line to change the default twitter link redirect to /mnt/user/appdata/nitter/nitter.conf and the change was not reflected in the webui.  My install uses container path "/src/nitter.conf" with host path "/mnt/user/appdata/nitter/nitter.conf" and this seems to work.

The instructions for creating nitter.conf should probably point to https://github.com/zedeus/nitter/blob/master/nitter.conf with a note to edit fields to fit the user's environment.  Most specifically the hostname field under [Server] and the replaceTwitter field under [Preferences].  Maybe include something about the need for nitter.conf within the 'Overview' section of the CA template as well with a link to either your wiki page or directly to the conf file?

Disclaimer: Please scrutinize everything I've said.  The reason I didn't share my installation as a template is because I'm not confident that I didn't screw something up that I just haven't noticed yet.

Side note: Good job and thanks for the work on the CA templates.  Especially invidious, I hit a wall trying to get that to work, gave up, and installed it in a VM.  I might give it another shot with your template.

**Comment by Joshndroid** [comment]
> 
> 
> I've had Nitter running on Unraid for a while now, I may be able to help. I just set up a new instance following your wiki page and here are some things I noticed.
> 
> Many of the steps (8, 9, 10, 13, and 14) are taken care of already by your CA template. Including them in an installation guide seems redundant and makes the process seem more complicated than it is.
> 

Totally understand that some of these steps are superfluous. The guide was written before I gave a crack at knocking up an actual template for unraid. I left the steps there for people like me who get to some guides that miss a bunch of steps/things and then wonder why something doesn't work for them. I was preferring to keep the guide as a method of understanding as well as providing the ability for people who may not trust my template to knock the whole thing over on their own going straight from dockerhub.

> For step 12, I could be wrong but I thought the general advice when using a custom proxy network was to not assign IP addresses and allow the containers to communicate through dns on the custom network.
> 

I set this due to it being a static address I want for the nitter docker. That way I was able to capture it within my reverse proxy (which required the IP address to be noted) and have the domain 'nitter.example.com' resolve to that address. If i left that blank at times in the past it would reissue an IP address and the reverse proxy would not resolve as intended/break.

> The location /config doesn't exist in the Nitter container from what I can tell. And placing a nitter.conf in the appdata location that /config points to doesn't seem to apply to the install. I tried adding the line to change the default twitter link redirect to /mnt/user/appdata/nitter/nitter.conf and the change was not reflected in the webui. My install uses container path "/src/nitter.conf" with host path "/mnt/user/appdata/nitter/nitter.conf" and this seems to work.
> 

I have tried changing my own initial setup to /src and it breaks the container. (this seems to be pretty common when changing after the fact tho I have seen)
I also have tried to create a fresh container with it linked to /src and it does not work.
I have had others use the nitter template as I have it made and haven't had anyone mention any issue? I am happy to be incorrect I just am unsure as of right now.
I will have a further look when I have some more time.

> The instructions for creating nitter.conf should probably point to https://github.com/zedeus/nitter/blob/master/nitter.conf with a note to edit fields to fit the user's environment. Most specifically the hostname field under [Server] and the replaceTwitter field under [Preferences]. Maybe include something about the need for nitter.conf within the 'Overview' section of the CA template as well with a link to either your wiki page or directly to the conf file?
> 

I will further look at this as well :)
For the CA template stuff they like you to have a support thread which contains some further information so i don't want to fill the overview up with too much. I will refine some of those things in these areas when I have a tad more time.

> Disclaimer: Please scrutinize everything I've said. The reason I didn't share my installation as a template is because I'm not confident that I didn't screw something up that I just haven't noticed yet.
> 
> Side note: Good job and thanks for the work on the CA templates. Especially invidious, I hit a wall trying to get that to work, gave up, and installed it in a VM. I might give it another shot with your template.

Thanks for the feedback i am happy for the criticism/notes/help/whatever and just want to help others out there get on these cool privacy focused projects.

**Comment by SnakeGator** [comment]
> Totally understand that some of these steps are superfluous. The guide was written before I gave a crack at knocking up an actual template for unraid. I left the steps there for people like me who get to some guides that miss a bunch of steps/things and then wonder why something doesn't work for them. I was preferring to keep the guide as a method of understanding as well as providing the ability for people who may not trust my template to knock the whole thing over on their own going straight from dockerhub.

Ah, sorry, I misunderstood.  If this guide is for building your own from the docker hub then perhaps add to step 5 to click to get more results from docker hub.  Additionally you could add a note that says you've already prepared a template that allows you to skip to step 15.

> I set this due to it being a static address I want for the nitter docker. That way I was able to capture it within my reverse proxy (which required the IP address to be noted) and have the domain 'nitter.example.com' resolve to that address. If i left that blank at times in the past it would reissue an IP address and the reverse proxy would not resolve as intended/break.

I get that, and I use static IPs a lot as well, but when you put the container on a custom network, it gets access to DNS within that network.  This allows the reverse proxy to be configured with 'containername:port' instead of 'containerip:port'.  This is why the SWAG container can come with a bunch of nginx conf files pre-made where basic installations only need to remove '.sample' from the filename.

> I have tried changing my own initial setup to /src and it breaks the container. (this seems to be pretty common when changing after the fact tho I have seen)
> I also have tried to create a fresh container with it linked to /src and it does not work.
> I have had others use the nitter template as I have it made and haven't had anyone mention any issue? I am happy to be incorrect I just am unsure as of right now.
> I will have a further look when I have some more time.

Here I think you may have misunderstood me.  You should not map "/src" but instead map the specific file "/src/nitter.conf" to your created nitter.conf in your appdata folder.  Without a .conf file nitter will still work, I believe it just creates a default .conf file in "/src" when you start the container.  You can edit this file to change the variables but as usual since it's not mapped the changes will be overwritten when the container is updated.

> For the CA template stuff they like you to have a support thread which contains some further information so i don't want to fill the overview up with too much. I will refine some of those things in these areas when I have a tad more time.

Container requirements in the overview is just a personal preference and not all templates do it but it's much appreciated when included (i.e. Wekan mentions needing MongoDB, element-web mentions required commands before first run).

**Comment by Joshndroid** [comment]
> 
> 
> > Totally understand that some of these steps are superfluous. The guide was written before I gave a crack at knocking up an actual template for unraid. I left the steps there for people like me who get to some guides that miss a bunch of steps/things and then wonder why something doesn't work for them. I was preferring to keep the guide as a method of understanding as well as providing the ability for people who may not trust my template to knock the whole thing over on their own going straight from dockerhub.
> 
> Ah, sorry, I misunderstood. If this guide is for building your own from the docker hub then perhaps add to step 5 to click to get more results from docker hub. Additionally you could add a note that says you've already prepared a template that allows you to skip to step 15.

I have added these to the guide in the wiki page.

> 
> > I set this due to it being a static address I want for the nitter docker. That way I was able to capture it within my reverse proxy (which required the IP address to be noted) and have the domain 'nitter.example.com' resolve to that address. If i left that blank at times in the past it would reissue an IP address and the reverse proxy would not resolve as intended/break.
> 
> I get that, and I use static IPs a lot as well, but when you put the container on a custom network, it gets access to DNS within that network. This allows the reverse proxy to be configured with 'containername:port' instead of 'containerip:port'. This is why the SWAG container can come with a bunch of nginx conf files pre-made where basic installations only need to remove '.sample' from the filename.

I think this becomes a horses for courses depending on the proxy software you are using. Be it traefik, nginx, swag, nginx proxy manager. I would like to keep that section generic as possible due to the differing software out there for unraid, for me it was easier to have this as a static IP, for you or others it may not which is understandable. In any case totally happy for whatever suits, I just dont want to have to go through every potential method as it was not the actual focus for the guide. I have made the italics a bit more general in its explanation.

> 
> > I have tried changing my own initial setup to /src and it breaks the container. (this seems to be pretty common when changing after the fact tho I have seen)
> > I also have tried to create a fresh container with it linked to /src and it does not work.
> > I have had others use the nitter template as I have it made and haven't had anyone mention any issue? I am happy to be incorrect I just am unsure as of right now.
> > I will have a further look when I have some more time.
> 
> Here I think you may have misunderstood me. You should not map "/src" but instead map the specific file "/src/nitter.conf" to your created nitter.conf in your appdata folder. Without a .conf file nitter will still work, I believe it just creates a default .conf file in "/src" when you start the container. You can edit this file to change the variables but as usual since it's not mapped the changes will be overwritten when the container is updated.
> 

I have since changed this myself and will have a play before changing the template before updating this section of the template/guide.

> > For the CA template stuff they like you to have a support thread which contains some further information so i don't want to fill the overview up with too much. I will refine some of those things in these areas when I have a tad more time.
> 
> Container requirements in the overview is just a personal preference and not all templates do it but it's much appreciated when included (i.e. Wekan mentions needing MongoDB, element-web mentions required commands before first run).

I actually realised I had made a mistake here after reviewing the contents. Thanks for making me have another look through.
I have updated the template to reflect the change regarding this as well as the guide it usually take a bit for it to sync across in unraid community apps bit.

**Comment by zedeus** [comment]
Thank you for the work put into this. Since this is now a brilliant wiki page, I'm marking this issue as done. Feel free to update the wiki with any changes you might have, or continue discussion here if needed.
