### ISSUE TITLE
License precisions

### ISSUE THREAD

**Issue by erdnaxe** [zedeus/nitter#413]
As the README is stating, Nitter is under AGPL-3.0.
There is nowhere in the code where I can find a license header indicating if Nitter is under AGPL3.0-Only or AGPL3.0-Plus.

As I am packaging Nitter in Nix, I'm making the assumption that the code is AGPL3.0-Only (because AGPL3.0-Plus implies it), but I would love to have confirmation of this fact.

Also AGPL license recommends to put a header in source files, or a SPDX header (a one-liner). It is not done yet, and I believe it would be great to do this change. What is your opinion?

**Comment by zedeus** [comment]
I've added `SPDX-License-Identifier: AGPL-3.0-only` to the top of the source code files, thank you!
