### ISSUE TITLE
staticDir is not being use everywhere in the code

### ISSUE THREAD

**Issue by erdnaxe** [zedeus/nitter#414]
Nitter can load the path to the `public` static files directory from `nitter.conf` which is great.

It seems that part of Nitter code does not use the `staticDir` variable, causing Nitter to crash if `public` folder is not in current folder.

For example:

```
io.nim(849)               readFile
Error: unhandled exception: cannot open: public/md/about.md [IOError]
```
because in `src/views/about.nim` there is a direct call to `readFile("public/md/about.md")`.

How hard should be this to change? Should I try to submit a PR?

**Comment by aquarial** [comment]
pull request https://github.com/zedeus/nitter/pull/406 could fix this
