### ISSUE TITLE
Proxy for outgoing requests

### ISSUE THREAD

**Issue by Mihara** [zedeus/nitter#418]
This is a feature request, I'm afraid.

In certain situations, Nitter would be a very useful censorship circumvention tool, if I could configure it to direct all outgoing requests to Twitter through a proxy, like you can do with, for example, Miniflux. Of course, I can set up some manner of vpn-based routing solution, but proxies are just massively easier to configure or switch in case one becomes compromised.

Is there any chance of that? I don't think `httpclient` can do SOCKS, but even a simple http proxy would help.

**Comment by zedeus** [comment]
All requests to twitter are already proxied through the server

**Comment by Mihara** [comment]
Which would require installing it somewhere where twitter is accessible, wouldn't it?

Here's a use case:
* I have a LAN and a server on it that I can install nitter on.
* Twitter is blocked in my country. *(Well, it isn't quite yet, but soon.)*
* I have access to a circumvention mechanism that presents itself as a socks proxy. *(Say, shadowsocks)*
* I cannot install software on a VPS.

If I can tell nitter to go through the socks proxy for outgoing requests, I just use Twitter through it, otherwise I have to jump hoops creating routing rules that would route requests to twitter from nitter through the socks proxy.

**Comment by zedeus** [comment]
You can run nitter with some software like tsocks to do this
