### ISSUE TITLE
Docker: ARM64 builds are all broken

### ISSUE THREAD

**Issue by slikie** [zedeus/nitter#422]
while #399 suggests one of the fix, the issue is that 
in Dockerfile base is `FROM nimlang/nim:alpine as nim`,
but nimlang/nim never releases any build other than arch amd64.

~~It is honestly crazy that with 1M pulls no one realize it was broken all along~~

**Comment by setenforce0** [comment]
It's not broken, it just doesn't support ARM64 :)
For now you can use the Dockerfile suggested in #399, if there is more demand for an ARM64 build, I might play around with adding it to our CI build

**Comment by zedeus** [comment]
Nitter won't officially provide an ARM64 image for now, instead you should use the image provided by unixfox. I've added a link to this in the readme as well.
