### ISSUE TITLE
/photo/1 endpoint not supported

### ISSUE THREAD

**Issue by Booteille** [zedeus/nitter#43]
Sometimes, I see twitter links ending with "/photo/1". I don't really know what it changes to usual links.

e.g: https://twitter.com/VotrubaT/status/1172509377640767489/photo/1
Nitter version: https://nitter.net/VotrubaT/status/1172509377640767489/photo/1

Nitter does not seem to recognize this kind of links and redirect to 404 error. Could you add support for it?

**Comment by Booteille** [comment]
I don't know if it has been implemented on the dev server but if you've submitted the commit it does not seem to work.

Tested url: https://dev.nitter.net/VotrubaT/status/1172509377640767489/photo/1

**Comment by zedeus** [comment]
Forgot to restart the instances, it works now

**Comment by Booteille** [comment]
Perfect, thanks!
