### ISSUE TITLE
Disable RSS via configuration option

### ISSUE THREAD

**Issue by Salastil** [zedeus/nitter#437]
Can we get a configuration switch to disable RSS Feeds? I'm entirely willing to run a Nitter instance and keep it public but when I'm getting somewhere between 10-25k RSS requests in a single minute this endeavor becomes unfeasible, connections to redis happen so fast that when running redis-cli monitor I'm unable to distinguish individual words or patterns, it just flies by at incredible speed. The Bibliogram project which is basically Nitter for Instantgram has this feature and I think it is sorely needed. This would give the option for Nitter users to purposefully their instances for RSS requests or just Twitter proxying.

**Comment by acarasimon96** [comment]
I can probably implement this for you if you don't mind.
