### ISSUE TITLE
Increase SSL/ TLS security

### ISSUE THREAD

**Issue by beerisgood** [zedeus/nitter#44]
SSLLabs.com give you a "B" (A is best) rating because this server does not support Forward Secrecy.
https://www.ssllabs.com/ssltest/analyze.html?d=nitter.net

Mozilla's observatory even give a "F" because of missing Content Security Policy (CSP), missing HTTP Strict Transport Security (HSTS) and missing HTTP headers like X-XSS-Protection
https://observatory.mozilla.org/analyze/nitter.net

Webbkoll confirm that: https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fnitter.net

**Comment by setenforce0** [comment]
A+ on SSLLabs now, B+ on Mozilla's observatory
Please reopen if you feel this is inadequate.
