### ISSUE TITLE
Looking for hardware requirements 

### ISSUE THREAD

**Issue by TimDaub** [zedeus/nitter#442]
I saw that many people run public instances of nitter: https://github.com/zedeus/nitter/wiki/Instances
I'm also a big fan of nitter and I'm capable of running an instance myself.
Is there a section somewhere in the repo that recommends the hardware requirements? What VPS should I use and how much storage/memory/ssds etc. should it have?

**Comment by utzer** [comment]
Very little resources should be fine, I run a docker based instance, I think max 1GB ram and 2 CPU cores are fine, mine runs on an idle 4 core 4GB ram, it just sits there and is idle all the time.

**Comment by zedeus** [comment]
Nitter can run on basically anything, including an old RPi, so I'm not sure this information is particularly relevant for the readme
