### ISSUE TITLE
DCR donations

### ISSUE THREAD

**Issue by xaur** [zedeus/nitter#461]
Nitter makes my life so much better every day (or, so much less miserable, but let's stay positive). Would you mind accepting donations in DCR?

**Comment by zedeus** [comment]
Thank you, I'm glad Nitter is helpful. I've created a DCR wallet at `DsfsD8ry73Nugdrhb5gKUWoimP3SKz4EfRV`

**Comment by xaur** [comment]
@zedeus thanks, glad I can support Nitter with my fav coin now!

If I need to prove someone that the address is legit I can link this issue, but you can also add it to README to make it more visible (and slightly more protected from unintended modifications).
