### ISSUE TITLE
Instance commit hash isn't showing properly

### ISSUE THREAD

**Issue by aouwt** [zedeus/nitter#463]
Go to https://n.0x0.st/about and scroll down to `Instance info` and you'll see this:
![image](https://user-images.githubusercontent.com/74026992/141876335-dc0d4c5f-74fd-4b50-b2fb-6560cc446922.png)

This is ***probably*** a relatively simple fix and I may open a PR in some time, but me being unfamiliar with this codebase, it may take longer than anticipated.

**Comment by zedeus** [comment]
The person that runs the server just has to install git on their system

**Comment by aouwt** [comment]
Ah, sorry about that. Thanks!
