### ISSUE TITLE
HLS Streaming

### ISSUE THREAD

**Issue by Loki-L1130** [zedeus/nitter#464]
Why not enable HLS Streaming by Default ?

**Comment by zedeus** [comment]
Requires JavaScript, which is against Nitter's goals

**Comment by Loki-L1130** [comment]
Then Why not use HTML video Players ?

**Comment by jackyzy823** [comment]
Video types like `mp4` which are supported by browsers natively have already used HTML video Players See Settings' `Enable Mp4 video playback`.

Video types like `m3u8` need javascript to play because these types are not supported by browsers natively.

**Comment by zedeus** [comment]
As jacky said, the video format used by Twitter cannot be played by browsers natively, requiring the hls.js library. At the time Nitter was under development, Twitter didn't expose MP4 urls, but later on they started including them alongside the m3u8 playlists. I spent a while last year implementing support for streaming their MP4 files proxied through Nitter, and it worked in most cases, but sometimes the videos refused to play. If I find time for it I might wrap it up and put it behind an experimental setting, warning users that it doesn't always work.
