### ISSUE TITLE
"No more items" when there are items left.

### ISSUE THREAD

**Issue by GitGondola** [zedeus/nitter#468]
"No more items" when there are items left.
Have to refresh multiple times.

**Comment by jackyzy823** [comment]
Maybe this instance is rate-limited. You could try another instance.

**Comment by aidenpitt** [comment]
sometimes it helps to turn your devices wifi on and off

**Comment by zedeus** [comment]
On `nitter.net` you can now add `/json` to the end of a timeline. It only works for the main profile page, so `nitter.net/<username>/json`, not `/media/json` or search. This will give you the raw JSON returned by Twitter, along with info about the guest token used to make the request. If Twitter returns non-JSON content, it's wrapped to an error along with the status code and token info.

If you get the "No more items" error on a profile page that should have tweets, try quickly adding `/json` and see what you get. If it returns anything other than the normal data, please post it here so I can take a look. Here's what the standard output looks like:
![image](https://user-images.githubusercontent.com/9434921/146697189-c3bb2e7b-bf68-4f58-96a9-881cdcad24b9.png)

**Comment by zedeus** [comment]
It appears to be a rate limit, which is actually good news. This likely means I messed up somewhere so it can be avoided with some more careful logic. By finding out what type of request triggers it, a workaround can likely be made easily.
![image](https://user-images.githubusercontent.com/9434921/146701479-119667d7-d4cc-4de6-82df-57c2ce0452c5.png)

**Comment by zedeus** [comment]
Should be fixed by 5b185c7, please reopen if the issue comes back.

**Comment by zedeus** [comment]
@haarp yes, you can check which commit is live by going to nitter.net/about (works in any instance), and clicking the link. Since my last message here Twitter added some weird rate limits to the endpoints used to fetch timelines and media. There's a replacement for it here that fixes this issue: https://github.com/zedeus/nitter/pull/812
