### ISSUE TITLE
Problem with the number of requests from GoogleBot

### ISSUE THREAD

**Issue by D3m1tx** [zedeus/nitter#470]
Hi,

I have a problem with google bots as they have multiplied x4 the cost of my nitter instances in Google Cloud (from 0.8$/day to 4$/day). Half of the requests come from googlebot.

Does anyone know how to add the robots.txt file easily starting from the precompiled docker image?
I have tried to pull the image, add the robots.txt to the container (docker cp...) and create a new image containing robots.txt, but when I deploy it to Google Cloud I get an error
`./start.sh: line 4: ./nitter: not found`
Both images seem to be the same size. Does anyone know how to fix this, or does anyone have precompiled an image that prevents crawling?

Thanks,

**Comment by jackyzy823** [comment]
Create your `robots.txt` and then do as follow:

` docker run  -p 8080:8080 -v `pwd`/nitter.conf:/src/nitter.conf -v `pwd`/robots.txt:/src/public/robots.txt zedeus/nitter`

**Comment by D3m1tx** [comment]
Hi jackyzy823,

Thank you for your reply. Although what you comment works when you run the container locally, when trying to create an image from that container, the volumes are not copied, so the robots.txt information is lost.

Google Cloud Run does not allow using docker volumes and therefore I have to generate a docker image with the robots.txt already included.

I will keep trying with the copy and backup volumes commands.

Thanks.

**Comment by jackyzy823** [comment]
Dockerfile like below and robots.txt in the same folder
```Dockerfile
FROM zedeus/nitter
MAINTAINER yourself
COPY robots.txt /src/public
```
do 
`docker build . -t <IMAGE_TAG>`

**Comment by D3m1tx** [comment]
It was easier than I thought.

`docker run -p 8080:8080`
`docker cp LOCAL_PATH_TO_ROBOTS_FILE CONTAINER_NAME:/src/public/robots.txt`
`docker commit CONTAINER_NAME zedeus/nitter`
`docker push zedeus/nitter`
You must replace zedeus/nitter for your repository

I had the problem because when using the command
docker run -p 8080:8080 -v `pwd`/nitter.conf:/src/nitter.conf -v `pwd`/robots.txt:/src/public/robots.txt zedeus/nitter
and then try to copy the file with the cp command, I got an error because it was already in use.

Sorry for the inconvenience and thank your for your reply.

**Comment by D3m1tx** [comment]
> Dockerfile like below and robots.txt in the same folder
> 
> ```dockerfile
> FROM zedeus/nitter
> MAINTAINER yourself
> COPY robots.txt /src/public
> ```
> 
> do `docker build . -t <IMAGE_TAG>`

Thanks jackyzy823, i solved it by copying the file and generating a new image in my repository.
