### ISSUE TITLE
Put rel=canonical links in page headers to redirect search engine attention

### ISSUE THREAD

**Issue by gThorondorsen** [zedeus/nitter#472]
Continuing the conversation in #431 brought up one point that I think could be actioned: indexing of Nitter instances by search engines hurts SEO of the original tweet. Conversely, some (most?) instance administrators could do without the attention that brings to their domain. (I know of instances that closed because they did not have the capacity to deal with the stream of #431-like complaints they got.)

The `rel="canonical"` link type has been designed by search engines implementers[[RFC6596](https://datatracker.ietf.org/doc/html/rfc6596)] for exactly such a purpose: telling crawlers that the page is a duplicate of another resource. It does work cross-domain, though I do not know how well that case is supported by search engines. Of the other site-specific proxying services that I know of, only [Invidious](https://github.com/iv-org/invidious) does something similar: it uses a `rel="alternate"` link [as a hint to `youtube-dl`](https://github.com/iv-org/invidious/pull/1730) (and forks). That may also work for search engines but feels like a weaker hint that might not have the desired effect. Someone with more SEO experience should chime in.

The `robots.txt` file should workaround this issue (and some more), but this currently relies on every instance administrator getting it right and not assuming Nitter comes bundled with it. Also, it is my understanding that such a solution *removes* SEO weight altogether when someone links to a Nitter instance while the `rel="canonical"` one *transfers* it to the twitter.com address.

Regarding the implementation, there are two points to watch out for.

- There are a few page that could be excluded from `rel="canonical"`, though `rel="alternate"` could apply: `/` and `/about` are obvious candidates, `/settings` feels like a subtle case worth discussing in details, and I have no idea about `/search`.

- What flexibility should instance administrators have? And what should be the default? I've currently settled weakly on `rel="canonical"` being the default, with instances being able to change (downgrade?) it to `rel="alternate"` or nothing if they feel confident in their `robots.txt` settings and/or want the search engine attention.

I am willing to do implementation work if needed, but I'll first wait for approval on the general direction and feedback on the pending design questions before seriously diving into it.

**Comment by arrowgent** [comment]
the point of privacy focused nitter is to remove tracking
rel="x" is url tracking.

**Comment by gThorondorsen** [comment]
> rel="x" is url tracking.

Is it? I am thinking about `<link rel="canonical|alternate" href="…" />` HTML elements in `<head>` or `Link: <…>; rel=canonical|alternate` HTTP headers, nothing on `<a>` links whatsoever. No resource I found suggest that browsers do anything with these, only search engines analysing their crawlers' results. But if there is evidence that some do, I am open to withdrawing the proposal.

**Comment by zedeus** [comment]
I approve, I'd be happy to merge an implementation of this
