### ISSUE TITLE
Use nitter without redis?

### ISSUE THREAD

**Issue by DUOLabs333** [zedeus/nitter#474]
Is there a way to disable the need for redis and all services that depend on it?

**Comment by zedeus** [comment]
No, Nitter becomes much slower without it and there's no option to disable it. What's you use case?

**Comment by DUOLabs333** [comment]
I just try to avoid running another server if possible. I'm self-hosting
for my own use.

**Comment by DUOLabs333** [comment]
Ok, I've set up redis, but for some reason, images are very slow to load (~10 seconds). This is probably a configuration problem on my end, as public instances can load much faster.
