### ISSUE TITLE
temporarily banned user profile's cache problem

### ISSUE THREAD

**Issue by jackyzy823** [zedeus/nitter#480]
When a user's profile if fetched when he/she is temporarily banned/suspended , nitter will not refresh profile when user returns to normal.

We should improve nitter's profile cache mechanism ie  if cached profile is in banned status, do a check again.

**Comment by zedeus** [comment]
Suspended profiles are no longer stored permanently in the ID tables, but a shell profile containing the username and suspended state is cached as a normal profile for the usual 1 hour duration.
