### ISSUE TITLE
Breaking change: Redis Issues when upgrading Nitter on Docker

### ISSUE THREAD

**Issue by FireMasterK** [zedeus/nitter#488]
Preferably, you should now use the docker-compose file at https://github.com/zedeus/nitter/blob/master/docker-compose.yml (and change `redisHost` to `redis` in nitter.conf)

Alternatively, follow https://github.com/zedeus/nitter#docker

This mostly affects people using Watchtower to automatically update their instances.

**Comment by toskou** [comment]
Fix it thanks !

**Comment by nixxquality** [comment]
It also affects anyone trying to update nitter to a version that works, only to have the rug pulled from under them when the previously self-contained image isn't self-contained anymore.

I already wasted enough time trying to get networking between external redis and the nitter image to a working state and it's failed.

Can I have a self-contained image back now?

**Comment by FireMasterK** [comment]
> I already wasted enough time trying to get networking between external redis and the nitter image to a working state and it's failed.

You should've used docker-compose, it just one command once you've created a config file.

> Can I have a self-contained image back now?

I don't re-adding the monolithic image is a good idea since it can cause a race condition when starting redis. (When nitter finishes starting before redis)

**Comment by nixxquality** [comment]
I don't use docker-compose because I use podman.
