### ISSUE TITLE
Setup CI and Coverage

### ISSUE THREAD

**Issue by talentlessguy** [zedeus/nitter#50]
To ensure that the project is well tested without reading tests, repo needs to have CI and Coverage installed.

[How to setup Travis for Nim](https://github.com/nim-lang/Nim/wiki/BuildServices#building-nim-projects-on-travis-ci)

[Nim coverage tool](https://github.com/yglukhov/coverage)

**Comment by zedeus** [comment]
CI has now been setup. Setting up coverage takes too much effort and imo is not worth it for this project.

**Comment by talentlessguy** [comment]
@zedeus ok
