### ISSUE TITLE
RSS *help

### ISSUE THREAD

**Issue by tjallemaal** [zedeus/nitter#505]
Dear all,

I'm sorry to bother, I'm a noob and I don't know how to extract the "right" line when I click the RSS symbol on nitter.
what exactly do I have to take from there?

Sry again.

Kind Regards, 

Halem

**Comment by LainLayer** [comment]
I'm not sure what you're asking specifically.
What are you trying to do?

If it's about how to use the RSS, simply copy the link, for example: https://nitter.net/elonmusk/rss
and place it in your RSS software of choice.

**Comment by tjallemaal** [comment]
Thank you! so its /rss

I clicked on the RSS button and just found a sea of gibberish there.
