### ISSUE TITLE
[Site.webmanfiest] Consider maybe removing start_url? Or is it possible to have this set in the .config?

### ISSUE THREAD

**Issue by Joshndroid** [zedeus/nitter#506]
I noticed a while back, very early on that I could create a home screen app based on the pages I had loaded (ie the full URL).

I found this super useful for having a different 'profile' of pages loaded that I could go straight to kind of like a easy homescreen bookmark.

I have noticed recently  that I had been unable to do that, in that no matter what page I had loaded the 'add to home screen' would always provide the root URL.

On some checking it seems that the site.webmanifest has the start_url string set as "/" which was causing the issues for me

I see that this was added with commit df41405251d7af878587846c398c15b96e2bb068

I was able to remove that line from within my docker and on reloading was able to add the whole URL as intended to the homescreen.

I am not sure if this is what you intended, or if its required from a web standards point of view or due to that fix you applied for lighthouse but it would seem to me that if your wanting to add something to your home screen it would be the url your trying to add, not necessarily the root URL.

In that case would you consider removing it?
Or is there a way that would could have that set within our .config so it can suit all parties?

**Comment by zedeus** [comment]
Thank you for the report, didn't realize it would break anything. I don't use it myself and I'm not too familiar with these standards, just tried to make Lighthouse stop complaining
