### ISSUE TITLE
RSS feed: Retweets & Quotes don't appear with new date

### ISSUE THREAD

**Issue by gloschtla** [zedeus/nitter#507]
Try retweeting and quoting two original tweets. The first tweet is about one hour old, and the second tweet is several weeks old. The older tweet won't appear in the RSS feed of the retweeting account, because it would not appear on top in the RSS feed. It seems that Retweets and Quotes don't get new proper time stamps, in order to appear as latest content in the RSS feeds.

**Comment by zedeus** [comment]
Please show an example

**Comment by zedeus** [comment]
Likely due to the RSS cache, closing.
