### ISSUE TITLE
RSS feed: different nitter instances not with same RSS feed entries

### ISSUE THREAD

**Issue by gloschtla** [zedeus/nitter#508]
I compared Nitter.net, Nitter.ca, Nitter.Snopyta.org, each time the RSS feed for the same account: None of the three RSS feeds is identical to another. The latest twitter entries on the considered account are all Retweets or Quotes of older original tweets. 

And none of the three is up-to-date: #507 

Is there any Nitter instance with working RSS feed?

**Comment by zedeus** [comment]
How out of date are they? The default RSS cache time is 15 minutes

**Comment by zedeus** [comment]
No examples and there's likely nothing Nitter can do about it anyway.
