### ISSUE TITLE
Support custom timezones

### ISSUE THREAD

**Issue by hilmiazizi** [zedeus/nitter#509]
Hello, im wondering if i can get version that have old time format not like current format that only show hours & minute

**Comment by zedeus** [comment]
Would it be enough to add seconds?

**Comment by acarasimon96** [comment]
I think the best way to approach this is to allow the user to choose between different date/time formats in settings. For obvious reasons, the old format should be included as one of the choices.

**Comment by hilmiazizi** [comment]
Hi there, i want to follow up this issue, do you know specific commit that still have old timeformat? not the current UTC format

**Comment by hilmiazizi** [comment]
found it!
