### ISSUE TITLE
Invalid enum value: newsletter_issue

### ISSUE THREAD

**Issue by hilmiazizi** [zedeus/nitter#517]
Hello, i've been running nitter from someone fork who still have old time format but i found this error. been trying to run it on different VPS but still having same issue. do you have any idea how to fix this?

ERROR enumutils.nim(66)        parseEnum
asyncfutures.nim(389)    read
asyncfutures.nim(389)    read
asyncfutures.nim(389)    read
asyncfutures.nim(389)    read
asyncfutures.nim(389)    read
Invalid enum value: newsletter_issue

**Comment by LainLayer** [comment]
Hi.

If this issue does not happen in the original nitter, please open an issue on the repository of your fork instead.
If it does happen with original nitter, please build and run it in debug mode (without `-d:release -d:danger`) and post the full stack trace here.

Would also appreciate if you could provide the tweet that causes this if you know which one.

**Comment by hilmiazizi** [comment]
fixed using commit 25191f7, thanks!
