### ISSUE TITLE
I need help deploying nitter in Google Cloud Run

### ISSUE THREAD

**Issue by D3m1tx** [zedeus/nitter#522]
Hi,

I am struggling to deploy nitter on Google Cloud Run. When redis was distributed with the Docker image I had no problems, but now I am not able to deploy it (because redis is not found).

Locally with docker-compose everything works fine, but I need to create an image containing both redis and nitter as it was before. 

Does anyone know the best way to do this or an alternative to get it working on Google Cloud Run?

Thank you.

**Comment by LainLayer** [comment]
Hello, can you please read https://github.com/zedeus/nitter/issues/510 and see if this is your problem?

**Comment by D3m1tx** [comment]
Hi @LainLayer,

Thank you for your response. It is not the same problem, in my case I do manage to create the container with docker-compose and it works correctly on my local machine by replacing redisHost = "redis". 
My problem is rather the impossibility to use docker-compose on Google Cloud Run. I have tried to split it into 2 services within Cloud Run, one for redis and one for nitter by changing the redisHost in the configuration, but I can't get it to work.
So I wanted to know if there is a way to put both services inside the same docker image to deploy them at the same time in Cloud Run, maybe modifying Dockerfile?
I will keep investigating, but I would appreciate any help or advice.

**Comment by zedeus** [comment]
Use the old Dockerfile: https://github.com/zedeus/nitter/blob/739eb12bed4921eba52f8dfba1faffbfd23ef8f8/Dockerfile

**Comment by D3m1tx** [comment]
Hi @zedeus ,

Thank you for your response.
I had to modify something else besides Dockerfile, but at least I managed to deploy it to Google Cloud Run and it works at least intermittently.

Thank you.
