### ISSUE TITLE
Some status links don't redirect

### ISSUE THREAD

**Issue by TotalCaesar659** [zedeus/nitter#53]
Hello, I've found that some status links (e.g. https://twitter.com/elonmusk/statuses/1158968745227780096) don't redirect to nitter.net correctly (https://nitter.net/elonmusk/statuses/1158968745227780096), but changed links (https://twitter.com/elonmusk/status/1158968745227780096) do (https://nitter.net/elonmusk/status/1158968745227780096).
P.S. I don't know is this a problem of Nitter by itself or just nitter.net website, so sorry if it's not a place for this thread.

**Comment by zedeus** [comment]
`/statuses/` seems to be an alias, I'll add a route to redirect it, thank you
