### ISSUE TITLE
Hashtags written with / without spaces broken

### ISSUE THREAD

**Issue by Symbian9** [zedeus/nitter#530]
Nitter does not support hashtags separated with only `/` (without extra spaces) — on Twitter it supported instead:

Example:
- `#Hashtag1/#Hashtag2`
- `#Hashtag1/#Hashtag2/#Hashtag3`

See profile about text of:

- https://nitter.net/FreeCADNews
- https://nitter.net/SolveSpace

**Comment by shirenn** [comment]
Also,

Non ASCII characters seem not to be supported in hashtags.

Example:
  * `#hâshtag`

See profile about text of:
  * https://nitter.net/reesmarc

(I am writing about it here as issues seem connected)
