### ISSUE TITLE
Add an rss-feed which does not show the Retweets

### ISSUE THREAD

**Issue by caminsha** [zedeus/nitter#533]
In the support chat there was a discussion about creating an rss-feed without the retweets from an account.

As far as I understand the sourcecode there's no feedoption for this. (Had a look at this: https://github.com/zedeus/nitter/blob/master/src/routes/rss.nim )

So as a reminder for that idea I created this issue (and might it's pretty easy to set up.

At the moment I see two possibilities for this

1. add a new route (i.e `/@name/rss/no_rt`)
2. add a new tab for the user (i.e. `/@name/@tab/rss` where `tab` could be `no_rt`)

**Comment by zedeus** [comment]
Use search to exclude retweets then click RSS.

**Comment by caminsha** [comment]
Thanks, didn't know about this option. Sounds good.
