### ISSUE TITLE
nitter.net rss response = 502 Bad Gateway 

### ISSUE THREAD

**Issue by Emporea** [zedeus/nitter#534]
Since 2022-01-29T00:00:00 utc I get a 502 Bad Gateway response when fetching rss feeds. 
I can download it manually and my ip does not seem restricted or anything.

Is it because of maintenance? The search is also not currently working.

I am using nitter.net.
Server error: `GET https://nitter.net/.../rss` resulted in a `502 Bad Gateway`

**Comment by zedeus** [comment]
Server ran out of space, should work now

**Comment by Emporea** [comment]
Thanks for that quick response! Yes its working again.
