### ISSUE TITLE
User search returns no results

### ISSUE THREAD

**Issue by Mennaruuk** [zedeus/nitter#542]
Hello zedeus, how are you? I hope you’re doing well.

Recently, I noticed that Nitter’s user search has stopped working. Searches for any user bring up nothing. Do you know what is causing this problem?
![FEDD6EC2-F32D-410E-9615-F1E61F390BD9](https://user-images.githubusercontent.com/52135169/153113323-91791336-ad58-44c3-9951-62e36001e3cf.jpeg)

Thank you.

**Comment by moom0o** [comment]
Happening for me too, probably just a simple fix that needs to be written since twitter decided to change something again, this happened before too and was fixed in a day or two.

**Comment by zedeus** [comment]
Similar change was already made here, won't be able to do it until I'm home in an hour or so.
https://github.com/zedeus/nitter/commit/adfd31c530cdfae052333123cd5999b333043bd3

@jackyzy823 if you can throw up a PR real quick I'll merge it right away!

**Comment by zedeus** [comment]
Fixed
