### ISSUE TITLE
Tweet ordering reversed for 'tweet threads'

### ISSUE THREAD

**Issue by FreeTrade** [zedeus/nitter#545]
Nitter shows tweets in the wrong order when tweets have the same timestamp -

consider
https://nitter.net/ericrweinstein
vs
https://twitter.com/ericrweinstein

I think if the user makes multiple tweets with the same time stamp, nitter should probably reverse the order of them to display in the correct order.

**Comment by zedeus** [comment]
Huh?
![image](https://user-images.githubusercontent.com/9434921/154823457-352b2aeb-b6ea-47d0-9560-d73969aff2b2.png)
![image](https://user-images.githubusercontent.com/9434921/154823458-002f8546-7896-49ec-a945-fb43e45aa710.png)

Looks the same to me.

**Comment by FreeTrade** [comment]
> Looks the same to me.

Hmm, possibly only affects the rss feed -

https://nitter.net/ericrweinstein/rss
