### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by jackyzy823** [zedeus/nitter#546]
latest dotenv (2.0+) conflict with current karax version used by nitter (this version of karax allow any version of dotenv) 

so either 
-  pin dotenv to  dotenv#08b82a6 or dotenv@1.1.1 (which is   before https://github.com/euantorano/dotenv.nim/commit/d80c0f07c51a74ecd570a227c4d733525c4debfb ) 
- update karax to latest

**Comment by zedeus** [comment]
Fixed, thanks!
