### ISSUE TITLE
Standard theme should by light not dark

### ISSUE THREAD

**Issue by mike29107** [zedeus/nitter#554]
The standard theme of Nitter (without configuring options) should be light not dark; dark schemes are great but nerdy and put off many normie users who are seeking an alternative that looks like Twitter, not like a hacker website.

**Comment by zedeus** [comment]
Nitter's dark theme is part of its personality. With a light theme as the default people might confused it for Twitter, which would likely cause a bunch of issues, more so than the ones we already get. I appreciate the suggestion, but it won't be the global default, and instance operators are free to change their config to make it default.

**Comment by mike29107** [comment]
@zedeus @LainLayer Then I'm sorry to tell you that Nitter is doomed to fail. A classic amateur mistake by Internet fringe nerds.
