### ISSUE TITLE
Reverse thread ordering on timeline?

### ISSUE THREAD

**Issue by Shadlock0133** [zedeus/nitter#556]
Currently, timelines are in reverse chronological order (newest first), but threads are chronologically (oldest first). It means reading long threads can be annoying. For example: if someone posts thread "a-b-d-e" with tweet c in the middle, it will show up as:
```
d
e
c
a
b
```
By reversing thread ordering (adding `.reversed`) here: https://github.com/zedeus/nitter/blob/6695784050605c77a301c0a66764fa9a9580a2f5/src/views/timeline.nim#L44 example would look like this:
```
e
d
c
b
a
```

**Comment by zedeus** [comment]
This is intended, Twitter does it the same way.

**Comment by Shadlock0133** [comment]
I often read https://twitter.com/Foone/ who writes very long thread. On twitter's timeline, they show up as individual tweets in reverse chronological order.

I've done the change in my fork, so it's not much of an issue for me, but it might be worth to add it as an option in preferences.

**Comment by zedeus** [comment]
They show up individually if you're not logged in, but threaded when you are:
![image](https://user-images.githubusercontent.com/9434921/154824273-a4970f0a-5748-4223-a7d7-7859c5f4fc8c.png)

I might consider it, but I think it would be too confusing and doubt many would use it.
