### ISSUE TITLE
Profile sidebar no longer sticks to top

### ISSUE THREAD

**Issue by Mennaruuk** [zedeus/nitter#573]
One thing I like about Nitter is how the profile sidebar floats as I scroll. It's a small but nice detail, and I always get to know whose profile I'm looking at. I noticed today this feature no longer works despite its box being checked in the settings.

**Comment by zedeus** [comment]
It works, but gets disabled if the window is too small. This is mainly to prevent the photo gallery from being hidden at the bottom of the screen.

**Comment by Mennaruuk** [comment]
I understand. It's strange, though. My window is fully maximized. I was able to reproduce on Chrome and Firefox. Also [September 2021 instances](https://nitter.ca/elonmusk) experience the same problem, but I didn't remember noticing the sidebar disappearing till today. I think I need to get some sleep.

**Comment by zedeus** [comment]
What is your screen resolution?

**Comment by Mennaruuk** [comment]
1366x768

**Comment by zedeus** [comment]
Can you see the entire sidebar on screen?
![image](https://user-images.githubusercontent.com/9434921/158037831-b14bb7fa-6343-4040-81cd-a0fcbef67fbc.png)

**Comment by Mennaruuk** [comment]
https://user-images.githubusercontent.com/52135169/158045377-996b6a44-44e3-417b-af36-42eb4dfde1f3.mp4



Don't worry about it, at this point I'm nitpicking, for all intents and purposes Nitter is perfect.

**Comment by zedeus** [comment]
You simply wouldn't be able to see the full gallery if this didn't happen, so while I understand it's a little strange it's just so the layout doesn't break on smaller screens.
![image](https://user-images.githubusercontent.com/9434921/158066570-dbf3c5bc-418c-4aeb-965e-65b44e0fe14b.png)
