### ISSUE TITLE
Feature request: Advanced search rather than to having to enter the search bar manuelly

### ISSUE THREAD

**Issue by GhbSmwc** [zedeus/nitter#575]
This feature:
![image](https://user-images.githubusercontent.com/13095760/158292062-950f4377-8430-48e1-a25a-a07b2d38ee1f.png)
Not sure if this is already fully implemented becauseI tried to search using manual methods (like entering ``(from:Twitter)`` into the search bar directly) and that worked.

**Comment by zedeus** [comment]
These operations are very simple to do unlike all the things included in Nitter's advanced search. I've previously rejected similar search menu changes, so this won't happen either sorry. If you want to do a search with tweets from Twitter, you can go here: https://nitter.net/Twitter/search
