### ISSUE TITLE
Media tweets not showing for this particular user

### ISSUE THREAD

**Issue by GhbSmwc** [zedeus/nitter#577]
Caution, some tweets may contain NSFW content. This:
https://nitter.net/_PatientZ_/media

results in:
![image](https://user-images.githubusercontent.com/13095760/158899701-7dcd0a2e-4828-480a-9a6f-30476a342ded.png)

vs.
https://twitter.com/_PatientZ_/media

Not sure why this occurs

**Comment by zedeus** [comment]
nitter.net is hosted in Germany where "sensitive" content is blocked for unauthenticated users, so there's nothing I can do about it. Use an instance hosted elsewhere.
