### ISSUE TITLE
FR: convert full Twitter URL to correct nitter link by removing "https://twitter.com/" 

### ISSUE THREAD

**Issue by JDJoe** [zedeus/nitter#578]
For example: 
`https://nitter.net/https://twitter.com/blah... `
is automatically converted to 
`https://nitter.net/blah... `

I am reading an article about blah. I have another web browser window open with nitter.net. 
Article has a link to a twitter post. 
I copy the link and paste it as is after the nitte.net and hit enter. 
Thanks.

**Comment by zedeus** [comment]
No

**Comment by JDJoe** [comment]
Why not?

**Comment by zedeus** [comment]
You might as well just change the url to nitter.net instead, this is a very uncommon and unnecessary use case. Alternatively you can use a browser extension or bookmarklet.
