### ISSUE TITLE
exonip domain change

### ISSUE THREAD

**Issue by 3ship** [zedeus/nitter#583]
Earlier I saw this message displayed on nitter.exonip.de:

>All privacy services that were previously accessible as subdomains of exonip.**com** (nitter.exonip.com, piped.exonip.com, etc.) are now accessible as subdomains of the new domain privacy.com.com (nitter.privacy.com.com, piped.privacy.com.com, etc.).

There was also a German text saying that exonip.**de** services are now available under privacy.com.de sub-domains (nitter.privacy.com.de, piped.privacy.com.de, etc.)

**Comment by zedeus** [comment]
Fixed wiki
