### ISSUE TITLE
New Public Instance - https://nitter.lunar.icu/

### ISSUE THREAD

**Issue by MaximilianGT500** [zedeus/nitter#585]
Hello, can you add my Instance to the Public List: https://nitter.lunar.icu/ ?

Thanks,
Maximilian

**Comment by zedeus** [comment]
Your instance can't show profile banners, you may want to fix that.

Example:
https://nitter.lunar.icu/pic/https%3A%2F%2Fpbs.twimg.com%2Fprofile_banners%2F34743251%2F1596331248%2F1500x500
https://nitter.lunar.icu/pic/https%3A%2F%2Fpbs.twimg.com%2Fprofile_banners%2F44196397%2F1576183471%2F1500x500

Normal pictures work:
https://nitter.lunar.icu/pic/media%2FFOKKuztVIAAOaCt.jpg%3Fname%3Dorig
https://nitter.lunar.icu/pic/media%2FFKriixDVcAsrZpM.jpg%3Fname%3Dorig

**Comment by MaximilianGT500** [comment]
How can i fix it?

**Comment by zedeus** [comment]
I don't know, depends on your web server

**Comment by MaximilianGT500** [comment]
I use docker to deploy it.

**Comment by zedeus** [comment]
By web server I mean reverse proxy (nginx, aphache, caddy, etc.), you probably have a bad configuration. You can try setting `base64Media` to `true` in nitter.conf. If that fixes it, it's a problem with your reverse proxy.

**Comment by MaximilianGT500** [comment]
Okay, i test it at home. Thanks

**Comment by MaximilianGT500** [comment]
Hello, the problem is the URL: https://nitter.lunar.icu/pic/https%3A%2F%2Fpbs.twimg.com%2Fprofile_banners%2F1092882173915467781%2F1625847224%2F1500x500

Without the https%3A%2F%2F it works:
https://nitter.lunar.icu/pic/pbs.twimg.com%2Fprofile_banners%2F1092882173915467781%2F1625847224%2F1500x500

**Comment by MaximilianGT500** [comment]
nitter          | ERROR base64.nim(233)          decode
nitter          | asyncfutures.nim(389)    read
nitter          | asyncfutures.nim(389)    read
nitter          | Invalid base64 format character `%` (ord 37) at location 103.

**Comment by zedeus** [comment]
base64Url changes how the url is generated, you need to go to a profile with it enabled to see if it works, opening those links after enabling it isn't supposed to work.

**Comment by MaximilianGT500** [comment]
If I try to open the picture without proxy it works: https://screenshot.m16k.de/5kfXQv8hQAxsayYF2FMmazs1H4zZgtjt.png but if I try it with proxy it doesn't work, I use as proxy the one from AAPanel (OpenLightSpeed) and as "man in the middle" Cloudflare that always worked only not with nitter

**Comment by MaximilianGT500** [comment]
With base64Media Cloudflare gives me an 502 Error: https://screenshot.m16k.de/OKKcbpkm1yvGLXS5Pxuyi8W81JmoCPOW.png

**Comment by zedeus** [comment]
Can you post the error log from Nitter?

**Comment by MaximilianGT500** [comment]
https://screenshot.m16k.de/ZuwYOXTeA9pEblZtVTeMrN22kCacGfxk.png

**Comment by zedeus** [comment]
That's from a previous error, can you show the newest logs?

**Comment by MaximilianGT500** [comment]
Thats the newest one.

**Comment by MaximilianGT500** [comment]
I try it with an other Proxy: Nginx Prox Manager

**Comment by MaximilianGT500** [comment]
Okay, it works.

**Comment by zedeus** [comment]
All the IP addresses point to the US, is it behind an American proxy?

**Comment by zedeus** [comment]
Oh, I see now it's behind Cloudflare

**Comment by MaximilianGT500** [comment]
Yes
