### ISSUE TITLE
Is there a way to exclude user name and handle when searching?

### ISSUE THREAD

**Issue by learnbyexample** [zedeus/nitter#589]
For example, searching for `regex` gives results even if the match is found in user name or the handle. I want to search only the tweet content. The current "Exclude" options don't seem to have a way to achieve this.

**Comment by zedeus** [comment]
Not really, you can exclude usernames doing either just `-username` or `-from:username` but in that case I believe the username must match perfectly.

**Comment by learnbyexample** [comment]
Thanks, that helps since it allows multiple users to be ignored. I can maintain a list of frequent tweeters on particular topics.
