### ISSUE TITLE
[feature request] Default search: tweets instead of users

### ISSUE THREAD

**Issue by marcel263** [zedeus/nitter#590]
The default behavior on nitter.net instance is to search for users. user needs to tap the Tweets tab manually. 

At least provide a setting to search for tweets first. What would be reasons, e.g. bandwith or api cost, to stop imementing this?

To  all who make nitter possible thank you

**Comment by zedeus** [comment]
Clicking on the search icon top left opens tweets by default, so it's already default? The homepage is a separate issue, where looking for users makes more sense than looking for tweets.

**Comment by marcel263** [comment]
> Clicking on the search icon top left opens tweets by default, so it's already default? The homepage is a separate issue, where looking for users makes more sense than looking for tweets.

You close the issue while you did not consider the point as to let users decide the default option.

When going to nitter.net, user search is the default option that is presented. Moreover, when one searches for a user in Tweet view, matching usernames's tweets are prioritized. 

So kindly reopen the issue because user preference, as simple as this at that, needs to be included in the development

**Comment by zedeus** [comment]
There won't be an option to change the default search for the homepage, it takes 1 click to open the tweet search page. I'd much rather create a far better homepage, but it takes a lot of work and I don't have much time these days. If you _really_ want to see a preference to change the homepage search, you're welcome to open a pull request with the required changes.

**Comment by marcel263** [comment]
> There won't be an option to change the default search for the homepage, it takes 1 click to open the tweet search page. I'd much rather create a far better homepage, but it takes a lot of work and I don't have much time these days. If you _really_ want to see a preference to change the homepage search, you're welcome to open a pull request with the required changes.

@zedeus 
Hello, great you understandung. If the request is reopened it regains visibility. it is a community effort 
thank you
