### ISSUE TITLE
/i/sattus/GUID links for "show this thread" behaves differently from twitter.

### ISSUE THREAD

**Issue by rezad1393** [zedeus/nitter#592]
then I see a thread in a twitter have links that are the same if you click on the time of post, situated after username, or when you click on show this thread at the end of first post in time line.
like this:
https://twitter.com/spriter99880/status/1508468216791719941

but in nitter the first one is like twitter but the second one is a /i/sattus/GUID format like like these two:
https://nitter.namazso.eu/spriter99880/status/1508468216791719941
https://nitter.namazso.eu/i/status/1508468216791719941

when I click in "open in twitter" from the /i/status/GUID link, then in twitter it goes to https://twitter.com/spriter99880/status/1508468216791719941 so twitter supports the links internally but redirects them to the username one.

can for sake of consistency in nitter the same be applied?
I think only the "show this thread" part needs to be corrected.

**Comment by zedeus** [comment]
I don't know if the tweet changed but I don't see "show this thread" anywhere. I get your point about the difference in behavior, but it's not something that matters, so I'm not going to implement an unnecessary redirect just to change the url.

**Comment by rezad1393** [comment]
what do you mean you dont see.
go to any twitter user that post mutil-post twits. twitter shows the first one and show a : "show this thread" at the end.
have you ever used twitter? joking :)

**Comment by zedeus** [comment]
It's not in the tweets you posted or the account that posted them. Yes I know about the "show this thread" functionality, I added that to Nitter a long time ago. I don't see how it's related to this redirection anyway.
![image](https://user-images.githubusercontent.com/9434921/160558040-0afa6831-8d28-4489-b857-65e5e141e83c.png)

**Comment by rezad1393** [comment]
> It's not in the tweets you posted or the account that posted them. Yes I know about the "show this thread" functionality, I added that to Nitter a long time ago. I don't see how it's related to this redirection anyway. ![image](https://user-images.githubusercontent.com/9434921/160558040-0afa6831-8d28-4489-b857-65e5e141e83c.png)

I am asking that like twitter clicking on the timestamp of the twit and the "show the thread" go the same url.

**Comment by zedeus** [comment]
When adding this "show this thread" feature I decided to make it more useful by actually taking you to the thread itself, rather than the tweet you can access by clicking on it or the timestamp. I don't understand why you want it to be less useful, but it's not gonna happen.

**Comment by rezad1393** [comment]
ok. this is your project not mine.
thanks for the answers.
