### ISSUE TITLE
Nitter page load crashes with error "Can't parse enum. At offset: 4118" when handling Twitter 3D models

### ISSUE THREAD

**Issue by WeebDataHoarder** [zedeus/nitter#597]
When loading Tweets with embedded 3D models, Nitter cannot handle them and crashes the load. Even if not supported, they should be handled gracefully.

Another issue is that any profile that has RT'd such tweets will also stop the profile from loading entirely, for example, https://twitter.com/tomventimiglia (Twitter ad dev that unleashed these onto the world).

## Tweets that reproduce the issue
https://twitter.com/Target/status/1509651281995919369

https://twitter.com/Lexus/status/1509270606411313152

https://twitter.com/newbalance/status/1507087258783924230

![image](https://user-images.githubusercontent.com/57538841/161342554-9499616f-d6c5-4f98-a6ca-f79a694fac3d.png)

## URLs under which 3D models are hosted under
* https://pbs.twimg.com/model_3d_img/1504180454051749888/FN_r3uJUcAQTbiK.glb
* https://pbs.twimg.com/model_3d_img/1504180454051749888/FN_r3uJUcAQTbiK.glb
* https://pbs.twimg.com/model_3d_img/1504181783759400967/FN_tG3WVIAIPauu.glb
* https://pbs.twimg.com/model_3d_img/1504182591762714628/FN_tzFxVUAQ6k58.glb

## Error excerpt
```
An error has occured in one of your routes.
Detail: jsony.nim(398) parseHook
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
Can't parse enum. At offset: 4118
```

```
An error has occured in one of your routes.
Detail: jsony.nim(398) parseHook
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
Can't parse enum. At offset: 3545
```

**Comment by Symbian9** [comment]
Just found same issue with opening `@LEGO_Group` Twitter account page on various instances (including main):

- https://nitter.net/LEGO_Group
- https://nitter.it/LEGO_Group
- https://nitter.fdn.fr/LEGO_Group

> An error has occured in one of your routes.
> 
> Detail: ```jsony.nim(398) parseHook
> asyncfutures.nim(389) read
> asyncfutures.nim(389) read
> asyncfutures.nim(389) read
> asyncfutures.nim(389) read
> asyncfutures.nim(389) read
> Can't parse enum. At offset: 182```
