### ISSUE TITLE
Sanitize RSS Feed names To Remove Slashes

### ISSUE THREAD

**Issue by roryyamm** [zedeus/nitter#600]
I'm using Claws-Mail to show several RSS feeds from nitter.1d4.us. I'm using it in part to create an archive of tweets for people I follow, but I'm running into an interesting issue. Every once in a while, RSSyl decides to create a subfolder inside the current MH directory, which it then fills with the latest 20 messages - and then forgets any message that occurred previously. I have to move messages around, and even that sometimes fails as the next update just creates _another_ level of directory. Eventually it gives up trying to name the folder at the end, leading to paths like   `~/.claws-mail/RSSyl/Feeds (RSSyl)/AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /AIRIS ATHENA #VTUBER /Untitled feed`.

I believe the problem is the default title of the RSS feed - in this case, `AIRIS ATHENA #VTUBER / @Athena_Airis`. RSSyl must be interpreting the forward slash as a literal filepath somehow, leading to the insane recursion. Would it be possible to change the forward slash to some other, non-interfering character like a dash or an underscore?

**Comment by zedeus** [comment]
I don't like changing Nitter to work around bugs in other programs, so I'm hesitant to do this unless it causes problems for other programs. Consider filing a bug report for RSSyl to escape feed titles properly.
