### ISSUE TITLE
Nitter.net RSS feeds - Sporadic 502 Bad Gateway errors

### ISSUE THREAD

**Issue by TehNolz** [zedeus/nitter#602]
Hey!

I've built a custom Discord bot that watches various RSS feeds and sends me Discord notifications whenever a feed gets updated. Works great, except I've noticed that the official nitter.net site seems to somewhat frequently return a 502 Bad Gateway error.

The issue seems to be super random. Sometimes it'll work fine for hours, other times I get an error every 5 minutes. They're common enough that I always seem to get at least a bunch of these errors every day. Usually it's only 1 feed that fails, but sometimes 2 or all 3 will fail because of that error. There doesn't seem to be any kind of pattern to it. Haven't tried using another instance yet, so I'm not entirely sure if this is a Nitter problem or if its specific to the official website. I haven't had any problems using the website through my browser so I think it's purely an RSS issue.
  
I'm checking 3 feeds every 5 minutes, which seems like a reasonable rate to me. I'm sending the GET requests using .NET's [`HttpClient.SendAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=net-6.0) method, and I'm not doing anything weird with headers or anything like that; It's just a standard GET request. Other RSS feeds (including Ars Technica's) work just fine so I highly doubt my bot is doing something wrong.
  
The error isn't causing me to miss any messages or anything like that so it's not a huge deal, but I'd appreciate it if it gets fixed. Would rather not mute it in case something else goes wrong.
  
Thanks in advance!

**Comment by clouedoc** [comment]
This error happens to me while using the web interface.

Some icons are also disappearing.

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/13921610/161814537-1d35bc66-1726-4ce7-9987-6185c689c8e5.png">

I'm using a VPN. Changing the browser does not help.

**Comment by zedeus** [comment]
nitter.net has been a bit flaky for a while, but I do what I can to keep it stable. It will be moved to a new provider in the near future, but for now you can either ignore the failures or use a more stable instance.
