### ISSUE TITLE
Twitter Age restriction

### ISSUE THREAD

**Issue by Salastil** [zedeus/nitter#604]
![1649458802](https://user-images.githubusercontent.com/46979341/162544913-56bd7807-74c6-4b3e-aac8-eafedfd3289c.png)

Looks like Twitter has rolled out an age restriction for some content. The thread I found it was this one: https://twitter.com/antiwar_soldier/status/1511701282620329989 its full of war combat and dead people. I cannot seem to trigger this age-gate by manually tweeting and flagging images so I cannot give you a tweet or thread that has nicer content for testing against.

**Comment by zedeus** [comment]
If you open that thread in incognito mode you get the same thing, nothing I can do.
