### ISSUE TITLE
Clarification regarding Twitter Developer TOS?

### ISSUE THREAD

**Issue by dschep** [zedeus/nitter#613]
Hey @zedeus, I just found your project. Pretty awesome! I'll likely be using it 🙂 

I was under the impression the developer terms of service prohibited republishing data from the API. 

Is that not the case? I can't find any mention of the developer TOS in this repo

Note, I'm not trying to cause any trouble, I've created tools to violate that part of the TOS(as far as I understood it) myself:
* https://github.com/dschep/twitter2rss
* https://github.com/dschep/Twitter-user_timeline.rss-proxy

**Comment by zedeus** [comment]
That is probably true, but Nitter doesn't use the developer API. There was some talk about the ToS here: https://github.com/zedeus/nitter/issues/482

**Comment by dschep** [comment]
🤦 how did i not see this line: 

> Uses Twitter's unofficial API (no rate limits or developer account required)
