### ISSUE TITLE
Accept micro-donations through Zink

### ISSUE THREAD

**Issue by tzvc** [zedeus/nitter#615]
Hey zedeus 😎

Like many people I'm sure, I've been using nitter almost everyday and I imagine the server costs are adding up.
I would love to have another easy way to support the project: by sending a few cents everytime I use it.

An easy way to do that is through [Zink](https://zink.tips/). It lets visitors send micro-donations (from $0.05) in a few clicks. ex. https://zink.tips/theo (disclaimer: i worked on this project)

Let me know what you think!

**Comment by u0nel** [comment]
The legal notice link doesn't work, also you have to login with google, which doesn't seem to be that privacy preserving. I also would like to know more about how this works. Which payment processor do you use? How do you make money if it's free? How does it work exactly? Stripe for example takes .25€ per transaction so is there some amount you have to donate until the money is transferred? Also for received donations, what will happen if you don't get enough donations for it to make sense to withdraw it? Also I can't find a privacy policy, which is required by the GDRP. Also the site connects to google without permission by the visitor, which isn't allowed.
Also there is no imprint (which is required in EU countries) or any other way to know who operates the website. Which is what I'd expect from a site I'll want to give money to.
