### ISSUE TITLE
UI is broken

### ISSUE THREAD

**Issue by Voxelstice** [zedeus/nitter#616]
I wanted to go to the site to look at something but,
![msedge_F0cuJSU72N](https://user-images.githubusercontent.com/95834462/166857357-e16f294c-4ea7-4c53-a838-55b892794840.png)

The UI seems to be broken. And sometimes, sites dont even load.
All I see in the console is this.
![image](https://user-images.githubusercontent.com/95834462/166857422-b2df776c-c463-4704-ad2d-4b3eb3e7a4eb.png)

From what I can understand in the console, It seems to be failing to load the .css file. I looked at the .css file with inspect element and there was nothing there.
![image](https://user-images.githubusercontent.com/95834462/166857693-0bf37aae-ffa2-4668-8e7b-7a2ceb61f34b.png)

Is this just a issue on my end? Or some people are being affected by this?

**Comment by zedeus** [comment]
Server issues
