### ISSUE TITLE
Please remove paranoid.cf and add https://twitter.beparanoid.de

### ISSUE THREAD

**Issue by hnhx** [zedeus/nitter#621]
I have changed my VPS and moved to another domain.

Country: Switzerland
Cloudflare: No
Clearnet: https://twitter.beparanoid.de
Tor v3 hidden service: http://twitter.prnoid54e44a4bduq5due64jkk7wcnkxcp5kv3juncm7veptjcqudgyd.onion
I2P hidden service: http://gseczlzmiv23p5vhsktyd7whquq2uy3c5fgkmdohh453qp3daoua.b32.i2p/

**Comment by zedeus** [comment]
Done!
