### ISSUE TITLE
Invalid Unicode Byte Sequence when trying to access some feeds

### ISSUE THREAD

**Issue by MasseR** [zedeus/nitter#624]
I get a unicode error when trying to access some feeds such as `GabriellaG439`.

```
An error has occured in one of your routes.

Detail: nre.nim:508 matchImpl
asyncfutures.nim:389 read
asyncfutures.nim:389 read
asyncfutures.nim:389 read
asyncfutures.nim:389 read
asyncfutures.nim:389 read
asyncfutures.nim:389 read
Invalid unicode byte sequence
```

I'm running revision 683c052036b268028f0ecae020a1519bc586516d

**Comment by zedeus** [comment]
Try deleting the `~/.nimble` folder and rebuild, someone had the same issue recently with an older version of Nitter

**Comment by MasseR** [comment]
Sorry, one detail was omitted. I'm building in nix, meaning that every build is built in a clean sandbox.

**Comment by MasseR** [comment]
Good catch! Thank you. For others trying to find this error: https://nixpk.gs/pr-tracker.html?pr=173214 shows when it's merged to unstable.
