### ISSUE TITLE
autoScroll=true won’t work in URL

### ISSUE THREAD

**Issue by VectorABC** [zedeus/nitter#626]
To force a light (Twitter) theme on a mobile browser I bookmark a Nitter URL with ?theme=Twitter added but when I use the Load More button it resets to default dark theme. I have my iPhone browser delete cookies regularly so I can’t rely on a cookie to retain my theme. But adding &infiniteScroll=true fails to load the needed JavaScript (infiniteScroll.js), so this needs to be added at the server side.

**Comment by zedeus** [comment]
Duplicate of #186
