### ISSUE TITLE
Provides better meta data in the header to include Nitter pages in external websites

### ISSUE THREAD

**Issue by Ravenbird** [zedeus/nitter#628]
There are many people in [Fediverse](https://en.wikipedia.org/wiki/Fediverse) who using Nitter to embed Twitter content. The problem is that no real corresponding preview is generated, so that only the Nitter URL is displayed, without knowing what is behind it, whether it is even interesting to call the page. With me that looks then on [Friendica](https://en.wikipedia.org/wiki/Friendica) e.g. in such a way:

![2022-05-26 Frindica Nitter 1](https://user-images.githubusercontent.com/2757648/170482788-0b365ba5-e67b-4070-8a20-d53ba9a07e19.png)

The post on Nitter looks like this:

![2022-05-26 Frindica Nitter 2](https://user-images.githubusercontent.com/2757648/170482808-9f2298fe-93e1-455c-9ab9-35bf26e2696b.png)

I had a [short exchange](https://anonsys.net/display/bf69967c-5862-8f56-dcb1-db7624963011) with one of the developers of Friendica and he said that the problem lies with the meta data stored by Nitter in the header. And that's why I'm here to ask if Nitter can do something about it.

**Comment by zedeus** [comment]
The photos appear to show different tweets posted by different people. It's not true Nitter doesn't provide any headers describing the content, it works just fine on many other platforms.
![image](https://user-images.githubusercontent.com/9434921/170498840-ed3ea936-ad8a-4ca8-a05b-ec43a712baa5.png)

**Comment by Ravenbird** [comment]
It's not about comments and quotes but the original post itself. Unfortunately I am not a programmer, so I can only write what I notice or was said. :-(

**Comment by zedeus** [comment]
Nitter uses the same og headers as any other service: https://ogp.me/
![image](https://user-images.githubusercontent.com/9434921/170502024-8c7ad4b3-0b9c-4788-a4ec-eb6f9dc73b83.png)
