### ISSUE TITLE
Use same parameters as Twitter uses in search

### ISSUE THREAD

**Issue by Perflyst** [zedeus/nitter#63]
For example Twitter uses https://twitter.com/search?f=users&q=test for user search while Nitter is using https://nitter.snopyta.org/search?kind=userSearch&q=test

Why this differences? It just adds complexity, I think.

**Comment by zedeus** [comment]
It's impossible for me to use the exact same parameters, but this brings us a step closer.

**Comment by Booteille** [comment]
What makes it impossible?

(But anyway, thanks for the work!)

**Comment by zedeus** [comment]
Twitter's advanced search makes use of operators entirely, with no toggles etc. Nitter has a dropdown panel to make things much easier for people that don't know about operators, and they're all separate parameters. For example, toggling "Videos" next to "Filter" adds a "f-videos=on" parameter to the request. This is then added to the `q=` parameter as `filter:videos` for the Twitter request.
