### ISSUE TITLE
Add internet utilization bar

### ISSUE THREAD

**Issue by pvenkatcharan-since2002** [zedeus/nitter#642]
Using an internet utilization bar for new users might make them feel the true light twitter. This helps in building trust on Nitter by user.

**Comment by zedeus** [comment]
What's that?

**Comment by pvenkatcharan-since2002** [comment]
A space to show internet utilization by nitter vs twitter.
It can contain network data in megabytes used by nitter and would be used by twitter.

**Comment by zedeus** [comment]
Impossible to accurately measure/predict and not really the main purpose of Nitter.
