### ISSUE TITLE
Extra space after apostrophe?

### ISSUE THREAD

**Issue by Victor239** [zedeus/nitter#649]
When I view this tweet on [Twitter](https://twitter.com/Cernovich/status/1540442002990411776) it looks normal. When I view it on any Nitter instance [for example](https://nitter.net/Cernovich/status/1540442002990411776#m) however it looks like this:

![](https://i.imgur.com/N62zUmw.png)

**Comment by zedeus** [comment]
Looks normal for me, maybe it's the font you're using
![image](https://user-images.githubusercontent.com/9434921/175781612-ff262c81-deb4-4aba-b80e-04ab1d827398.png)

**Comment by Victor239** [comment]
Something wrong with my browser instead, thanks anyway.
