### ISSUE TITLE
Unable to play videos on TweetDeck

### ISSUE THREAD

**Issue by seth100** [zedeus/nitter#66]
Hi,

I use [TweetDeck](https://tweetdeck.twitter.com/) and when I open a tweet with a video and I have the Nitter extension active I get a "Page not found" error:

<a href="https://ibb.co/x3ZsrHf"><img src="https://i.ibb.co/x3ZsrHf/IMG-20191008-144012-463.jpg" alt="IMG-20191008-144012-463" border="0"></a>

How to handle this?
Thanks

**Comment by zedeus** [comment]
What url does it open?

**Comment by seth100** [comment]
e.g. this one:

```
https://video.twimg.com/amplify_video/1181733041414258688/vid/720x720/jlUUozwgD3-UDdAe.mp4?tag=13
```

but even coming from:

```
https://twitter.com/i/videos/tweet/1181998954139062273?image_src=https://pbs.twimg.com/amplify_video_thumb/1181733041414258688/img/U9AvRxH5d3N43BMb.jpg&media_id=1181733041414258688&video_url=https://video.twimg.com/amplify_video/1181733041414258688/vid/720x720/jlUUozwgD3-UDdAe.mp4?tag=13&content_type=video/mp4&owner_id=&auto_buffer=1&autoplay=1
```

**Comment by zedeus** [comment]
First one is an issue with the extension you're using, please open an issue in the repo belonging to it. Second one is a video embed, unsupported for now but I'll look into it. Thank you.

**Comment by seth100** [comment]
@zedeus , ok thank you for your help!
