### ISSUE TITLE
[Request] Include the tweet being replied to

### ISSUE THREAD

**Issue by leodoi3** [zedeus/nitter#661]
When you go to view a profile's tweet and replies on Twitter, it always shows the tweet being replied to on the timeline. Such as this: 
https://twitter.com/BrendanEich/with_replies
![image](https://user-images.githubusercontent.com/46114199/177059481-c54d2d79-b099-42d5-b589-7c35ead43628.png)

But on nitter it doesn't include that tweet. 
https://nitter.net/BrendanEich/with_replies
![image](https://user-images.githubusercontent.com/46114199/177059510-b62da3a3-590e-456a-8449-61e8dd85ce68.png)

If possible could you include that on nitter?

**Comment by distbit0** [comment]
This would be awesome.

**Comment by Deagan** [comment]
Would love this! I follow accounts that reply often, and I have to click back and forth to view the original tweets **a lot**.

**Comment by zedeus** [comment]
Twitter only does this if you're logged in, so it's not something I can support without making a request per tweet which is far too much.
