### ISSUE TITLE
Replies in Multi Nitter link

### ISSUE THREAD

**Issue by EdwardLangdon** [zedeus/nitter#663]
For Example, Take this, Multi link - https://nitter.net/@firefox,@marvelstudios,@warnerbros,@reddit,@icanhazdadjoke

After Visiting. Go to twitter by Clicking the Twitter icon in Top right corner.

![image](https://user-images.githubusercontent.com/101938856/177287076-06fd3484-753e-4b4e-b116-3edf439cc051.png)

If you see the feed in Twitter, You can see the replies of those accounts. It would be great to see replies in Nitter too.

**Comment by zedeus** [comment]
Just click on Tweets & Replies, there's a large button at the top of the page that does exactly what you're asking for.

**Comment by EdwardLangdon** [comment]
Oops, Sorry, I didn't notice that.
