### ISSUE TITLE
I want to remove my nitter tweet

### ISSUE THREAD

**Issue by grabhubnews** [zedeus/nitter#667]
Hi, I don't know how to connecting with nitter with my twitter account, but I want to remove one tweet on nitter, so please let me know how to remove it?

**Comment by zedeus** [comment]
You can't, that's not how Nitter works.

**Comment by grabhubnews** [comment]
so let me know how to process it, my twitter account connecting all tweet with nitter. How to remove it?

**Comment by zedeus** [comment]
You can't, Nitter is just a proxy. If you want to remove your tweets and/or Twitter account, you must do so via Twitter.

**Comment by grabhubnews** [comment]
Thank you for confirmation.
