### ISSUE TITLE
Instance randomly gets HTTP error 500

### ISSUE THREAD

**Issue by moom0o** [zedeus/nitter#674]
Hello, my instance randomly gets error 500, nitter backend is unreachable for upwards of a minute. All traffic receives the error.
This isn't a nginx problem because the nginx logs are showing the errors. I can't see any errors in the nitter logs.

I'm wondering if I need to increase any options in the config? I get upwards of 75-100 requests per second, all day long.

Currently redisMaxConnections are 100, and connections are 30
tokencount is 100.

**Comment by zedeus** [comment]
>tokencount is 100

20 is fine, you can enable debugMode and check `/.tokens` to see how many are active in the pool, but changing this shouldn't solve this problem. It's quite difficult to say what's wrong with no info here, it may just be that your instance can't handle it. How much CPU does it use on average, and in those cases where it's unreachable? You can try spreading the load between a few Nitter processes on the same machine with [nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/).

**Comment by moom0o** [comment]
I have fixed this. For some reason in NGINX, requests will work fine for a while, but will randomly start failing as it tries to connect to the literal word "backends" (I was trying load balancing) or "localhost", resulting in error 502. 

![image](https://user-images.githubusercontent.com/48740106/180605009-c2159d5a-df35-4f3a-a205-abcc2555bea8.png)
![image](https://user-images.githubusercontent.com/48740106/180605015-7c3c7b56-04ab-44a3-8db8-06701015ae2b.png)


To fix: Use 127.0.0.1 instead of words.
