### ISSUE TITLE
Unable to control vertical video on Firefox

### ISSUE THREAD

**Issue by B0pol** [zedeus/nitter#680]
On quoted tweets, and especially on mobile, I’m unable to control vertical videos : pause, fullscreen, change volume…

Desktop:
![image](https://user-images.githubusercontent.com/58657617/184004211-f1c2f330-dfee-4d0f-b3a9-59b1f1f845e0.png)

Mobile:
![Screenshot_20220810-213308_Fennec](https://user-images.githubusercontent.com/58657617/184004568-1a2b6a76-d9c4-4008-b4a2-27692a6729fc.png)

How to reproduce:
1. Install Firefox
2. Find a tweet with a vertical video
3. Search quoted tweets

Example URL:
https://nitter.pussthecat.org/search?f=live&q=include%3Anativeretweets+-from%3Aquotedreplies+url%3Ahttps%3A%2F%2Ftwitter.com%2Ffranceinfo%2Fstatus%2F1557303824016105478&src=typed_query

**Comment by zedeus** [comment]
Fixed by #680
