### ISSUE TITLE
Divide the "Not safe" search setting into "Sensitive" and "Adult"

### ISSUE THREAD

**Issue by DandelionSprout** [zedeus/nitter#681]
Some months ago, Twitter created (and began to loosely enforce) an option to designate tweets as "Age-restricted adult content." Nitter does a very stellar job at bypassing Twitter's login requirements for such tweets, but Nitter's search options currently don't have a way to distinguish between those tweets and "Sensitive" tweets, as (from what I can tell) they're [both grouped as the opposite of the "Safe" setting](https://github.com/zedeus/nitter/blob/master/src/views/search.nim). 

![image](https://user-images.githubusercontent.com/22780683/184061774-3af5c73e-22a2-45ae-80b0-a8ff8633c483.png)

I feel that splitting the two apart would be worthwhile (despite the probable difficulty in adapting CSS values to fit a 3rd row or 7th column), in particular because perhaps 97% of "Sensitive" tweets are normal safe tweets that got the tag put on them by Twitter bots, whereas "Age-sensitive" tweet tags seem to be opt-in only. It's probably a given that this would be most commonly used by people who actively look for adult art and would use "Filter: ✓ Adult", I admit.

• Instance used during my testing: `https://nitter.42l.fr`
• Browser: Chrome 104.0.5112.81 x64
• OS: Windows 11 21H1 x64

**Comment by zedeus** [comment]
All the filters are made by Twitter (in this case `filter:safe`), so unless they've added new ones since then it's not possible to do this.
