### ISSUE TITLE
[help] RSS feed points to nitter.net instead of my instance hostname

### ISSUE THREAD

**Issue by woj-tek** [zedeus/nitter#687]
I just setup own nitter instance and it works great but I have an issue with RSS links. I configured `replaceTwitter` and `hostname` with my instance URL and it works just fine for main view `https://my.nitter.com/<account>` and I see links pointing to `https://my.nitter.com/` but once I open RSS feed `https://my.nitter.com/<account>/rss` all links use `https://nitter.net/<account>` instead of my.nitter.com

I checked https://github.com/zedeus/nitter/blob/master/src/prefs_impl.nim but I don't see any other option that would apply only to rss and not main view.

**Comment by zedeus** [comment]
Could it be the Redis cache? Try opening another feed

**Comment by woj-tek** [comment]
I thought about it and checked it (opened random profile) - on main page (in html) links are to my instance but on rss it links to nitter.net.

According to https://github.com/zedeus/nitter/blob/master/src/views/rss.nimf#L28 I should see `Twitter feed for: ${desc}. Generated by ${cfg.hostname}` but on rss page I see `Twitter feed for: @RokJerzy. Generated by nitter.net` so it seems that for some reason `${cfg.hostname}` is wrong

**Comment by zedeus** [comment]
Nice, so it's working now? Indeed forgetting to mount the config file would cause this

**Comment by woj-tek** [comment]
No, that's the thing that even after adding the line it's still not working and I have no clue why. I added the line, went with `sudo docker-compose up -d`. The output looks ok:

```
$ sudo docker-compose config
services:
  nitter:
    container_name: nitter
    depends_on:
      redis:
        condition: service_started
    environment:
      REDIS_HOST: '"redis"'
    healthcheck:
      interval: 30s
      retries: 2
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit
        1
      timeout: 5s
    image: quay.io/unixfox/nitter:latest
    ports:
    - published: 8089
      target: 8080
    restart: unless-stopped
    volumes:
    - /home/wojtek/nitter/nitter.conf:/src/nitter.conf:ro
    - /home/wojtek/nitter/data/nitter:/data:rw
  redis:
    container_name: redis
    healthcheck:
      interval: 30s
      retries: 2
      test: redis-cli ping
      timeout: 5s
    image: redis:alpine
    restart: unless-stopped
    volumes:
    - /home/wojtek/nitter/data/redis:/data:rw
version: '3'
```

I noticed that in original `docker-compose.yml` from repo there is no mount for `- ./data/nitter:/data` (but I think it shouldn't cause issues?). The second thing is that in that data directory there is another conf file: (`nitter/data/nitter/nitter.conf`) which contains default configuration.

I removed that line, recreated the containers:
```
$ sudo docker-compose config
services:
  nitter:
    container_name: nitter
    depends_on:
      redis:
        condition: service_started
    environment:
      REDIS_HOST: '"redis"'
    healthcheck:
      interval: 30s
      retries: 2
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit
        1
      timeout: 5s
    image: quay.io/unixfox/nitter:latest
    ports:
    - published: 8089
      target: 8080
    restart: unless-stopped
    volumes:
    - /home/wojtek/nitter/nitter.conf:/src/nitter.conf:ro
  redis:
    container_name: redis
    healthcheck:
      interval: 30s
      retries: 2
      test: redis-cli ping
      timeout: 5s
    image: redis:alpine
    restart: unless-stopped
    volumes:
    - /home/wojtek/nitter/data/redis:/data:rw
version: '3'
```

I reset the preferences in the browser on random account - I see it now uses `nitter.net` for "Twitter -> Nitter", yet I see that all links on the page still use my domain. Only the RSS is incorrect.

I wanted to check the actual content of the `/src/nitter.conf` file from within the container but I can't "exec"-inside.

**Comment by zedeus** [comment]
If you mount the file into the "public" folder, you should be able to access it at /nitter.conf

**Comment by woj-tek** [comment]
Which one? I now included both in docker-compose.yaml:

```
    volumes:
    - /home/wojtek/nitter/data/nitter:/data:rw
    - /home/wojtek/nitter/nitter.conf:/src/nitter.conf:ro
```

`/home/wojtek/nitter/nitter.conf` contains my (correct) configuration. The one in `data` directory is incorrect:
```
$ cat /home/wojtek/nitter/data/nitter/nitter.conf
[Server]
address = "0.0.0.0"
port = 8080
https = false  # disable to enable cookies when not using https
httpMaxConnections = 100
staticDir = "./public"
title = nitter
hostname = nitter.net
…
```
It seems that `/data` is incorrect altogether.

Is there another place apart from `/src/nitter.conf` where the hostname configuration is hold? Or is there a way I could check if the file/configuration is read correctly (logs of some sort)?

**Comment by woj-tek** [comment]
OK, after some more digging (prompted by seeing that other instances have this correct) I noticed that when running normally (even with `docker run`) there is a bunch of environment variables populated:

```
$ docker inspect nitter | jq '.[0].Config.Env'
[
  "REDIS_HOST=redis",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "REDIS_PASS=",
  "REDIS_PORT=6379",
  "NITTER_HTTPS=false",
  "NITTER_HOST=nitter.net",
  "NITTER_NAME=nitter",
  "NITTER_THEME=Nitter",
  "REPLACE_TWITTER=nitter.net",
  "REPLACE_YOUTUBE=invidio.us",
  "REPLACE_REDDIT=teddit.net",
  "REPLACE_INSTAGRAM="
]
```

I'm not really sure how/why those are populated (instead of using configuration from `nitter.conf` file; searching repo for `NITTER_HOST` didn't yield any result) but after configuring `NITTER_HOST` in `docker-compose.yaml` I have correct link in RSS feed.

**Comment by zedeus** [comment]
I think this is a custom config thing implemented by unixfox for his Nitter image, so I wouldn't know. Glad it works.

**Comment by woj-tek** [comment]
Actually [it uses](https://github.com/goodtiding5/docker-nitter/blob/master/compose/docker-compose.yml) an [`epenguincom/nitter` image](https://hub.docker.com/r/epenguincom/nitter) as base. Would be nice to have multi-arch nitter builds from original source :-)
