### ISSUE TITLE
Network will randomly go to 0mbps

### ISSUE THREAD

**Issue by moom0o** [zedeus/nitter#688]
This is a really weird issue. Nitter network usage will go to 0mbps randomly (SSH still works fine, and pinging api.twitter.com has no packet loss)
Incoming nitter requests will take a few seconds to load until it spikes back up.
Is there any way to debug this? Logs don't show any errors/warnings.

![image](https://user-images.githubusercontent.com/48740106/185754895-f7823e31-3ed4-45fb-876e-0a441df962ab.png)
![image](https://user-images.githubusercontent.com/48740106/185754914-57b8ebec-af7c-41ad-8d49-8d1118707d7b.png)

**Comment by zedeus** [comment]
Could be too much traffic. How's the CPU and memory usage like? Have you tried running two or more Nitter processes to spread the load via Nginx's load balancer?

**Comment by moom0o** [comment]
Setting up the docker version seems to have fixed it, at least temporarily. Maybe its the caching? I deleted the dump.rdb but the issue was still happening.

**Comment by zedeus** [comment]
Deleting the dump file won't help, but you can always run `flushdb` through redis-cli

**Comment by zedeus** [comment]
@moom0o is it still working fine?

**Comment by moom0o** [comment]
> @moom0o is it still working fine?

Not really, I have to delete the docker container every once in a while to fix it.
