### ISSUE TITLE
Feature Request: Fold Threads by default.

### ISSUE THREAD

**Issue by MintMain21** [zedeus/nitter#692]
Some users write large threads that, in the default Twitter UI, are folded into a single tweet and need to be "unfolded" to read properly.

There should be an option to do this by default in Nitter as well. Something that could be toggled on/off via cookies. This would make navigating Nitter much easier.

**Comment by zedeus** [comment]
Example?

**Comment by MintMain21** [comment]
https://unofficialbird.com/Schaffrillas/status/1585412448106221569?theme=Auto&infiniteScroll=true&mp4Playback=true&hlsPlayback=true

At least once every month, this user does a "Hungry Games" event, that eats up space on his timeline when browsing.

If this thread were folded by default, it would make browsing his timeline significantly easier.

**Comment by zedeus** [comment]
How does it look with Twitter's default UI that folds it?

**Comment by MintMain21** [comment]
@bigdiff https://www.youtube.com/watch?v=P3ALwKeSEYs

**Comment by zedeus** [comment]
This just isn't possible, and it's not something Twitter does. Nitter does not fetch additional tweets to show the thread, it just turns tweets from the same thread on the same page into an easy to read thread without the "Show this thread" link under all of them spread throughout the timeline. You might want no threading at all, which may become a preference option in the future, but then the timeline will just have the same tweets scattered around.
