### ISSUE TITLE
stop at downloading zippy

### ISSUE THREAD

**Issue by msfm360** [zedeus/nitter#695]
when i use nimble build -d:release

the code stop at 
C:\Users\mohammed\Downloads\nim-1.6.6_x64\nim-1.6.6\nitter>nimble build -d:release
  Verifying dependencies for nitter@0.1.0
      Info: Dependency on jester@>= 0.5.0 already satisfied
  Verifying dependencies for jester@0.5.0
      Info: Dependency on https://github.com/timotheecour/asynctools@#pr_fix_compilation already satisfied
  Verifying dependencies for asynctools@#pr_fix_compilation
      Info: Dependency on karax@#6abcb77 already satisfied
  Verifying dependencies for karax@#6abcb77
      Info: Dependency on ws@any version already satisfied
  Verifying dependencies for ws@0.5.0
      Info: Dependency on dotenv@>= 2.0.0 already satisfied
  Verifying dependencies for dotenv@2.0.1
      Info: Dependency on sass@#e683aa1 already satisfied
  Verifying dependencies for sass@#e683aa1
      Info: Dependency on nimcrypto@#a5742a9 already satisfied
  Verifying dependencies for nimcrypto@#a5742a9
      Info: Dependency on markdown@#a661c26 already satisfied
  Verifying dependencies for markdown@#a661c26
      Info: Dependency on packedjson@#9e6fbb6 already satisfied
  Verifying dependencies for packedjson@#9e6fbb6
      Info: Dependency on supersnappy@#2.1.1 already satisfied
  Verifying dependencies for supersnappy@#2.1.1
      Info: Dependency on redpool@#8b7c1db already satisfied
  Verifying dependencies for redpool@#8b7c1db
      Info: Dependency on https://github.com/zedeus/redis@#d0a0e6f already satisfied
  Verifying dependencies for redis@#d0a0e6f
      Info: Dependency on https://github.com/zedeus/redis@#d0a0e6f already satisfied
  Verifying dependencies for redis@#d0a0e6f
 **_### Installing zippy@#0.9.11
Downloading https://github.com/guzba/zippy using git_**

![image](https://user-images.githubusercontent.com/50640440/190613569-a1b44e8a-9083-4b61-bf44-8c634f3b3734.png)

**Comment by msfm360** [comment]
![image](https://user-images.githubusercontent.com/50640440/190614272-e59f190b-ee4b-43d9-9bd7-67fe5e7c1d4a.png)

**Comment by zedeus** [comment]
Can you try changing zippy's version in nitter.nimble from 0.9.11 to 0.10.4?
