### ISSUE TITLE
Nitter

### ISSUE THREAD

**Issue by Arsenal4904** [zedeus/nitter#703]
I emailed the address listed on nitter. net and I haven't got a response. I wanted to ask:

I want to see REtweets - not original account's tweets - REtweets - from  a long time ago. Twitter API doesn’t allow that, and neither does Nitter. I can’t see retweets with Twitter search and Nitter search.

Also why is "tHiS mEdIa iS uNaVaiLaBLe" appearing when it doesn't on Twitter? Even without adblockers it still happens. Can both my issues I asked about be fixed?"
![fssfsfsf](https://user-images.githubusercontent.com/115781322/195947948-e878849f-b28c-463e-96a1-fe12f4a5cc0c.JPG)

**Comment by Arsenal4904** [comment]
I posted this on element and have got no legitimate help.

**Comment by zedeus** [comment]
The video might be a broadcast/livestream which nitter doesn't currently support, I'd need the tweet link to know. 

Retrieving older tweets is not always possible due to API limitations, nothing can be done.

**Comment by Arsenal4904** [comment]
https://nitter.net/FOXSoccer/status/1578414890015854592#m

If you're located in America, it loads on twitter. com. But it's not available on nitter, regardless of where you are located. If it doesn't load on twitter. com, use a VPN.

**Comment by zedeus** [comment]
nitter.net is hosted in the Netherlands, so if it's not available due to a region lock then nothing can be done.

Like I said, the search API has unreliable limitations that cannot be worked around.
