### ISSUE TITLE
Question - Client IP Address Visible to Twitter or Not

### ISSUE THREAD

**Issue by stef204** [zedeus/nitter#706]
Can anyone answer this question please:

`client` --> `nitter instance` --> `twitter`

My understanding is in the case above, the client's IP address is obviously visible to the nitter instance, but _not_ to twitter which would receive the request by the nitter instance, pass it on to it, and the nitter instance passes it back to client.  Twitter does not see client's IP address.

`client` <-- `nitter instance` <-- `twitter`

Is this correct or not?

**Comment by zedeus** [comment]
That is correct. Twitter can only ever see your IP address if video proxying is manually disabled on the preferences page.
