### ISSUE TITLE
Provide documentation for proper application of URL Parameters

### ISSUE THREAD

**Issue by MintMain21** [zedeus/nitter#708]
The Invidious Documentation includes a list of URL Parameters, helpful for custom redirects. https://github.com/cloudrac3r/invidious-documentation/blob/master/List-of-URL-parameters.md

Nitter evidently supports URL Parameters as well, but there's no documentation for it save for this: https://github.com/zedeus/nitter/issues/553#issuecomment-1150761574

I propose a proper entry on URL Parameters in the Nitter Wiki clearly explaining their function and how to properly append them to URLs using extensions like Redirector https://github.com/einaregilsson/Redirector

From my by experience of trial and error, the use of URL Parameters is frustratingly inconsistent between &(URL Parameter) and ?(URL Parameter) depending on what page you are on. This is where proper documentation would come in handy, as to properly enfore the desired Parameters one needs a few different rules set up.

**Comment by zedeus** [comment]
There aren't really any URL parameters that should be used by users, so this will be part of #186
