### ISSUE TITLE
Images sometimes not loading, and returns “tweet not found” or 404, even though they exists

### ISSUE THREAD

**Issue by ArchivingToolsForWBM** [zedeus/nitter#709]
This seems to happen at random, on any tweet on twitter that have images on them and have occurred on my chrome browser on my iphone SE, on 9am EST.

When archiving to the WBM, this happens extremely often.

**Comment by zedeus** [comment]
What instance? nitter.net does have some issues, I'd recommend using another one.

**Comment by ArchivingToolsForWBM** [comment]
It’s hard to reproduce. I didn’t get the message “Instance have been rate limited”.

**Comment by Arsenal4904** [comment]
I get the exact same issue.

**Comment by ArchivingToolsForWBM** [comment]
Sample: https://nitter.net/yyy_m_z
![image](https://user-images.githubusercontent.com/89951208/198704755-8fdd97c9-9a14-4fd2-8934-91646ec40353.png)
Example tweet: https://nitter.net/yyy_m_z/status/1549961498617085952#m
![image](https://user-images.githubusercontent.com/89951208/198704899-868c1ff2-35ae-42f3-898e-b01f3874a0df.png)
I had to keep refreshing to get the images to load properly. Annoying.

**Comment by ArchivingToolsForWBM** [comment]
![image](https://user-images.githubusercontent.com/89951208/198731578-b9f3991d-1baf-4776-ad69-074be7e8d88a.png)
URL in question: https://nitter.net/pic/orig/media%2FFMRo458aIAACf8S.jpg

**Comment by zedeus** [comment]
Please use another instance, nitter.net is unstable at the moment.

**Comment by IceCereal** [comment]
> Please use another instance, nitter.net is unstable at the moment.

@zedeus Is there some kind of (semi-live) way to know this online instead of going through Github issues or joining the matrix channel? Maybe something like nitter.net/status which reports activities.

Thanks!

**Comment by anshumankmr** [comment]
I had found the same issue myself, 
For example, this tweet: 
On Nitter.net: https://nitter.net/GrizzliesPR/status/1608153238292897796
![Nitter.net](https://user-images.githubusercontent.com/24219264/210263711-ee3d4310-f0f6-4e01-b59a-6247e7337c34.png)

On Nitter.CZ
https://nitter.cz/GrizzliesPR/status/1608153238292897796
![nitter.cz](https://user-images.githubusercontent.com/24219264/210263750-2fa2a8c9-8c2a-4014-8650-f29f56255b5d.png)

Original Tweet:
https://twitter.com/GrizzliesPR/status/1608153238292897796
![image](https://user-images.githubusercontent.com/24219264/210263813-0021da6e-6a75-4bd4-8dd9-c7fb72463ec1.png)

**Comment by zedeus** [comment]
nitter.net is very unstable due to odd recurring rate limits.
