### ISSUE TITLE
Remove Tweet Stats without using cookies.

### ISSUE THREAD

**Issue by MintMain21** [zedeus/nitter#710]
I just want a way to use Nitter without having to save my NoTweetStat preference as a cookie.

I don't care if it's a URL Parameter, I don't care if it's something to block with uBlock Origin, I don't care if I need to use an instance that has Tweet Stats disabled by default, I just don't want to deal with TweetStats and I'd prefer a more elegant solution than Cookies.

**Comment by zedeus** [comment]
You can create a [userstyle](https://add0n.com/stylus.html) to hide elements with the `tweet-stats` class. For a URL parameter, wait for #186
