### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by ArchivingToolsForWBM** [zedeus/nitter#712]
Right now, when visiting ANY pages of nitter, including just the home page this happens
![image](https://user-images.githubusercontent.com/89951208/198905412-1a9d5631-f337-488f-a12c-8a94330b6a0f.png)
This is on google chrome. On firefox:
![image](https://user-images.githubusercontent.com/89951208/198905477-2dd39ddd-0c1e-4bf3-92e2-8efe1d08a466.png)
Umm, yeah. Did someone forget to update the web certificate?

**Comment by markcellus** [comment]
Same thing happened with nitter.hu in https://github.com/zedeus/nitter/issues/705 :smile:. I'm sure they'll fix soon.

**Comment by vhcrack** [comment]
Until this is fixed all you need to do to bypass this (for google chrome specifically) is click anywhere in the blank space and type "thisisunsafe", you will be able to access the site without it popping up for a little while.

**Comment by BeholdersEye** [comment]
From the error page:

> Websites prove their identity via certificates, which are valid for a set time period. The certificate for nitter.net expired on 10/30/2022.

> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by AbelLykens** [comment]
Tagging @zedeus

**Comment by axb21** [comment]
> thisisunsafe

Just confirming this works fine in Vivaldi. Again with the caveat that you shouldn't do it if you don't feel comfortable bypassing the warning!

**Comment by megabert** [comment]
If I can support, to get this issue fixed permanently, just contact me.

**Comment by julianw10** [comment]
Ah, this reminds me of the Linux Manjaro team who regularily let expire their SSL certificates. Pure incompetence. Is it so hard to make a cronjob to auto renew it?

**Comment by lightningHoneypot** [comment]
> You should probably set up a cron job to renew the certificate automatically. Otherwise such storm is bound to happen every 90 days or so. I can see it is not the first time (#118 #287 #347 #475 #705).

why is it that they don't do that?
