### ISSUE TITLE
Docker Hub States ARM64 Available

### ISSUE THREAD

**Issue by UtopiaOpera** [zedeus/nitter#713]
Your official listing on hub.docker states arm64 as being available, which isn't the case. Please can you correct this by removing the arm64 tag or uploading the image.

**Comment by Kirk1984** [comment]
Just as an fyi:

I'm no coder nor do i know github except for complaining, but this Dockerfile worked. I build it on my Pi4. It took a while, but the result works. Basically i switched the amd64 only nim docker to installing nim in the alpine image so the changes to the original are minimal. I don't know if all added Packages are needed, but i works :P 

`FROM alpine:latest as nim
RUN apk --no-cache add nim nimble libsass-dev pcre git gcc curl libgcc libc-dev
WORKDIR /src/nitter
COPY nitter.nimble .
RUN nimble install -y --depsOnly
COPY . .
RUN nimble build -d:danger -d:lto -d:strip \
    && nimble scss \
    && nimble md

FROM alpine:latest
WORKDIR /src/
RUN apk --no-cache add pcre ca-certificates
COPY --from=nim /src/nitter/nitter ./
COPY --from=nim /src/nitter/nitter.example.conf ./nitter.conf
COPY --from=nim /src/nitter/public ./public
EXPOSE 8080
CMD ./nitter
`

**Comment by vijfhoek** [comment]
For what it's worth, there's a working arm64 image on https://quay.io/repository/unixfox/nitter (`docker pull quay.io/unixfox/nitter`), as the README states

**Comment by Kirk1984** [comment]
I know. And i used it too. It is based on this: https://github.com/goodtiding5/docker-nitter

And it still relies on nimlang/nim:alpine for the build which only runs on amd64 at the time of writing.

I wanted to see what it takes to use the Official Dockerfile with minimal changes. So i switched to alpine:latest, installed what was needed for the build and it runs. It should built on every architecture that the alpine:latest docker image uses.

It was more an experiment for me. But it works.

**Comment by zedeus** [comment]
Since this was opened, official AMD64 and ARM64 images get build using GitHub actions and published to Docker.
