### ISSUE TITLE
Nitter redirected to Twitter

### ISSUE THREAD

**Issue by ousia** [zedeus/nitter#723]
With this two sample addresses (https://nitter.net/amparo_manes and https://nitter.ca/amparo_manes), the destination is https://twitter.com/amparo_manes.

Is this a bug or why is Nitter “misbehaving” here?

Many thanks for your help.

**Comment by zedeus** [comment]
Clicking on those links opens nitter just fine. What do you mean?

**Comment by ousia** [comment]
@zedeus, now it is working fine.

Sorry for the noise.
