### ISSUE TITLE
Link replacement for Youtube breaks "/c" links to channels

### ISSUE THREAD

**Issue by RichardSimple** [zedeus/nitter#724]
If a link to Youtube channel is given as "https://youtube.com/c/someName", Link replacement functionality removes the "/c" part, making it "https://example.com/someName"

As far as I understand, this was introduced in df943c0, to "Fix converted youtube channel links." But as a farily new user of Nitter I don't understand what it attempts to fix? I don't see it being referenced from anywhere.

As of now, it's more of the opposite – if the replacement is used to substitute Youtube with Invidious, updated links do not work and default front page (/feed/popular) of the instance is opened instead. Piped does not work either (404 error is shown). All the while "https://example.com/c/someName" does work, for both of them.
This could actually be a problem of Invidious/Piped, as "https://youtube.com/someName" works and opens the channel, but it still is Nitter that changed the link.

If there is no real purpose for this (any longer?), I suggest this removal of "/c" to be removed itself.

**Comment by razetime** [comment]
for reference, /c/ does work in the case of https://www.youtube.com/c/anthpo and https://piped.kavin.rocks/c/anthpo, nitter gives https://www.youtube.com/anthpo
