### ISSUE TITLE
Cannot pause a video filmed in portrait mode if video in a quote retweet

### ISSUE THREAD

**Issue by sha-e-256** [zedeus/nitter#725]
Issue:

If a video is filmed in portrait mode, and that video is in a quote retweet, there is no pause/play button to the left of the video progress bar. However, the pause button is present when the video is filmed in portrait mode and is not inside of a quote retweet.

This issue appears on both mobile and desktop. I am using the Firefox web browser with both. 

What did I expect to happen:

The pause button should be visible regardless of if the video is within a quote retweet or a retweet.

Other info.:

Videos filmed in landscape mode do not have this issue. It seems to be specific to videos filmed in portrait mode.

Here are some screenshots that better describe the issue.

Video in portrait mode not in a quote retweet (pause button is visible and accesible).

![Screenshot_20221113-154332_Firefox.jpg](https://user-images.githubusercontent.com/105937174/201543765-f9f2ae9f-561b-44a6-aae7-ea9dcaeea68b.jpg)

Video in portrait mode in a quote retweet (pause button not visible and not accesible):

![Screenshot_20221113-163530_Firefox.jpg](https://user-images.githubusercontent.com/105937174/201545818-39211121-9ce3-455b-9ac0-da7ba43c145f.jpg)

Thanks!

**Comment by jackyzy823** [comment]
Which instance did you use and can you provide the instance info from bottom of the  page: `https://<instance>/about`.

There's a similar issue #680 and it was fixed in #683.

**Comment by sha-e-256** [comment]
> Which instance did you use and can you provide the instance info from bottom of the  page: `https://<instance>/about`.
> 
> There's a similar issue #680 and it was fixed in #683.
> 

Hey! Thanks for the reply. 
I am seeing this issue on the nitter.net instance. I also use the nitter.ca instance, but I don't see the issue there.
Here's the instance info for both nitter.net and nitter.ca (they are the same version): [Version 2022.09.21-2ac3afa](https://github.com/zedeus/nitter/commit/2ac3afa)

I am using the Firefox vanilla app which is version 107.1.0 (Build #2015915067) which was released on November 10, 2022 (that's the most recent version).

**Comment by jackyzy823** [comment]
It seem that `nitter.net` 's css file is not updated to the fixed version (maybe due to cache issue causing by not-updated `?v` parameter in stylesheet url `/css/style.css?v=`).

**Comment by zedeus** [comment]
Please check again

**Comment by sha-e-256** [comment]
> Please check again

Pause button is now accessible on the nitter.net instance. Thanks!
