### ISSUE TITLE
Support for Twitter's old API may be deprecated soon?

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [zedeus/nitter#730]
https://twitter.com/elonmusk/status/1594076600701579264

>Notes from last night:  
>- Maybe deprecate TLS[-API] this week, as only needed if Android app >1 year old.

The deprecation would be in favor of what's listed as GraphQL, so I *think* the API is the one used by nitter. I might be wrong, though, maybe it's some other API. Since the listed timeframe is "this week" and Musk seems to be trying to save money, removal might be rapid and I figured it'd be better to report it.

**Comment by zedeus** [comment]
Nitter only uses GraphQL for a handful of things, so it would indeed break if they shut the APIs down.

**Comment by lazyteddy** [comment]
Has it been shut down? On every profile I look at, I get the profile info, but no tweets - only "No items found". Only if somebody has a pinned tweet, that will show up.

I first noticed that this morning (CET).

**Comment by zedeus** [comment]
No, just more bot swarms causing rate limits.

**Comment by lazyteddy** [comment]
> No, just more bot swarms causing rate limits.

Ah, ok. Thanks.

**Comment by Trit34** [comment]
[Both APIs v1.1 and v2 will be shut down on 9 Feb](https://twitter.com/TwitterDev/status/1621026986784337922). Does it means that it will be the end for Nitter too?

In the worse case scenario, could scrapping like [Twint](https://github.com/twintproject/twint) did be a possible workaround?

**Comment by zedeus** [comment]
Probably not, we'll see.

**Comment by Trit34** [comment]
> **Probably not**, we'll see.

“Not” what: breaking Nitter or scrapping method? But you’re right: we’ll see. “He” can still change his mind like he already did, after all (though I have very little hope about that).

Anyway: thanks a lot for Nitter! It is (was?) a really convenient way to see tweets, even on outdated devices unable to connect to Twitter anymore, and for the RSS! o/

**Comment by zedeus** [comment]
Nitter doesn't use the APIs in the normal way with developer credentials, so I really doubt it would be affected.

**Comment by antibot4navalny** [comment]
Is it correct to assume Nitter was not affected by recent API- and related changes / limitations?

**Comment by Trit34** [comment]
> Is it correct to assume Nitter was not affected by recent API- and related changes / limitations?

Not really, since search was broken (no results for tweets, still working for users) for several days when search was set to logged in users only on Twitter. The only way to have search working was to use an instance with a login cookie set, like PrivacyDev’s, but it was quickly rate limited.

Nitter now relies on GraphQL to retrieve Twitter contents, so I think that it is actually more prone to be affected by upstream API changes (NSFW flagged contents are not shown anymore, for example, when they still were when Nitter used that non-public API key)..
