### ISSUE TITLE
Does Nitter support connecting to an IPV6 Redis Instance?

### ISSUE THREAD

**Issue by cubismod** [zedeus/nitter#731]
Hey there, I'm trying to setup Nitter on [fly.io](https://fly.io) which extensively uses IPV6 addresses and hostnames for resolution. I am deploying using the `zedeus/nitter` image on Docker which is then configured to connect to one of Fly's [managed Redis instances](https://fly.io/docs/reference/redis/) via a private IPV6 hostname and password.

However, each time I try to launch Nitter via Fly I get a message like: `Failed to connect to Redis.` I am able to connect to this instance via redis-cli while connected to Fly's VPN tunnel but found a couple of threads on their website indicating folks also had issues connecting their apps to Redis due to it using IPV6. Is there a limitation around IPV6 addresses with Redis?

Snippet of my `nitter.conf`:

```
[Cache]
listMinutes = 240  # how long to cache list info (not the tweets, so keep it high)
rssMinutes = 10  # how long to cache rss queries
redisHost = "REDACTED.upstash.io"  # Change to "nitter-redis" if using docker-compose
redisPort = 6379
redisPassword = "REDACTED"
redisConnections = 20  # connection pool size
redisMaxConnections = 30
```

**Comment by jackyzy823** [comment]
Maybe you should enable docker's ipv6 support first? (Ref:https://docs.docker.com/config/daemon/ipv6/)

**Comment by cubismod** [comment]
Actually, Fly doesn't run Docker containers. It just uses Docker as a way to package and run micro-VM images.

**Comment by jackyzy823** [comment]
Sorry for the wrong info.

After some digging , i found the library `redis` seems not support ipv6 properly.

You should do some modification to make ipv6 work.

Patch for https://github.com/zedeus/redis


```diff
diff --git a/src/redis.nim b/src/redis.nim
index eed0762..1e431d6 100644
--- a/src/redis.nim
+++ b/src/redis.nim
@@ -94,22 +94,18 @@ proc `$`*(cursor: RedisCursor): string =
 proc open*(host = "localhost", port = 6379.Port): Redis =
   ## Open a synchronous connection to a redis server.
   result = Redis(
-    socket: newSocket(buffered = true),
+    socket: net.dial(host, port),
     pipeline: newPipeline()
   )

-  result.socket.connect(host, port)
-
 proc openAsync*(host = "localhost", port = 6379.Port): Future[AsyncRedis] {.async.} =
   ## Open an asynchronous connection to a redis server.
   result = AsyncRedis(
-    socket: newAsyncSocket(buffered = true),
+    socket: await asyncnet.dial(host, port),
     pipeline: newPipeline(),
     sendQueue: initDeque[Future[void]]()
   )

-  await result.socket.connect(host, port)
-
 proc finaliseCommand(r: Redis | AsyncRedis) =
   when r is AsyncRedis:
     r.currentCommand = none(string)
```


you may apply this patch to ~/.nimble/pkgs/redis-\#d0a0e6f/redis.nim after the line `nimble install -y --depsOnly` in Dockerfile.

then edit conf's redisHost to ipv6 address (without square brackets)

**Comment by cubismod** [comment]
No worries! Thank you so much for digging into this @jackyzy823 , I will try these patches this evening after work
