### ISSUE TITLE
Some users can't be found. Intentional?

### ISSUE THREAD

**Issue by Andre601** [zedeus/nitter#732]
Was trying out Nitter and when I was searching my own username on Twitter was the page returning "No items found" for the "Users" tab.

Clicking the "Tweets" tab shows my tweets tho. And adding my name to the domain also displays the account without problems.

Is that a bug? Or is it perhaps an intentional behaviour for certain cases?
I'm not aware of my account being shadow-banned or something similar (Although I did reply to Elon Musk with a non-positive tweet so he might have become angry... idk).

So... tl;dr: Is it a bug that certain usernames won't show as a result in search, or is there something else behind all this?

**Comment by zedeus** [comment]
No filtering is done by Nitter
