### ISSUE TITLE
Host under sub-path / custom URL

### ISSUE THREAD

**Issue by piegamesde** [zedeus/nitter#733]
I know this may be a weird feature request given that doing so means that you can't just replace twitter.com with the instance host name, but I'd like to host my Nitter instance on a custom root path, like example.org/nitter.

The idea is that `twitter.com/user` becomes `example.org/nitter/user` everywhere.

**Comment by zedeus** [comment]
This is a task for your reverse proxy, along with adding /nitter to the host name in nitter's config.

**Comment by piegamesde** [comment]
Oh sorry, I should have mentioned that I tried that. When setting the hostname preference to `example.org/nitter` and configuring the reverse proxy accordingly I can reach the service, but all links within refer to `example.org/username` instead of `example.org/nitter/username` so they are broken.

**Comment by zedeus** [comment]
The links are relative, e.g. `/username`, so I'd expect a reverse proxy could be configured to handle it properly

**Comment by piegamesde** [comment]
Those are not "relative enough"; they are only relative to the domain. They would have to be `./username` for that to work.

There is the option of rewriting all links in the html output, but this would certainly be non-standard and way too brittle

**Comment by piegamesde** [comment]
After doing a lot more research and trying to get this to work I conclude that it is not possible to achieve it in the reverse proxy without help from the application. Thus, please consider reopening this issue.

**Comment by jackyzy823** [comment]
it's not easy to host nitter under subpath , because `jester` (underlying http framework) do not support subpath .
so the only way is to rewrite everything.

Here's a reference nginx config. (not every path/route tested)
```nginx
 location /proxypath/ {
    # keep uri encoded for /pic/https%25%2f.... and /video/https%25%2f...
    rewrite ^ $request_uri;
    rewrite ^/proxypath/(.*) $1 break;
    return 400;

    proxy_pass   http://127.0.0.1:8080/$uri;
    # make saving prefs work
    proxy_redirect /(?!proxypath)/ /proxypath/;

    sub_filter_once off;
    sub_filter_types text/html text/css application/vnd.apple.mpegurl;
    # html/css
    sub_filter '"/' '"/proxypath/';
    sub_filter "'/" "'/proxypath/";
    # video m3u8
    sub_filter "/video/" "/proxypath/video/";

}
```

**Comment by GenocideStomper** [comment]
This works well enough.
For some reason the homepage under <domain>/proxypath/ doesn't work with a 500 Internal Server Error, and the error.log for nginx contains "the rewritten URI has a zero length".
But for anything outside of the homepage it works.

**Comment by jackyzy823** [comment]
Changing  `rewrite ^/proxypath/(.*) $1 break;` to `rewrite ^/proxypath(.*) $1 break;` may do the trick , but may also cause other unexpected issue.

**Comment by GenocideStomper** [comment]
Thanks for the quick reply, the change doesn't work for me. But no worries, I don't use the homepage much anyway.

**Comment by GenocideStomper** [comment]
Thanks for the quick reply and suggestion, however unfortunately it breaks everything with a 400 Bad Request error.

But I don't use the homepage, so the original comment from Nov 27th is good enough for me. I just wanted to let the next person that wants to use this know that the homepage doesn't work, because without the homepage I thought the whole thing didn't work during testing.
