### ISSUE TITLE
Docker doesn't work anymore since last update - libcrypto.so / nimDebug issue

### ISSUE THREAD

**Issue by eqniz** [zedeus/nitter#738]
> could not load: libcrypto.so(.1.1|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|.48|.47|.46|.45|.44|.43|.41|.39|.38|.10|)
> 
> (compile with -d:nimDebugDlOpen for more information)

Is this gonna be fixed soon? I use the pre-compiled Docker image. 

greetings

**Comment by Joshndroid** [comment]
I can confirm on Unraid my docker is now broken and just crashes... I can't even get to logs as it just crashes out :(

**Comment by Joshndroid** [comment]
i rolled back to the 8 day ago release and all is well again... will wait until there is a fix to move back to latest releases.

**Comment by IrIougER** [comment]
Got the same issue.

**Comment by jackyzy823** [comment]
possibly related to https://github.com/zedeus/nitter/issues/720
the builder's nim is 1.6.3 which do not support openssl3 , the runtime(alpine:latest) has openssl3  . https://alpinelinux.org/posts/Alpine-3.17.0-released.html

so @zedeus we should update Dockerfile's nim builder version.

**Comment by zedeus** [comment]
Fixed
