### ISSUE TITLE
Down

### ISSUE THREAD

**Issue by stopmotio** [zedeus/nitter#740]
Nitter has become mostly nonfunctional within the past few hours.

**Comment by zedeus** [comment]
nitter.net was hit by a large bot attack which has caused weird rate limiting. Please use another instance.

**Comment by stopmotio** [comment]
Thank you so much, sorry for the false alarm. I thought it might have something to do with the potential API deprecation and decided to make sure you were aware to be safe.

**Comment by zedeus** [comment]
Seems back to normal now

**Comment by stopmotio** [comment]
Thanks man
