### ISSUE TITLE
ETIMEOUT error while scraping the data

### ISSUE THREAD

**Issue by bigansh** [zedeus/nitter#741]
Hey, so we are building an app that scraped older Twitter threads. While the scraping for the thread was working fine on the local machine, when hosted, I was getting ETIMEOUT error. What is the reason? Also, please let me know if it isn't allowed & if it isn't, do let me know a better way to achieve the same end goal. Thank you.

**Comment by zedeus** [comment]
Thats because my nginx rate limit is functioning as intended. Please do not scrape nitter.net, host your own instance locally instead. You can spin an instance up in a few seconds if you have docker installed, along with default Redis (see also the docker-compose file).
