### ISSUE TITLE
Tweets not found (examples included)

### ISSUE THREAD

**Issue by oonamistwalker** [zedeus/nitter#745]
https://nitter.net/KyivIndependent/status/1601290246880055296?t=Yy0FAaO12Ptl7eWwIftw6A&s=19

https://nitter.net/EraMertyn/status/1601303276661903361?t=jHa2C2nU-aQtHhULkj5nMg&s=19

https://nitter.net/Angry_Staffer/status/1601405470958563330?t=Iga1e7CsjDDh-GhNtDrS0Q&s=19

What's up? Been running into this for days.

**Comment by NormanJS** [comment]
I can confirm this, only pinned tweets are visible in profiles,all other tweets are gone.
