### ISSUE TITLE
How to check what my instance receive from twitter?

### ISSUE THREAD

**Issue by Latrolage** [zedeus/nitter#746]
My twitter instance always seems to give "no items found" on some users so I was wondering if there is a quick cURL command I can run on my server to see if my server is receiving any errors. 

Because the docker container logs don't have anything useful. They just say, "Connected to redis" and just stop after that

My instance seems to have trouble with users who have their posts set to "sensitive" or whatever twitter's nsfw setting is called

**Comment by zedeus** [comment]
In some countries, Twitter requires you to login to be able to see sensitive content. Unfortunately this also affects the API if requests are made from those countries. I don't know the full list, but Germany and Sweden are on it.

**Comment by danielegobbetti** [comment]
I'm a long time nitter user and all of a sudden the multiple users combined timelines do not work anymore "No items found".

Just to be clear these work:
- https://my.instance/elonmusk
- https://my.instance/twitter

This doesn't work:
- https://my.instance/elonmusk,twitter

I should probably open a new issue for the specific issue, but I'm also interested in the topic of checking what twitter is actually providing to my instance for helping in debugging.

**Comment by zedeus** [comment]
@danielegobbetti another user reported something similar but said the issue went away by itself. The multi-user timeline feature uses Twitter's search with a special query to get content from the listed users, so it was likely just a temporary issue on Twitter's side.

**Comment by zedeus** [comment]
Closed since @Latrolage never gave more information and it's likely to be caused by sensitive content being unavailable without authenticating in the server's location.

**Comment by danielegobbetti** [comment]
For completeness sake, I dug a bit deeper.

To OP: In order to see the request made to twitter you could head over to ``src/api.nim`` and add ``echo url`` in the appropriate place(s), then rebuild nitter. For instance here for the search request:

```
diff --git a/src/api.nim b/src/api.nim
index dfcf413..1e69358 100644
--- a/src/api.nim
+++ b/src/api.nim
@@ -95,6 +95,7 @@ proc getSearch*[T](query: Query; after=""): Future[Result[T]] {.async.} =
     return Result[T](beginning: true, query: query)
 
   let url = search ? genParams(searchParams & @[("q", q), searchMode], after)
+  echo url
   try:
     result = parse(await fetchFunc(url, Api.search), after)
     result.query = query
```

@zedeus as per above, I then performed the same call from my home PC and from the VPS where nitter is running, and while I am getting some content from home, the reply on the VPS is as follows:
```
{"errors":[{"message":"Sorry, that page does not exist","code":34}]}
```
Getting single users' timelines still works.
