### ISSUE TITLE
RSS feeds all 404 as of 2022-12-16 20:35 UTC

### ISSUE THREAD

**Issue by molo1134** [zedeus/nitter#747]
Example:  https://nitter.net/nim_lang/rss

> User "nim_lang" not found

This happens on any user ID I've tried.

This looks like a regression, as I was successfully reading feeds before 2022-12-16 20:35 UTC.

Thank you for nitter.

**Comment by zedeus** [comment]
Bot attack, it'll be back eventually.

**Comment by markcellus** [comment]
@molo1134 openrss has RSS feeds available for twitter as an alternative: https://openrss.org/twitter.com/nim_lang
