### ISSUE TITLE
Show only first tweet in a thread?

### ISSUE THREAD

**Issue by highroller** [zedeus/nitter#748]
Some Twitter threads have 10+ tweets, and it takes up the whole page. Is there a nitter url parameter or setting that force it always show only first tweet of a thread and hide the rest?  I need it to work in nitter rss too

**Comment by zedeus** [comment]
No, sounds useless. You could add /embed I guess.

**Comment by highroller** [comment]
> No, sounds useless. You could add /embed I guess.

I am not trying to embed other people's thread. I am reading other people's threads in rss. It's really confusing when some threads have 10+ tweets, and each tweet is its own rss post. It's much simpler if rss shows only first post and hide the rest, I will click the URL to read the rest of necessary.

**Comment by zedeus** [comment]
Doesn't matter if you're actually embedding, it's an efficient and simple way to just view the main tweet.
