### ISSUE TITLE
Nitter wont compile on arm64 / nim latest version

### ISSUE THREAD

**Issue by ghost** [zedeus/nitter#750]
`sadler32_simd.nim.c:525:32: error: incompatible types when assigning to type uint8x8_t from type uint32x2_t
sadler32_simd.nim.c:526:32: error: incompatible types when assigning to type uint8x8_t from type uint32x2_t
sadler32_simd.nim.c:527:42: error: incompatible type for argument 1 of vpadd_u32
Tip: 37 messages have been suppressed, use --verbose to show them.
Error: Build failed for package: nitter
`

Nim Compiler Version 1.6.10 [Linux: arm64]
Compiled at 2022-12-21
Copyright (c) 2006-2021 by Andreas Rumpf
active boot switches: -d:release
RHEL  9.1 aarch64 latest nitter compiled from src.

**Comment by zedeus** [comment]
Fixed
