### ISSUE TITLE
New Public Instance - https://nitter.lunar.icu/

### ISSUE THREAD

**Issue by MaximilianGT500** [zedeus/nitter#752]
Hello, can you add my Instance?

**Comment by shruuub** [comment]
You can simply edit [the wiki](https://github.com/zedeus/nitter/wiki/Instances). Your instance currently seems to be listed under [discontinued](https://github.com/zedeus/nitter/wiki/Instances#discontinued), you'd want to remove that.

**Comment by MaximilianGT500** [comment]
Okay, I added it, thanks!
