### ISSUE TITLE
Unavailable tweet

### ISSUE THREAD

**Issue by Arsenal4904** [zedeus/nitter#760]
I would like to know reasons why a tweet is unavailable. I can often see it on twitter.com, after I go past its filters, but not on Nitter. It would be helpful to find out why.

**Comment by zedeus** [comment]
This is the third time you have opened a duplicate issue about the same thing. I am banning you from the project.

**Comment by Arsenal4904** [comment]
Test

**Comment by ArsenaI4904** [comment]
> This is the third time you have opened a duplicate issue about the same thing. I am banning you from the project.

Good thing I made a new account LOLOLOLOL. And if you ban me I'll still keep making new accounts. Dick

**Comment by ArsenaI4904** [comment]
FREEDOM!!!!!!!!!!!!

**Comment by ArsenaI4904** [comment]
Again, ban me and I'll delete this account and make Arsenal4905.

**Comment by ArsenaI4904** [comment]
> This is the third time you have opened a duplicate issue about the same thing. I am banning you from the project.

Good thing I made a new account.

**Comment by ArsenaI4904** [comment]
Ban me all you want, I got new accounts to create. Hahahahahahahaha!

**Comment by ArsenaI4904** [comment]
> This is the third time you have opened a duplicate issue about the same thing. I am banning you from the project.

Good thing I made a new account. LOL

**Comment by zedeus** [comment]
What's your problem?
