### ISSUE TITLE
Remove Bibliogram

### ISSUE THREAD

**Issue by throwaway-d** [zedeus/nitter#761]
Bibliogram is discontinued.

https://cadence.moe/blog/2022-09-01-discontinuing-bibliogram

**Comment by PeterDaveHello** [comment]
There are some alternatives that listed here may be worthy to take a llok : https://github.com/libredirect/libredirect/issues/573 (by [snocodile](https://github.com/snocodile))

- [Imginn](https://imginn.com/)
- [GreatFon](https://greatfon.com/)
- [Dumpor](https://dumpor.com/)
- [Pixwox](https://pixwox.com/)
- [Gramhir](https://gramhir.com/)
- [StoriesIG](https://storiesig.app/)

**Comment by markcellus** [comment]
None of the alternatives appear to work either. Going to any page shows no Instagram data. Aren't they supposed to be working alternatives?

**Comment by throwaway-d** [comment]
> * [Imginn](https://imginn.com/)
> * [GreatFon](https://greatfon.com/)
> * [Dumpor](https://dumpor.com/)
> * [Pixwox](https://pixwox.com/)
> * [Gramhir](https://gramhir.com/)
> * [StoriesIG](https://storiesig.app/)

They aren’t open-source, self-hostable.

**Comment by PeterDaveHello** [comment]
Haven't try them myself yet because I don't use Instagram, but will test them once we would like to integrate any of them.
