### ISSUE TITLE
nitter.at is linking to nitter.net in RSS feeds

### ISSUE THREAD

**Issue by sojusnik** [zedeus/nitter#765]
If you create an RSS feed through nitter.at, the URL will still link to nitter.net, see f.i. https://nitter.at/excalidraw/rss

Can the maintainer of this instance change the URL in RSS feeds to nitter.at as well, please?

**Comment by austinhuang0131** [comment]
@lnm98 since you're the one who added the instance to the wiki?

**Comment by lnm98** [comment]
Thank you for the report @austinhuang0131 @sojusnik, should be fixed now!
