### ISSUE TITLE
Images return 404 if proxy enabled

### ISSUE THREAD

**Issue by coolsantino** [zedeus/nitter#766]
Docker:latest

All images return 404, if proxy enabled, all other stuff loads normaly.

**Comment by twiclo** [comment]
How did you fix this?

**Comment by coolsantino** [comment]
> How did you fix this?

switched from proxy to vpn for outgoing traffic.

**Comment by twiclo** [comment]
So are reverse proxies just broken?

**Comment by coolsantino** [comment]
> So are reverse proxies just broken?

Not reverse, i had issue with upstream proxy.
