### ISSUE TITLE
Get number of Followers/Following?

### ISSUE THREAD

**Issue by shtefcs** [zedeus/nitter#777]
Hey @zedeus hope you are well.

Previously we used this `https://cdn.syndication.twimg.com/widgets/followbutton/info.json?screen_names=shtefcs` to get a number of followers for a specific account. They disabled it a few days ago, so do you have a simple alternative to this?

**Comment by zedeus** [comment]
Hello, sorry about the delay. You can use the old endpoints https://api.twitter.com/1.1/users/lookup.json and https://api.twitter.com/1.1/users/show.json with a guest token. Both take a `screen_name` query, but lookup.json supports fetching multiple users at a time, e.g. `screen_name=elonmusk,nasa`. From there you just grab the followers_count and friends_count ("following") values. If using show.json, you can add `skip_status=1` to exclude the user's latest tweet. 

Alternatively you can use the newer GraphQL endpoint UserByScreenName, also with a guest token, more info here: https://github.com/fa0311/TwitterInternalAPIDocument/blob/master/docs/markdown/GraphQL.md#userbyscreenname
Note the variables query parameter here is: `{"screen_name":"username"}`

**Comment by shtefcs** [comment]
> Hello, sorry about the delay. You can use the old endpoints https://api.twitter.com/1.1/users/lookup.json and https://api.twitter.com/1.1/users/show.json with a guest token. Both take a `screen_name` query, but lookup.json supports fetching multiple users at a time, e.g. `screen_name=elonmusk,nasa`. From there you just grab the followers_count and friends_count ("following") values. If using show.json, you can add `skip_status=1` to exclude the user's latest tweet.
> 
> Alternatively you can use the newer GraphQL endpoint UserByScreenName, also with a guest token, more info here: https://github.com/fa0311/TwitterInternalAPIDocument/blob/master/docs/markdown/GraphQL.md#userbyscreenname Note the variables query parameter here is: `{"screen_name":"username"}`

Thank you!
