### ISSUE TITLE
Latest builds are not reading configuration properly

### ISSUE THREAD

**Issue by mostfunkyduck** [zedeus/nitter#778]
I am running on ARM using builds from https://quay.io/repository/unixfox/nitter.

As of build build-20230119, the container fails to start with:
```
Starting Nitter at http://nitter.net
Failed to connect to Redis.
```
Note that it is using `http://nitter.net` instead of my server's hostname, which is configured in the nitter.conf I deploy to the server.

I confirmed that the container is starting with my nitter.conf in place and that the running process has permissions to view it.

After rolling back to build `build-20221119`, everything works again. As of this writing, all subsequent builds are not functioning.

I can't test/verify on other architectures right now, but this feels like a code problem vs. a system problem, so I thought I'd bring it to your attention.

**Comment by zedeus** [comment]
@unixfox did you make any changes?

**Comment by unixfox** [comment]
Relevant discussion: https://github.com/unixfox/periodic-build-with-github-actions/issues/10#issuecomment-1398307200

The environment variables have changed, please see https://github.com/goodtiding5/nitter/blob/master/src/config.nim?rgh-link-date=2023-01-20T12%3A35%3A12Z#L25

I'm using the work from this person for the environment variables, so I'm dependent on their changes: https://github.com/goodtiding5/docker-nitter

----

I have been thinking of creating a separate official docker image just for ARM. And I would be really pleased if we could integrate the ability to set the configuration through the environment variables like this person did: https://github.com/zedeus/nitter/compare/master...goodtiding5:nitter:master

Would you be favorable of these new changes in the nitter repository @zedeus?

**Comment by HowellBP** [comment]
Also, don't use quotes in environment variables, the new config interprets quotes literally. I.E. `CACHE_REDIST_HOST="nitter-redis"` is NOT the same as `CACHE_REDIS_HOST=nitter-redis`.

**Comment by unixfox** [comment]
@zedeus you can close this issue as now it is recommended to use the official docker image: https://github.com/zedeus/nitter/pull/799
