### ISSUE TITLE
Pictures often don't load

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [zedeus/nitter#779]
E.g. https://nitter.cz/elonmusk/status/1616955534879645696#m, the profile pictures, also the tweet pictures simply don't load:
![image](https://user-images.githubusercontent.com/9642545/213936041-e20c4e37-49eb-47d3-9924-4ad0db759951.png)

E.g. https://nitter.cz/pic/profile_images%2F1495778916560166913%2FkdNI539s_bigger.jpg says "Page not found". _Sometimes_ the pictures load, sometimes they don't (seems random to me).

I tried multiple browsers, as well as phone/vs pc.

**Comment by IgorArnaut** [comment]
This is per instance. You should find an instance that works for you.

**Comment by WhyINeedToFillUsername** [comment]
so not "nitter.cz", but another instance, e.g. https://nitter.net?

**Comment by zedeus** [comment]
I don't run nitter.cz and this doesn't seem to be an issue with other instances, closing.
