### ISSUE TITLE
nitter.net/about broken commit link

### ISSUE THREAD

**Issue by CorruptCommit** [zedeus/nitter#78]
Currently, [nitter.net/about][0] contains a broken commit link. 

recreated in markdown:
### Instance info
Commit [f27d5d2][1]

screenshot:
![broken](https://user-images.githubusercontent.com/26208843/66864176-0def0300-ef84-11e9-89dd-7f565aacc5ec.png)

There is no `f27d5d2` commit in this repository. 

[0]: https://nitter.net/about
[1]: https://github.com/zedeus/nitter/commit/f27d5d2

**Comment by Perflyst** [comment]
Maybe zedeus just tests unpublished  things on nitter.net ;)

**Comment by zedeus** [comment]
Sorry, got sidetracked, it's pushed now
