### ISSUE TITLE
How can a single instance serve many clients and not get rate limited?

### ISSUE THREAD

**Issue by dan1338** [zedeus/nitter#782]
From my arguably limited understanding of this project (#706), I'm lead to believe all traffic that normally would be sent from the client browser to twitter, has to go through nitter which only then communicates with the public twitter API on behalf of the user.

If that is in fact the case, how come this service can even function when more than one person is actively using it?

From my experience the guest twitter API is not entirely ratelimit-less, and even with modest intervals (on the order of 10s of seconds) between requests I sometimes would still trip some limit on my token, when making no more than 40 reqs in total.

**So, as per the title of this issue, _how does nitter avoid this happening to a single instance?_**

At this point my motivation behind writing this is a little blurry, but there is one conclusion that I'm sure of and it leads my to ask,
Why isn't nitter an entirely in-browser addon?
That would surely help the (_nonexistent?_) problem by making each user do their own requests?

**Comment by zedeus** [comment]
If Nitter was just an addon, it wouldn't be able to mask the user's IP address, and serving a custom UI would be difficult. It would also be impossible to easily visit on any device with a web browser, not even requiring JavaScript.

Nitter employs several tricks to carefully use the APIs available without hitting rate limits. The endpoints used to retrieve timelines and tweets are hitting rate limits now though, but they will be replaced with ones that avoid that problem when I get around to it.

How? You'll have to try to understand the code, or you can join the Matrix server where I can give a brief explanation.

**Comment by dan1338** [comment]
I've consulted the source a few times but for the most part reading nim gives me a headache, it feels like reading a json :p

Thank for the outline though, it's reassuring to know that some of that is indeed a problem.

I'll join the matrix and ask a few questions in some time if you don't mind.
