### ISSUE TITLE
Will the new Twitter API policy impact Nitter?

### ISSUE THREAD

**Issue by Tiv0w** [zedeus/nitter#783]
Twitter Dev account tweeted today that there will soon be no free access API anymore: https://nitter.net/TwitterDev/status/1621026986784337922#m

My school project is heavily reliant on Twitter (it's a requirement from the school), and deprecating the free access, I'm seeking alternatives. And one possibility would be to host my own Nitter instance and scrape it after (if the project still functions given this new Twitter information).

So I'm asking this to know if I should invest dev time into scraping my own Nitter instance or if I'm better off waiting for more news?
Thanks in advance for the reply.

(And thanks for Nitter, I only consume Twitter through Nitter instances for my personal entertainment.)

**Comment by zedeus** [comment]
It's very unlikely Nitter will be affected since the APIs aren't used in the official way with developer credentials. I'm slowly moving stuff to use their newer GraphQL APIs anyway, so if it breaks it'll be fixed soon-ish.

**Comment by BartTerpstra** [comment]
@halictuz 
the "Developer Agreement", last modified 23 januari 2023, does contain the following clause.

"II. Restrictions on Use of Licensed Materials
A. Reverse Engineering and other Restrictions:
You will not or attempt to (and will not allow others to) [...]
 c) use or access the Licensed Materials to create or attempt to create a substitute or similar service or product to the Twitter Applications; "
 
so :shrug:

**Comment by zedeus** [comment]
I'm not bound by that developer agreement, so whatevs.

**Comment by zedeus** [comment]
@jman-schief It's not a real GraphQL API, it's really just an RPC-like API on a /graphql/ route, so the implementation isn't quite as complex.

**Comment by jcmag** [comment]
some news : https://twitter.com/TwitterDev/status/1641222782594990080
(what a joke...)

**Comment by jadedgnome** [comment]
as of 2 hours ago, nitter no longer displays NSFW media unless you click the search option but don't actually search.

**Comment by UmBottesWillen** [comment]
Apart from the issue mentioned above, I also noticed that instances other than the official `nitter.net` instance, even up-to-date ones, will sometimes error out when trying to access pages of NSFW accounts. This issue is not guaranteed to occur, but it happens regularly enough since the announced Twitter API change.
Only the following message will be displayed:

```
Tab title: Jester route exception

An error has occured in one of your routes.

Detail: fatal.nim(53) sysFatal
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
index 0 not in 1 .. 12
```

**Comment by zedeus** [comment]
This will be fixed by #812 which I will merge soon. Twitter just banned unauthenticated access to the endpoint used for search, so I'm replacing it in that PR as well.

**Comment by sawtoothpuma** [comment]
Any updates yet? I want to view age restricted content but don't want to create an account to do so.

**Comment by Trit34** [comment]
> Any updates yet? I want to view age restricted content but don't want to create an account to do so.

Use [PrivacyDev’s instance](https://nitter.privacydev.net/), then. But beware of the rate limit!

**Comment by innov8tor3** [comment]
@zedeus , first up thanks for Nitter.

I notice the Twitter Nitter account is now blocked.

I love the idea of Nitter instances on GitHub, is there a way to map all the instances, so folk can navigate if they need to?

And apologies, I don't properly understand Github. It would be great if the answer is here, but I am effectively wearing a blindfold, and would need very simple instruction, if possible.

Thanks again.

**Comment by zedeus** [comment]
@innov8tor3 

> I notice the Twitter Nitter account is now blocked.

What account? There is no account for Nitter.
Here's a list of instances: https://github.com/zedeus/nitter/wiki/Instances

**Comment by zedeus** [comment]
The answer was no, thankfully.
