### ISSUE TITLE
All media is broken on new installation

### ISSUE THREAD

**Issue by twiclo** [zedeus/nitter#784]
This is a new manual installation built from source. All images and videos are 404ing. I see no errors when running `./nitter`. I'm running it through an apache reverse proxy. Let me know what other info you need

**Comment by twiclo** [comment]
I just tried putting my full URL with the https:// in the `proxy` section of the config file. When I did that my output looked like this
```
[tokens] fetching token failed: The proxy server rejected a CONNECT request, so a secure connection could not be established.
[tokens] fetching tokens paused, resuming in 30 minutes
[tokens] fetching token failed: The proxy server rejected a CONNECT request, so a secure connection could not be established.
[tokens] fetching tokens paused, resuming in 30 minutes
[tokens] fetching token failed: The proxy server rejected a CONNECT request, so a secure connection could not be established.
[tokens] fetching tokens paused, resuming in 30 minutes
[tokens] fetching token failed: The proxy server rejected a CONNECT request, so a secure connection could not be established.
[tokens] fetching tokens paused, resuming in 30 minutes
```

**Comment by jackyzy823** [comment]
the `proxy` is used in this situation  **your instance <-> proxy <-> twitter** , you misunderstand it.

> This is a new manual installation built from source. All images and videos are 404ing. I see no errors when running `./nitter`. I'm running it through an apache reverse proxy. Let me know what other info you need

This might be related to URL encoding problem when reverse proxying.

This might help https://github.com/zedeus/nitter/issues/376#issuecomment-1002529974

You could try this
> Use base64Media=true in nitter.conf will mitigate this issue.

**Comment by twiclo** [comment]
So what should go in my proxy field? Nothing?

**Comment by jackyzy823** [comment]
Yes, unless your instance has network issue with twitter server.

**Comment by twiclo** [comment]
Setting `base64Media` to `true` and leaving `proxy` empty resolved the issue
