### ISSUE TITLE
Is the viewing of Twitter lists supported?

### ISSUE THREAD

**Issue by pgroce** [zedeus/nitter#786]
Thanks for all the work you’ve put into Nitter! 

From #155:

> Another way to do this already is to create a Twitter list of all the accounts you follow, then access it like this: https://nitter.net/username/lists/list (eg. https://nitter.net/NASA/lists/astronauts). Then enable infinite scrolling in the preferences menu, and it should be a decent experience.

When I do this with a public list I’ve created (size: 16 members), I get “Unsupported Feature: Nitter doesn't support this feature yet, but it might in the future.…”

Is this a regression?

**Comment by jackyzy823** [comment]
Viewing Twitter `List`'s content is supported. Url like `/<screen_name>/lists/<slug_name>` or `/i/lists/<list_id>`

Viewing a list of Twitter `List` is not supported yet. Url like `/<screen_name>/lists`

**Comment by pgroce** [comment]
Thanks very much for your response. Trying this on nitter.net, The `/i/lists/<list_id>` syntax appears to be working for me. 

The `/<screen_name>/lists/<slug_name>` is causing me problems; perhaps I don't understand what a slug is. It seems to be related to the title of a list, but using the name for the slug (e.g., `/PhilGroce/lists/ukraine`) returns `List "<name>" not found`. I have found another, older list, (`/i/lists/1111706722958217217` aka `/emptywheel/lists/brexit`) that seems to work as described above.

I will also note that an older [YouTube video](https://www.youtube.com/watch?v=OiSqUzbpLsE) describing how to find a Twitter list demonstrates an older API in which Twitter itself links to the list from `<screen_name>/lists` using the slug. Reproducing those steps on the modern Twitter website produces an ID link.

Is it possible that Twitter lists created after this change may not have a slug, and therefore may not be able to be referenced in this format?

The ID syntax above is sufficient for my use case, but if it's true that some lists can't be accessed by slug, that may be helpful for you to know.

At any rate, I can access the lists I wanted now, so thanks again for your help.

**Comment by zedeus** [comment]
That's very possible, I'm not aware of any internal changes. Are you saying that the API returns a link where the "slug" is the same as the numerical ID for your new list?

**Comment by pgroce** [comment]
I'm saying that when one visits the Twitter in a browser and clicks on a list from a users "Lists" page, it returns the ID URL for the individual list page.  For example, going to https://twitter.com/PhilGroce/lists and selecting the "Ukraine" list resolves to the by-ID page for the list, https://twitter.com/i/lists/1499399753099997188. 

I haven't tested anything with the Twitter API. 

So Twitter doesn't seem to be using the slug in their web client anymore. I can't speak for their other products, but it's possible they quietly deprecated it at some point, and retained the "slug" API for lists created pre-deprecation so older links work.

**Comment by jackyzy823** [comment]
slug is not the same as title. See explanation in https://github.com/zedeus/nitter/pull/445

according to my observation there's no slug in twitter lists API response now.

So maybe they keep /<screen_name>/lists/<slug_name> for backward compatibility and redirect it to /i/lists/<list_id> which is the same as nitter.

**Comment by robindz** [comment]
@zedeus Is it possible to add some extra data to retweets in a list so you can tell who has retweeted a tweet? As far as I know it currently only shows the retweeters' nickname, not their screenname or id, which is not unique. Like for example, on Twitter's site you can click on the "♲ <nickname> retweeted" text in the tweet header to go to that user's profile.

**Comment by zedeus** [comment]
@robindz yes, it has long been on my todo list to make the retweeted text clickable to visit their profile
