### ISSUE TITLE
Tweets not updating after first viewing on an instance

### ISSUE THREAD

**Issue by roryyamm** [zedeus/nitter#788]
I'm using the nitter.1d4.us instance in this case. When I read a tweet for the first time, it shows the tweet and any replies that are there, which is to be expected. What's not to be expected is that, when you click on the tweet hours later, you are served exactly what you saw the first time. This happens in incognito mode and on other devices - even on my phone, I get the same page I saw hours ago on my computer. If you want to see additional replies to the tweet, you have to go to Twitter itself, which defeats the entire purpose of Nitter. 

For instance, this is an image taken at 6:58:31 EST, showing a tweet with 5 replies posted about two hours ago. This is on the user's main page.
![Screenshot From_2023-02-06 185831](https://user-images.githubusercontent.com/24758288/217116770-819c954d-f556-4b13-9971-cf69e1d6d580.png)
This image of the individual tweet taken 9 seconds later, however, shows the same tweet only having a single reply - and having been posted 4 minutes ago. This is because I first saw it approximately 4 minutes after it was tweeted. Since I appear to be the first, if not the only one, using this Nitter instance to view this tweet, it seems as though I froze this tweet on this instance at this specific point in time. 
![Screenshot From_2023-02-06 185839](https://user-images.githubusercontent.com/24758288/217116855-3653f333-9abe-4531-87fe-110f292705a0.png)

This same issue also happens on other instances - although the status of the tweet there is dependent on the time a tweet is viewed for the first time on that instance. It also occurs when viewing replies of tweets, where the same sort of snapshotting occurs for the state of the replied-to tweet. You can have the age of a tweet rapidly change just by clicking on different replies first viewed at different times.
For those who honestly wish to read replies, or see the result of a poll, it's annoying to have tweets be frozen in amber like this. That it persists across different devices makes me think it's a server-side issue and not a client-side one. Is there some kind of caching system for Nitter tweets, and if so, would it be possible to have it periodically re-fetch a tweet?

**Comment by zedeus** [comment]
Tweets are not cached, so this doesn't make sense. I'll have to look into it.

**Comment by jackyzy823** [comment]
It is server side's cache , maybe due to CDN or reverse proxy.

You can see the response header contains "x-cache-status:HIT" . The "nitter.1d4.us" is a CNAME of "glb.1d4.us" , glb  obviously means global load balancer.

What nitter can do is to specifiy a header "Cache-Control" in response to control reverse proxy/CDN/browser's cache on what to cache and how long it should cache .

**Comment by zedeus** [comment]
This is instance-specific behavior, not a Nitter problem.
