### ISSUE TITLE
[Bug] Link loop with big tweets

### ISSUE THREAD

**Issue by allanf181** [zedeus/nitter#789]
https://twitter.com/wongmjane/status/1623010218002219008

Nitter shows a link to the tweet itself instead of the entire content.

**Comment by MrMetric** [comment]
Cheesus Crust, that's nasty. It froze my Chrome tab. Superior Firefox handled it pretty well, though.

**Comment by zedeus** [comment]
Another example: https://nitter.net/elonmusk/status/1624660886572126209

**Comment by zedeus** [comment]
Fixed
