### ISSUE TITLE
RSS Feed Update Frequency

### ISSUE THREAD

**Issue by net-tech** [zedeus/nitter#790]
How often/fast does Nitter update its RSS feeds? Additionally, does Nitter have any rate limits when fetching RSS feeds or some frequency of checking (e.g. every <1m) that is too frequent and may result in 404s?)

**Comment by zedeus** [comment]
This is dependent on the configured RSS cache time. The default is 15 minutes, which is likely used by most instances including nitter.net, but you can very easily host your own instance and lower the cache to 0 to always get a fresh feed.
There's no built-in rate limit, but nitter.net has a rate limit that prevents dozens of requests at the same time, spreading them out over time unless there's way too many. I forgot the numbers, but you get the gist.
