### ISSUE TITLE
image url format change?

### ISSUE THREAD

**Issue by GhbSmwc** [zedeus/nitter#791]
I noticed that image urls format are now different, for example::
https://nitter.1d4.us/pic/enc/bWVkaWEvRm94bUVPMlhvQWdQSjhnLmpwZz9uYW1lPXNtYWxs
used to be this:
https://nitter.1d4.us/pic/orig/media%2FFoxmEO2XoAgPJ8g.jpg

Why?

**Comment by jackyzy823** [comment]
https://github.com/zedeus/nitter/blob/36c72f98603e6387431224b3fb65ada765e9ab65/nitter.example.conf#L24

**Comment by zedeus** [comment]
This is instance-specific, the instance operator changed their Nitter config as showed by jackyzy.
