### ISSUE TITLE
Some retweets are getting truncated temporarily

### ISSUE THREAD

**Issue by nemobis** [zedeus/nitter#801]
https://nitter.lacontrevoie.fr/EIB/status/1630481119090036736#m (using version [2023.02.26-33e34c2](https://github.com/zedeus/nitter/commit/33e34c2)) was showing as

> RT [@shirinwheelerEU](https://nitter.lacontrevoie.fr/shirinwheelerEU): “The problem was not the loss of Russian gas , but our dependence on it “  [@TeresaCzerwnska](https://nitter.lacontrevoie.fr/TeresaCzerwnska)  [@EIB](https://nitter.lacontrevoie.fr/EIB)  Vice President tell…

![Screenshot_20230228_103259](https://user-images.githubusercontent.com/901528/221797675-4d944995-8b10-4e12-9856-0afb7a17e2d7.png)

https://nitter.cz/EIB/status/1630481119090036736#m (using version [2022.11.29-56d2b71](https://github.com/zedeus/nitter/commit/56d2b71)) showed the full text.

Upon refresh, https://nitter.lacontrevoie.fr/EIB is now showing the entire text. Maybe it was a temporary error on Twitter's side? If so it would be great if Nitter could detect that it received partial data, and warn the user about it.

**Comment by zedeus** [comment]
This was likely a bug on Twitter's side, not sure. Please reopen if you encounter it again.
