### ISSUE TITLE
Long tweets with 'read more' only show up with the part before the read-more

### ISSUE THREAD

**Issue by Jofkos** [zedeus/nitter#805]
Long tweets that go beyond the character limit have a 'read more' link on the twitter web client. In nitter, that 'read more' is just a link to the same post, and clicking on it does not reveal the full tweet.

**Comment by zedeus** [comment]
Where do you see this? An implementation of long/note tweets is in master and live on nitter.net already.

**Comment by Jofkos** [comment]
Apologies, I was under the impression the instance I was using was on the latest version. My bad. It does work on nitter.net – and after updating to the newest nitter.
