### ISSUE TITLE
Searching for tweets by latest

### ISSUE THREAD

**Issue by IgorArnaut** [zedeus/nitter#806]
Hello. I'd like to search for latest tweets (sorted by date) on Nitter, like on regular Twitter, but it seems that there is no feature yet.

**Comment by zedeus** [comment]
That is what's done by default. If you want to hide retweets, simply tick the Retweets option in the exclude section when performing a search.

**Comment by IgorArnaut** [comment]
> That is what's done by default. If you want to hide retweets, simply tick the Retweets option in the exclude section when performing a search.
No. I did not mean viewing tweets of an account. I meant getting search results sorted by time, like in this picture:
![image](https://user-images.githubusercontent.com/57326929/225891009-95a12f24-8d0f-4dca-b23d-a3d4ba016a2f.png)

**Comment by zedeus** [comment]
![image](https://user-images.githubusercontent.com/9434921/225899746-a4067e86-a44b-46f6-92cf-0cb245ad411e.png)

**Comment by IgorArnaut** [comment]
No. This is what I was talking about.
![image](https://github.com/user-attachments/assets/bd757c5c-a4d4-422e-8d2e-c604104b5a7b)
![image](https://github.com/user-attachments/assets/1ee4fa43-9216-47e4-93f2-acfcd730f877)
![image](https://github.com/user-attachments/assets/7ecc82a3-5942-4d66-b800-ef96d40e1f6d)
The results here ARE NOT SORTED BY DATE.

Also, if I filter by PERIOD, posts that are OUTSIDE of this period APPEAR TOO.

**Comment by IgorArnaut** [comment]
Has the issue been fixed yet?
