### ISSUE TITLE
Fallback images for wepb or get rid of it (even better)

### ISSUE THREAD

**Issue by Ileca** [zedeus/nitter#808]
Beyond the irony of using a format that strengthen the supremacy of a company notorious for violating the privacy of its users _on a project that is supposed to fight against that very same problem_ with twiter, webp is a nightmare given the lack of support.

That's why I enabled `image.webp.enabled = false` on Firefox. Thanks to that choice, I get to retain my sanity by having access to the regular pictures. And can't see any images on Nitter as of now...

Please revert that decision. If you don't want to, to save some octets, please put fallback images for people who can't/don't want to see webp shit.

Thank you very much.

**Comment by zedeus** [comment]
The irony here is you disabling support and complaining about it not working. I don't get your irrational hatred for a superior image compression format just because Google made it. It's exclusively used for thumbnails, so any images you may want to download will be in jpeg/png.

**Comment by Ileca** [comment]
My irrational hatred like you call it came from having to convert that format every fucking time I downloaded such a picture as no software I use handle it.
I disabled support on Firefox because it's the only way to be served universal formats as a fallback. Yes, fallback images for webp is the norm and the reason why I have the "gall" to complain here.
It might be used for thumbnails but I can't see such thumbnails (I for a moment didn't even know I was missing pictures) so I guess you expect me to search them in the developer tool like I should buy photoshop to be able to handle webp?

**Comment by WineAunt** [comment]
> Beyond the irony of using a format that strengthen the supremacy of a company notorious for violating the privacy of its users _on a project that is supposed to fight against that very same problem_ with twiter, webp is a nightmare given the lack of support.
> 
> That's why I enabled `image.webp.enabled = false` on Firefox. Thanks to that choice, I get to retain my sanity by having access to the regular pictures. And can't see any images on Nitter as of now...
> 
> Please revert that decision. If you don't want to, to save some octets, please put fallback images for people who can't/don't want to see webp shit.
> 
> Thank you very much.

Do you have an instance w/ these settings?
