### ISSUE TITLE
Trouble with ports and `getUrlPrefix`

### ISSUE THREAD

**Issue by isker** [zedeus/nitter#809]
The example configuration: https://github.com/zedeus/nitter/blob/bc219aa792cc0e4117888b2036a969559f4f2689/nitter.example.conf#L1-L8 sets a non-protocol-default port and does not include it in the hostname.  But the way `hostname` is used in `getUrlPrefix`: https://github.com/zedeus/nitter/blob/bc219aa792cc0e4117888b2036a969559f4f2689/src/formatters.nim#L30-L32 means that if a non-protocol-default port is set, URLs generated using that prefix, like in the RSS feeds, are incorrect.

Should `getUrlPrefix` include the configured port if it's not the protocol default port?  Or should the example config make clear that you have to re-specify the port in `hostname`, such that that config should have `hostname = "nitter.net:8080"`?

**Comment by zedeus** [comment]
It's intended to be hosted behind a reverse proxy, so the port shouldn't be the default http protocol. If it is something non-standard and you intend to access it directly, you need to add the port to hostname as well.
