### ISSUE TITLE
Plan from migrating away from dockerhub?

### ISSUE THREAD

**Issue by hydrargyrum** [zedeus/nitter#813]
Nitter's docker image is currently hosted on dockerhub, which has released a [new policy that might endanger your hosting there](https://blog.alexellis.io/docker-is-deleting-open-source-images/) ([see also](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)). Do you have any plans for migrating hosting elsewhere?

**Comment by zedeus** [comment]
I host it with a private account, not an organization, so this doesn't affect me. I have no plans as of now to switch. Only big alternative I see would be using GitHub's "packages" container repo feature, but I doubt that would make people cheer.

**Comment by hydrargyrum** [comment]
If you're not affected, then it's fine!
