### ISSUE TITLE
Nitter-plugin for wordpress

### ISSUE THREAD

**Issue by Stratoprutser** [zedeus/nitter#827]
Wouldn't it be nice if there would be drop in nitter replacement for [twitter embeds](https://github.com/SimonBrazell/privacy-redirect/issues/320#issuecomment-1013378326) in [Wordpress](https://wordpress.org/documentation/article/twitter-embed/)....

**Comment by nextgenthemes** [comment]
I made a WP plugin. https://github.com/nextgenthemes/nextgenthemes-nitter-embeds it has not yet been approved by wp.org but if you can try it already and let me know if it works correctly. I have made the decision to just scrape a instance for the HTML and ship css with the plugin, iframe does not work anyway and a web component would require JS.

So this way true to Nitter itself it works just without any JS.

**Comment by zedeus** [comment]
Added to the wiki, thanks @nextgenthemes!
