### ISSUE TITLE
18+/"sensitive" tweets no longer available

### ISSUE THREAD

**Issue by kaijudude** [zedeus/nitter#829]
Any 18+ Tweet that could be viewed before can't be any longer, did some update age restrict them? If so, then how do I switch it off?

**Comment by markcellus** [comment]
I believe this may not be due to a Nitter change. There's been a hange Twitter has made that places 18+ content behind an age verification check. Since there's no way they can verify that users (that consume content from their API) are of appropriate age, they just dont include them.

**Comment by kaijudude** [comment]
> I believe this may not be due to a Nitter change. There's been a change Twitter has made that places 18+ content behind an age verification check. Since there's no way they can verify that users (that consume content from their API) are of appropriate age, they just dont include them.
Well crap, that sucks. Hope they can find a way around it.

**Comment by gentlecolts** [comment]
> I believe this may not be due to a Nitter change. There's been a change Twitter has made that places 18+ content behind an age verification check. Since there's no way they can verify that users (that consume content from their API) are of appropriate age, they just dont include them.

I can't believe that that's entirely correct, I still see some thumbnailing services, such as vxtwitter, fxtwitter, still functioning in this case.  That said, I also note it started occurring on nitter.net itself a few days ago while it only seemingly just started hitting some mirror sites, so I suppose it's possible that it's a slow rollout, but it's still also possible these other sites are doing something that nitter isn't

**Comment by AlyoshaVasilieva** [comment]
IIRC based on some warnings I've seen when using yt-dpl plus other stuff:

* The new graphql API won't show 18+ tweets to guest users (aka nitter)
* the old api that's getting shut down does, but only in some regions

**Comment by crockpoot** [comment]
Will the workaround be added to the browser instances?

**Comment by ultrajae** [comment]
> IIRC based on some warnings I've seen when using yt-dlp plus other stuff:
> 
> * The new graphql API won't show 18+ tweets to guest users (aka nitter)
> * the old api that's getting shut down does, but only in some regions
> 
> Edit: nitter.net uses more graphql endpoints than most instances because it's running a dev version

Idk,. 
It seems like Twitter's API has changed

I haven't found one instance that works now. 
I tried many of those not updated.

**Comment by PrivacyDevel** [comment]
> > IIRC based on some warnings I've seen when using yt-dlp plus other stuff:
> > 
> > * The new graphql API won't show 18+ tweets to guest users (aka nitter)
> > * the old api that's getting shut down does, but only in some regions
> > 
> > Edit: nitter.net uses more graphql endpoints than most instances because it's running a dev version
> 
> Idk,. It seems like Twitter's API has changed
> 
> I haven't found one instance that works now. I tried many of those not updated.

That is definitely the case. I tried them all and a few unofficial ones. And some of the ones I tested have not been updated in months.

Mine has my workaround already applied and works tho.
nitter.privacydev.net

**Comment by roryyamm** [comment]
How does the workaround… work? Whose credentials are used?

**Comment by PrivacyDevel** [comment]
> How does the workaround… work? Whose credentials are used?

The administrator of the respective instance needs to create a Twitter account, sign in and then put their session information into Nitter's configuration file. This session information will then basically be shared for all users. It's the instance's Twitter account, if you will.

As an end user, you shouldn't need to do anything.

**Comment by roryyamm** [comment]
Won't that lead to severe rate limiting, though?

**Comment by PrivacyDevel** [comment]
> Won't that lead to severe rate limiting, though?

It seems like that does indeed happen sometimes. But for the most part it seems like it's actually working fairly well for my instance. But I am not yet aware of any other satisfying workaround for that problem. Forcing a user to login and get tracked is not really a satisfying solution for me.

I see the following general solutions for this problem, personally:

1. rate limit the end users to make it so that the instance works more reliably overall
2. create more accounts and make the server juggle between different accounts / sessions as needed
3. maybe try to cache things more aggressively
4. a combination of those options that I just listed

**Comment by crockpoot** [comment]
Luckily, the workaround works but it's unfortunately very slow.

**Comment by ultrajae** [comment]
indeed, slow. probably rate limited already I guess unfortunately.

I am waiting so far 5 minutes for a vid clip to play. gonna have to give up

At least the tweet comes up tho, 
A+ on effort

TYVM

**Comment by roryyamm** [comment]
>Forcing a user to login and get tracked is not really a satisfying solution for me.

What about a voluntary system - ask for a login to increase the rate limit, but fall back on a set account if no login is provided? 

I use Nitter mostly for its RSS feeds. Since I have a lot of NSFW accounts as feeds, some of whom tweet frequently, the frequency by which I ask for tweets is probably a major reason why the instance is so slow. If I could somehow pass my own credentials when fetching those RSS feeds, even if it meant I was tracked, I'd do it if that meant a faster or more reliable system with less caching for all.

 Perhaps users willing to forgo the non-tracking nature could put a query string at the end of the URL for the RSS feed, and the server could use those credentials instead of its own.

**Comment by PrivacyDevel** [comment]
> indeed, slow. probably rate limited already I guess unfortunately.
> 
> I am waiting so far 5 minutes for a vid clip to play. gonna have to give up
> 
> At least the tweet comes up tho, A+ on effort
> 
> TYVM

I just made it so that videos aren't proxied anymore by default to take some load of my poor server and to hopefully make Twitter not rate limit my instance as harshly.

And I also made it so that the request of userIds is  made without unauthenticated. Hopefully that makes it so the instance doesn't get rate limited as fast anymore as well.

**Comment by crockpoot** [comment]
> > Forcing a user to login and get tracked is not really a satisfying solution for me.
> 
> What about a voluntary system - ask for a login to increase the rate limit, but fall back on a set account if no login is provided?
> 
> I use Nitter mostly for its RSS feeds. Since I have a lot of NSFW accounts as feeds, some of whom tweet frequently, the frequency by which I ask for tweets is probably a major reason why the instance is so slow. If I could somehow pass my own credentials when fetching those RSS feeds, even if it meant I was tracked, I'd do it if that meant a faster or more reliable system with less caching for all.
> 
> Perhaps users willing to forgo the non-tracking nature could put a query string at the end of the URL for the RSS feed, containing the exact ct0, auth_token and csrf-token, and the server could use those credentials instead of its own if all are present.

A URL-based solution would work the best for my needs, if possible.

**Comment by ultrajae** [comment]
> > indeed, slow. probably rate limited already I guess unfortunately.
> > I am waiting so far 5 minutes for a vid clip to play. gonna have to give up
> > At least the tweet comes up tho, A+ on effort
> > TYVM
> 
> I just made it so that videos aren't proxied anymore by default on my server to take some load of my poor server, make it so that people can actually watch videos again on my instance and to hopefully make Twitter not rate limit my instance as harshly.
> 
> And I also made it so that the request of userIds is made without unauthenticated. Hopefully that makes it so the instance doesn't get rate limited as fast anymore as well.

Thanks for that

Now working flawlessly

Hopefully it can last but appreciate what you're doing nonetheless!

**Comment by jve-engineering** [comment]
The [search tab](https://nitter.net/TwitterAPI/search) still shows the complete feed. Could fetching this way be a workaround? However, it seems to depend on the region again, e.g. US works, DE does not.

**Comment by crockpoot** [comment]
> The [search tab](https://nitter.net/TwitterAPI/search) still shows the complete feed. Could fetching this way be a workaround? However, it seems to depend on the region again, e.g. US works, DE does not.

That bizarrely works (not with nitter.net but with other instances at least) lol thank you very much for this.

**Comment by PrivacyDevel** [comment]
> The [search tab](https://nitter.net/TwitterAPI/search) still shows the complete feed. Could fetching this way be a workaround? However, it seems to depend on the region again, e.g. US works, DE does not.

That's a great find! The only thing that's missing there is the pinned tweet.

**Comment by PrivacyDevel** [comment]
And threads and retweets unfortunately also don't show up properly in the search

**Comment by RepresentativeCry66** [comment]
> > > IIRC based on some warnings I've seen when using yt-dlp plus other stuff:
> > > 
> > > * The new graphql API won't show 18+ tweets to guest users (aka nitter)
> > > * the old api that's getting shut down does, but only in some regions
> > > 
> > > Edit: nitter.net uses more graphql endpoints than most instances because it's running a dev version
> > 
> > 
> > Idk,. It seems like Twitter's API has changed
> > I haven't found one instance that works now. I tried many of those not updated.
> 
> That is definitely the case. I tried them all and a few unofficial ones. And some of the ones I tested have not been updated in months.
> 
> Mine has my workaround already applied and works tho. https://nitter.privacydev.net/

<img width="812" alt="image" src="https://user-images.githubusercontent.com/130816137/232182907-e8aaec7f-ed03-4b71-9250-23dfe997742a.png">
Hmm, doesn't appear like it's working for me. Anything I'm doing wrong or is this an issue on your end?

**Comment by PrivacyDevel** [comment]
> > > > IIRC based on some warnings I've seen when using yt-dlp plus other stuff:
> > > > 
> > > > * The new graphql API won't show 18+ tweets to guest users (aka nitter)
> > > > * the old api that's getting shut down does, but only in some regions
> > > > 
> > > > Edit: nitter.net uses more graphql endpoints than most instances because it's running a dev version
> > > 
> > > 
> > > Idk,. It seems like Twitter's API has changed
> > > I haven't found one instance that works now. I tried many of those not updated.
> > 
> > 
> > That is definitely the case. I tried them all and a few unofficial ones. And some of the ones I tested have not been updated in months.
> > Mine has my workaround already applied and works tho. https://nitter.privacydev.net/
> 
> <img alt="image" width="812" src="https://user-images.githubusercontent.com/130816137/232182907-e8aaec7f-ed03-4b71-9250-23dfe997742a.png">
> Hmm, doesn't appear like it's working for me. Anything I'm doing wrong or is this an issue on your end?

The global search doesn't show nsfw results. That didn't even work when I tried doing it with my usual authentication headers for some reason. When you access a profile directly, it should work tho (unless one of my instances / accounts (signified by the number in the parenthesis) is currently rate limited).
Just open https://nitter.privacydev.net/NAME_OF_NSFW_USER

**Comment by zedeus** [comment]
Twitter blocks certain searches, including that hashtag. You can check by doing it on Twitter and checking the adaptive.json response in devtools, which should contain an error about the query being invalid.

**Comment by WaywardHeart** [comment]
For those searches to work, the account owner needs to go to https://twitter.com/settings/search and uncheck "Hide sensitive content".

**Comment by PrivacyDevel** [comment]
> For those searches to work, the account owner needs to go to https://twitter.com/settings/search and uncheck "Hide sensitive content".

Thank you! Fixed it.

**Comment by DrSocket** [comment]
@PrivacyDevel could you link to your fork or give any info on the changes made allowing for authentication? thanks!

**Comment by PrivacyDevel** [comment]
> @PrivacyDevel could you link to your fork or give any info on the changes made allowing for authentication? thanks!

My fork is here: https://github.com/PrivacyDevel/nitter
It's regular Nitter with the commits of the following PRs applied:
- https://github.com/zedeus/nitter/pull/830 (the actual changes needed for the authentication)
- https://github.com/zedeus/nitter/pull/837 (so that my load balancer can detect account based rate limiting and switch to another instance)

**Comment by DrSocket** [comment]
@PrivacyDevel thanks a lot, so I added the necessary variables to nitter.conf from a logged account, tested successful request with postman and ran it with docker compose, the instance doesn't do anything different to nitter.net. I don't get a responses as if logged. Am I missing something? it seems to just proxy to nitter.net

**Comment by holdit** [comment]
@PrivacyDevel Thanks for your work and for running the instance. Not sure if you're aware, but settings are not saved and sometimes pages have a different theme, probably because of the caching you're doing. Could be a good idea to stop access to the settings page.

**Comment by PrivacyDevel** [comment]
> @PrivacyDevel thanks a lot, so I added the necessary variables to nitter.conf from a logged account, tested successful request with postman and ran it with docker compose, the instance doesn't do anything different to nitter.net. I don't get a responses as if logged. Am I missing something? it seems to just proxy to nitter.net

I'm not entirely sure what you mean. If you have your own instance, it should be completely independent of nitter.net. And well, you can test if it worked by opening the profile of a user that posts nsfw content. If you see that kind of content, then it's working. If it does not show up it isn't working. Or you can check a profile page and check if you see a "like" tab and if it works. If it does, you're all set.

Note: if you want the search function to show nsfw results, you need to enable that here https://github.com/zedeus/nitter/issues/829#issuecomment-1510067533

**Comment by PrivacyDevel** [comment]
> @PrivacyDevel Thanks for your work and for running the instance. Not sure if you're aware, but settings are not saved and sometimes pages have a different theme, probably because of the caching you're doing. Could be a good idea to stop access to the settings page.

Yeah, I was kind of afraid of this happening... Blocking the settings page won't be enough. I would have to ignore the cookies as well at the very least. But I don't really want to block off settings either... It's tricky.

**Comment by holdit** [comment]
> > @PrivacyDevel Thanks for your work and for running the instance. Not sure if you're aware, but settings are not saved and sometimes pages have a different theme, probably because of the caching you're doing. Could be a good idea to stop access to the settings page.
> 
> Yeah, I was kind of afraid of this happening... Blocking the settings page won't be enough. I would have to ignore the cookies as well at the very least. But I don't really want to block off settings either... It's tricky.

Probably a dumb idea, but... would it be possible to add the caching layer between Twitter and Nitter? It would still reduce requests to Twitter, but Nitter itself would work normally (with delayed updates for popular content, I guess),

**Comment by DrSocket** [comment]
> > @PrivacyDevel thanks a lot, so I added the necessary variables to nitter.conf from a logged account, tested successful request with postman and ran it with docker compose, the instance doesn't do anything different to nitter.net. I don't get a responses as if logged. Am I missing something? it seems to just proxy to nitter.net
> 
> I'm not entirely sure what you mean. If you have your own instance, it should be completely independent of nitter.net. And well, you can test if it worked by opening the profile of a user that posts nsfw content. If you see that kind of content, then it's working. If it does not show up it isn't working. Or you can check a profile page and check if you see a "like" tab and if it works. If it does, you're all set.
> 
> Note: if you want the search function to show nsfw results, you need to enable that here [#829 (comment)](https://github.com/zedeus/nitter/issues/829#issuecomment-1510067533)

I guess I'm not understanding how to run the instance. I've compiled the code successfully, running a redis server but when I start ./nitter I get "Starting Nitter at http://nitter.net"
which is the hostname in the conf file. what am I missing?

**Comment by PrivacyDevel** [comment]
> > > @PrivacyDevel Thanks for your work and for running the instance. Not sure if you're aware, but settings are not saved and sometimes pages have a different theme, probably because of the caching you're doing. Could be a good idea to stop access to the settings page.
> > 
> > 
> > Yeah, I was kind of afraid of this happening... Blocking the settings page won't be enough. I would have to ignore the cookies as well at the very least. But I don't really want to block off settings either... It's tricky.
> 
> Probably a dumb idea, but... would it be possible to add the caching layer between Twitter and Nitter? It would still reduce requests to Twitter, but Nitter itself would work normally (with delayed updates for popular content, I guess),

That or using redis for caching more extensively would probably be the cleaner solution than what I am currently doing tbh. But it's also quite a bit more work. But I found a solution that should make it so that the issue you just described isn't going to happen anymore once the current cache expires.

**Comment by PrivacyDevel** [comment]
> I guess I'm not understanding how to run the instance. I've compiled the code successfully, running a redis server but when I start ./nitter I get "Starting Nitter at http://nitter.net" which is the hostname in the conf file. what am I missing?

You have to replace nitter.net with your own address.

**Comment by DrSocket** [comment]
> 

I did that but my instance looks just like nitter.net, shouldn't it have "nitter (NSFW 2)" on the upper left if I ran your fork?

**Comment by PrivacyDevel** [comment]
No, that's just because I changed the title in my config file so that I can easily see which of my instances has been picked by the load balancer.

On first glance it should just look like normal Nitter. Because it mostly is.

**Comment by DrSocket** [comment]
> No, that's just because I changed the title in my config file so that I can easily see which of my instances has been picked by the load balancer.
> 
> On first glance it should just look like normal Nitter. Because it mostly is.

great ! thanks a lot for your work, still have a hard time reading nim, wouldn’t have been able to add auth.

**Comment by Melanpan** [comment]
Thanks for your work! I'm running your fork locally for my own app that combines multiple twitter users into a single rss feeds. So I essentially have my own curated twitter home page without needing to use Twitter anymore.

That said, any plans to add this pull request as well? https://github.com/zedeus/nitter/pull/812 
It fixes the search being broken for non-logged in accounts.

**Comment by Seeings** [comment]
@PrivacyDevel Tried using your fork, but I'm trying to use it via Docker Compose. and I assume that when I do `docker compose up -d` it pulls the files from zedeus version which have not been updated with this commit.
Tried 3 different logged on twitter CT0/authtoken/xcsfrtoken combos but none of them work for me, still getting that I need to be logged in.
I could be wrong in this, but I am not sure what is causing the issue.

**Comment by PrivacyDevel** [comment]
> Thanks for your work! I'm running your fork locally for my own app that combines multiple twitter users into a single rss feeds. So I essentially have my own curated twitter home page without needing to use Twitter anymore.
> 
> That said, any plans to add this pull request as well? #812 It fixes the search being broken for non-logged in accounts.

I've seen that at least some threads are not working properly with the GraphQL update anymore so I won't merge it into my fork just yet.

**Comment by PrivacyDevel** [comment]
> @PrivacyDevel Tried using your fork, but I'm trying to use it via Docker Compose. and I assume that when I do `docker compose up -d` it pulls the files from zedeus version which have not been updated with this commit. Tried 3 different logged on twitter CT0/authtoken/xcsfrtoken combos but none of them work for me, still getting that I need to be logged in. I could be wrong in this, but I am not sure what is causing the issue.

Yes, the docker-compose pulls the official docker image. You have to build it yourself.

**Comment by Seeings** [comment]
> > @PrivacyDevel Tried using your fork, but I'm trying to use it via Docker Compose. and I assume that when I do `docker compose up -d` it pulls the files from zedeus version which have not been updated with this commit. Tried 3 different logged on twitter CT0/authtoken/xcsfrtoken combos but none of them work for me, still getting that I need to be logged in. I could be wrong in this, but I am not sure what is causing the issue.
> 
> Yes, the docker-compose pulls the official docker image. You have to build it yourself.

Ok, well I'm not that well versed in how to do that, so I'll wait for zedeus to hopefully add the pull request. Or if I get the time to learn how to do it at a later time.
Thanks for the info though!

**Comment by Seeings** [comment]
> > > @PrivacyDevel Tried using your fork, but I'm trying to use it via Docker Compose. and I assume that when I do `docker compose up -d` it pulls the files from zedeus version which have not been updated with this commit. Tried 3 different logged on twitter CT0/authtoken/xcsfrtoken combos but none of them work for me, still getting that I need to be logged in. I could be wrong in this, but I am not sure what is causing the issue.
> > 
> > 
> > Yes, the docker-compose pulls the official docker image. You have to build it yourself.
> 
> Ok, well I'm not that well versed in how to do that, so I'll wait for zedeus to hopefully add the pull request. Or if I get the time to learn how to do it at a later time. Thanks for the info though!

Managed to build it and make it work, however I had to edit this command `docker run -v $(pwd)/nitter.conf:/src/nitter.conf -d --network host nitter:latest` to `docker run -v '$(pwd)'/nitter.conf -d --network host nitter:latest`
Running the command from the guide i only got this error: docker: invalid reference format.

**Comment by crockpoot** [comment]
The "search" workaround doesn't even work anymore...

**Comment by zedeus** [comment]
What do you mean? It works fine.
![Uploading Screenshot_2023-04-22-11-46-41-68_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by zedeus** [comment]
What do you mean? It works fine.
![Screenshot_2023-04-22-11-46-41-68_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/9434921/233776691-ba4ee778-0964-4701-bc86-a056f0810c11.jpg)

**Comment by crockpoot** [comment]
> What do you mean? It works fine. ![Screenshot_2023-04-22-11-46-41-68_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/9434921/233776691-ba4ee778-0964-4701-bc86-a056f0810c11.jpg)

I meant from user specific searches like so:
https://nitter.net/[18+_twitter_handle]/search
This used to work as a workaround that [jve-engineering](https://github.com/jve-engineering) found earlier but, a few days ago, even that stopped working. I've tried several instances as well with no luck.

> The [search tab](https://nitter.net/TwitterAPI/search) still shows the complete feed. Could fetching this way be a workaround? However, it seems to depend on the region again, e.g. US works, DE does not.

**Comment by orbea** [comment]
@PrivacyDevel Your workaround doesn't work if the NSFW twitter user is also blocked by the nitter host country. Unfortunately Germany censors things they do not like liberally, much more than other countries.

**Comment by PrivacyDevel** [comment]
@orbea really? That sucks... Could you give me an example somehow by any chance?

**Comment by orbea** [comment]
@PrivacyDevel Certainly not the only account I have seen blocked by Germany, but the example I noticed now that prompted my comment.
> [@mdfzeh](https://nitter.privacydev.net/mdfzeh)'s account has been withheld in Germany based on local law(s). https://support.twitter.com/articles/20169222

While other nitter instances show the expected.
> Age-restricted adult content. This content might not be appropriate for people under 18 years old. To view this media, you’ll need to log in to Twitter.

**Comment by PrivacyDevel** [comment]
Hm.. that's really annoying..

**Comment by crockpoot** [comment]
> Hm.. that's really annoying..

Twitter in general and its recent API is really annoying right now and it seems to just keep getting worse every other week.

**Comment by orbea** [comment]
> Twitter in general and its recent API is really annoying right now and it seems to just keep getting worse every other week.

I try to tell people to not use proprietary social media platforms that can easily spy on, manipulate and censor their users, but it often falls on deaf ears... Even Minds depends on cloudflare.

**Comment by SMylk** [comment]
> > @PrivacyDevel could you link to your fork or give any info on the changes made allowing for authentication? thanks!
> 
> My fork is here: https://github.com/PrivacyDevel/nitter It's regular Nitter with the commits of the following PRs applied:
> 
>     * [added login-based workaround to view NSFW content #830](https://github.com/zedeus/nitter/pull/830) (the actual changes needed for the authentication)
> 
>     * [raise a RateLimitError when Twitter returns HTTP status 429 #837](https://github.com/zedeus/nitter/pull/837) (so that my load balancer can detect account based rate limiting and switch to another instance)
> 
> 
> I have currently 4 instances. 3 instances with their own accounts each and a backup instance without any account that's used when all other instances have been rate limited. The selection is done by nginx, my load balancer.
> 
> On top of that I also set up caching + rate limiting with nginx as well, in an attempt to speed things up and get rate limited less frequently.

Can we get a hub.docker.com image?

**Comment by c-chell** [comment]
I read this discussion, but I still don't understand where to put the "session" information ?
I check to see if the option is in "nitter.conf", but it seems not.
Maybe it's simple, but I don't get the point.

**Comment by Owyn** [comment]
Are there any instances yet that show NSFW twitter posts?

cuz twitter (nitter) without NSFW is just as useless as tumblr without it

**Comment by PrivacyDevel** [comment]
> Can we get a hub.docker.com image?

I am thinking about it.

**Comment by PrivacyDevel** [comment]
> I read this discussion, but I still don't understand where to put the "session" information ? I check to see if the option is in "nitter.conf", but it seems not. Maybe it's simple, but I don't get the point.

@c-chell it's probably easiest if you just use [my fork](https://github.com/PrivacyDevel/nitter) for the time being.

**Comment by PrivacyDevel** [comment]
> Are there any pubic instances yet that show NSFW twitter posts?
> 
> cuz twitter (nitter) without NSFW is just as useless as tumblr without it

@Owyn other than [mine](https://nitter.privacydev.net) there are currently no other public ones afaik.

**Comment by c-chell** [comment]
> > I read this discussion, but I still don't understand where to put the "session" information ? I check to see if the option is in "nitter.conf", but it seems not. Maybe it's simple, but I don't get the point.
> 
> @c-chell it's probably easiest if you just use [my fork](https://github.com/PrivacyDevel/nitter) for the time being.

Thank you, I see you add a PR, I think will wait to get it to the main line. 
In the discussion I understand that is already in it.
(I'm not really at ease to get around the Docker build)

**Comment by DisasterInbound** [comment]
> What about a voluntary system - ask for a login to increase the rate limit, but fall back on a set account if no login is provided?
> 
> Perhaps users willing to forgo the non-tracking nature could put a query string at the end of the URL for the RSS feed, containing the exact ct0, auth_token and csrf-token, and the server could use those credentials instead of its own if all are present.

I would like to request for this option to be added.
This should be only an optional setting that would be used to avoid getting rate limited by Twitter (when using the default account) and for also when the fork/mantainer doesn't include their own account.

I personally already have a Twitter account which I use to follow artists but I use nitter to open their feed without having to use lots of CPU such as when using the normal Twitter page. Having an optional setting would allow me to log in and get the content that I want without killing my PC.

**Comment by DisasterInbound** [comment]
@PrivacyDevel I found some tweets were still age locked even when using the NSFW3 instance. Interestingly, only some of these tweets are locked but others are properly shown

[https://nitter.privacydev.net/huzeu1](https://nitter.privacydev.net/huzeu1)

![25A8MqQ65t5swzwz_2023-06-04_02-14-23](https://github.com/zedeus/nitter/assets/64549167/3a4fc64a-1175-475b-88bc-675c422066da)

**Comment by PrivacyDevel** [comment]
> @PrivacyDevel I found some tweets were still age locked even when using the NSFW3 instance. Interestingly, only some of these tweets are locked but others are properly shown
> 
> https://nitter.privacydev.net/huzeu1
> 
> ![25A8MqQ65t5swzwz_2023-06-04_02-14-23](https://user-images.githubusercontent.com/64549167/243145910-3a4fc64a-1175-475b-88bc-675c422066da.png)

Thank you for bringing this to my attention. I've never seen this before and was not able to reproduce it either. I feel like I know why this is happening tho. I guess the NFSW instances reused the data from the redis cache that is shared between all of the instances.

**Comment by zedeus** [comment]
Tweets aren't cached.

**Comment by PrivacyDevel** [comment]
Hm ok. Thank you for this info @zedeus. Then I actually don't know what might've caused this..

**Comment by Owyn** [comment]
What about when it shows "This tweet is unavailable"? is it the rate limit? cuz sometimes I get an RSS with a tweet (which is shown fine there), but when I open it on nitter (privacydev) it says "unavailable", but on twitter itself it shows fine If I try

**Comment by zedeus** [comment]
@Owyn you'd have to provide an example for me to know

**Comment by jadedgnome** [comment]
is it possible to add support for multiple accounts to get around the rate-limit?

**Comment by mischif** [comment]
Is there anything preventing #830 or #897 being merged to resolve this? I would like to stand up my own instance but I would like to view sensitive feeds.

**Comment by zedeus** [comment]
Fixed.

**Comment by DropTable69** [comment]
Checked a dozen instances. Not actually fixed.

**Comment by zedeus** [comment]
Depends on the country the instance runs in, and potentially the country from which its guest accounts were made, haven't tested that.

**Comment by ShadowJonathan** [comment]
Can confirm that generating from the Netherlands and/or Finland (I mixed them, cant know which one worked) works with nsfw accounts

**Comment by vehosah** [comment]
> Fixed.

Fixed aaand it's still broken 👀
