### ISSUE TITLE
Can't open RSS feed in NetNewsWire

### ISSUE THREAD

**Issue by kimonostereo** [zedeus/nitter#832]
I tried to add some Nitter RSS feeds using NetNewsWire and get the error "can't add a feed because no feed was found." Adding Nitter feeds with Feedly works. Any idea why NetNewsWire doesn't work?

**Comment by diego898** [comment]
Just wanted to reference this issue here as well https://github.com/Ranchero-Software/NetNewsWire/issues/3935

**Comment by geoffeg** [comment]
It seems like the main nitter.net blocks NetNewsWire. Other instances work fine for me.

**Comment by zedeus** [comment]
It got banned due to a large amount of requets. I've unblocked it now, so this should work again.
