### ISSUE TITLE
RSS feed of personal timeline

### ISSUE THREAD

**Issue by tylerbenson** [zedeus/nitter#834]
Is it possible to provide an rss view of what the user would normally see in their timeline? (Similar to what NNW offered via the Twitter extension.)

It's nice seeing replies between people you follow, but too noisy to get all replies.

Thanks!

**Comment by tylerbenson** [comment]
I don't think that NNW has filtering.  I use their iCloud/Local connection, so no external service.

**Comment by markcellus** [comment]
Yeah doesn't look like NNW offers filtering currently, but there's an issue open for it: https://github.com/Ranchero-Software/NetNewsWire/issues/1864.

**Comment by tylerbenson** [comment]
I assume this would be more difficult because it would require some form of authentication which is not required for the current implementation.

**Comment by pin-grid-array** [comment]
I'm not familiar with NetNewsWire so this might be a silly question but are you seeing replies because you are subscribed to `username/with_replies/rss` instead of `username/rss`?

**Comment by tylerbenson** [comment]
Oops.  I guess I was confused.  Sorry about that.  I think it's still nice seeing conversation between people I follow though, so I think my request still applies?

**Comment by robindz** [comment]
> Closest you can get to this is creating a multi-user timeline: https://nitter.net/elonmusk,tesla,spacex
> Behind the scenes this generates a search query and returns the result, note however that Twitter's' max query length is 500 characters, so the max amount of users per timeline is ~25 for now. Modifying the query to include replies between the accounts would lengthen it exponentially, significantly reducing the max amount of users. Instead you'd have to get the timeline with replies (probably more than 20 tweets at a time as well), filter out replies to irrelevant accounts, and rearrange the tweets. They'd have to line up though, seems like a rare event.

If one is willing to create a Twitter account for the sake of creating a public list, then you could use `https://nitter.net/i/lists/<list_id>` and treat that as a timeline. However, depending on the amoutn of accounts you wish to follow this could take a while to create the list. Twitter seems to have a rate limit of adding ~100-150 accounts to a list per 24h.

**Comment by tylerbenson** [comment]
Ooh, that's an interesting idea.  Thanks for the suggestion.

If the original request is unfeasible, go ahead and close the issue.

**Comment by tylerbenson** [comment]
Using a list has been a reasonable solution. Going to close this issue.
