### ISSUE TITLE
Feature: Allow config to be set using environment variables

### ISSUE THREAD

**Issue by binaryben** [zedeus/nitter#835]
Would be handy for these variables so I can keep the nitter.conf file static and shareable for others wanting to reuse my configs:

```
[Server]
hostname = "${...}"

[Config]
hmacKey = "secretkey"
```

Expected mapping would be along the lines of `NITTER_SERVER_HOSTNAME`.

***

<details>
<summary>Extra question that has since been answered</summary>

To save a issue ticket for a question, can anyone point out where these are used please?

```
[Preferences]
replaceTwitter = "nitter.net"
replaceYouTube = "piped.video"
replaceReddit = "teddit.net"
```

</details>

**Comment by jackyzy823** [comment]
>  Can nitter.conf be set using environment variables

No.

However i also hope that nitter can use env like  `SERVER_HOSTNAME=xxx CONFIG_HMACKEY=xxxx ./nitter`

> where these are used please?

Links in a tweet / user's biography etc (maybe any where there's a `<a>` element )

**Comment by binaryben** [comment]
> No.

Thanks. Have changed issue to feature request now.

> Links in a tweet / user's biography etc (maybe any where there's a `<a>` element )

Ah, akin to SearXNG hostname replace plugin. Cool!

**Comment by zedeus** [comment]
This shouldn't be too hard to implement, I'll add it to my todo list. This issue is a duplicate though: #633

**Comment by binaryben** [comment]
Thanks @zedeus, sorry I didn't catch the duplicate!
