### ISSUE TITLE
Searches no longer return any results

### ISSUE THREAD

**Issue by fuzxi** [zedeus/nitter#839]
As of a few hours ago, searches on my self-hosted instance always return "No items found". I do not appear to be rate-limited, because I can still access profiles and tweets. I was using an older version of nitter in a docker container and have now updated to the latest version that was posted a few hours ago, but the issue is still present. Searching still works on other instances. Is there some kind of search-only rate limit that I've been hit by?

The older version logged the following when running a search:
```
fetch error: (errors: @[(code: forbidden, message: "Forbidden.")])
error: RateLimitError, msg: rate limited, token: (tok: "1649243253525606400", init: (seconds: 1682045207, nanosecond: 773624352), lastUse: (seconds: 1682045207, nanosecond: 773624352), pending: 1, apis: (data: @[], counter: 0)), url: https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=0&include_blocking=0&include_blocked_by=0&include_followed_by=0&include_want_retweets=0&include_mute_edge=0&include_can_dm=0&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=false&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=false&send_error_codes=true&simple_quoted_tweet=true&include_quote_count=true&query_source=typed_query&pc=1&spelling_corrections=1&q=from%3Aceresfauna&result_filter=user&ext=mediaStats&include_ext_alt_text=true&include_ext_media_availability=true&count=20
```
The newest version has not logged any errors.

**Comment by zedeus** [comment]
Twitter has started requiring authentication for the main search endpoint. This even means twitter.com/search requires you to log in. #812 has a replacement.

**Comment by fuzxi** [comment]
Ah, I see. Thank you!

**Comment by zedeus** [comment]
No, that's not my instance, I only run nitter.net

**Comment by cgillett** [comment]
If the main search endpoint now requires user login, isn't it a safe assumption that the graphql endpoint will soon also require use login?

**Comment by zedeus** [comment]
Indeed, but it works for now
