### ISSUE TITLE
Verified accounts not showing checkmarks in profile on Nitter instances

### ISSUE THREAD

**Issue by ParamoreFan** [zedeus/nitter#845]
While the checkmarks do appear on the timelines, the profile on the left has no checkmark while it used to. Any reason why?

https://nitter.net/paramore/ Example

**Comment by 0x263b** [comment]
Looks like every tweet has the verified icon applied. compare the replies:

https://nitter.net/paramore/status/1648795957293613057#m
https://twitter.com/paramore/status/1648795957293613057

**Comment by Ipstenu** [comment]
I checked a bunch of accounts, and I am seeing accounts who didn’t pay for blue having their posts (not the accounts) showing on Nitter as verified.

I own https://twitter.com/lefoxfans and I did not pay, nor does the official site show me as blue. But if you look at https://nitter.net/lefoxfans then almost all my posts are ‘verified.’

I wonder what the heck Twitter did to do that…

**Comment by zedeus** [comment]
Probably due to an incorrect check on my part, I'll look into it

**Comment by jve-engineering** [comment]
There is a [browser extension](https://addons.mozilla.org/en-US/firefox/addon/legacy-verified/) that shows a check mark on accounts which had a blue check mark under the old verification system. The account list is available [here on github](https://github.com/roberrrt-s/legacy-verified-extension/blob/main/public/legacy-verified.csv). 

Imho this information would be more valuable than the _[paid checkmarks](https://slate.com/technology/2023/04/elon-musk-twitter-blue-check-marks-verification-lebron-james.html)_.
