### ISSUE TITLE
[OT?] unofficial Twitter API

### ISSUE THREAD

**Issue by rinaldi6109** [zedeus/nitter#846]
Where can I get some precise info about unofficial Twitter API?

**Comment by pin-grid-array** [comment]
Does this help?

https://pypi.org/project/twitter-api-client/

"Complete implementation of the undocumented Twitter API. Includes tools to scrape, automate, and search Twitter."

No tokens needed, just a username and password.

**Comment by rinaldi6109** [comment]
Thank you. Do you know if someone ported it to javascript? I would need to use it in google apps script.

**Comment by pin-grid-array** [comment]
@rinaldi6109 I'm sorry, I have no idea. I found that website quite by accident. I'm just an average computer user who has only minute knowledge of programming and don't know how to go about porting it to Javascript.

**Comment by zedeus** [comment]
https://github.com/fa0311/TwitterInternalAPIDocument/
https://github.com/fa0311/twitter-openapi-typescript
https://github.com/BANKA2017/twitter-monitor
