### ISSUE TITLE
Details on RSS feed?

### ISSUE THREAD

**Issue by psegovias** [zedeus/nitter#848]
Hi, how i can add more elements like, retweet count, likes, real username, etc?

**Comment by markcellus** [comment]
Bringing the full Twitter experience to RSS 😀

**Comment by markcellus** [comment]
Agree. Things like retweet counts or likes change frequently, which would be hard to get accurate in an RSS feed. They'd always be out of date depending on when the feed is polled or if cached in an RSS reader. Much better to just see this information in Twitter. But I appreciate any effort to encourage more RSS usage vs the apps, nonetheless. 👍

**Comment by psegovias** [comment]
I basically use nitter to see old times searches, and generally the data like rt and likes don't change often, it would also be a good way to auto scrape the search with all the data already obtained.

**Comment by psegovias** [comment]
I basically use nitter to see old times searches, and generally the data like rt and likes don't change often, it would also be a good way to auto scrape the search with all the data already obtained.

**Comment by zedeus** [comment]
Both those use cases are not a good fit for RSS. Use the website to search for old tweets, and either modify your own instance to spit out JSON or wait for the API to be implemented.
