### ISSUE TITLE
JSON option request

### ISSUE THREAD

**Issue by Shifter2600** [zedeus/nitter#849]
@zedeus I used your edits to turn the search into a JSON API. and this is awesome and wish it was part of the core project sort of like how you implemented rss.....
I was going down the route of scraping the front end of nitter and was pleasantly surprised when I seen the JSON output and saw that all the replyid's and user fields were already in the JSON output so it didn't require clicking into additional endpoints. 

> ```diff
> diff --git a/src/routes/search.nim b/src/routes/search.nim
> index 02c14e3..b2ceefc 100644
> --- a/src/routes/search.nim
> +++ b/src/routes/search.nim
> @@ -11,6 +11,12 @@ include "../views/opensearch.nimf"
>  
>  export search
>  
> +import jsony, times
> +export jsony
> +
> +proc dumpHook*(s: var string, v: DateTime) =
> +  s.add $v.toTime().toUnix()
> +
>  proc createSearchRouter*(cfg: Config) =
>    router search:
>      get "/search/?":
> @@ -37,8 +43,7 @@ proc createSearchRouter*(cfg: Config) =
>          let
>            tweets = await getGraphSearch(query, getCursor())
>            rss = "/search/rss?" & genQueryUrl(query)
> -        resp renderMain(renderTweetSearch(tweets, prefs, getPath()),
> -                        request, cfg, prefs, title, rss=rss)
> +        resp tweets.toJson
>        else:
>          resp Http404, showError("Invalid search", cfg)
> ```

**Comment by DrSocket** [comment]
@zedeus is can anything similar be done for user timeline? I'm trying but since respTimeline() is async I'm not sure it will work, I don't know if the response from renderMain is always json? and if I change `respTimeline*()` to `resp t.toJson` instead of just `t` It's just a badly formatted html page. any tips?

**Comment by zedeus** [comment]
@DrSocket `renderMain` and other `render` procs all return HTML, either as a string or a virtual DOM object. I suggest modifying `showTimeline` to return JSON immediately after line 90, e.g. `return toJson(profile)` but you will have to define some conversion procs as shown in the this issue.

**Comment by DrSocket** [comment]
hi @zedeus I hadn't had time to work on that but was trying to make this work over the weekend and had absolutely no luck. I'm quite new to nim so I'm having a hard time with the syntax and the procs even to output different vars for debugging. do you have any more recommendations that could help me get into nim more and how I could implement this conversion to Json on the user timeline? thanks a lot!
