### ISSUE TITLE
Tweets returned after searching a hashtag do not always contain such hashtag

### ISSUE THREAD

**Issue by rmnhg** [zedeus/nitter#850]
Hello. I was trying to find tweets within a date interval searching for a hashtag.

For instance, I am looking for tweets containing "#realmadrid" on the last day, so I search for them using the following URL:
[https://nitter.net/search?f=tweets&q=%23realmadrid&since=2023-04-25&until=2023-04-26&near=](https://nitter.net/search?f=tweets&q=%23realmadrid&since=2023-04-25&until=2023-04-26&near=)

But looking at the results I get, I observed that the dates are fine, but the tweets contain words related to the hashtag I searched without always having the hashtag inside the tweet content.

Here is a screenshot with the result of the search:
![image](https://user-images.githubusercontent.com/15710257/234557241-18bb7dc3-061e-43c6-b8f3-be26575eb347.png)

Is this the expected behavior? Is there any other way to obtain tweets containing the hashtag with other filters?

Thanks in advance for the help and for the effort with this amazing project you are maintaining.

**Comment by zedeus** [comment]
Related to search being broken. This specific issue was because the newer GraphQL endpoint was used, but now it's gone. Closing, refer to #852
