### ISSUE TITLE
Unverified account not showing!

### ISSUE THREAD

**Issue by TempYoUser** [zedeus/nitter#851]
The only instance which used to show both verified and unverified “comments” was fly.dev which has not been updated for a while and currently out of service!

Basically, a tweet shows 10 comments but when I click on it, I do not see all the comments - except those by verified members.

Or, perhaps there is a hidden setting somewhere I’m missing?

FWIW, I am an end user!

**Comment by zedeus** [comment]
Unverified comments are shown, Twitter just started prioritizing verified accounts.
https://mashable.com/article/twitter-verified-accounts-prioritized-elon-musk
