### ISSUE TITLE
Multi twitter feeds stopped working

### ISSUE THREAD

**Issue by rcsavo** [zedeus/nitter#855]
For a few days multi twitter feeds, like https://nitter.net/github,mozilla no longer give results but say that no items are found.

**Comment by iscilyas** [comment]
same here. running the latest 'master' ([2023.04.21-2254a07](https://github.com/zedeus/nitter/commit/2254a07)).  iirc it was working fine yesterday but hasn't been working this morning (and i was surprised nobody else opened an issue)

**Comment by cybersphinx** [comment]
Maybe the multi user page could be implemented by combining the single user pages instead of using the search?

**Comment by zedeus** [comment]
@cybersphinx of course, but then you suddenly need to make 25 requests just to load a page, not nice.
Since multi feeds rely entirely on search I'm going to close this as a duplicate of #852
