### ISSUE TITLE
instagram support

### ISSUE THREAD

**Issue by treble2019** [zedeus/nitter#86]
Any plans to create a similar service for instagram? Many thanks for your great service.

**Comment by zedeus** [comment]
As far as I know this is no longer possible:
https://thenextweb.com/socialmedia/2019/10/28/instagram-now-forces-people-to-sign-in-to-view-public-profiles/

**Comment by treble2019** [comment]
@zedeus  Thanks for the quick reply.

I did see the link you posted. In the meanwhile (or still) it is possible to see (at least 1 or 2 pages - 10 pics) of the last post of instagram user. 

For example, even without any logging in  if you visit
https://www.instagram.com/therock/

you can see at least 20 pics, before the dreaded model for login appears. 

So even the last 10 pics would be good enough reason to see (IMHO).

:-)

**Comment by dimqua** [comment]
@treble2019 AFAIK you could block the pop-up (with uBO) and be able to see all of them.

**Comment by dimqua** [comment]
BTW, [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge) supports Instagram (among others).

**Comment by Perflyst** [comment]
I tried, I was not able to block it with uBlock since it does not load any new images

**Comment by treble2019** [comment]
Just adding note to everyone...

https://github.com/rarcega/instagram-scraper
