### ISSUE TITLE
The certificate for nitter.net has expired.

### ISSUE THREAD

**Issue by vinyl-umbrella** [zedeus/nitter#862]
The public key certificate for nitter.net has expired.
So, please renew the certificate.

```sh
❯ openssl s_client -connect nitter.net:443  2> /dev/null | openssl x509 -noout -subject -dates
subject=CN = nitter.net
notBefore=Jan 30 23:35:03 2023 GMT
notAfter=Apr 30 23:35:02 2023 GMT
```

**Comment by zedeus** [comment]
Working on it

**Comment by jaawerth** [comment]
@zedeus I don't know what you're using server-wise, but for what it's worth, I've found automating the renewals using [certbot](https://certbot.eff.org/) to be a much smoother process than one would expect - for simple setups it might even be as little as enabling a systemd timer that ships with the certbot package if you used it to generate the cert in the first place.

Apologies if you *did* set it up and it simply broke, meaning I'm giving useless unsolicited advice - I've just seen this a lot, and put off the automation part myself when I first set up LE only to kick myself later, so I thought it'd be worth a comment 😁

**Comment by vinyl-umbrella** [comment]
I have confirmed that the certificate has been renewed.
Thank you.
