### ISSUE TITLE
Block Twitter content through Nitter instances (or blacklist ALL Nitter instances)

### ISSUE THREAD

**Issue by PlaisirN** [zedeus/nitter#863]
For some time now, I've successfully blocked Twitter and its content, as I have no desire to see any of it.

Until a little while ago I stumbled upon Nitter. I think Nitter is great for those who use it and kudos to the maintainers. However, neither DNS blockers and Application blockers block the Twitter content on these instances, which I dislike.

My question are; 
1. How come Twitter content is still viewable on Nitter instances, even though Twitter's domains are blacklisted? I'm not sure how Nitter works, but one thing I do know is that it fetches data from Twitter, which is blacklisted.
2. How can the Twitter content (images and video) still be blocked on these Nitter instances?
3. If that's not possible, is there some way that ALL Nitter instances can be blocked without having to manually blacklist each one as soon as a new server pops up? I use a content filter which also blocks proxies, but that doesn't always help. 

What I've tried:

I looked through the source code and I saw some domains that are likely to be used by the instances here: https://github.com/zedeus/nitter/blob/master/src/utils.nim in the `const twitterDomains`. I blacklisted all of these domains, but Twitter content is still available through these instances.

I'm not too familiar with how Nitter works; it seems that it "Uses Twitter's unofficial API", but I cannot find more information on this.

I know that this is probably not the best place to ask this question; I did sent an e-mail to @zedeus , but unfortunately I had no response. So that's why I'm asking it here.

Hope someone can help out.

**Comment by zedeus** [comment]
Where are you seeing content from these instances? I doubt they get embedded a bunch, simply don't visit them.

**Comment by PlaisirN** [comment]
> Where are you seeing content from these instances? I doubt they get embedded a bunch, simply don't visit them.

That's a solution, indeed. However by just not visiting them, it does not solve the problem of Twitter content being available.

To answer your first question; I quickly tested it before posting this issue; on every instance I visit, I see Twitter content. I would just like for a way for the blockers to also block Twitter content on these instances, just as they do on any other website that use show Twitter content.

**Comment by zedeus** [comment]
If you don't want to see the content, just don't visit the public instances? They do not serve content directly from Twitter, you cannot block any of it by blocking Twitter domains or css classes. You can add every domain from the public instance list to your hostname blocker, besides that I can't help you.

**Comment by PlaisirN** [comment]
You keep saying to just not visit the public instances like it's that easy. If it was just that, I wouldn't be posting this question. 

Besides, it's not just for me, but for all people/devices using a certain network. Telling them to "just not visit the public instances" won't cut it. 

Anyways, thanks for the information. I'll just add every instance to the blocklist and all instances that pop up after that.

**Comment by markcellus** [comment]
> I'll just add every instance to the blocklist and all instances that pop up after that.

Good luck doing that. That list is nowhere near the amount of instances that actually exist.  What you're asking for seems impossible. There's no possible way for anyone to determine every possible domain name (now and in the future) that hosts a nitter instance. Any website could host anything it wants at anytime. You'd have to build something that monitors every website on the internet at every millisecond of the day to determine whether it hosts a nitter instance to achieve what you want.
