### ISSUE TITLE
show the hidden part of long tweets

### ISSUE THREAD

**Issue by 2011** [zedeus/nitter#864]
First of all, I did search in the issues (but it seems strange that no one has opened an issue on this yet), and I apologize if I have just created a duplicate issue.

If I understand (far from certain), Twitter now allows longer tweets for paid users. Nitter only shows the first part of those longer tweets. Twitter (which only displays the first part by default) contains a "show more" link which (when clicked on) reveals the remainder of the tweet.

An example seems like the best way to illustrate this:

https://twitter.com/stats_feed/status/1653056125330239489

I don't know any way (in nitter) to access the hidden part of the tweet.

**Comment by BANKA2017** [comment]
Twitter uses path `note_tweet.note_tweet_results.result.text` instead of `legacy.full_text` to obtain the text of long tweets.

I think edit file `~/src/parser.nim` will work, but I don't know how to write in nim.

**Comment by 2011** [comment]
Oops. I have used nitter.snopyta.org (primarily because I virtually never have any rate limiting issues with them, but also because they also run an invidious instance, which makes it easy for me to remember :) ), and just checked which version they run (2022.09.21-2ac3afa, which explains why I don't see long tweets).

Strangely, they don't appear in the list of nitter instances (which perhaps explains why they never get too busy :) ).

Apologies, and thanks for the quick reply.
