### ISSUE TITLE
Not showing

### ISSUE THREAD

**Issue by HariTyraxes** [zedeus/nitter#865]
I been using nitter for 2 years, past 1 week i been noticing that i cant see "Age-restricted adult content. This content might not be appropriate for people under 18 years old. To view this media, you’ll need to log in to Twitter" 
How to see it without log in?

**Comment by zedeus** [comment]
You can't. One possible solution is hosting an instance with the API credentials from a throwaway account, implemented in #830, otherwise there is no way around it.
