### ISSUE TITLE
Query results not working

### ISSUE THREAD

**Issue by trhakan** [zedeus/nitter#866]
https://nitter.net/search?f=tweets&q=BarackObama
This query was working until a few days ago.
Now I'm facing **"Not item found"** warning and no results are returned.
But there is no problem with the ?f=users value. This is working for now.
Has the **?f=tweets** query been removed? Or what could be wrong? King regards.

**Comment by zedeus** [comment]
Broken for now because Twitter disabled unauthenticated search, may be fixed in the future. Duplicate of #852
