### ISSUE TITLE
Filter by language

### ISSUE THREAD

**Issue by cloud1992** [zedeus/nitter#867]
Please, can anyone tell me how can I search and filter by language. For example, I only want tweets in English. Thanks

**Comment by BANKA2017** [comment]
Add ` lang:en ` to your query string.

You can learn more about advanced search from [igorbrigadir/twitter-advanced-search#supported-languages](https://github.com/igorbrigadir/twitter-advanced-search#supported-languages)

**Comment by cloud1992** [comment]
Thank you
