### ISSUE TITLE
ERROR fatal.nim(54) when fetching /rss

### ISSUE THREAD

**Issue by xgedev** [zedeus/nitter#868]
When fetching about 100 RSS feeds in a few seconds, the following error is sent 2-10 times:
```
ERROR fatal.nim(54)            sysFatal
asyncfutures.nim(389)    read
asyncfutures.nim(389)    read
asyncfutures.nim(389)    read
index 0 not in 1 .. 12
```
I set `tokenCount = 10`, `redisMaxConnections = 200` and `rssMinutes = 0`.
Most requests resolve successfully though. Does anyone know what is causing this / how to fix it? Thanks!

**Comment by xgedev** [comment]
Seems like there are definitely requests that don't resolve successfully. Any fix for this?

**Comment by banterCZ** [comment]
I have added several RSS feeds, but I observe the same error for only one specific username https://nitter.cz/adent/rss

**Comment by zedeus** [comment]
Can't reproduce, maybe you were running an old version of Nitter?

**Comment by duxovni** [comment]
... I can consistently reproduce this on nitter 2023-05-20 https://github.com/zedeus/nitter/commit/e3b3b38 by visiting an account that has recent age-restricted tweets, but you're right that I can't reproduce it on nitter 2023-05-30 https://github.com/zedeus/nitter/commit/38985af , and I'm not sure why; neither of the two commits between those versions look like they'd affect this, but maybe I'm missing something. Applying my linked PR on top of https://github.com/zedeus/nitter/commit/e3b3b38 does also fix the issue, for what it's worth.

**Comment by twiclo** [comment]
I'm getting this same error when just navigating to any account. I also have nothing in my search results. I'm not sure how I can see my version but I did do a git pull before posting. Running the manual install, no docker
