### ISSUE TITLE
Fail to open multi-user URLs

### ISSUE THREAD

**Issue by whaler-ragweed** [zedeus/nitter#869]
Since yesterday, when I try to open multi-user URLs, for example `https://MY.DOMAIN/Chord_O_Calls,Dafore3,IckyMTG,JasonILTG,justlolaman,limiteddecks,lordtupperware,lsv,mistermetronome,MagicOnline,PlayMTG,PVDDR,SamuelHBlack,Sierkovitz,SLKerstens,TaJoordan,Trumpetman__,twoduckcubed,Veveil,wizards_magic`, it always fail on the first try, but if I open it again immediately, it would work as normal.

Here is the log:

> Starting Nitter at http://MY.DOMAIN
> Connected to Redis at nitter-redis:6379
> error: OSError, msg: Operation timed out, token: (tok: "1655718819292418049", init: (seconds: 1683589103, nanosecond: 6211432), lastUse: (seconds: 1683589103, nanosecond: 6211432), pending: 1, apis: (data: @[], counter: 0)), url: https://api.twitter.com/graphql/gkjsKepM6gl_HmFWoWKfgg/SearchTimeline?variables=%7B%22rawQuery%22%3A%22from%3AChord_O_Calls+OR+from%3ADafore3+OR+from%3AIckyMTG+OR+from%3AJasonILTG+OR+from%3Ajustlolaman+OR+from%3Alimiteddecks+OR+from%3Alordtupperware+OR+from%3Alsv+OR+from%3Amistermetronome+OR+from%3AMagicOnline+OR+from%3APlayMTG+OR+from%3APVDDR+OR+from%3ASamuelHBlack+OR+from%3ASierkovitz+OR+from%3ASLKerstens+OR+from%3ATaJoordan+OR+from%3ATrumpetman__+OR+from%3Atwoduckcubed+OR+from%3AVeveil+OR+from%3Awizards_magic+filter%3Aself_threads+OR-filter%3Areplies+include%3Anativeretweets%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Afalse%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22longform_notetweets_richtext_consumption_enabled%22%3Atrue%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22responsive_web_edit_tweet_api_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Afalse%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%2C%22spaces_2022_h2_clipping%22%3Atrue%2C%22spaces_2022_h2_spaces_communities%22%3Atrue%2C%22standardized_nudges_misinfo%22%3Afalse%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Afalse%2C%22verified_phone_label_enabled%22%3Afalse%2C%22vibe_api_enabled%22%3Afalse%2C%22view_counts_everywhere_api_enabled%22%3Afalse%7D
> error: OSError, msg: Operation timed out, token: (tok: "1655718829761372161", init: (seconds: 1683589105, nanosecond: 501131796), lastUse: (seconds: 1683589109, nanosecond: 506680865), pending: 1, apis: (data: @[(hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: -8667131158406858863, key: search, val: (remaining: 499, reset: 1683590009)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0)), (hcode: 0, key: tweetDetail, val: (remaining: 0, reset: 0))], counter: 1)), url: https://api.twitter.com/graphql/gkjsKepM6gl_HmFWoWKfgg/SearchTimeline?variables=%7B%22rawQuery%22%3A%22from%3AChord_O_Calls+OR+from%3ADafore3+OR+from%3AIckyMTG+OR+from%3AJasonILTG+OR+from%3Ajustlolaman+OR+from%3Alimiteddecks+OR+from%3Alordtupperware+OR+from%3Alsv+OR+from%3Amistermetronome+OR+from%3AMagicOnline+OR+from%3APlayMTG+OR+from%3APVDDR+OR+from%3ASamuelHBlack+OR+from%3ASierkovitz+OR+from%3ASLKerstens+OR+from%3ATaJoordan+OR+from%3ATrumpetman__+OR+from%3Atwoduckcubed+OR+from%3AVeveil+OR+from%3Awizards_magic+filter%3Aself_threads+OR-filter%3Areplies+include%3Anativeretweets%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Afalse%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22longform_notetweets_richtext_consumption_enabled%22%3Atrue%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22responsive_web_edit_tweet_api_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Afalse%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%2C%22spaces_2022_h2_clipping%22%3Atrue%2C%22spaces_2022_h2_spaces_communities%22%3Atrue%2C%22standardized_nudges_misinfo%22%3Afalse%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Afalse%2C%22verified_phone_label_enabled%22%3Afalse%2C%22vibe_api_enabled%22%3Afalse%2C%22view_counts_everywhere_api_enabled%22%3Afalse%7D

**Comment by zedeus** [comment]
Does it also happen when you do a regular search, open an account, or visit a tweet?

**Comment by whaler-ragweed** [comment]
> Does it also happen when you do a regular search, open an account, or visit a tweet?

Regular search for single user and multi-user: Same issue.
Visit a profile and tweet: All good.

**Comment by whaler-ragweed** [comment]
> Does it also happen when you do a regular search, open an account, or visit a tweet?

FYI, I tried these:
1. Debian 11 on Azure: Error.
2. Ubuntu 22.04 on Azure: Error.
3. Debian 11 on Linode: No issue.

It seems the issue only happens on Azure.

**Comment by zedeus** [comment]
I guess this is a weird Azure bug, or Twitter blocks Azure hosts in a specific way. Nothing I can really do here from the looks of it. Please reopen if you have more information or think there is a way to fix it.
