### ISSUE TITLE
New Restriction Requires Log-in

### ISSUE THREAD

**Issue by juanpc2018** [zedeus/nitter#878]
see: May 11
Over "I got lucky"  https://twitter.com/evavlaar
Not Log-in
or using Nitter: https://nitter.net/evavlaar
vs. 
https://twstalker.com/EvaVlaar

Nitter:
<img width="951" alt="image" src="https://github.com/zedeus/nitter/assets/33388902/b7f7ef8a-46a4-416f-8310-e191634f1c9e">

BlueBird:
<img width="926" alt="image" src="https://github.com/zedeus/nitter/assets/33388902/519190f1-a522-4696-86b6-d3721afcb2ba">

**Comment by zedeus** [comment]
#829
