### ISSUE TITLE
HLS playback on mobile doesn't work due to content-security-policy

### ISSUE THREAD

**Issue by extremelyonline** [zedeus/nitter#881]
Hi, I've noticed that video playback doesn't work on mobile (Mull browser) on my instance.

The issue is with the following Content-Security-Policy header in the [Caddy config listed in the Wiki.](https://github.com/zedeus/nitter/wiki/Caddy). 

`default-src 'none'; script-src 'self' 'unsafe-inline'; script-src-attr 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'; style-src-elem 'self'; font-src 'self'; object-src 'none'; media-src 'self' blob:; worker-src 'self' blob:; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; connect-src 'self' https://*.twimg.com; manifest-src 'self'`

I was able to solve this issue. After changing the header to the following (copied from [nitter.net](nitter.net)), video works again on mobile.

`default-src 'none'; script-src 'self' 'unsafe-inline'; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'; media-src 'self' blob:; worker-src 'self' blob:; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; connect-src 'self' https://*.twimg.com; manifest-src 'self'`

I am not sure if this a rare occurrence caused by my setup/mobile browser. But just to let you know in case the wiki needs to be revised. Thanks!

**Comment by zedeus** [comment]
Weird, thanks! I've updated the Caddy config in the wiki.
