### ISSUE TITLE
Feature request: RSS feed without retweets (separate from the current one)

### ISSUE THREAD

**Issue by Mikaela** [zedeus/nitter#89]
I am using Nitter through a RSS reading bot and I was asked if it would be possible to disable the retweets from coming to a channel.

Thank you in advance.

**Comment by zedeus** [comment]
Click search, exclude retweets, then clicking the RSS icon should give you a feed without retweets. I'll add a simple FAQ with this as similar questions have been asked recently.

**Comment by Mikaela** [comment]
Thank you, nice to learn that it was already supported.

Will the FAQ be in the GitHub Wiki or Nitter.net information? Is there any issue I could follow?
