### ISSUE TITLE
with_replies threading behavior is broken

### ISSUE THREAD

**Issue by pin-grid-array** [zedeus/nitter#893]
That subject line is probably confusing but it will be obvious what I mean after seeing an example.

Look at this feed:
https://nitter.d420.de/MarkHamill/with_replies/rss

Notice how one of the items contained in this feed is this tweet:
https://nitter.d420.de/Miriam2626/status/1664073688034037760#m

This is not a tweet made by or retweeted by @/MarkHamill, so it should not appear in the feed.

However, @/MarkHamill *did* reply to it, and his reply does correctly appear as an item in the feed, here:
https://nitter.d420.de/MarkHamill/status/1664172119339716608#m

As far as I can tell, the tweets that incorrectly appear in the feed are ones that received a reply from the user (in this example @/MarkHamill) whose feed I am subscribed to.

***

Here are some other examples. These tweets below appear in the feed but are not made by or retweeted by @/MarkHamill:

(1) https://nitter.d420.de/phoefsutton/status/1664077589059870720#m
(2) https://nitter.d420.de/IDreamOfHamill/status/1656204757466484744#m
(3) https://nitter.d420.de/JAGJ2001/status/1656270936323280896#m

Tweet (1) by @/phoefsutton received a reply from @/MarkHamill:
https://nitter.d420.de/MarkHamill/status/1664171890913738752#m

Tweet (3) by @/JAGJ2001 is a reply to tweet (2) by @/IDreamOfHamill. @/MarkHamill replied to tweet (3) while also tagging tweet (2) creator @/IDreamOfHamill (and also tagging somebody not involved with replies @/HamillsTheater):
https://nitter.d420.de/MarkHamill/status/1664169056239493120#m

***

I randomly checked a few other public instances to see how widespread this bug is.

Here are instances whose feeds have this bug:

https://nitter.ktachibana.party/MarkHamill/with_replies/rss
https://nitter.lacontrevoie.fr/MarkHamill/with_replies/rss
https://nitter.lunar.icu/MarkHamill/with_replies/rss
https://nitter.one/MarkHamill/with_replies/rss
https://nitter.privacydev.net/MarkHamill/with_replies/rss
https://nitter.projectsegfau.lt/MarkHamill/with_replies/rss
https://nitter.sethforprivacy.com/MarkHamill/with_replies/rss
https://twitter.dr460nf1r3.org/MarkHamill/with_replies/rss
https://unofficialbird.com/MarkHamill/with_replies/rss

Here are instances whose feeds **do not** have this bug:

https://nitter.caioalonso.com/MarkHamill/with_replies/rss
https://nitter.privacytools.io/MarkHamill/with_replies/rss

Here are instances whose feeds do not have this bug, but are broken in a different way. Their feeds do not show replies and retweets at all (i.e. they function like the `MarkHamill/rss` feed instead of the `MarkHamill/with_replies/rss` feed) and they only contain 4 items instead of the normal 20. I suspect this problem is related to the bug.

https://nitter.at/MarkHamill/with_replies/rss
https://nitter.cz/MarkHamill/with_replies/rss
https://nitter.it/MarkHamill/with_replies/rss
http://nitter.kylrth.com/MarkHamill/with_replies/rss
https://nitter.moomoo.me/MarkHamill/with_replies/rss
http://read.whatever.social/MarkHamill/with_replies/rss

***

I believe this bug started occurring within the past 12 hours.

I hope I was clear with my explanation but please ask if you need me to clarify further.

**Comment by markcellus** [comment]
Yeah I've actually been seeing this happen randomly in other third-party Twitter apps as well. So this may not be a problem for Nitter but an issue with Twitter's GraphQL responses.

**Comment by pin-grid-array** [comment]
Oh... That's not good.

But at the same time, I'm hopeful that there is a solution because not every instance is afflicted by this bug. I hope somebody smarter than me can figure out what makes https://nitter.caioalonso.com/ and https://nitter.privacytools.io/ different and immune from the bug.

**Comment by PrivacyDevel** [comment]
Related issue https://github.com/PrivacyDevel/nitter/issues/8

**Comment by xgedev** [comment]
I found a random issue that may be related to this:
Fetching the RSS feed for the user `Hylidae_` does not work on my up to date local instance when adding `with_replies`.

`GET http://localhost/Hylidae_/rss` returns 200 with ~ `6000` content length.
`GET https://nitter.net/Hylidae_/rss` returns 200 with ~ `6000` content length.

`GET http://localhost/Hylidae_/with_replies/rss` returns 200 with `0` content length.
`GET https://nitter.net/Hylidae_/with_replies/rss` returns 200 with ~ `7000` content length.

Other public instances I found don't have this issue, just my local instance. Any ideas?

**Comment by zedeus** [comment]
This has been fixed with much better handling of threading that knows about the new data structure used by Twitter
