### ISSUE TITLE
Libpcre dependency

### ISSUE THREAD

**Issue by pipinstallpotato** [zedeus/nitter#896]
I'm fairly confident I have exhausted every braincell trying to figure this out. 

Once the command "nimble build -d:release" is run, a massive log of errors show up on screen following: Building nitter/nitter.exe using c backend.  This is the most common message "Warning: The bare except clause is deprecated; use `except CatchableError:` instead [BareExcept]"

Downloaded Pcre 8.45, following Install instructions. 
-Installed make-3.81.exe
-Installed WSL
-Installed Powershell 7
Shell command "./configure && make && make install"   (yes this is the exact command I used)
*make: *** No targets specified and no makefile found.  Stop.
I check the directory and found: Makefile.am and Makefile.in
Running the ./Configure command by itself only prompts the "Open with program" selection for the Configure file, no Makefile gets created in the directory.
Gave up trying to install this version of Pcre because I can't find any workaround or explanation for this anywhere.

Downloaded Pcre2 from: https://github.com/PCRE2Project/pcre2
Installed tortoisesvn, ran the commands with no errors. (Assuming this installed correctly)

ran command again in the nitter directory: "nimble build -d:release" same long list of errors after "Building nitter/nitter.exe using c backend" shows up. 

When nitter.exe is being built using C backend, is there another requirement that I'm ignoring or is it required that the older version of Pcre gets installed for the build process to function properly?

**Comment by zedeus** [comment]
The `BareExcept` warnings can be ignored, they don't impact anything. Is it compilation that fails, or is it running the program? You can try extracting these DLLs in the project root next to the binary https://nim-lang.org/download/dlls.zip

**Comment by grandpa1946** [comment]
> The `BareExcept` warnings can be ignored, they don't impact anything. Is it compilation that fails, or is it running the program? You can try extracting these DLLs in the project root next to the binary [nim-lang.org/download/dlls.zip](https://nim-lang.org/download/dlls.zip)

on wsl the same?

**Comment by zedeus** [comment]
No, WSL requires Linux stuff.

**Comment by grandpa1946** [comment]
> No, WSL requires Linux stuff.

i found the command [here](https://sagan.readthedocs.io/en/latest/install.html#cmdoption-arg-sudo)
