### ISSUE TITLE
Add twitter link to RSS feed

### ISSUE THREAD

**Issue by Rathmox** [zedeus/nitter#902]
I needed to use a Twitter RSS feed so I used Nitter but I needed the link to the original post on Twitter.

It can be useful to have the Twitter link directly into the RSS feed

**Comment by Rathmox** [comment]
@markcellus I tried to use it but it doesn't work in the app I want to use (it works in the others)

**Comment by markcellus** [comment]
Eek.. if its Reeder, its a known issue and a lot of us have reached out to them about it but Reeder team hasnt responded.

**Comment by Rathmox** [comment]
it's a discord bot called MonitoRSS
