### ISSUE TITLE
Exclude search results containing specific text?

### ISSUE THREAD

**Issue by soundchippy** [zedeus/nitter#908]
Is it possible, when using search, to exclude posts which include a specific word or phrase?

For example if I use the search function to look for tweets about various stock tickers, quite often the results will be flooded with bots advertising their stock trading discord servers. Selecting _exclude links_ gets rid of these posts, but also removes some legitimately interesting content. Being able to filter posts that include "discord", for example, would be helpful in isolating useful content.

Here's an example search for reference...

https://uk.unofficialbird.com/search?f=tweets&q=%24dna&since=&until=&near=

**Comment by zedeus** [comment]
You can add a dash in front of a word to exclude it, but in this case you need to use a url filter as well, like this: https://nitter.net/search?f=tweets&q=%24dna+-url%3Adiscord

**Comment by MadAim123** [comment]
@zedeus is it possible to search with wildcard?
something like 
`searchterm%found` or `searchterm*found`?

and i would find tweets with
`seachterm**s** found`
and also
`searchterm found`

maybe with only some characters between or also with whole words between?

**Comment by zedeus** [comment]
No, I'm afraid Twitter doesn't support that.
