### ISSUE TITLE
Broken image links in RSS feed - missing site port number

### ISSUE THREAD

**Issue by quickwick** [zedeus/nitter#911]
I'm self-hosting a private nitter (only accessible within my home LAN). The website is running on port 8080 (the default, yes?).

The RSS feeds created from this nitter have broken image links. I noticed that the image URLs don't contain the port number. Here's an example broken image link:

`http://nitter.home.arpa/pic/ext_tw_video_thumb%2F1647619025332211713%2Fpu%2Fimg%2FQB82xflC7nYM3oXX.jpg`

If I add :8080 to the domain, then the link works:
`http://nitter.home.arpa:8080/pic/ext_tw_video_thumb%2F1647619025332211713%2Fpu%2Fimg%2FQB82xflC7nYM3oXX.jpg`

Did I maybe miss a step during my nitter install/config?

**Comment by zedeus** [comment]
What does your nitter.conf look like?

**Comment by quickwick** [comment]
See below. I tried making it a quote or a code block, but it turned the comment lines into headers (markdown?)

I have the cookieHeader and xCsrfToken entries because I'm currently using this branch: https://github.com/PrivacyDevel/nitter/tree/nsfw

That branch is only 2 commits behind the head of your main repo, and the two commits seem entirely unrelated to this issue.

------------
[Server]
hostname = "nitter.home.arpa"  # for generating links, change this to your own domain/ip
title = "nitter"
address = "0.0.0.0"
port = 8080
https = false  # disable to enable cookies when not using https
httpMaxConnections = 100
staticDir = "./public"

[Cache]
listMinutes = 240  # how long to cache list info (not the tweets, so keep it high)
rssMinutes = 10  # how long to cache rss queries
redisHost = "localhost"  # Change to "nitter-redis" if using docker-compose
redisPort = 6379
redisPassword = ""
redisConnections = 20  # minimum open connections in pool
redisMaxConnections = 30
# new connections are opened when none are available, but if the pool size
# goes above this, they're closed when released. don't worry about this unless
# you receive tons of requests per second

[Config]
hmacKey = "secretkey"  # random key for cryptographic signing of video urls
base64Media = false  # use base64 encoding for proxied media urls
enableRSS = true  # set this to false to disable RSS feeds
enableDebug = false  # enable request logs and debug endpoints (/.tokens)
proxy = ""  # http/https url, SOCKS proxies are not supported
proxyAuth = ""
tokenCount = 10
# minimum amount of usable tokens. tokens are used to authorize API requests,
# but they expire after ~1 hour, and have a limit of 500 requests per endpoint.
# the limits reset every 15 minutes, and the pool is filled up so there's
# always at least `tokenCount` usable tokens. only increase this if you receive
# major bursts all the time and don't have a rate limiting setup via e.g. nginx

cookieHeader = "[redacted]" # authentication cookie of a logged in account, required for the likes tab and NSFW content
xCsrfToken = "[redacted]" # required for the likes tab and NSFW content

# Change default preferences here, see src/prefs_impl.nim for a complete list
[Preferences]
theme = "Nitter"
replaceTwitter = "nitter.net"
replaceYouTube = "piped.video"
replaceReddit = "teddit.net"
proxyVideos = true
hlsPlayback = false
infiniteScroll = false

**Comment by quickwick** [comment]
So I just added :8080 to end of the hostname value, and that seems to have fixed things. Was that the correct thing to do?

**Comment by zedeus** [comment]
Indeed, the hostname is used directly for links
