### ISSUE TITLE
For all twitter users whose Tweets are protected gives 500 error

### ISSUE THREAD

**Issue by sajiljosephs** [zedeus/nitter#913]
I am using local nitter instance. All users who have protected their tweets or no tweets or user suspended gives 500 error(user not found) while fetching it from rss.  Also all users who doesnt have any tweets also gives user not found. It would be great to have the error  precise for rss also which should be helpful to specify as "tweets are protected for this user" or "No items found" which is visible in the page without converting to rss.

Eg: 
https://nitter.net/hannelorekraft gives correct response
https://nitter.net/hannelorekraft/rss gives User "hannelorekraft" not found
https://twitter.com/hannelorekraft

![image](https://github.com/zedeus/nitter/assets/87175483/c52ac78a-2601-4e15-94a9-2a09c31d839f)

**Comment by sajiljosephs** [comment]
Can you please check and correct this ?

**Comment by grahamperrin** [comment]
Maybe fixed. 

<https://nitter.net/jasonkafer> 

> This account's tweets are protected.

- without error 500.

**Comment by sajiljosephs** [comment]
This is not fixed. Still rss on the local instance gives user not found:
URL: http://localhost:8080/hannelorekraft/rss (nitter docker container is running on localhost port 8080)

![image](https://github.com/zedeus/nitter/assets/87175483/a6867f5d-a5af-4489-b63e-0dfea4f85036)

**Comment by zedeus** [comment]
What commit? Check the about page. Clear Redis and try again. Can this machine/network access the API otherwise?
