### ISSUE TITLE
/with_replies seem to not work on any instance (of the 6 I checked) ...

### ISSUE THREAD

**Issue by asdf8dfafjk** [zedeus/nitter#915]
... and even regular doesn't work for many 

nitter.fly.dev nitter.fdn.fr nitter.it nitter.1d4.us (and a couple more that I tested)

**Comment by BANKA2017** [comment]
I found the response from twitter is empty:

```json
{
  "data": {
    "user": {
      "result": {
        "__typename": "User",
        "timeline_v2": {}
      }
    }
  }
}
```

And I noticed that accessing any Twitter page from an incognito window now requires a login, just like Instagram

**Comment by asdf8dfafjk** [comment]
https://www.theverge.com/2023/6/30/23779764/twitter-blocks-unregistered-users-account-tweets Likely this
