### ISSUE TITLE
search isnt working and i cant go to the user directly in the url on my instance

### ISSUE THREAD

**Issue by aysilu-kitsune** [zedeus/nitter#921]
so, user search was unavailable since yesterday, but I could search for their tweets and go to their profiles from here. now tweet search doesn't work as well. it returns "no items found" in both cases
I tried typing the username into the URL and got
```
An error has occured in one of your routes.

Detail: jsony.nim(45) parseHook
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
asyncfutures.nim(389) read
Expected { but end reached. At offset: 0
```
RSS parsing stopped working too

the instance is https://birbs.foxhaven.cyou , if that matters

**Comment by absturztau-be** [comment]
seems like twitter now requires a login to view content and therefore nitter can't access it anymore

**Comment by tio-trom** [comment]
So that means Nitter is dead?

**Comment by zedeus** [comment]
Duplicate. It's a temporary measure by Twitter.
