### ISSUE TITLE
(Probably a failed build) CSS not working?

### ISSUE THREAD

**Issue by FurretDev** [zedeus/nitter#926]
![image](https://github.com/zedeus/nitter/assets/99131021/51a07e68-5bd2-46df-aec2-2065539f104b)

The server returns 404 when requesting CSS

**Comment by zedeus** [comment]
From Docker hub?

**Comment by FurretDev** [comment]
> From Docker hub?

nope, i didn't use docker

**Comment by zedeus** [comment]
Weird, maybe a permission thing. I'd need more details to figure it out, along with a way to reproduce.

**Comment by FurretDev** [comment]
> Weird, maybe a permission thing. I'd need more details to figure it out, along with a way to reproduce.

hmm, what exactly do you need? i will try to give you all the necessary information

**Comment by gfpj** [comment]
For me it looked the same, I built on Windows with the same command above, without Docker, redis running in wsl, nim 1.6.12.

**Comment by FurretDev** [comment]
issue solved, i don't really know what i did but it's working now, however...

the search function does not work, and I have noticed that in most of the nitter instances it does not work either, not sure why

**Comment by zedeus** [comment]
I thought "Tweet search is unavailable for now" was obvious enough to make it clear that it isn't broken, it just isn't implemented right now. I'll work on it soon.

**Comment by osalbahr** [comment]
> I thought "Tweet search is unavailable for now" was obvious enough to make it clear that it isn't broken, it just isn't implemented right now. I'll work on it soon.

It was clear to me. However, I am biased since I'm following this issue and already know. I can see how it can be interpreted as "it's broken".

I think the message is good as-is, but something along the lines of "Tweet search isn't implemented right now" would be clearer.

**Comment by FurretDev** [comment]
> I thought "Tweet search is unavailable for now" was obvious enough to make it clear that it isn't broken, it just isn't implemented right now. I'll work on it soon.

i mean it happened on almost every nitter instances so that's why i thought it was broken 😭, but okay

**Comment by osalbahr** [comment]
> i mean it happened on almost every nitter instances so that's why i thought it was broken 😭, but okay

Which instances did nitter search work on?

**Comment by FurretDev** [comment]
> > i mean it happened on almost every nitter instances so that's why i thought it was broken 😭, but okay
> 
> Which instances did nitter search work on?

https://tweet.whateveritworks.org/

this one is **partly functional**, most of the things do not work but for example, i can search users but most of the things will give a 502 error (i think)
