### ISSUE TITLE
Unable to play videos on iOS

### ISSUE THREAD

**Issue by nitrohorse** [zedeus/nitter#93]
Hi, I've noticed recently that embedded videos on iOS (Safari, Firefox, and DDG Browser) don't even load and simply hang on playback. I also can't reproduce the issue on desktop (tried changing to a mobile user agent too).

Compared to https://github.com/zedeus/nitter/issues/66, I don't get a "Page Not Found" error, the video just hangs.

**Comment by zedeus** [comment]
I've pushed a potential fix, for cases where hls.js isn't supported. Let me know if this fixes it.

**Comment by nitrohorse** [comment]
Excellent, from my testing videos appear to play fine now. Thanks!
