### ISSUE TITLE
Multi-user RSS broken?

### ISSUE THREAD

**Issue by fishy** [zedeus/nitter#930]
Nitter used to work with multi-user RSS feed, for example `/caltrainalerts,caltrain/rss` would give the combined RSS of `@caltrainalerts` and `@caltrain`.

Now with latest master it seems that will just give an error of `User "caltrainalerts,caltrain" not found`.

**Comment by fishy** [comment]
> RSS is currently broken overall

single user rss seem to work for me

**Comment by liyqiy2022** [comment]
Please restore the rss
