### ISSUE TITLE
Issues updating [Docker]

### ISSUE THREAD

**Issue by net-tech** [zedeus/nitter#932]
Hi there, I'm having trouble updating to the newest version of Nitter. I'm using docker.

The first thing I did was run `git pull` in the directory where the nitter source code is, and then I ran `docker compose up -d --build`. After this, the about page of my instance still showed the version as Version [2023.03.06-bc219aa](https://github.com/zedeus/nitter/commit/bc219aa). I ran a few more troubleshooting steps after this, like deleting the docker containers and making them again, and so forth. In the end as a final attempt I deleted the nitter directory, `git clone`'d it again, inputted the same config, and got the same old version number displayed.

Am I doing something wrong? Has the version been pushed to docker?

**Comment by loma-baldsson** [comment]
did you rebuild everything with `nimble`?

**Comment by net-tech** [comment]
No, I'll try now

**Comment by net-tech** [comment]
@loma-baldsson Did not have to do this the first time I installed nitter so I doubt I manually need to build. Docker should be handling that part: https://github.com/zedeus/nitter/blob/0bc3c153d9b38a3c02f321fb64a375fef6b97e8e/Dockerfile#L12

**Comment by net-tech** [comment]
A simple `docker build -t nitter:latest .` was the fix.

**Comment by net-tech** [comment]
I'm still having this issue and the above 'fix' does not work. 

I've tried:
- Purging docker cache
- Deleting the whole nitter directory
- Restarting the VPS

I update by doing `git pull`, then `docker build -t nitter:latest .`, and then `docker compose up -d`. @zedeus or anyone have any ideas?

**Comment by net-tech** [comment]
Docker pull did the trick.
