### ISSUE TITLE
Discontinued Instances

### ISSUE THREAD

**Issue by JimmyBoyHalpert** [zedeus/nitter#934]
Sorry, don't know if this is the best place to ask this. 

One of the instances that I frequented a lot is listed under "Discontinued" in the wiki. Is there somewhere we users can read if maintainers are no longer going to take care of an instance or why an instance will be discontinued? Or is there some other qualification that will land an instance under discontinued?

**Comment by zedeus** [comment]
It's usually put there if it's completely broken, not just outdated. For example an expired certificate, expired domain name, or the instance being taken down.

**Comment by JimmyBoyHalpert** [comment]
Thanks, @zedeus
