### ISSUE TITLE
RSS-Feed on main instance not working

### ISSUE THREAD

**Issue by dravolin** [zedeus/nitter#937]
https://nitter.net/soren_iverson/rss gives a "Page not found" but other instances are working, like this one for example: https://nitter.kavin.rocks/soren_iverson/rss

**Comment by zedeus** [comment]
It's working, just disabled. I'll enable it soon.

**Comment by tomislaveric** [comment]
Hi @zedeus unfortunately, its not working again. I got a 403 forbidden

**Comment by zedeus** [comment]
It hasn't been enabled yet

**Comment by ujjwal-kr** [comment]
why.

**Comment by michaelskyba** [comment]
Relevant comment from the main X broken issue:

```
@Thorvarium it's disabled still. It'll be turned back on when all of this is over and things are stable enough.
```

_Originally posted by zedeus in https://github.com/zedeus/nitter/issues/983#issuecomment-1685056953_

**Comment by johnpc** [comment]
How can I enable RSS on my own instance?

**Comment by zedeus** [comment]
RSS is enabled by default, check `enableRSS` in your nitter.conf file.

**Comment by johnpc** [comment]
I'm seeing the 403 on my local instance. This is the stanza from my docker-compose.yml

```
  web:
    image: ceramicwhite/nitter:build-38985af@sha256:594a184c3a834c29957ddd917800d61f3d560411d26fa6cf389bef350d4c4ac6
    restart: on-failure
    stop_grace_period: 1m
    init: true
    user: 1000:1000
    command: >
      /bin/sh -c "sed -i 
      -e 's/localhost/nitter_redis_1/g' 
      -e 's/redisPassword = \"\"/redisPassword = \"{REDACTED}\"/g' 
      -e 's/theme = \"Nitter\"/theme = \"auto_(twitter)\"/g' 
      /src/nitter.conf
      && ./nitter"
    depends_on:
      - redis
```

Maybe I need to add another line to my `sed`?

**Comment by zedeus** [comment]
Shouldn't be necessary:
https://github.com/zedeus/nitter/blob/d7ca353a55ea3440a2ec1f09155951210a374cc7/nitter.example.conf#L25

`enableRSS` set to false would return a 404 instead, so you're probably getting the rate limited error. `ceramicwhite/nitter` is not an official build and the last tag was 5 months ago which definitely won't work. For the time being, to get Nitter working you need to compile the `guest_accounts` branch and acquire some accounts. There's a quick guide on how to do that here: https://github.com/zedeus/nitter/wiki/Guest-Account-Branch-Deployment
