### ISSUE TITLE
Tweet search results only go 10 days back

### ISSUE THREAD

**Issue by wanniethecharacter** [zedeus/nitter#938]
Whenever i write something like “billie eilish releases therefore i am” or set the before date to 10 June 2023, there are no results. I’m glad that search is back, but why did it have to happen?

**Comment by zedeus** [comment]
This is a limitation of the API used, which is one of two that I'm aware of is still accessible without user credentials. I may switch to the other one, but it seems to have some stability issues.

**Comment by zedeus** [comment]
No fix, but you just have to reload at least once, it's a weird issue with the endpoint that affects legacy Tweetdeck the same way. Currently there's no better option.
