### ISSUE TITLE
full screen videos

### ISSUE THREAD

**Issue by TheShanMan** [zedeus/nitter#945]
Would it be possible to have a query parameter or some form of url alteration to fill the page with a tweet's video? This would be similar to how invidious (and youtube itself) do it with "/embed/<video id>" (here's an actual example: https://vid.puffyan.us/embed/5LWDl5qaQbA).

I use this approach to watch videos on my htpc TV and would love to also watch twitter shows this way. I haven't found a way to do this with twitter itself but hopefully nitter can provide it.

**Comment by zedeus** [comment]
Here you go: https://nitter.net/i/videos/tweet/1678435695222747138
It's primarily intended for chat embeds, so it streams an mp4 directly from Twitter, which occasionally doesn't work on the first try because of Twitter's weird mp4 support.
