### ISSUE TITLE
nightly builds?

### ISSUE THREAD

**Issue by untitaker** [zedeus/nitter#949]
https://github.com/PrivacyDevel/nitter by @PrivacyDevel uses github actions to publish docker images when pushing to master. can we have the same for upstream? sometimes (rarely) docker is missing a particular commit i want.

**Comment by zedeus** [comment]
This is already done. When is it missing?

**Comment by untitaker** [comment]
there was no build for https://github.com/zedeus/nitter/commit/dcf73354ff173c0407c62f84ea3bb90a130303c1, but i see now that it was due to broken CI. nevermind!
