### ISSUE TITLE
@IFTTT recipe for Nitter's great RSS feed with its expanded URLs within tweets

### ISSUE THREAD

**Issue by gloschtla** [zedeus/nitter#95]
It would be great, if there would be a Nitter recipe on @IFTTT. It should be a derivative of the **Twitter recipe**, because IFTTT’s **RSS feed** recipe misses one element (called _ingredient_): it cannot grab the {first link} contained in a tweet. The great advantage of Nitterify is the plain URL (expanded t.co short link) and also RSS Feed feature, which has been disabled on Twitter.

examples for existing Twitter recipes on ifttt.com

    https://archive.is/04Q3E#18% - https://archive.is/1e6kn#15% - https://archive.is/kjJBd 

By the way, i discovered Nitter through [Nitterfy alias Invidition](https://codeberg.org/Booteille/Invidition)

**Comment by Z3ROGRAV1TYx** [comment]
I apologise for asking this here, I don't have anything of help for you, but I do have a question.

>RSS feed recipe
Curiously, does this mean Nitter can be implemented to RSS? So we can add Nitter (Twitter) user profiles to our RSS Feeds and it will show posts? Or is this something different? (because that is something that would be cool to be able to do)

**Comment by zedeus** [comment]
@Z3ROGRAV1TYx If you're asking whether Nitter supports RSS, the answer is yes, just click the RSS icon top-right when visiting a profile or doing a search

**Comment by gloschtla** [comment]
It would be great, if someone could create an ifttt recipe for nitter. [Here is a RSS feed example](https://nitter.net/search/rss?f=tweets&q=%23stop5g).

I created a new [issue about invidio.us link previews on nitter.net ](https://github.com/zedeus/nitter/issues/98)

**Comment by gloschtla** [comment]
problem solved: use nitter's advances search function, hit enter, and take the resulting rss feed to trigger ifttt
