### ISSUE TITLE
Docker: User tweets cannot be found

### ISSUE THREAD

**Issue by yunwei17** [zedeus/nitter#950]
I am running a selfhosted nitter. 

The user search is returning results. 

However, when I tried getting the user tweets, it is not returning any results.

Any one faces similar issue?

**Comment by zedeus** [comment]
What commit are you running? Check the bottom of the /about page.

**Comment by yunwei17** [comment]
Referencing issue #933, the only differences are that I am not using docker-compose and my redis is not dockerize. 
Any idea what could be the issue?

**Comment by yunwei17** [comment]
@zedeus I am closing this issue, The latest image works!!!
