### ISSUE TITLE
RSS feed does not include collapsed replies

### ISSUE THREAD

**Issue by spiffytech** [zedeus/nitter#951]
The with_replies RSS feed omits any replies that the web page would hide behind a "more replies" link. This sounds like it's because RSS feeds [shows the same data as the web page](https://github.com/zedeus/nitter/issues/574#issuecomment-1067084567).

Can the feed be adjusted to include EVERYTHING the person has recently tweeted? In the UI there's at least a way to tell something was missed, but in the feed there's not.

**Comment by zedeus** [comment]
No, this isn't possible without doing additional requests. Nitter's UI is not hiding anything, the "more replies" is necessary to indicate that more tweets are included in the thread.
