### ISSUE TITLE
[API] - Access to endpoints

### ISSUE THREAD

**Issue by stom79** [zedeus/nitter#96]
Hello,

It could be nice to be able to access some endpoints from the Nitter API. That would help to display timelines.

A simple workaround would be to extend the rss feed. Currently, I can check last feeds related to the first page.
https://nitter.net/fedilab_app -> https://nitter.net/fedilab_app/rss

But for the second page: https://nitter.net/fedilab_app?max_position=1190334000142921735 I didn't find a solution to use this pagination ie: https://nitter.net/edilab_app?max_position=1190334000142921735/rss

**Comment by stom79** [comment]
It could be really useful, if such URLs[1] could be handled with the above description:

[1] https://nitter.net/fedilab_app,joinpeertube,MastodonProject

**Comment by zedeus** [comment]
Using RSS for the time being would easiest, but using `max_position` is really just a hack as it defies the purpose of the feed. Regarding multi-timelines, RSS support has been added for them now, but it uses the advanced search so you won't be able to find `max_position` as it uses some weird cursor format not related to the tweet IDs. 

API support seems like a lot of work right now so it might take some time, but it is of course planned. I can add `max_position` support for now if you want. Let me know what you think.

**Comment by stom79** [comment]
Yes, thanks! `max_position` would help. Also, as far as I can get this value in the header or in the body, it's not a problem for building pagination.

**Comment by zedeus** [comment]
Done, there is now a `Min-Id` value in the headers which can be used with `max_position` to paginate the results. Example: https://nitter.net/elonmusk/rss?max_position=1190334000142921735

**Comment by stom79** [comment]
Great! Thanks a lot.
