### ISSUE TITLE
RSS links for Twitter lists no longer working

### ISSUE THREAD

**Issue by jaswinder77** [zedeus/nitter#961]
Earlier, for any twitter list https://twitter.com/i/lists/1234567890123456789 ,

 there was a corresponding rss feed with the link https://nitter.net/i/lists/1234567890123456789/rss .

Is there a likelihood of that thing returning soon ?

**Comment by zedeus** [comment]
It works just fine: https://nitter.net/i/lists/53645372
Do you have an example that doesn't work?

**Comment by Mr-Freewan** [comment]
Not this topic, but...hmm, just now, for example (any host):
https://nitter.nohost.network/elonmusk - tweets timeline is not available
https://nitter.nohost.network/elonmusk/with_replies - with replies is available

**Comment by net-tech** [comment]
I'm having the same issue. I got an alert from my monitoring platform just an hour ago.

**Comment by ImTheDeveloper** [comment]
https://twitter.com/i/api/graphql/3JNH4e9dq1BifLxAa3UMWg/UserWithProfileTweetsQueryV2 will return:
 `{
    "data": {
        "user_result": {
            "result": {
                "timeline_response": {
                    "id": "VGltZWxpbmU6CgBdAAAAAFIvaMAA",
                    "timeline": {
                        "instructions": [
                            {
                                "__typename": "TimelineClearCache"
                            },
                            {
                                "__typename": "TimelineTerminateTimeline",
                                "direction": "TopAndBottom"
                            }
                        ],
                        "metadata": {
                            "scribeConfig": {
                                "page": "profileBestHighlights"
                            }
                        }
                    }
                }
            }
        }
    }
}`

Same user with https://twitter.com/i/api/graphql/8IS8MaO-2EN6GZZZb8jF0g/UserWithProfileTweetsAndRepliesQueryV2 provides full response and tweets.

`{
    "data": {
        "user_result": {
            "result": {
                "timeline_response": {
                    "id": "VGltZWxpbmU6CgBeAAAAAFIvaMAA",
                    "timeline": {
                        "instructions": [
                            {
                                "__typename": "TimelineClearCache"
                            },
                            {
                                "__typename": "TimelineAddEntries",
                                "entries": [
                                    {
                                        "entryId": "tweet-1668154996372697089",
                                        "sortIndex": "1682262476449644544",
                                        "content": {
                                            "__typename": "TimelineTimelineItem",
                                            "content": {
                                                "__typename": "TimelineTweet",
                                                "tweetResult": {
                                                    "result": {
                                                        "__typename": "Tweet",
                                                        
                                                        etc....`

**Comment by zoubidabida** [comment]
> It works just fine: https://nitter.net/i/lists/53645372 Do you have an example that doesn't work?

Old tweets show up in random order : 
[Rer_a](https://nitter.net/rer_a) 

This account is updated many times a day normally :)

**Comment by oystermon** [comment]
I have the same thing (jumbled up main tweets page), but I realised the tweets and replies page is the right chronological order..

**Comment by zedeus** [comment]
The issues described here are no longer relevant. The 403 error is on purpose, please use another instance for now.
