### ISSUE TITLE
Twitter is becoming X. Should Nitter rebrand as well?

### ISSUE THREAD

**Issue by MintMain21** [zedeus/nitter#964]
I never liked Nitter's name. Maybe it's just in American English that it sounds bad, but given that Twitter is rebranding anyway, it might be a good opportunity to rename the Nitter project.

**Comment by gscbravo** [comment]
I feel like with rebranding comes the risk of having to build up recognition again.

**Comment by zedeus** [comment]
I don't really want to do that, the name is fine by itself and doesn't have to be explicitly tied to Twitter. It's a portmanteau of Nim + Twitter, and Nim + X doesn't really work.

**Comment by hollowshiroyuki** [comment]
> I don't really want to do that, the name is fine by itself and doesn't have to be explicitly tied to Twitter. It's a portmanteau of Nim + Twitter, and Nim + X doesn't really work.

Nix is now an OS, a package manager, a language and an X alternative 🙃

**Comment by AndyHee** [comment]
> Maybe it's just in American English that it sounds bad

Isn't that the whole point, that one can't polish a turd?

**Comment by Pythone** [comment]
Nitter is now "N"!

**Comment by Pythone** [comment]
The current "N" we have is similar enough

**Comment by 4yR1l1k** [comment]
I believe the name "xiktir" would be the most visionary choice.

**Comment by AnthonyLenglet** [comment]
Renaming to ℕ would be hilarious but I don't think it should follow every dumb on-the-spot decisions thats being made, otherwise it would be endless

on April fools however....

**Comment by xbdmHQ** [comment]
NitterX

**Comment by ddvarpdd** [comment]
>Maybe it's just in American English that it sounds bad

For me it always sounded like "neater", and Nitter is for sure neater than whatever the current official Twitter frontend is.

**Comment by thechesu** [comment]
What about Xitter?

**Comment by frepke** [comment]
I don't fully understand why this is a issue :-(

**Comment by 1-Rasky-1** [comment]
what about nginX?

**Comment by xaur** [comment]
Rebranding and established name is a lot of work to rename everything. Rebranding makes it harder to discuss the thing, now you have to say "Xitter (formerly Nitter)" everywhere for the next few years. Rebranding causes confusion among instance admins and end users. Rebranding breaks code and scripts. I think Nitter does not need any more breakage now. Even discussing the rebrand can burn a lot of collective energy and build nothing.

Unless the name is really, really bad, I think rebrand is a bad idea.

**Comment by DoogeJ** [comment]
> Renaming to ℕ would be hilarious but I don't think it should follow every dumb on-the-spot decisions thats being made, otherwise it would be endless
> 
> on April fools however....

Just use ℕ as the logo, keep the name Nitter

**Comment by MintMain21** [comment]
> > Renaming to ℕ would be hilarious but I don't think it should follow every dumb on-the-spot decisions thats being made, otherwise it would be endless
> > on April fools however....
> 
> Just use ℕ as the logo, keep the name Nitter

It'd be funny, but I really like the current N logo.

In fact, I'll just close this issue. I guess Mods can reopen it if they have any good ideas, but it seems like everyone universally thinks a rebrand is a bad idea, and frankly, ya'll are right.
