### ISSUE TITLE
Does nitter ban if request many times?

### ISSUE THREAD

**Issue by hmtrii** [zedeus/nitter#966]
Hi there,

I have a bot that request to nitter.net about 50 times per 5 minutes.

Recently the bot faced 403 connection timeout.

If I change IP address, it solve error but after a duration, it appear again.

Does nitter banned if request many times? and Why?

Thank advance!

**Comment by zedeus** [comment]
Yes, because it's harmful to people that actually use the service. Please don't scrape it, it's extremely easy to host your own instance and scrape that instead. Just run it via Docker, takes at most a couple of minutes to set up.
