### ISSUE TITLE
question: what is the purpose of the `base64Media` config option?

### ISSUE THREAD

**Issue by climbTheStairs** [zedeus/nitter#971]
The description for this option is "use base64 encoding for proxied media urls"; however, I can't find out anywhere or think of *why* this option exists - what reasons are there to prefer either URL-encoded vs base 64 encoded URLs? Does it make any practical difference (and if not, why does this option exist?)?

**Comment by ojaha065** [comment]
In my Windows-based homelab I've Microsoft IIS acting as a reverse proxy and I had some difficulties with Nitter when using the default URL-encoded option. I don't recall the exact details but it had something to do with IIS automatically decoding the URL or something. I'm sure there's a way around that in IIS but I never bothered to look into it.

Outside this kind of special circumstances, I don't think there's much practical difference between using URL-encoded and Base64 URLs.

**Comment by zedeus** [comment]
Someone had a similar issue with a cloud host that had strange restrictions, or some Apache issue, I'm not sure. In any case it should only be used if necessary, since it obfuscates the link.

**Comment by climbTheStairs** [comment]
Thanks for the answer!
Could this be documented somewhere, perhaps in the comment in `nitter.example.conf`, lest others are also confused by this option?
Possibly, something like:

```
base64Media = false  # base64-encode proxied media URLs to bypass network restrictions
````
