### ISSUE TITLE
Search showing different and limited results everytime

### ISSUE THREAD

**Issue by tatta123** [zedeus/nitter#972]
I was swarching for tweets with these params from:jimmybutler since:2011-08-01 until:2023-07-05
it does work with the load more button but that too after 4 tries to load one page but its not loading please help

**Comment by zedeus** [comment]
This is weird behavior caused by Twitter, not a Nitter bug.

**Comment by tatta123** [comment]
> This is weird behavior caused by Twitter, not a Nitter bug.

So how to get through this?

**Comment by zedeus** [comment]
Right now the only way I'm aware of is if you're ok with only 7 days of history, or just logging into twitter.

**Comment by zedeus** [comment]
Fixed
