### ISSUE TITLE
Filtering by images doesn't work?

### ISSUE THREAD

**Issue by AskerCPU87456** [zedeus/nitter#974]
when I filter images/media no tweets show, despite there being a lot of image/media tweets.

Is it bugged and if its is there a solution to show tweets which have an image linked? whether including text or not

**Comment by LainLayer** [comment]
I could not reproduce this. Please show an example search query where it fails. Also, are you using nitter.net or some other instance?
![image](https://github.com/zedeus/nitter/assets/10339438/486a13a9-22d1-4cce-83ca-a0f5f0b257bc)
