### ISSUE TITLE
Doesn't show all tweets

### ISSUE THREAD

**Issue by paranoikcodit** [zedeus/nitter#976]
Nitter page - https://nitter.net/paranoikcodit
Twitter page - https://twitter.com/paranoikcodit

![изображение](https://github.com/zedeus/nitter/assets/111517049/eee4f667-b0c1-435f-8ca4-cef025b1b721)
![изображение](https://github.com/zedeus/nitter/assets/111517049/42ce7740-85f9-4a4c-af76-6620cc0b3809)

but it shows up fine on the Tweets & Replies page:
![изображение](https://github.com/zedeus/nitter/assets/111517049/e382c48c-e2b3-485e-a6ef-b5081e57574f)

**Comment by zedeus** [comment]
Fixed

**Comment by zedeus** [comment]
Fixed
