### ISSUE TITLE
Support /user/status/:status_id redirects used by Twitter embeds

### ISSUE THREAD

**Issue by jahed** [zedeus/nitter#979]
Nitter currently shows "503 Service Temporarily Unavailable" for URLs in the format:

```
/user/status/:status_id
```

Where `user` is the literal string `"user"` rather than a username. I've seen this format used in some Twitter embed widgets to link to a tweet when Twitter is blocked, likely so that they aren't affected by username changes.

https://github.com/s9e/s9e.github.io/blob/master/iframe/2/twitter.html

Twitter automatically redirects to the author of the status:

```
/:username/status/:status_id
```

It's not clear if this is known behaviour since the #919 rewrite and I haven't found an existing issue covering this.

**Comment by zedeus** [comment]
It was blocked by nitter.net some time ago due to a massive botnet scraping Nitter with thousands of IPs, and the only thing in common was "/user/status/...". They've stopped long ago so I'll remove the block.

**Comment by jahed** [comment]
Links are working now. Thanks, Zed!
