### ISSUE TITLE
Nitter.net without invidio.us link previews?

### ISSUE THREAD

**Issue by gloschtla** [zedeus/nitter#98]
When people post youtube URLs on twitter, they appear as invidio.us URL on nitter.net 
Sometimes the youtube interface invidio.us is down.

It would be great, if nitter.net would try to check for [alternative invidioUS instances](https://uptime.invidio.us/), or just re-try to load the link preview a few hours later when invidio.us might be online again.

**Comment by zedeus** [comment]
The link previews are created by Twitter, it's only the link itself that gets replaced by invidio.us (unless you disable it in the settings).

**Comment by zedeus** [comment]
Please close the issue unless you have more to add. I'm not going to add custom link previews as that's a ton of extra complexity when Twitter provides them already
