### ISSUE TITLE
jester is making jokes at this route

### ISSUE THREAD

**Issue by bangbangyouall** [zedeus/nitter#984]
An error has occured in one of your routes.
Detail: fatal.nim(53) sysFatal
asyncfutures.nim(385) read
asyncfutures.nim(385) read
asyncfutures.nim(385) read
asyncfutures.nim(385) read
asyncfutures.nim(385) read
asyncfutures.nim(385) read
packedjson.nim(294, 19) `false` unexpected end of object

**Comment by zedeus** [comment]
#983
