### ISSUE TITLE
Add feature: RSS feed

### ISSUE THREAD

**Issue by Fntoomen** [zedeus/nitter#986]
Hi,

In the past Nitter had the option to make RSS feed like that `https://nitter.net/{USERNAME}/rss`, but now when you try to use it, it return 403 Forbidden.
Can someone explain to me why this no longer works? Are you planning on adding this back in the future?

**Comment by zedeus** [comment]
It's disabled on purpose, it's not a missing feature. I don't know when I'll turn it back on.

**Comment by Fntoomen** [comment]
Ok, I guessed that, but why is it disabled?

**Comment by zedeus** [comment]
To reduce traffic and memory leaks, things are very unstable right now.

**Comment by evilsh3ll** [comment]
> To reduce traffic and memory leaks, things are very unstable right now.

do you know a free temporary alternative to get twitter feeds in rss form? rsshub is not working :(

**Comment by zedeus** [comment]
Nope, but there are a few workinginstances online now that do allow RSS. 
Check here: https://status.d420.de/
