### ISSUE TITLE
User not found whatever the user for basic get 

### ISSUE THREAD

**Issue by zoubidabida** [zedeus/nitter#987]
Hi !
Since yesterday every user I’m trying to get returns user not found error. 
Like this one which still works with nitter.net though : curl http://127.0.0.1:8081/greatdismal

was there a special fix recently ?
Thanks

**Comment by sihimaa** [comment]
Same problem here!

**Comment by zedeus** [comment]
A solution for everyone hasn't been built yet. Stay tuned at #983 and #985
