### ISSUE TITLE
 [UNKNOWN] Unable to load twitter data via web console

### ISSUE THREAD

**Issue by rajeshramamoorthy** [zedeus/nitter#990]
[UNKNOWN] Unable to load twitter data via web console

### Description:

Twitter data is not loaded after installation

### Steps to followed

I followed instruction in documentation : 

docker run -v $(pwd)/nitter.conf:/src/nitter.conf -d --network host zedeus/nitter:latest

After enabling Debug log.

<img width="837" alt="Screenshot 2023-08-25 at 4 35 41 PM" src="https://github.com/zedeus/nitter/assets/12644153/1902ab28-d28a-40a0-8e28-6d3f54844a22">

Empty response from webserver.

<img width="1150" alt="Screenshot 2023-08-25 at 4 36 15 PM" src="https://github.com/zedeus/nitter/assets/12644153/b12df332-1703-460a-b1fa-7f8139057b4b">

@zedeus, Please do the needful

**Comment by zedeus** [comment]
#983
