### ISSUE TITLE
I'm getting mixed language results for nitter/twitter feed.

### ISSUE THREAD

**Issue by jointri** [zedeus/nitter#993]
For example, lets say I'm reading the gimp_official twitter account to read GIMP news for the project. I get some results in english like I expect it to be, but some tweets are translated into french? Screenshot example for what I'm seeing -
![GIMP-Nitter](https://github.com/zedeus/nitter/assets/81046576/cd2c839c-39d8-464b-905b-4c9bc13c1169)
I don't even live in france nor do I have french set as a locale or language or anything like that. Is this a bug?

**Comment by zedeus** [comment]
No, that's just actually what the tweets are.
![image](https://github.com/zedeus/nitter/assets/9434921/d0ecafaf-3334-4971-b345-663e0c2c8e0d)
